### ISSUE TITLE
How to build with -fPIC?

### ISSUE THREAD

**Issue by qokelate** [open-source-parsers/jsoncpp#1006]
**Describe the bug**
```
/usr/bin/ld: ../input/libjsoncpp.a(json_value.cpp.o): in function `Json::Value::nullSingleton()':
json_value.cpp:(.text+0xbec): undefined reference to `__dso_handle'
/usr/bin/ld: ../input/libjsoncpp.a(json_value.cpp.o): relocation R_X86_64_PC32 against undefined hidden symbol `__dso_handle' can not be used when making a shared object
```

**To Reproduce**
1.  cmake3 -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_CXX_FLAGS=-fPIC ..
2. link libjsoncpp.a in dynamic lib(xx.so)

**Expected behavior**

**Desktop (please complete the following information):**
fedora 30
`Linux fedora 5.2.5-200.fc30.x86_64 #1 SMP Wed Jul 31 14:37:17 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**

**Comment by dota17** [comment]
> link libjsoncpp.a in dynamic lib(xx.so)

How do you link static lib in dynamic lib? Could you post the command you used?  
I can't get linux fedora, so I can't reproduce this issue. But I think the problem arises in the step of linking a static lib to a shared lib.

**Comment by qokelate** [comment]
you are right, thank you very much!

bad:
```
target_link_libraries(xxx 
	"-Wl,--no-whole-archive"
	"-fPIC"
	"-Wl,-whole-archive"
	"/xxx/libjsoncpp.a"
)
```

resolved:
```
target_link_libraries(xxx 
	"-Wl,-whole-archive"
	"/xxx/libjsoncpp.a"
	"-Wl,--no-whole-archive"
	"-fPIC"
)
```

**Comment by jiudianren** [comment]
if i use  CMAKE_POSITION_INDEPENDENT_CODE instead of "-fPIC" ，how i Specify order of  libjsoncpp.a and fPIC。 
when use CMAKE_POSITION_INDEPENDENT_CODE , "fPIC" will before at libjson.cpp.
like this in cmake_lists:

set(CMAKE_POSITION_INDEPENDENT_CODE on)
find_package(jsoncpp REQUIRED)
target_link_libraries(xx PUBLIC jsoncpp_static)
