### ISSUE TITLE
`add_compile_definitions` command not available in cmake 3.8.2

### ISSUE THREAD

**Issue by crazySocket** [open-source-parsers/jsoncpp#1018]
**Describe the bug**
You cannot build library with cmake in version 3.8.2.

**To Reproduce**
Make sure your cmake version is 3.8.2. Build the library.

**Expected behavior**
CMake fails to configure build since `add_compile_definitions` is not available in version 3.8.2.

**Desktop (please complete the following information):**
 - OS: windows 10

**Comment by baylesj** [comment]
Good catch. We say we support version 3.8.0, but sounds like we don't.

**Comment by dota17** [comment]
In [CMake 3.12 Release Notes](https://cmake.org/cmake/help/v3.12/release/3.12.html?highlight=add_compile_definitions)， `add_compile_definitions` may be not added until CMake 3.12.

From PR #932 ,  `add_definitions` was changed to `add_compile_definitions`.
But in CMakeList.txt (root directory) , the oldestversion is still 3.8.0
```
set(JSONCPP_OLDEST_VALIDATED_POLICIES_VERSION "3.8.0")
```

Maybe we should change the above message or revert some change of the cmake cleanup.

**Comment by cdunn2001** [comment]
I have found Cmake to be nearly impossible to maintain because different versions are so very different. I only both with Meson, and I generally accept any PR submitted for Cmake.

If someone has a fix for this, great. If the solution is to specify a later version of Cmake, that's fine with me.

**Comment by hjmjohnson** [comment]
As this project is using C++11 features, cmake provides more robust support for C++11 features starting with version 3.12 and greater.

The new Cmake feature of "add_compiler_definitions" is certainly more appropriate, and more robust, but it a new feature that is only available in cmake 3.12 and greater.    Ubuntu 18.04 envirionments come standard with cmake 3.10, so using the bleeding edge features of cmake is probably not a good idea for a project like jsoncpp.  I'll have a look at fixing this later this week.
