### ISSUE TITLE
Could you refactory valueToString() mothod with function templates?

### ISSUE THREAD

**Issue by fredgan** [open-source-parsers/jsoncpp#1019]
For example:
```c++
template <typename Out, typename In>
Out convert(const In& value) {
  std::stringstream stream;
  Out result;
  stream << value;
  stream >> result;
  return result;
}
```
how to use:
```c++
template <typename T> String JSON_API 
valueToString(T value) {
  return Json::convert<String>(T(value));
}
```

**Comment by baylesj** [comment]
I don't see why not. Feel free to put up a patch if you like, I'll keep this in the backlog.

**Comment by BillyDonahue** [comment]
The proposed `convert` function has nothing to do with JSON.
It is what's known as a lexical cast.

We're not going to do as complete a job as `Boost::conversion::lexical_cast`, and we should stick to JSON codec functions.

https://www.boost.org/doc/libs/1_42_0/libs/conversion/lexical_cast.htm#lexical_cast
