### ISSUE TITLE
Precompiled libraries

### ISSUE THREAD

**Issue by DrewRWx** [open-source-parsers/jsoncpp#102]
Howdy,

Are there any plans to host precompiled libraries (or at least pre-amalgamated sources) for releases on Window.

Than you,
Drew

**Comment by cdunn2001** [comment]
In GitHub, no. In fact, we don't even test on Windows. But we'd consider a web-hook to notify your own app, which code host your binaries somewhere.

**Comment by DrewRWx** [comment]
Sorry for the delay. After thinking through my options, I'm trying to package your project for https://github.com/Alexpux/MINGW-packages . So far the unit tests seem happy. :)

**Comment by cdunn2001** [comment]
+1

**Comment by DrewRWx** [comment]
Alexpux/MINGW-packages#422

**Comment by cdunn2001** [comment]
Thank you! [Noted](https://github.com/open-source-parsers/jsoncpp/wiki/NEWS).

**Comment by DrewRWx** [comment]
The package actually targets the [MinGW-w64 fork](http://mingw-w64.sourceforge.net/).
