### ISSUE TITLE
Compilation fails with clang 10

### ISSUE THREAD

**Issue by DarkWingMcQuack** [open-source-parsers/jsoncpp#1021]
**Describe the bug**
Compilation with clang 10 fails at this [line](https://github.com/open-source-parsers/jsoncpp/blob/fd940255ced7773489f818e62d7074fbcfda81cc/src/lib_json/json_value.cpp#L115) the error
```
error: implicit conversion from 'long' to 'double' may lose precision [-Werror,-Wimplicit-int-float-conversion]
  return d >= min && d <= max;
           ~~ ^~~
```

**To Reproduce**
1. compile with clang 10

**Expected behavior**
should compile

**Additional context**
simply adding the `static_cast`s which are already implemented in the comment above solves the issue

**Comment by baylesj** [comment]
Fixed in HEAD.
