### ISSUE TITLE
parsing comment in array fails

### ISSUE THREAD

**Issue by richardeakin** [open-source-parsers/jsoncpp#103]
I really like that jsoncpp supports comments, though it seems that comments at the start of arrays cause parsing errors. Take the following example:

```
{
	"array-test" : [
	    // comment at beginning of array
		"one",
		"two"
	]
}
```

For me, this produces the following message:
```
Line 3, Column 6
Syntax error: value, object or array expected.
```

Is it possible to support comments at the beginning of arrays too? This tends to bite me when least expected..

**Comment by cdunn2001** [comment]
Interesting. No time to debug that right now, but if you figure it out, submit a patch. We would welcome it!

**Comment by datadiode** [comment]
You may want to consider [this fairly invasive changeset](https://github.com/datadiode/jsoncpp/commit/6654d5a1c4308ad58767cb2a82801b0089e2f054) (which certainly goes way beyond the border case addressed in this ticket).

**Comment by cdunn2001** [comment]
@datadiode, let's discuss that changeset at #112. We can leave this issue open until we have a smaller, targeted changeset.

**Comment by cdunn2001** [comment]
Merged a fix. Added a test. Thanks for pointing this out.

**Comment by richardeakin** [comment]
Thanks!  Out of curiousity, what commit is responsible for the fix?  I'll probably update our jsoncpp version once this makes it into a release.

**Comment by datadiode** [comment]
Tested with richardeakin's example. The issue persists.

**Comment by cdunn2001** [comment]
I was never able to repro this crash. If that still happens for you please provide more details:
* commit
* OS (version + 32/64-bit)
* cmake command

I will look into the loss of the comment from StyledWriter. The comment is definitely read by the *Reader*.

**Comment by cdunn2001** [comment]
Oh, I see . The array has only 2 elements, so it is considered a single-line array, which suppresses comments.

I guess the styled writer needs a flag to indicate whether to preserve comments, which would also prevent single-line output. Would that be ok?
```
// enum class CommentStyle {None, Some, All};
Json::StyledStreamWriter w;
w.setCommentStyle(Json::StyledStreamWriter::CommentStyle::All);
w.write(std::count, value);
```

**Comment by richardeakin** [comment]
Sorry, I don't quite understand your diagnosis - my test array has two elements and they are on multiple lines, so how is it considered to be a single-lined array?

Also, do you mean that the following is not expected to work (by default anyway)?

```
{
    "array-test" : [
        // comment at beginning of array
        "one", "two"
    ]
}
```

I could see someone doing the above in the wild and expecting it to work.  But if there is a CommentStyle option, this seems like it could be made to work (we'd probably either set it to all or none).

Thanks again for looking into this..

**Comment by cdunn2001** [comment]
It's a two-element array, so the Styled writer cheats and writes it like this:
```
["one", "two"]
```
Because it gets written on only one-line, `//` comments cannot be included. For simplicity, all comments are excluded in this case.

It's fixable, and it's contrary to the documentation. But I want to switch to a [`WriterBuilder`](https://github.com/open-source-parsers/jsoncpp/issues/132) first.

Either way, it should never crash, but I was never able to repro the crash anyway. Hopefully it's no longer crashing for you.

**Comment by richardeakin** [comment]
Thanks for the explanation. I have tested wih latest master and indeed and the parsing is as expected. I would consider this issue resolved, I take it the other problem you are planning to fix is more entailed that my original request (preserving the comment?).

In any event, thanks again for addressing this.

**Comment by cdunn2001** [comment]
Fixed.
