### ISSUE TITLE
win10 CMake succeed，but VS2017and meson install failed

### ISSUE THREAD

**Issue by TianLeebx** [open-source-parsers/jsoncpp#1034]
![image](https://user-images.githubusercontent.com/44290599/65410507-23f22380-de1d-11e9-9269-448dba03f1c6.png)
![image](https://user-images.githubusercontent.com/44290599/65410533-32d8d600-de1d-11e9-9f8c-61a0227df289.png)
![image](https://user-images.githubusercontent.com/44290599/65410618-67e52880-de1d-11e9-9cac-c754febbdbeb.png)

安装失败，CMake和meson均失败，不知道是什么原因

**Comment by TianLeebx** [comment]
that is OK,but have a other problem
![image](https://user-images.githubusercontent.com/44290599/65412475-e5129c80-de21-11e9-8135-b32b388f1a56.png)

![image](https://user-images.githubusercontent.com/44290599/65412294-83eac900-de21-11e9-881d-2fcf0632167e.png)

![image](https://user-images.githubusercontent.com/44290599/65412590-1ee3a300-de22-11e9-9075-4bd1b95b0cba.png)

**Comment by dota17** [comment]
Which version of jsoncpp are you using? 
Just to confirm : It's ok with CMake in your Win10, but the testcase `parseChineseWithOneError` failed?

**Comment by TianLeebx** [comment]
1.9.2 . the testcase parseChineseWithOneError has no problem now,And now have a other problem,i don't know the reason.


------------------ 原始邮件 ------------------
发件人: "dota17"<notifications@github.com>;
发送时间: 2019年9月23日(星期一) 下午5:29
收件人: "open-source-parsers/jsoncpp"<jsoncpp@noreply.github.com>;
抄送: "⊙●╯╰没有失望的孩纸"<751808646@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [open-source-parsers/jsoncpp] win10 CMake succeed，but VS2017and meson install failed (#1034)




Which version of jsoncpp are you using?
 Just to confirm : It's ok with CMake in your Win10, but the testcase parseChineseWithOneError failed?

**Comment by TianLeebx** [comment]
![image](https://user-images.githubusercontent.com/44290599/65431593-4ea7a080-de4c-11e9-9d0c-932374776b3d.png)
