### ISSUE TITLE
PR to optionally emit UTF-8 encoded JSON text.

### ISSUE THREAD

**Issue by nicolaswilson** [open-source-parsers/jsoncpp#1042]
Hi
Our application requires that we send UTF-8 encoded JSON. Consequently, I've locally modified jsoncpp to output UTF-8 JSON, adding a new setting 'printUTF-8'.
Would you be willing to accept a PR? 
I'll have to write tests in the jsoncpp test framework, hence asking first.

Best regards,

Nick.

**Comment by dota17** [comment]
Hi Nick, it's a great feature from your description, please feel free to submit your PR.

**Comment by nicolaswilson** [comment]
See PR #1045.
