### ISSUE TITLE
Memory leak issue in jsoncpp ver 0.10.7(0.y.z)

### ISSUE THREAD

**Issue by subithaparamasivan** [open-source-parsers/jsoncpp#1051]
We tried to feed  128KB data in JSON parser API , which took almost 2MB of memory . 

Please find the below code for your reference ,

if(!reader.parse(buf, root))
			{
		         return false;
			}

Could you please provide your input on this .

Thanks & Regards,
Subitha.P

**Comment by cdunn2001** [comment]
Does this happen with `CharReaderBuilder`? A fuller example would help. (We might not be able to fix this if it's in the old, deprecated API.)

**Comment by subithaparamasivan** [comment]
Thank your for the response.

We are getting memory leak issue in jsoncpp ver 1.0.0 also. In this ver "CharReaderBuilder" API is not available . 

we are facing this issue in  corresponding API " bool successful = readValue();".

After finished readValue () callback , jsoncpp sourecode took  2MB of memory for both ver(jsoncpp ver 1.0.0 & 0.10.7)

We are using ARM compiler 5 , which supports c and c++ languages only . We tried to Integrate latest source code jsoncpp ver 1.9.1 in our module, we getting many more compiler error . 

Could you please suggest which source doesn't have memory leak for C++ . This would be helpful for us. 

Thanks,

**Comment by baylesj** [comment]
I would need to see more information about what is leaking. What is the source data that you used? 

Is that 2MB after the buffer has been freed? What tool are you using to check? Do you have a memory dump of the leaked addresses?

**Comment by subithaparamasivan** [comment]
We integrated Jsoncpp source code ver 1.0.0 in our module.
The original response is confidential . So please find sample response as given below,
{
    "Response": {
        "status": [
            {
                "status": "Success",
                "code": 100
            }
        ],
	   "List": {
            "list data": [
			.
                        .-> Total array size is nearly 128KB
			
			]
			}
			}
Is that 2MB after the buffer has been freed? 
  >> No , it's didn't freed.
What tool are you using to check?
 we have real time os in our module . based on "os "command ,we are calculate the remaining memory after  readValue() API.
Kindly let us know for any clarifications.

Thanks,

**Comment by subithaparamasivan** [comment]
Could you please provide your input on the above query.
Kindly do needful ASAP.

**Comment by dota17** [comment]
As cdunn2001 said:
> We might not be able to fix this if it's in the old

It's better to use current maintenance version.

And as you said:
> We are using ARM compiler 5 , which supports c and c++ languages only . We tried to Integrate latest source code jsoncpp ver 1.9.1 in our module, we getting many more compiler error .

Could you post some compiler error log here? That will be helpful for us to fix this issue.

**Comment by subithaparamasivan** [comment]
The following file is not opened ,Because of it a  C++11 style language.
----------------------------------------------------------------------------------------
 error  #5: cannot open source input file "type_traits": No such file or directory
--------------------------------------------------------------------------------------------
Could you please share the corresponding c++ file. It would be helpful for integrate json ver 1.9.2 in our module.
Thanks,

**Comment by subithaparamasivan** [comment]
Please provide your inputs on above query.
Kindly do needful ASAP

**Comment by dota17** [comment]
And now, the question is that in your ARM compiler 5, you can't find `type_traits` header? I can't test this in the ARM compiler, but I suggest you try to delete this header in your local file, then you can tell me whether is ok or not.

**Comment by subithaparamasivan** [comment]
the question is that in your ARM compiler 5, you can't find type_traits header?
 >> type_traits header file is not found in ARM compiler 5.
When we remove type_traits in local file, we are facing more compiler error in "allocator .h" file \
Please find the below log for your reference,
----------------------------------------------------------------------------------------------
json/allocator.h(18,9) : error  #738: a class-qualified name is required
json/allocator.h(18,20) : error  #65: expected a ";"
json/allocator.h(19,9) : error  #738: a class-qualified name is required
json/allocator.h(19,17) : error  #65: expected a ";"
json/allocator.h(20,9) : error  #738: a class-qualified name is required
json/allocator.h(20,23) : error  #65: expected a ";"
json/allocator.h(21,9) : error  #738: a class-qualified name is required
json/allocator.h(21,19) : error  #65: expected a ";"
json/allocator.h(22,9) : error  #738: a class-qualified name is required
json/allocator.h(22,25) : error  #65: expected a ";"
json/allocator.h(23,9) : error  #738: a class-qualified name is required
json/allocator.h(23,19) : error  #65: expected a ";"
json/allocator.h(24,9) : error  #738: a class-qualified name is required
json/allocator.h(24,25) : error  #65: expected a ";"
json/allocator.h(29,3) : error  #20: identifier "pointer" is undefined
json/allocator.h(29,20) : error  #20: identifier "size_type" is undefined
json/allocator.h(41,28) : error  #20: identifier "pointer" is undefined
json/allocator.h(41,39) : error  #20: identifier "size_type" is undefined
json/allocator.h(50,21) : error  #40: expected an identifier
json/allocator.h(50,46) : error  #20: identifier "pointer" is undefined
json/allocator.h(50,57) : error  #20: identifier "Args" is undefined
json/allocator.h(50,61) : error  #18: expected a ")"
json/allocator.h(55,3) : error  #20: identifier "size_type" is undefined
json/allocator.h(57,3) : error  #20: identifier "pointer" is undefined
json/allocator.h(57,19) : error  #20: identifier "reference" is undefined
json/allocator.h(59,3) : error  #20: identifier "const_pointer" is undefined
json/allocator.h(59,25) : error  #20: identifier "const_reference" is undefined
json/allocator.h(59,17) : error  #403: invalid redeclaration of member function "Json::SecureAllocator<T>::address(<error-type>) const" (declared at line 57)
json/allocator.h(64,16) : error  #20: identifier "pointer" is undefined
json/allocator.h(72,47) : error  #738: a class-qualified name is required
---------------------------------------------------------------------------------------------
Could you please help on this.

 Based on my understanding , Jsoncpp ver 1.9.2 memory allocation and deallocation using secure allocator.

**Comment by subithaparamasivan** [comment]
Could you please help on above query information.

**Comment by dota17** [comment]
Well, I mean delete this [include/json/config.h](https://github.com/open-source-parsers/jsoncpp/blob/master/include/json/config.h#L15) in your local jsoncpp lib. Because I think this is redundant.

**Comment by BillyDonahue** [comment]
armcc5 is not even close to being a C++11 implementation.
https://developer.arm.com/docs/dui0472/m/c-and-c-implementation-details/c11-supported-features

**Comment by subithaparamasivan** [comment]
Yes .. your shared link says "ARM® Compiler 5 includes only the C++03 standard template library".

When we remove "include/json/config.h" local file , we facing below complier error in include/json/json_features.h and  json_tool.h
Is it possible to add this memory leak issue fix in jsoncppver 1.0.0 .
Could you please check on this.
Thanks,

**Comment by dota17** [comment]
> Yes .. your shared link says "ARM® Compiler 5 includes only the C++03 standard template library".

Template is another feature, in this issue we no need to care about template feature.

What I say in this: https://github.com/open-source-parsers/jsoncpp/issues/1051#issuecomment-549226052 is to suggest to delete `#include <type_traits>` in include/json/config.h, not to delete this file.
https://github.com/open-source-parsers/jsoncpp/blob/2703c306a3168e15613d94e57fb8832138d9155d/include/json/config.h#L15

**Comment by subithaparamasivan** [comment]
Initially we removed #include <type_traits> in include/json/config.h file and also removed from local dir(type_traits.h). In this case we are faced compiler error in "allocator.h" file .

json/allocator.h(18,9) : error #738: a class-qualified name is required
json/allocator.h(18,20) : error #65: expected a ";"
json/allocator.h(19,9) : error #738: a class-qualified name is required
json/allocator.h(19,17) : error #65: expected a ";"
json/allocator.h(20,9) : error #738: a class-qualified name is required
json/allocator.h(20,23) : error #65: expected a ";"
json/allocator.h(21,9) : error #738: a class-qualified name is required
json/allocator.h(21,19) : error #65: expected a ";"
json/allocator.h(22,9) : error #738: a class-qualified name is required
json/allocator.h(22,25) : error #65: expected a ";"
json/allocator.h(23,9) : error #738: a class-qualified name is required
json/allocator.h(23,19) : error #65: expected a ";"
json/allocator.h(24,9) : error #738: a class-qualified name is required
json/allocator.h(24,25) : error #65: expected a ";"
json/allocator.h(29,3) : error #20: identifier "pointer" is undefined
json/allocator.h(29,20) : error #20: identifier "size_type" is undefined
json/allocator.h(41,28) : error #20: identifier "pointer" is undefined
json/allocator.h(41,39) : error #20: identifier "size_type" is undefined
json/allocator.h(50,21) : error #40: expected an identifier
json/allocator.h(50,46) : error #20: identifier "pointer" is undefined
json/allocator.h(50,57) : error #20: identifier "Args" is undefined
json/allocator.h(50,61) : error #18: expected a ")"
json/allocator.h(55,3) : error #20: identifier "size_type" is undefined
json/allocator.h(57,3) : error #20: identifier "pointer" is undefined
json/allocator.h(57,19) : error #20: identifier "reference" is undefined
json/allocator.h(59,3) : error #20: identifier "const_pointer" is undefined
json/allocator.h(59,25) : error #20: identifier "const_reference" is undefined
json/allocator.h(59,17) : error #403: invalid redeclaration of member function "Json::SecureAllocator::address() const" (declared at line 57)
json/allocator.h(64,16) : error #20: identifier "pointer" is undefined
json/allocator.h(72,47) : error #738: a class-qualified name is required

**Comment by dota17** [comment]
My suggest to delete `#include <type_traits>` is all based on your comment https://github.com/open-source-parsers/jsoncpp/issues/1051#issuecomment-547911173
So, just removed #include <type_traits> in include/json/config.h file, `not the other, no more other`. And I tested it in my local, it's ok to delete this header.

And now, we'd better to make it clear that what we really fucus on, is about memory leak in old version or is about compiler error in ARM compiler?

If we want to discuss ARM compiler error, we should in a new issue, not in a issue about memory leak.

PS: Before this issue is really fixed, we should not close/reopen it frequently, and we should use mrakdown syntax correctly in our comment.

**Comment by subithaparamasivan** [comment]
In this  issue id , we will discuss about only memory leak in old version. I will create one more issue id for jsoncpp 1.9.2 lib compiler error by using ARM compiler 5.
Before this issue is really fixed, we should not close/reopen it frequently, and we should use mrakdown syntax correctly in our comment.
    >> Sorry for your inconvenience . I will follow on the same.
Thanks,

**Comment by subithaparamasivan** [comment]
Is the similar issue is faced earlier in any one of issue id .
if so , please share to us. We will Integrate those changes in our old jsoncppver 1.0.0.
Kindly  let us know your feedback.

Thanks,
Thanks,

**Comment by subithaparamasivan** [comment]
could you please help on this issue .

**Comment by dota17** [comment]
Did you free the `root` when you call `parse(buffer, root)`?

**Comment by Hoohaha** [comment]
I met a same problem with 0.10.7(0.y.z). How to use workaround to free memory? My project used leagcy C++, it's hard to upgrade to C++ 11.

**Comment by dota17** [comment]
@Hoohaha 
> I would need to see more information about what is leaking. What is the source data that you used?
Need more information, such as your code or your input data.

**Comment by cdunn2001** [comment]
You can try an older `1.y.z` release, before we began to require C++11.

But anyway, maybe we should create a special release for `0.10.z` but with some fixes, plus the caveat that the ABI has changed. If anyone has time, we could do that. It's not exactly high priority.
