### ISSUE TITLE
In Function uintToString 

### ISSUE THREAD

**Issue by doveliu2019** [open-source-parsers/jsoncpp#1059]
The last member of the current must be assigned to '\0' instead of 0.

source :
static inline void uintToString(LargestUInt value, char*& current) {
  *--current = 0;
  do {
    *--current = char(value % 10) + '0';
    value /= 10;
  } while (value != 0);
}

**Comment by dota17** [comment]
The version of function you used looks like very old. In current active branch(even in 0.10.7), the code has changed: [link](https://github.com/open-source-parsers/jsoncpp/blob/master/src/lib_json/json_tool.h#L84)

**Comment by doveliu2019** [comment]
I means when a char array transfer to string, the last member of
