### ISSUE TITLE
Jsoncpp writing float values incorrectly

### ISSUE THREAD

**Issue by qokelate** [open-source-parsers/jsoncpp#1065]
**Describe the bug**

**To Reproduce**
example:
```
"Parameters":
{
"MinXValue": 0.1,
"MaxXValue": 0.15,
"MinYValue": 0.25,
"MaxYValue": 1.1,
"MinObjectSizeValue": 1
}
```

result:
```
"Parameters":
{
"MinXValue": 0.10000000000000001,
"MaxXValue": 0.14999999999999999,
"MinYValue": 0.25,
"MaxYValue": 1.1000000238418579,
"MinObjectSizeValue": 1
}
```

**Expected behavior**

**Desktop (please complete the following information):**
 - Meson version
 - Ninja version

**Additional context**

**Comment by schroeder-** [comment]
It is not a bug, it is the normal behavior of floating point values. They have a limited precession. So the values you see as output, are the values your programm is working with. You can reduce the output precesion and rounding:

 ```
Json::StreamWriterBuilder b;
 b.settings_["precision"] = 5;
 // b.settings_["precisionType"] = "significant"; // default
 b.settings_["precisionType"] = "decimal";
```

**Comment by qokelate** [comment]
resolved, thanks a lot!
