### ISSUE TITLE
template-based as<type>() accessor

### ISSUE THREAD

**Issue by JulianvDoorn** [open-source-parsers/jsoncpp#1066]
**Is your feature request related to a problem? Please describe.**
It's slightly disappointed when I have to write a helper function which allows to determine the type of the lookup at compile time.
**Describe the solution you'd like**
I wish to be able to call JsonValue::as<double>() as an alternative of JsonValue::asDouble().

**Describe alternatives you've considered**
I've written a function that uses metaprogramming features to determine the type which is being looked up at compile time. (assumes C++17, but I imagine an implementation is possible, SFINAE?):
```C++
template <class dat_type>
dat_type jsonValueAsType(const Json::Value& jsonVal) {
    if constexpr (std::is_same_v<dat_type, double>) {
        return jsonVal.asDouble();
    } else if constexpr (std::is_same_v<dat_type, float>) {
        return jsonVal.asFloat();
    }
}
```

**Additional context**
No additional context is required, I believe. But with focus of the C++ community to work towards better metaprogramming facilities, I think it is in place to add an JsonValue::as\<T\>() function.

**Comment by dota17** [comment]
Please submit a PR if that's really what you want.

**Comment by dota17** [comment]
Closing as fixed.
