### ISSUE TITLE
Equality of Value(Uint(4)) == Value(Int(4))

### ISSUE THREAD

**Issue by schwabe** [open-source-parsers/jsoncpp#1068]
**Describe the bug**

**To Reproduce**
A small unit test with Google test fails:

```
  Json::Value ji(Json::Int(4));
  Json::Value ju(Json::UInt(4));
  ASSERT_EQ(ji, ju);
  ASSERT_EQ(ju, ji);
```
fails with 

```
test_json.cpp:129: Failure
Expected equality of these values:
  ji
    Which is: 4
  ju
    Which is: 4
```

Small test program to test this without google test:

```
#include "json/json.h"             // JsonCpp library
#include <iostream>

int main (int argc, char** argv)
{
  Json::Value ji(Json::Int(4));
  Json::Value ju(Json::UInt(4));

  std::cout << "ji == ju:" << (ji == ju) << std::endl;
  std::cout << "ju == ji:" << (ju == ji) << std::endl;
}
```

also display 0 (=false) for both comparisons

**Desktop (please complete the following information):**
 - OS: macOS 10.15
 - jsoncpp 1.9.1 from homebrew

**Comment by dota17** [comment]
Good catch.
The problem is in the method `operator==`:
https://github.com/open-source-parsers/jsoncpp/blob/6c9408d12848773d74fb2c5879dab04851ddd901/src/lib_json/json_value.cpp#L549

Compare the types first, and compare the values when the types are same.
All the compare methods have this problem.

I am not sure if those codes are written based on special purposes.

**Comment by BillyDonahue** [comment]
I'm not sure this is a problem. Those are different Json::Value objects.
The held type is considered a salient value component of Json::Value.

It may be unexpected, and maybe the documentation is not clear enough.
But I wouldn't say the behavior is illogical or incorrect.

We internally hold all these distinct types, and have accessors to find out what type the Value is holding.

```
  union ValueHolder {
    LargestInt int_;
    LargestUInt uint_;
    double real_;
    bool bool_;
    char* string_; // if allocated_, ptr to { unsigned, char[] }.
    ObjectValues* map_;
  } value_;
```

It would be a real change in semantics to collapse numeric types together for the purpose of comparison operators.

**Comment by cdunn2001** [comment]
There's a fair argument that 2 Json values should be "equal" if their JSON representations would be identical. But I also understand BillyDonahue's argument. We might have to reserve this kind of change for 2.0.

After we improve our test coverage, we could start a 2.0 branch and start thinking about bigger changes.
