### ISSUE TITLE
Return success with invalid json

### ISSUE THREAD

**Issue by purewell** [open-source-parsers/jsoncpp#107]
input: 0:2:3
Json::Reader::parse returns true. But accessing member makes assert exception.

> json: src/lib_json/json_value.cpp:1176: const Json::Value& Json::Value::operator[](const char*) const: Assertion `type_ == nullValue || type_ == objectValue' failed.

test code:
```C
Json::Value root;
Json::Reader reader;

if ( not reader.parse("0:2:3", root) )
{
    cerr << "failed!" << endl;
    cerr << reader.getFormatedErrorMessages() << endl;
}
else
{
    cerr << "success!" << endl;
}

root.isMember("sss");

**Comment by cdunn2001** [comment]
I think it's parsing `0` as valid JSON, and ignoring `:2:3`. (Some complain about that, but that's another conversation.) `isMember()` requires a dictionary (i.e. *object*). (I'm not sure why we allow NULL, but that's too late to change.)

**Comment by cdunn2001** [comment]
Fixed with `failIfExtra` feature.
