### ISSUE TITLE
Question; Is there an up to date libCurl and Jsoncpp example code?

### ISSUE THREAD

**Issue by Alppuccino** [open-source-parsers/jsoncpp#1073]
Title - All of the examples I have found use the deprecated Json::Reader and FastWriter, is there an up to date version of these? If not, can someone help me update this [Curl HTTP GET and JsonCpp parsing code](https://gist.github.com/connormanning/41efa6075515019e499c), please? Thanks.

**Comment by dota17** [comment]
hi
In fact, the new classes **Json::StreamWriterBuilder** and **Json::CharReaderBuilder** have been added into these examples. Moreover，Jsoncpp has good compatibility and these eprecated classes still can be used theoretically.
 I suggest you use the new classes  by referring to the test case/examples. especially， the **readFromString.cpp** and **stringWrite.cpp** (jsoncpp/example/) are very suitable for you.
