### ISSUE TITLE
How about a 1.9.2 release?

### ISSUE THREAD

**Issue by mloy** [open-source-parsers/jsoncpp#1074]
Hello,

we are using version 1.8.4 in lots of places, pc and embedded. It would be really nice to upgrade to 1.9.1 in order to have all the great new stuff. 

Unfortunately this version has problems being build with our cross compilation toolchain.

Those problems are fixed in master. Is there a release plan for 1.9.2?

**Comment by dota17** [comment]
Yes, a lot of fixes and updates have merged into master branch, A new release could be in the plan.

**Comment by baylesj** [comment]
I have issued a pre-release 1.9.2. I'm still getting used to the workflow of how we manage releases, so I want to try a few more pre-releases before issuing a proper "stable" release.

Please feel free to check it out and report bugs with it.

**Comment by mloy** [comment]
Great, I think we are going to use this in some development branches.

Thank you very much!
