### ISSUE TITLE
Upgrading to Python 3

### ISSUE THREAD

**Issue by jakirkham** [open-source-parsers/jsoncpp#1081]
**Is your feature request related to a problem? Please describe.**

It appears that Python 2.6 is used in some places like [here]( https://github.com/open-source-parsers/jsoncpp/blob/80bc776bae74261742b7c2d0b8dc31ec1718ba4a/makerelease.py#L8 ) and [here]( https://github.com/open-source-parsers/jsoncpp/blob/aebc7faa4fa69fa16ffe9082d03a3527120d5fa3/src/jsontestrunner/CMakeLists.txt#L1 ). However Python 2.6 has long since reach its EOL. Not to mention Python 2.7 will not be supported further in the new year.

**Describe the solution you'd like**

It would be good to move all scripts to support Python 3.

**Describe alternatives you've considered**

A good compromise would be to get all of the scripts to support Python 2/3, which should continue to work after Python 2 reaches its EOL.

**Additional context**

Here's the [Python EOL guide]( https://devguide.python.org/devcycle/#end-of-life-branches ).

**Comment by cdunn2001** [comment]
I've deleted makerelease.py (#1082). Problem solved! :smile:

@hjmjohnson, Could you take care of py2.6 in CMake?

* https://github.com/open-source-parsers/jsoncpp/blob/aebc7faa4fa69fa16ffe9082d03a3527120d5fa3/src/jsontestrunner/CMakeLists.txt#L1

Note: We actually run jsontestrunner via Meson in TravisCI, using python3, so I don't think the python version actually matters.

... Oh, we actually still use CMake -- in the AppVeyor build. I think that runs jsontestrunner too -- yes, `jsontestrunner_exe.vcxproj` -- so we have a test for whatever change you make. I just hate dealing with CMake at all. I wonder if we could use Meson in AppVeyor.

**Comment by hjmjohnson** [comment]
OK. Moving to python3 only for support.
