### ISSUE TITLE
version.h is missing in release packet

### ISSUE THREAD

**Issue by eigen2017** [open-source-parsers/jsoncpp#1094]
https://github.com/open-source-parsers/jsoncpp/archive/1.9.1.tar.gz

newest release don't have version.h file

**Comment by cdunn2001** [comment]
Doesn't running `cmake` or `meson` generate the `version.h` file for the given version?

**Comment by cdunn2001** [comment]
https://github.com/open-source-parsers/jsoncpp/wiki/Building

**Comment by dota17** [comment]
@eigen2017 Thanks for reporting. the release package 1.9.1.zip and 1.9.1.tar.gz are indeed missing head file version.h, this is a small operational error.
