### ISSUE TITLE
fatal error: cpptl/smallmap.h: No such file or directory

### ISSUE THREAD

**Issue by eigen2017** [open-source-parsers/jsoncpp#1097]
i opened this config:
```c
#  define JSON_USE_CPPTL_SMALLMAP 1
```
and got fatal error

anyone can help to give a instruction for how to using smallmap in jsoncpp ?
thks!!

**Comment by eigen2017** [comment]
i only find smallmap.h in cppunit project:
https://sourceforge.net/projects/cppunit/files/latest/download
is smallmap.h a component in cpp unit test framework?
it's wierd..

**Comment by baylesj** [comment]
As far as I can tell, this define dates back all the way to the beginning of JsonCpp.

I don't know what CPPTL is, what the use case is, or if we even intend to support it. The code around CPPTL hasn't changed in 12 years.

@blep / @cdunn2001 what is CPPTL support and can we just delete it?

**Comment by cdunn2001** [comment]
I think at this point we could drop CPPTL support.

**Comment by eigen2017** [comment]
> As far as I can tell, this define dates back all the way to the beginning of JsonCpp.
> 
> I don't know what CPPTL is, what the use case is, or if we even intend to support it. The code around CPPTL hasn't changed in 12 years.
> 
> @blep / @cdunn2001 what is CPPTL support and can we just delete it?

thks for replying so soon，i just want to know is there any config for jsoncpp can improve performance when parsing a large string ?

parse a 245kb json string costs 10ms，and perf report shows that the recursive function：
readValue cause the main cost

**Comment by eigen2017** [comment]
i used 0.10.7
i will try 1.8.4 and report the performance here~

**Comment by eigen2017** [comment]
1.8.4 costs even little higher than 0.10.7

**Comment by baylesj** [comment]
It's not surprising that most of the cost is in `readValue`, after all that's the primary job of a JSON parser so most of our time should be spent there.

JsonCpp is actually pretty reasonably fast. I don't have anything more modern unfortunately, but here's a benchmark from a few years ago (https://blog.thousandeyes.com/efficiency-comparison-c-json-libraries/) and it seems to agree with your findings.

I'll take a look and see if there are any easy avenues for optimization, but if JsonCpp is simply not fast enough for your use case I would suggest trying a different library more optimized for speed, like [RapidJson](https://rapidjson.org/) or [Jsmn](https://github.com/zserge/jsmn). We have a lot of code for compatibility which makes our library larger and probably costs us in performance signficantly in some cases.

One suggestion: have you tried running JsonCpp in strict mode? For an example of this, see this code snippet:
https://chromium.googlesource.com/openscreen/+/refs/heads/master/util/json/json_reader.cc

**Comment by eigen2017** [comment]
> It's not surprising that most of the cost is in `readValue`, after all that's the primary job of a JSON parser so most of our time should be spent there.
> 
> JsonCpp is actually pretty reasonably fast. I don't have anything more modern unfortunately, but here's a benchmark from a few years ago (https://blog.thousandeyes.com/efficiency-comparison-c-json-libraries/) and it seems to agree with your findings.
> 
> I'll take a look and see if there are any easy avenues for optimization, but if JsonCpp is simply not fast enough for your use case I would suggest trying a different library more optimized for speed, like [RapidJson](https://rapidjson.org/) or [Jsmn](https://github.com/zserge/jsmn). We have a lot of code for compatibility which makes our library larger and probably costs us in performance signficantly in some cases.
> 
> One suggestion: have you tried running JsonCpp in strict mode? For an example of this, see this code snippet:
> https://chromium.googlesource.com/openscreen/+/refs/heads/master/util/json/json_reader.cc

many thanks for these detailed suggestions, strict mode is slightly faster.  about 1 to 2 ms faster.
