### ISSUE TITLE
Warning in CZString copy constructor

### ISSUE THREAD

**Issue by jmbushman** [open-source-parsers/jsoncpp#110]
When compiling with GCC v4.7.0 and v4.6.3 with the -Wextra flag, I get the following warning:

$ g++ -m32 -std=c++0x -Wextra -I. -c jsoncpp.cpp
jsoncpp.cpp: In copy constructor ‘Json::Value::CZString::CZString(const Json::Value::CZString&)’:
jsoncpp.cpp:1650:26: warning: enumeral and non-enumeral type in conditional expression [enabled by default]

**Comment by cdunn2001** [comment]
Already fixed in #84.

You need to run

    python amalgamate.py
to get the latest code into `dist/jsoncpp.cpp`.
