### ISSUE TITLE
Static linking using Visual Studio 2019

### ISSUE THREAD

**Issue by julianxhokaxhiu** [open-source-parsers/jsoncpp#1111]
**Is your feature request related to a problem? Please describe.**
I am trying to include your library within my code, but unfortunately I'm not able to build your library using Static linking ( MT/MTd ).

**Describe the solution you'd like**
You could potentially set the policy `CMP0091` to `NEW` in your CMakeLists.txt which could then allow anyone including as third_party your library to pass the variable `CMAKE_MSVC_RUNTIME_LIBRARY` which will take care automatically to add the relative flags to the linker.

**Describe alternatives you've considered**
Maybe another C++ JSON library.

**Additional context**
None.

**Comment by cdunn2001** [comment]
You'd have to submit a pull-request. We test VS, but we don't actually use it ourself.

Also, we don't maintain the **cmake** files at all. You'd have to submit PRs for those. We use **meson** now.

**Comment by cdunn2001** [comment]
Fixed by #1259.
