### ISSUE TITLE
CMake build failure

### ISSUE THREAD

**Issue by baylesj** [open-source-parsers/jsoncpp#1113]
Scanning dependencies of target jsoncpp_test
[ 38%] Building CXX object src/test_lib_json/CMakeFiles/jsoncpp_test.dir/main.cpp.o
/usr/local/src/jsoncpp/[src/test_lib_json/main.cpp:128](https://github.com/open-source-parsers/jsoncpp/blob/a3c8642886b348d4f8fcb5384266c3a94ffe66b3/src/test_lib_json/main.cpp#L128):41: error: implicit conversion changes signedness: 'int' to
      'unsigned long' [-Werror,-Wsign-conversion]
  auto exponentStartIndex = index + 1 + hasSign;
                                      ~ ^~~~~~~
1 error generated.

**Comment by BillyDonahue** [comment]
The warning isn't wrong. The `hasSign` on the preceding line should be a `size_t`.
