### ISSUE TITLE
JsonCpp installation / deployment methods

### ISSUE THREAD

**Issue by jbsysadmin** [open-source-parsers/jsoncpp#1119]
Greetings! 
I write because a user has requested a Bamtools installation, and this JsonCpp is a dependency. 
Many people have releases that place items in system directories of local machines. In your release JsonCpp, is there any way to deploy this to an arbitrary, non-system, named directory which might be referenced by a PATH addition? (In many compilations, there is a standard step "configure" which takes care of this, with "prefix=<location>") Thanks for any leads.

The workflow you list on your website probably won't work, if we need an arbitrary location for the files or wish to deploy internally by custom RPM.
---- your docs ---
_You can download and install JsonCpp using the vcpkg dependency manager:_
_git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.sh
./vcpkg integrate install
vcpkg install jsoncpp_

**Comment by jbsysadmin** [comment]
Note that, in Centos 6.10, using the instructions at bottom, the builds failed for jsoncpp-1.8.0, jsoncpp-1.8.4, and jsoncpp-1.9.2. One such error from the 2nd of the attempts is below:

--- error ---
In file included from /usr/local/installs/jsoncpp-1.8.4/include/json/reader.h:11,
                 from /usr/local/installs/jsoncpp-1.8.4/src/lib_json/json_reader.cpp:9:
/usr/local/installs/jsoncpp-1.8.4/include/json/value.h:404: error: only declarations of constructors can be ‘explicit’

--- steps ---
mkdir -p build/debug
cd build/debug
cmake -DCMAKE_BUILD_TYPE=debug -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_INCLUDEDIR=include/jsoncpp -DARCHIVE_INSTALL_DIR=. -G "Unix Makefiles" ../..
make

**Comment by dota17** [comment]
@jbsysadmin Sorry for replying so late. 
1) If your problem is that the deployment with vcpkg fails in Linux, then you can refer to this [link](https://github.com/microsoft/vcpkg/issues/7951).
2) and you can also specify the installation path via cmake options `DARCHIVE_INSTALL_DIR` or `LIBRARY_INSTALL_DIR`. 
3) In my machine, building jsoncpp 1.8.4 or 1.9.2 with cmake didn't cause the problem you wrote. so, can you provide more info about your environment? e.g. your cmake version?

**Comment by jbsysadmin** [comment]
It seems I was finally able to build 1.9.2. “make” didn’t have any errors.
However, the pre-make step ended in:

CMake Warning:
  Manually-specified variables were not used by the project:

    ARCHIVE_INSTALL_DIR
    BUILD_STATIC_LIBS
    LIBRARY_INSTALL_DIR


The context is that a requested build Bamtools 2.5.1 has this as a dependency. I need the locations of the resulting binary and libraries, for PATH & LD_LIBRARY_PATH, respectively. I need the output for be somewhere other than system library locations. If local, that needs to be portable by rsync to an NFS location.

**Comment by cdunn2001** [comment]
If you can help us fix the "vcpkg" script, please submit a PR. It would be welcome.

We normally use **meson** to build/install, and it definitely provides the feature you desire.
