### ISSUE TITLE
amalgamate.py on windows (fix)

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [open-source-parsers/jsoncpp#1129]
**Describe the bug**
`py amalgamate.py` does not work on windows console

**Expected behavior**
print to console and execute the script

**Desktop (please complete the following information):**
 - OS: Windows 10

**Fix**
The shebang (top line) is preventing windows from running the script correctly.
Take out the shebang on windows and run the command with
`py amalgamate.py COMMAND_LINE_ARGUMENTS`

The script will work as expected.

[Read more](https://stackoverflow.com/questions/47227301/python-script-doesnt-print-output-in-command-prompt)

**Comment by dota17** [comment]
Move to [FAQ](https://github.com/open-source-parsers/jsoncpp/wiki/FAQ#py_amalgamatepy_does_not_work_on_windows_console)
Thanks your help.
