### ISSUE TITLE
Validate the key when we try to access it.

### ISSUE THREAD

**Issue by Rullec** [open-source-parsers/jsoncpp#1135]
Hi guys, I have been working on a project that jsoncpp have a big benefit. Thank you for this excellent work!

But I truly get a little confused that why the jsoncpp can not throw out an exception, when we try to access such an **invalid key**. for example:
```
Json::Value root;
// parsing it properly
// and then: this line didn't report any error
double value = root["invalid key"].asDouble();
return 0;
```
I know the method "isNull" for json::Value which can judge the key validity of it. But it would be dirty to have it each time when I try to evaluate a value. 

I also searched on SO for a while, ang a guy said that "it is designed as it is, and we have no way".

1. Is it true? Maybe we can let the user to decide this behavior just like "JSON_CPP_THROW_INVALID_KEY". 

2. Maybe it exsits but I just don't know. Would you please give me a help on it?

Thanks in advance:)
Xudong

**Comment by dota17** [comment]
Json::Value uses std::map to store value, so its behavior is same as std::map sometimes.
And when you use std::map, you also need to judge.

However, there is a way to solve your problem-override the operator[] and other related methods to support the validity.

**Comment by Rullec** [comment]
> Json::Value uses std::map to store value, so its behavior is same as std::map sometimes.
> And when you use std::map, you also need to judge.
> 
> However, there is a way to solve your problem-override the operator[] and other related methods to support the validity.

Thank your for the reply. I will ovverride it.
So is this the designed idea? If it is, please close this issue :)

**Comment by dota17** [comment]
I can't give you a very positive answer.
But from the implementation, it seems to be true.
