### ISSUE TITLE
How to format the json output in a more flexible way

### ISSUE THREAD

**Issue by Rullec** [open-source-parsers/jsoncpp#1147]
Hi all,
&nbsp;Thank you for this great project, It helps a lot! I work on OS X Mojave and gets my jsoncpp from brew, the version info shows below:
```
>> brew info jsoncpp
jsoncpp: stable 1.9.1 (bottled), HEAD
Library for interacting with JSON
https://github.com/open-source-parsers/jsoncpp
/usr/local/Cellar/jsoncpp/1.9.1 (23 files, 282.9KB) *
  Poured from bottle on 2020-01-31 at 16:21:33
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/jsoncpp.rb
==> Dependencies
Build: meson ✘, ninja ✘
==> Options
--HEAD
Install HEAD version
```

&nbsp;But recently I have **a small problem about jsoncpp output formatting**. When I use the default configuration over the Json::StreamWriterBuilder, I can get a quite loose output like this:
```
"key1" : 1,
"key2": 2,
"key3" : 
[
  0.0,
  2.0,
  2.0,
  3.0,
  4.0,
  6.0,
  7.0,
],
"key4":
[
  0.0,
  2.0,
  2.0,
  3.0,
  4.0,
  6.0,
  7.0,
]
```
After then, I set the the "indentation"="", I get a extremely compat output like this:
```
"key1" : 1, "key2": 2, "key3" : [0.0, 2.0, 2.0, 3.0, 4.0, 6.0, 7.0], "key4": [0.0, 2.0, 2.0, 3.0, 4.0, 6.0, 7.0, ]
```
**And I am wondering if it is possible for me to get:** an intermediate configuration.
```
"key1" : 1,
"key2": 2,
"key3" : [0.0, 2.0, 2.0, 3.0, 4.0, 6.0, 7.0],
"key4": [0.0, 2.0, 2.0, 3.0, 4.0, 6.0, 7.0, ]
```
I check the doc carefully and can not find an evidence.
Thans a lot in advance!

**Comment by dota17** [comment]
I'm afraid that this project doesn't support such kind of intermediate configuration now.
If you really want that, pull requests are welcome.

**Comment by Rullec** [comment]
> I'm afraid that this project doesn't support such kind of intermediate configuration now.
> If you really want that, pull requests are welcome.

Thanks you for your reply, I will try it. Basicly I'm a newbie in both github and open source project, and feel a little nervous for trying to contribute to a great project now:).

So can I infer that what I can do is, just developing the desired functionality along with obeying the coding rules in jsoncpp and commit it as a "Pull Request", then it will be judged to be admit or refused? Is it true for the correct working pipeline?

I will try to do it in my spare time. :) Maybe now this issue can be closed(I'm not sure whether it is the correct pipeline, sorry), Thank you.

**Comment by dota17** [comment]
Yes, basically you're right. you can clone this repo in your local, make some developing, then commit and upload your change, people will review your code, and give some suggestions for changes, etc. 
That's it, have fun!
