### ISSUE TITLE
cmake install jsoncpp in centos gcc-4.8.5

### ISSUE THREAD

**Issue by YanMario** [open-source-parsers/jsoncpp#1148]
err:错误：‘hexfloat’不是‘std’的成员
     oss << std::setprecision(16) << std::hexfloat << value;

是因为gcc版本过低吗？

**Comment by dota17** [comment]
Yes, `std::hexfloat` starts from C++17, your gcc version is too low to support it.

**Comment by YanMario** [comment]
解决方案，临时升级gcc版本：
yum -y install centos-release-scl
yum -y install devtoolset-6-gcc devtoolset-6-gcc-c++ devtoolset-6-binutils
scl enable devtoolset-6 bash

**Comment by dota17** [comment]
OK, thanks for reporting.
