### ISSUE TITLE
Json::Value::end() broken?

### ISSUE THREAD

**Issue by jimvonmoon** [open-source-parsers/jsoncpp#115]
In MSVC 2013 following code generates infinite loop:
```
Json::Value root; // root isn't empty and contains one Object value.
// ...
for(auto iter = root.begin(); iter != root.end(); ++iter) { ... }
```
However these work as expected:
```
for(auto iter = root.begin(), end = root.end(); iter != end; ++iter) { ... }

for(auto& val : root) { .. }
```

**Comment by cdunn2001** [comment]
Hmm. Works with `clang++ -std=c++11`. I just tried it.
```
#include <iostream>
#include <json/value.h>

void test115() {
  Json::Value root; // root isn't empty and contains one Object value.
  root["foo"] = "bar";
  for(auto iter = root.begin(); iter != root.end(); ++iter) {
    //
  }
}
int main() {
  std::cout << "hello\n";
  test115();
  return 0;
}
```
Maybe you're modifying `root` inside your loop?

Otherwise, we'll need you to debug this somehow. If you have visual studio, can you step into the iterators?

Also, which commit are you using? People sometimes use old code from source-forge.

**Comment by cdunn2001** [comment]
Re-open if it recurs. And please provide:
* commit
* exact OS
* cmake command
