### ISSUE TITLE
Some thoughts and suggestions about jsoncpp

### ISSUE THREAD

**Issue by dota17** [open-source-parsers/jsoncpp#1151]
Currently, this community seems not very active, but there are still some issues left to deal with. This is not a good signal for a popular open source software, so I will try to push some issues and make them go forward.
At the same time, I also have some thoughts and questions, so I open this new issue, and everyone can discuss here.
- Firstly, more than two years have passed since the release of the last `stable version`, a lot of commits have accepted, and we just released a few `pre-released` versions, is it time to release a stable version? 

- Secondly, the latest release is 0.10.7, and it was released two years ago. We know that the 0.y.z branch is for compatibility for older compilers and environment. But this branch is too old, some users are in an awkward situation: they want to try some new features on the 1.y.z branch, but their environment only supports the 0.y.z version, but the current 0.10.7 version has not been upgraded for a long time, so it is time for us to consider upgrade the 0.y.z branch. 
- Thirdly, following the previous point, I still have questions about the release standard for the 0.y.z branch. How do we release this version? Do we really need to release two versions? There should be a way to unify them, such as by compiling switches. 

Recently, I did receive complaints from some users that they didn't know which version to choose.  If two versions are selected at the same time, the maintenance cost will be doubled.

The best way I can think of is that there is a `develop branch`, a `release branch` or a release version, and the release version number is uniform, and the release version only through some compilation skills to choose the environment required for compilation.
Do you have any ideas or suggestions?
@baylesj @BillyDonahue @blep @cdunn2001 @hjmjohnson

**Comment by dota17** [comment]
From the git histroy, i found that when we release the new `0.y.z` version from the master, we have to do a lot of repeating works. From examples, revert some changes:
![image](https://user-images.githubusercontent.com/50514813/79230235-da3f5800-7e96-11ea-8d3a-9e383cda3992.png)

What i want is that there is a only a code branch, people can build the library in different env - pre C++11 or C++11. Of course, the library built in pre C++11 must be *binary* compatible with `0.y.z` versions. So does the library built in C++11.

**Comment by neheb** [comment]
Probably should add a buildbot that forces c++98 mode if you really want to keep compatibility.
