### ISSUE TITLE
Error building jsoncpp with GCC-4.9.4

### ISSUE THREAD

**Issue by vandanphadke** [open-source-parsers/jsoncpp#1152]
I'm getting an error while building the package with GCC-4.9.4. 

c++locale.h:52:23: error: 'uselocale' was not declared in this scope
   extern "C" __typeof(uselocale) __uselocale;
                       ^
error: invalid type in declaration before ';' token
   extern "C" __typeof(uselocale) __uselocale;
                                             ^
c++locale.h:75:53: error: '__gnu_cxx::__uselocale' cannot be used as a function
     __c_locale __old = __gnu_cxx::__uselocale(__cloc);
                                                     ^
c++locale.h:100:33: error: '__gnu_cxx::__uselocale' cannot be used as a function
     __gnu_cxx::__uselocale(__old);

**Comment by dota17** [comment]
How did you build the project? with Meson or CMake? Can you provide more details about your problem?

**Comment by vandanphadke** [comment]
Built using Cmake version 4

**Comment by cdunn2001** [comment]
This would only work with an older version of **jsoncpp**. You did not even specify the version of branch. This is an open-source project, so we cannot spend huge amounts of time. We did try to ensure that older releases worked with older compilers, and we *might* be able to fix a problem on an older branch in that regard, but you would have to be extremely specific.
