### ISSUE TITLE
Memory Leak when creating a variable Json::Value var

### ISSUE THREAD

**Issue by nsmohan** [open-source-parsers/jsoncpp#1157]
**Describe the bug**
Valgrind detects memory leak . If I have a simple program like the one below and I do is create a Json::Value variable. 

#include <iostream>
#include <map>
#include <jsoncpp/json/json.h>

using namespace std;
int main()
{
    Json::Value test;
    cout << "Hello World!" << endl;
    return 0;
}

$valgrind Test/a.out 
==12078== Memcheck, a memory error detector
==12078== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==12078== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==12078== Command: Test/a.out
==12078== 
Hello World!
==12078== 
==12078== HEAP SUMMARY:
==12078==     in use at exit: 40 bytes in 1 blocks
==12078==   total heap usage: 3 allocs, 2 frees, 73,768 bytes allocated
==12078== 
==12078== LEAK SUMMARY:
==12078==    definitely lost: 0 bytes in 0 blocks
==12078==    indirectly lost: 0 bytes in 0 blocks
==12078==      possibly lost: 0 bytes in 0 blocks
==12078==    still reachable: 40 bytes in 1 blocks
==12078==         suppressed: 0 bytes in 0 blocks
==12078== Rerun with --leak-check=full to see details of leaked memory
==12078== 
==12078== For counts of detected and suppressed errors, rerun with: -v
==12078== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**To Reproduce**
1. Create a simple program like the Hello World example above.
2. Create a Json::Value variable and do nothing with it. 
3. Compile and run with valgrind. > Report will show 40 bytes lost. 

**Expected behavior**
No memory leak. 

**Desktop (please complete the following information):**
 - OS: Unbuntu
 - Meson version
 - Ninja version

**Additional context**

**Comment by BillyDonahue** [comment]
Thank you for the report, but there is no memory leak reported here.

`==12078== still reachable: 40 bytes in 1 blocks`

There are 40 _reachable_ bytes, in one block.
(This is probably the immortal null value singleton.)

May be useful to rerun with --leak-check=full to confirm this if you like.
Reopen if that reveals something unexpected though!
