### ISSUE TITLE
Documentation outdated (removeMembers)

### ISSUE THREAD

**Issue by hrkrshnn** [open-source-parsers/jsoncpp#1161]
**Describe the bug**
Doxygen documentation seems to be outdated.

**To Reproduce**
The documentation [here](http://open-source-parsers.github.io/jsoncpp-docs/doxygen/class_json_1_1_value.html#aa52f7873b95d29627d6e83ba96f69aaa) about the function `removeMembers` is outdated. It says that the members are deprecated and also have incorrect signature (`Value` instead of `void`.)

**Comment by dota17** [comment]
Sorry, the document produced by Doxygen is based on JsonCpp-1.8.3, howerver the current version is 1.9.2, so the document is indeed outdated. If you have time and interest, welcome to update it from [here](https://github.com/open-source-parsers/jsoncpp-docs#documentation-for-jsoncpp).

**Comment by cdunn2001** [comment]
We'll update the docs soon after we tag a new release. Thanks for reminding us.
