### ISSUE TITLE
Undefined Reference to Json::Reader::Reader() and many more

### ISSUE THREAD

**Issue by laneciar** [open-source-parsers/jsoncpp#1164]
**Describe the bug**
I am getting 141 errors to undefined references of various functions in classes when trying to build so I am assuming this is a compiler error.
**To Reproduce**
1. Include json.h and use one of its functions
2. Build project and it will show that it is a undefined reference

**Expected behavior**
To build and run without error
**Desktop (please complete the following information):**
 - OS: x64 windows
- Built using mingw64 and vcpkg
- Using within Qt Creator
- Compiler is mingwx64
- Made sure to download x64-jsoncpp

**Additional context**
This may just be an error on my side but i cant seem to get it working on QT and it is a key part of my program, i am trying to use an api from iex cloud and I cant seem to get jsoncpp to work, I will attach pictures of everything below.

[Pictures](https://imgur.com/a/meY9GQ8)

**Comment by dota17** [comment]
I can't debug your problem in QT Creator, So i can't do much help.
From your pictures, it seems that you are using jsoncpp ver 1.9.1, I suggest you use the latest version.
And for more similar discussions, you can see [here](https://github.com/open-source-parsers/jsoncpp/issues/738).
