### ISSUE TITLE
Large memory consumption when to build large Object and write to a file

### ISSUE THREAD

**Issue by zegang** [open-source-parsers/jsoncpp#1179]
A large object which has lots of sub-items will consume large memory and even failing as requiring more memory than VM/memory usage limitation.

How to build a large object (lots of sub-items) and write to a file ? Does jsoncpp support SAX ?

**Comment by dota17** [comment]
> Does jsoncpp support SAX ?

It seems that the library doesn't support. I am thinking about it and welcome for PRs.
