### ISSUE TITLE
Inconsistent tags

### ISSUE THREAD

**Issue by egorpugin** [open-source-parsers/jsoncpp#1181]
Hi,

You had all tags without `v` prefix like `1.9.2`, now it's `v1.9.3`.
This breaks some scripts.
Is it possible to use consistent tags?

**Comment by dota17** [comment]
@baylesj  Please take a look.

**Comment by extrimexxx** [comment]
![awfawfaf](https://user-images.githubusercontent.com/33065618/83384712-494e1d00-a401-11ea-9ade-d9b3be737970.png)

@dota17

**Comment by dota17** [comment]
Done.
![image](https://user-images.githubusercontent.com/50514813/83389039-19fbd800-a422-11ea-95e0-45237b152075.png)

![image](https://user-images.githubusercontent.com/50514813/83389016-0badbc00-a422-11ea-9c40-0e9a960c73a4.png)

**Comment by dota17** [comment]
Is it ok to delete the inconsistent tag  `v1.9.3`? I am not sure. @baylesj

**Comment by baylesj** [comment]
That's fine.

**Comment by TheStormN** [comment]
Removing the inconsistent flag actually failed the Conan package... You should be more careful when removing URL's.
