### ISSUE TITLE
Errors in testsuite log

### ISSUE THREAD

**Issue by diizzyy** [open-source-parsers/jsoncpp#1184]
**Describe the bug**
Test suit contains errors but still passes

**To Reproduce**
Run tests

**Expected behavior**
Shouldn't generate errors

**Desktop (please complete the following information):**
 - OS: FreeBSD 13-CURRENT
 - Meson version - 0.54.2
 - Ninja version - 1.10.0
 - Python version - 
[testlog.txt](https://github.com/open-source-parsers/jsoncpp/files/4721913/testlog.txt)
3.7.7

**Additional context**
See attached log

**Comment by dota17** [comment]
What I see in your testlog is all test passed.
> Ok:                 3   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

some failures are expected, because we parse some ill-formed json data to test if it can detect the error correctly.

**Comment by diizzyy** [comment]
Ok, so those are "normal" errors?

**Comment by dota17** [comment]
> Ok, so those are "normal" errors?

Yep, that shows the parse function work normal, or to say, it can recognize the error json string and print error info.

**Comment by diizzyy** [comment]
I see, thanks for the clarification
