### ISSUE TITLE
Undefined Reference to functions/constructors/destructors

### ISSUE THREAD

**Issue by Robonics** [open-source-parsers/jsoncpp#1186]
I recently installed jsoncpp for a project I am working on, I have a JSON that contains data for the App to read that determines the stats for certain objects. I went to compile with MinGW using the include Directory with a `-I` line argument. It originally compiled fine, but after I added the following code:
```
    Json::Value cardData;
    cardData_v_file >> cardData;
```
my compiler began returning the following output:
```
C:\Users\ezj21\AppData\Local\Temp\ccBdAuuf.o:main.cpp:(.text+0x5e): undefined reference to `Json::Value::Value(Json::ValueType)'
C:\Users\ezj21\AppData\Local\Temp\ccBdAuuf.o:main.cpp:(.text+0x6e): undefined reference to `Json::operator>>(std::istream&, Json::Value&)'
C:\Users\ezj21\AppData\Local\Temp\ccBdAuuf.o:main.cpp:(.text+0xa3): undefined reference to `Json::operator<<(std::ostream&, Json::Value const&)'
C:\Users\ezj21\AppData\Local\Temp\ccBdAuuf.o:main.cpp:(.text+0x102): undefined reference to `Json::Value::~Value()'
C:\Users\ezj21\AppData\Local\Temp\ccBdAuuf.o:main.cpp:(.text+0x124): undefined reference to `Json::Value::~Value()'
collect2.exe: error: ld returned 1 exit status
```
I haven't the foggiest how to fix this and I was wondering if someone knew what to do.

**Comment by Robonics** [comment]
I tried adding a `-L ${pathToLibrary}` as suggested in [this](https://github.com/open-source-parsers/jsoncpp/issues/738) issue and that did not make any difference

**Comment by BillyDonahue** [comment]
I'm not a MinGW person and haven't used it in a while, so this half a guess.

`-L` adds directories to the linker's search path.
you also need to say which library you want. So usually there's a `-L${libdir} -ljsoncpp`,
This will find a `${libdir}/libjsoncpp.dll` shared library.

You can also just directly put a full path to the `${libdir}/libjsoncpp.dll` on your linker's command line just like you would list any object file, and that should work too.

**Comment by Robonics** [comment]
I tried both `g++ main.cpp player.cpp vcpkg/installed/x86-windows/bin/jsoncpp.dll -I vcpkg/installed/x86-windows/include` and `g++ main.cpp player.cpp -I vcpkg/installed/x86-windows/include -L vcpkg/installed/x86-windows/bin -l jsoncpp.dll` and neither worked, the later of the two told me it couldn't find `'jsoncpp.dll'` even though I could look at it in the directory and the former gave me the same error as before.

**Comment by Robonics** [comment]
Would it be a good idea to attempt installing jsoncpp via another method than vcpkg?

**Comment by BillyDonahue** [comment]
http://www.mingw.org/wiki/specify_the_libraries_for_the_linker_to_use

Try replacing`-l jsoncpp.dll` with `-ljsoncpp` ? (no space, no filename extension)

**Comment by Robonics** [comment]
Well it did something *different*, just nothing good:
```
C:\Users\ezj21\OneDrive\Desktop\peternityCardGame>g++ main.cpp player.cpp -I vcpkg/installed/x86-windows/include -L vcpkg/installed/x86-windows/bin -ljsoncpp -o PeternityCards.exe
C:/mingw/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible vcpkg/installed/x86-windows/bin/jsoncpp.dll when searching for -ljsoncpp       
C:/mingw/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible vcpkg/installed/x86-windows/bin/jsoncpp.dll when searching for -ljsoncpp       
C:/mingw/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ljsoncpp
collect2.exe: error: ld returned 1 exit status
```

**Comment by Robonics** [comment]
It obviously sees the DLLs but chooses to ignore them for some reason?

**Comment by BillyDonahue** [comment]
Try `objdump.exe -x vcpkg/installed/x86-windows/bin/jsoncpp.dll`

And see if it agrees with your expectations.
You might have a 32-bit vs 64-bit incompatibility?

**Comment by Robonics** [comment]
I did update to a 64 Bit Version of MinGW because the 32 bit version for some reason had issues with `std::this_thread` being undeclared as a namespace, also what am I looking for because that command sent a lot to the console

**Comment by Robonics** [comment]
Ok, I did some research and I *think* that the DLL is 32 bit. Is there a 64 bit version somewhere because I will need `std::this_thread` for this project
