### ISSUE TITLE
Compilation warnings with gcc 10

### ISSUE THREAD

**Issue by Shaac** [open-source-parsers/jsoncpp#1188]
**Describe the bug**
Compile jsoncpp with gcc 10 triggers deprecated compilation warnings.
```
src/lib_json/json_reader.cpp:756:34: warning: ‘Reader’ is deprecated: Use CharReader and CharReaderBuilder instead. [-Wdeprecated-declarations]
  756 | Reader::Char Reader::getNextChar() {
      |                                  ^
In file included from src/lib_json/json_reader.cpp:10:
/usr/include/json/reader.h:37:63: note: declared here
   37 |     "Use CharReader and CharReaderBuilder instead.") JSON_API Reader {
      |                                                               ^~~~~~
src/lib_json/json_reader.cpp:810:21: warning: ‘Reader’ is deprecated: Use CharReader and CharReaderBuilder instead. [-Wdeprecated-declarations]
  810 | std::vector<Reader::StructuredError> Reader::getStructuredErrors() const {
      |                     ^~~~~~~~~~~~~~~
In file included from src/lib_json/json_reader.cpp:10:
/usr/include/json/reader.h:37:63: note: declared here
   37 |     "Use CharReader and CharReaderBuilder instead.") JSON_API Reader {
      |        
```

Here json cpp triggers deprecated warnings from itself. How to proceed here is a question of policy. I guess it would be acceptable to say it is a bug/strange behavior from gcc, and not do anything about it. But I wanted you to have the information so that you could make the best with it.

**To Reproduce**
1. Compile json_reader.cpp with gcc 10 (`g++ -c src/lib_json/json_reader.cpp`)

**Expected behavior**
Should not have compilation warnings

**Desktop (please complete the following information):**
 - OS: Archlinux
 - gcc version 10.1.0

**Comment by dota17** [comment]
The deprecated compilation warnings is expected because you are using very old APIs. The policy is to warn users, inform them to use CharReader and CharReaderBuilder instead, and I don't think this is a bug or strange behavior from gcc.

**Comment by mrjoel** [comment]
The issue most commonly occurs for me when building the examples from jsoncpp itself. The real issue is that jsoncpp ships examples which use deprecated functionality from its own API - not the greatest of "examples" to use as a starting point.

The real issue here is that the examples should be updated to not use deprecated functionality, the fact of C++20 or GCC is secondary. I'd recommend reopening and retitling/reworking the issue.

To work around the issue, disable building of examples in CMake or meson as appropriate.

**Comment by dota17** [comment]
As you can see, the building of example is turned off by default in CMake: https://github.com/open-source-parsers/jsoncpp/blob/c8453d39d1d98ddafd15267d9d55223cdc48f2b1/CMakeLists.txt#L82

**Comment by Shaac** [comment]
Sorry for the late reply 1 month after.

You misunderstood the problem. It is not because I have some code that use deprecated code, the warning comes from lib_json itself. Not even the examples.

You can reproduce the warning by doing this:
```
git clone https://github.com/open-source-parsers/jsoncpp.git 
cd jsoncpp/
cmake .
make jsoncpp_lib
```

Or just `g++ -c src/lib_json/json_reader.cpp` in a clean repo.

So, not an error from the user, but a strange gcc behavior.
Anyway I’ll just silence all warnings from json-cpp, no big deal.

**Comment by cdunn2001** [comment]
I think we need to drop "deprecate" annotations. Simple comments in the docs should suffice. We can't remove tests for code that exists. The whole point is to maintain backward-compatibility.

We could remove the deprecated code in a major-version-bumped release.
