### ISSUE TITLE
Including this library as a submodule breaks the parent project

### ISSUE THREAD

**Issue by AntonioND** [open-source-parsers/jsoncpp#1192]
**Describe the bug**
Before including this project in our tree, all binaries and libraries are generated in the folder where they are declared in CMake (``build/src/tool/mytool``) and afterwards they are generated in ``build/bin/mytool``. We use the tools in successive build steps and need them to be in the expected directory.

This is because of the following lines:
https://github.com/open-source-parsers/jsoncpp/blob/632044ad956b9ca55703d98d852bc815077f6afc/CMakeLists.txt#L88-L91

The variables turn out to affect the whole project:
https://cmake.org/cmake/help/v3.18/variable/CMAKE_RUNTIME_OUTPUT_DIRECTORY.html

**To Reproduce**
1. Include this project with ``add_subdirectory()``
2. The binaries and libraries aren't generated in the same folder they were.

**Expected behavior**
This library shouldn't change the behaviour of the rest of the build system.

**Desktop (please complete the following information):**
 - OS: Linux
 - Ninja version: 1.8.2
- CMake version:  3.16.4

**Comment by cdunn2001** [comment]
Please submit a PR.

**Comment by AntonioND** [comment]
Well, I would, but this will definitely change the layout of the build directory, which is probably something a maintainer would have an opinion about. I mean, the lines are explicitly setting the location of the build output, so there must be a reason why someone did that: https://github.com/open-source-parsers/jsoncpp/commit/a4fb5db54389e618a4968a3feb7f20d5ce853232 I'm definitely not going to bother creating a PR if it's going to be rejected because the maintainers think that this is a feature, not a bug, for example.

Also, I don't think that closing this issue is the right approach when the bug is not fixed... I don't think I am the only one having this problem, and leaving it open would help other people find it, and know what's going on. It definitely took me a while to figure out what was breaking our builds.

**Comment by cdunn2001** [comment]
By submitting a PR, you're basically having a conversation with other CMake users. If you submit a change that makes sense, we'll merge it. If other CMake users say, "Hey, that broke us!", then we'll revert it. Actual CMake users know what's best way better than we do.
