### ISSUE TITLE
Access violation reading location 0x00000008.

### ISSUE THREAD

**Issue by galiptopcu** [open-source-parsers/jsoncpp#1198]
**Describe the bug**
I'm using 0.10.7 version of jsoncpp.
I'm posting the code blow..
I'm getting "Access violation reading location 0x00000008." if I use "sampleValue" function to get Json::Value
My target is to generate json data from structure that has nested structures. So, I'm tryig to return json::value from function.

 - OS : windows 10
 

**Additional context**

Json::Value	sampleValue()
{

	Json::Value v;
	v["appToken"] = "appToken";
	v["languageCode"] = "languageCode";
	return v;

}
void test_jsoncpp()
{

	//======================works fine====================
	Json::Value root1;
	Json::Value data1;
	root1["action"] = "run";
	Json::StreamWriterBuilder builder1;
	const std::string json_file1 = Json::writeString(builder1, root1);
	//======================works fine====================
	Json::Value root2;
	Json::Value data2;
	root2["action"] = "run";
	root2["samplenode"] = sampleValue();
	Json::StreamWriterBuilder builder2;
	const std::string json_file2 = Json::writeString(builder2, root2);
	//======================works fine====================
	{
		Json::Value root4;
		Json::Value data4;
		Json::Value v;
		v["appToken"] = "appToken";
		v["languageCode"] = "languageCode";
		root4 = v;
		Json::StreamWriterBuilder builder4;
		const std::string json_file4 = Json::writeString(builder4, root4);
	}
	//======================works fine====================
	{
		Json::Value root4;
		Json::Value data4;
		{
			Json::Value v;
			v["appToken"] = "appToken";
			v["languageCode"] = "languageCode";
			root4 = v;
		}
		Json::StreamWriterBuilder builder4;
		const std::string json_file4 = Json::writeString(builder4, root4);

	}
	//==============================!!!!!!!!!ERROR!!!!!!!!!!!======================
	//I'm getting "Access violation reading location 0x00000008."
	Json::Value root3;
	root3 = sampleValue();
	Json::StreamWriterBuilder builder3;
	const std::string json_file3 = Json::writeString(builder3, root3);

}

**Comment by galiptopcu** [comment]
hi;
I go a little deeper...
below code  cause Access violation ;
	Json::Value root3;
	root3["action"] = "run";
	Json::StreamWriterBuilder builder3;
	const std::string json_file3 = Json::writeString(builder3, root3);

if "Json::StreamWriterBuilder builder3;" line moved to upper, as below,it works fine.

	Json::StreamWriterBuilder builder3;
	Json::Value root3;
	root3["action"] = "run";
	const std::string json_file3 = Json::writeString(builder3, root3);
 
for "Access violation" case please check the images that captured in visual studio 213  watch window. after "Json::StreamWriterBuilder builder3;" executed "root3" memory overwriten.
![before builder3 inited](https://user-images.githubusercontent.com/8451939/86582540-75be0180-bf8a-11ea-92cc-efeb20c9fe61.png)

![after builder3 inited](https://user-images.githubusercontent.com/8451939/86582539-75256b00-bf8a-11ea-8b39-6c33b68d3fbf.png)

**Comment by dota17** [comment]
@galiptopcu I can't test your issue on Windows10 right now, but I tested your demo code in Ubuntu with jsoncpp version 0.10.7, but I didn't get the access violation error. So, I'm not sure if this is a bug, I suggest you use a higher version of this library.
