### ISSUE TITLE
Creating universal binary(arm64 and x86_64) for Mac system

### ISSUE THREAD

**Issue by Swetha-ch** [open-source-parsers/jsoncpp#1206]
How can we build jsoncpp library for arm64 and x86_64 architecture binaries to support the new universal format for Apple Silicons(new Mac hard ware.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15

**Comment by gjasny** [comment]
You'd use [CMAKE_OSX_ARCHITECTURES](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html) like before when we had PPC/Intel Universal Binaries:

```
cmake .. -GNinja -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
ninja
 file bin/jsoncpp_test 
bin/jsoncpp_test: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
bin/jsoncpp_test (for architecture x86_64):	Mach-O 64-bit executable x86_64
bin/jsoncpp_test (for architecture arm64):	Mach-O 64-bit executable arm64
```

Hope that helps!

**Comment by gjasny** [comment]
BTW: you need CMake 3.18 or newer.

**Comment by Swetha-ch** [comment]
Thanks It helped , i could build both architectures using -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64".
With lipo is see Architectures in the fat file: ...  libjsoncpp.a are: x86_64 arm64

**Comment by aparnatiwari30** [comment]
We are getting this error when trying to build jsoncpp on mac OS 10.15 with xcode 12
```
/bin/sh: ../../bin/jsoncpp_test: Input/output error
make[2]: *** [bin/jsoncpp_test] Error 126
make[2]: *** Deleting file `bin/jsoncpp_test'
make[1]: *** [src/test_lib_json/CMakeFiles/jsoncpp_test.dir/all] Error 2
make: *** [all] Error 2
```

We are trying to build using 
`cmake -DCMAKE_BUILD_TYPE=debug -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF "-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" -DARCHIVE_INSTALL_DIR=. -G "Unix Makefiles" ../..`

**Comment by alecazam** [comment]
@aparnatiwari30  - You have to have Xcode 12.2 to build universal apps.
