### ISSUE TITLE
string copy operation in parse function is useless

### ISSUE THREAD

**Issue by ayrb13** [open-source-parsers/jsoncpp#1209]
https://github.com/open-source-parsers/jsoncpp/blob/5be07bdc5e2d5b7715ecbc73749af3e625674dcb/src/lib_json/json_reader.cpp#L93
there is string copy operation while we use reader to parse json from std::string. I think it is useless, we can directly use document param, there is no need to copy it.
could someone explain it for me, thanks

**Comment by ayrb13** [comment]
if we remove this copy operation, the parsing time cost will be reduced by 20%

**Comment by dota17** [comment]
`Reader` class is deprecated, we highly recommand that you use `OurReader` class, which is better designed than `Reader`

**Comment by fedormsv** [comment]
Still Json::parseFromStream is potentially doing extra copy: if I have an std::string to parse JSON from, I'm still forced to wrap it into stringstream, pass this stream to operator>> or parseFromStream function.  There the provided stream is directed to istringstream and finaly str() return a string, actually a copy of original one. Having parseFromString or even from string_view would save time and memory.

**Comment by cdunn2001** [comment]
@fedormsv , please submit a PR. Could be a good idea. This sounds like it's not a bug, so we probably won't spend time on it ourselves.

**Comment by fedormsv** [comment]
PR is submitted. I'm not sure why it gets new number. 
https://github.com/open-source-parsers/jsoncpp/pull/1221

It doesn't seem to be really welcomed.
