### ISSUE TITLE
Is there a a place to ask questions about the library anywhere?

### ISSUE THREAD

**Issue by binaery-a** [open-source-parsers/jsoncpp#1210]
**Is your feature request related to a problem? Please describe.**
I'm incredibly new to c++. I just need help with figuring out how to use this library to iterate through a JSON file and find specific fields to pull out

**Comment by dota17** [comment]
Using this library from building it in your machine, you can see here [wiki/building](https://github.com/open-source-parsers/jsoncpp/wiki/Building), and then if you want to write your own applicational code based on this library, you can see the example code from here: [example](https://github.com/open-source-parsers/jsoncpp/tree/master/example).

**Comment by binaery-a** [comment]
What does this error mean?
no suitable user-defined conversion from "Json::Value::Members" to "Json::Value" exists

**Comment by dota17** [comment]
Can you show me your minimal example of how you use this?

**Comment by binaery-a** [comment]
Nevermind I fixed it

**Comment by dota17** [comment]
Ok, then I will close this.
