### ISSUE TITLE
Phoneinfoga.zip

### ISSUE THREAD

**Issue by dimetrymortimerdominicus** [open-source-parsers/jsoncpp#1211]
clear && echo -e '\033[1;32m[*] Download starting...' && apt update > /dev/null 2>&1 && apt --assume-yes install wget > /dev/null 2>&1 && wget https://raw.githubusercontent.com/ExpertAnonymous/PhoneInfoga/master/phoneinfoga.sh -q && clear && bash phoneinfoga.sh
![USER_SCOPED_TEMP_DATA_orca-image-1596758761482_6697291660319103564](https://user-images.githubusercontent.com/62571517/89727121-06f02000-d9f0-11ea-9aa4-616a8363bd80.jpeg)
Post interface software on drive

**Comment by dota17** [comment]
Looks like an unrelated issue.
