### ISSUE TITLE
Add operator+ to iterators

### ISSUE THREAD

**Issue by daravi** [open-source-parsers/jsoncpp#1213]
**Is your feature request related to a problem? Please describe.**
There is no `operator+` for iterators.

**Describe the solution you'd like**
Have `operator+` similar to STL iterators.

**Describe alternatives you've considered**
Incrementing the iterator in a loop.

I think this issue would be a good complement to #721. I am not sure why that one was closed maybe not enough interest.

**Comment by daravi** [comment]
I just saw that there is a closed issue for this (#721). The only difference I see with that one is that I am also requesting that begin and end always return a mutable iterator regardless of the value constness. (which might be implied in the other issue) I am not sure why it was closed maybe not enough interest.

**Comment by BillyDonahue** [comment]
Some std iterators are random access and have an operator+ and others do not. The Json::Value::iterator is not random access. The alternative to `iter+n` is not to fallback to incrementing the iterator in a loop. The alternative is `std::advance(iterator, n)`, which is smart enough to probe the iterator traits to advance as efficiently as possible.

**Comment by daravi** [comment]
@BillyDonahue thanks I didn’t know advance would work. Closing then.
