### ISSUE TITLE
Projects using this library

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [open-source-parsers/jsoncpp#1218]
I don't know if you know this, but Fallout 4 uses this json library. I believe it uses it for interactions with the pipboy app.

**Comment by dota17** [comment]
so, what kind of issue that you are running into ?

**Comment by Ryan-rsm-McKenzie** [comment]
I just thought you'd find it interesting

**Comment by dota17** [comment]
Thnaks Ryan 👋. welcome to use this library, feel free to feedback any issue when you use it.

**Comment by cdunn2001** [comment]
Yes, thank you, @Ryan-rsm-McKenzie. If your project requires any changes to Jsoncpp, please let us know.
