### ISSUE TITLE
Parsing in a loop will eventually crash

### ISSUE THREAD

**Issue by antithing** [open-source-parsers/jsoncpp#1219]
Hi,. and thanks for this code!

I am testing sending json strings over tcp, using asio.

I am sending:

```
{
        "number" : 17242,
        "record" : false,
        "valid" : "true"
}

```

On the other side, i read until the '}' and then send to this parse function:

```

std::string ParseJSON(std::string rawJson)
{	
		const auto rawJsonLength = static_cast<int>(rawJson.length());
		JSONCPP_STRING err;
		Json::Value root;

		Json::CharReaderBuilder builder;
	
		const std::unique_ptr<Json::CharReader> reader(builder.newCharReader());

		std::string errors;

		if (rawJsonLength > 10)
		{
			if (!reader->parse(rawJson.c_str(), rawJson.c_str() + rawJsonLength, &root,
				&err))
			{
				std::cout << err << std::endl;
			}
			else
			{
				std::cout << root["number"].asString() << std::endl;
			}

		}
	

	return "";
}

```

Running in a loop, this works fine for a second or so, then crashes with:

`in Json::Value::resolveReference(key, end): requires objectValue
`

The main loop function is:

```
int main(int argc, char* argv[])
{
	try
	{
		asio::io_context io_context;
		tcp::resolver resolver(io_context);
		tcp::resolver::results_type endpoints =
			resolver.resolve("127.0.0.1", "daytime");

		tcp::socket socket(io_context);
		asio::connect(socket, endpoints);

		while (true) 
                {						
				
				asio::error_code error;
				asio::streambuf sb;
			
					std::size_t n = asio::read_until(socket, sb, '}');
				asio::streambuf::const_buffers_type bufs = sb.data();
				std::string line(
					asio::buffers_begin(bufs),
					asio::buffers_begin(bufs) + n);

				ParseJSON(line);
			//	std::cout << line << std::endl; //This looks good when printed.			
			
		}
	}
	catch (std::exception& e)
	{
		std::cerr << e.what() << std::endl;
	}

	return 0;
}
```
			
	
What am i doing wrong here? Is there a way to validate the json before parsing?

Thank you.

**Comment by BillyDonahue** [comment]
Please fix your indentation. That `else` might not be binding to the `if` you intended it to. It looks correct but indentation is important for making the example understandable.

Also you need to free your `reader`. You're making a new reader on every invocation of the function and leaking them. So reuse the same reader every time, or manually delete it when you're done with it, or use a `std::unique_ptr`.

This doesn't explain the problem you're seeing exactly, but could be contributing.

I'm now a little skeptical of the caller of `ParseJSON`. I would like to see a complete program that explicitly calls `ParseJSON` with that input data, in a loop.

**Comment by antithing** [comment]
@BillyDonahue Thank you for getting back to me. I have updated the above with your notes, and the main loop function to make it easier to see what is going on. The crash occurs in the `ParseJson` function, when I just print the incoming data it runs and looks fine.

**Comment by BillyDonahue** [comment]
Why is indenting still so bad?

This is still using asio and the input data isn't present in the program.

I want a program without dependencies that will just run and crash. So we can debug it.

I have no idea if that asio code is correct, or what input the program was given.

**Comment by antithing** [comment]
Hi @BillyDonahue, as suspected, it is to do with the asio, rather than jsoncpp. Adding a check for `root.size()` works as a workaround:

```
if (root.size() > 0)
{
    std::cout << root["number"] << std::endl;
}
```

I will dig more into my asio code and work it out. Thank you for your help.
