### ISSUE TITLE
How can I use jsoncpp with Visual Studio on C++

### ISSUE THREAD

**Issue by batata004** [open-source-parsers/jsoncpp#1226]
I already tried everything and nothing works. I already went to properties of the project and added the "Include" path to the C/C++ -> GENERAL -> ADDICIONAL INCLUDE... but I can never make it work. How can I simply import this library to VS?

I am creating a blank project with just this line:

Json::Value root;

and it trows lots of error. I am using this at the top of the file:

#include <json/value.h>
#include <json/json.h>
#include <json/reader.h>

I am getting all these errors:

![image](https://user-images.githubusercontent.com/8988923/94991351-ec05dc00-0558-11eb-95a0-73ce4107002b.png)

**Comment by cdunn2001** [comment]
If you tell us what to add, we'll add something. Please submit a PR. Someone added a vproj file at some point.

We do test that we can build on windows in CI. But we do the bare minimum. You can use **meson** with either cygwin or WSL.
