### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by prasantapal** [open-source-parsers/jsoncpp#1227]
CMake error : Make Error at src/lib_json/CMakeLists.txt:214 (install):
  install TARGETS given unknown argument "OBJECTS". (with screenshot attached.)
compiler: GCC 8.3.0
OS: Linux
arch: x84_64

<img width="1207" alt="Screen Shot 2020-10-03 at 5 07 25 PM" src="https://user-images.githubusercontent.com/4718136/95001746-f1841600-059a-11eb-906e-c59ed937d621.png">

**Describe the bug**

**To Reproduce**
1.

**Expected behavior**

**Desktop (please complete the following information):**
 - Meson version
 - Ninja version

**Additional context**

**Comment by cdunn2001** [comment]
If you provide the fix, we'll merge it. We do not maintain cmake ourselves, and we *strongly* recommend switching to **meson**.
