### ISSUE TITLE
Tests fail on windows due to pipes.quote() (which doesn't work on that platform)

### ISSUE THREAD

**Issue by mzeren-vmw** [open-source-parsers/jsoncpp#123]
See e.g. the discussion here: https://mail.python.org/pipermail/python-win32/2010-May/010547.html
The issue was introduced with commit 1a4dc3a888c7e6e179503250ccb391820a586b1b.

**Comment by cdunn2001** [comment]
That was already reverted and re-fixed.

* https://github.com/open-source-parsers/jsoncpp/commit/dc2e1c98b9e7baaba8ffc58a4af86528e4a48976
* https://github.com/open-source-parsers/jsoncpp/commit/4ca9d25ccceaa198c4e92b86d8ad8b8d01fb87ff
