### ISSUE TITLE
ECCN for Jsoncpp 

### ISSUE THREAD

**Issue by Likhitha2809** [open-source-parsers/jsoncpp#1233]
Hi, For documentation purpose and project release process we need the Export control classification number(ECCN) for Jsoncpp if it applies. Can you please let me know the ECCN ?

**Comment by cdunn2001** [comment]
**jsoncpp** is not intended for use in encryption libraries, and I would advice against it. (In fact, I have personally used **msgpack** for encryption, and I strongly recommend that, for its simplicity and its predictable memory-management.) So I don't think any export restrictions apply. If I'm wrong, please link more information.
