### ISSUE TITLE
Wrong version in jsoncpp.pc for Fedora 33

### ISSUE THREAD

**Issue by AmarOk1412** [open-source-parsers/jsoncpp#1235]
Not sure it's the good place, but I don't find the maintainer of jsoncpp-devel for Fedora 33 and https://apps.fedoraproject.org/packages is down since some time know and it's the only link in the package

**Describe the bug**
The jsoncpp-devel package is not correct on fedora 33. The jsoncpp.pc file doesn't contains the version

**To Reproduce**
I did a quick and dirty repo:

https://github.com/AmarOk1412/jsoncpp-fed33

```
$ cat /usr/lib64/pkgconfig/jsoncpp.pc 
prefix=/usr
exec_prefix=/usr
libdir=${exec_prefix}/lib64
includedir=${prefix}/include

Name: jsoncpp
Description: A C++ library for interacting with JSON
Version: 
URL: https://github.com/open-source-parsers/jsoncpp
Libs: -L${libdir} -ljsoncpp
Cflags: -I${includedir}
```

Version: is empty, should be 1.9.4

**Desktop (please complete the following information):**
 - OS: Fedora 33

**Comment by dota17** [comment]
Thanks @AmarOk1412 , this is a little bug, I'll fix it soon.

**Comment by AmarOk1412** [comment]
Oh I don't worry, it's indeed a little bug :)
Have a nice day

**Comment by cdunn2001** [comment]
@AmarOk1412, would it be possible for Fedora to use Meson instead of Cmake for jsoncpp?

**Comment by cdunn2001** [comment]
I think this is fixed now, using Meson at least.
