### ISSUE TITLE
1.9.4 do not compile with older cmake (cmake < 3.12) in libjson/cmakefile.txt

### ISSUE THREAD

**Issue by Pascal-Fremaux** [open-source-parsers/jsoncpp#1239]
**Describe the bug**
Compiling with an older cmake (no choice) v3.8 do not recognize the install (OBJECTS) (available only since cmake 3.12)
https://cmake.org/cmake/help/v3.12/command/install.html

CMake Error at src/lib_json/CMakeLists.txt:214 (install):
  install TARGETS given unknown argument "OBJECTS".

**To Reproduce**
Use cmake v3.8 (any cmake < 3.12) and build

**Expected behavior**
The file has a lot of older cmake adaptation, but not for this one.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Yocto
 - Meson version ?
 - Ninja version ?

**Additional context**
Build done on Yocto with cmake

**Comment by Pascal-Fremaux** [comment]
Quick workaround: removing the OBJECTS line for cmake < 3.12

**Comment by cdunn2001** [comment]
If you submit a PR for that, we'd probably merge it.
