### ISSUE TITLE
The Chinese Character Code Format data is abnormal

### ISSUE THREAD

**Issue by w136111526** [open-source-parsers/jsoncpp#1240]
I used your example streamWrite to print json information, and the Chinese field display is not normal，Can you tell me how to transcode ？my code is following:
   Json::Value root;
  root["Name"] = "你好,中国";
  root["Age"] = 20;
  std::string result = root.toStyledString();
  printf("%s", result.c_str());
  writer->write(root, &std::cout);

**Comment by dota17** [comment]
Please see the discussion here https://github.com/open-source-parsers/jsoncpp/pull/1232#discussion_r504396311, this library assumes all strings are UTF-8, so you should use `u8"你好,中国"` instead.

**Comment by w136111526** [comment]
But I like the console display gbk text information, how to modify the JSON source encoding format

**Comment by BillyDonahue** [comment]
GBK isn't part of the JSON spec, as discussed in Chen's link to #1232. Displaying in GBK is out of scope for the library. I'd help if I could but I'm not familiar enough with Chinese text. The standard solution is probably libiconv.

https://www.gnu.org/software/libiconv/
