### ISSUE TITLE
output error with comment, before and after "//"

### ISSUE THREAD

**Issue by kjflyback** [open-source-parsers/jsoncpp#1241]
thanks..., and next issue, talk is cheap,show code to you:

> 1st bug about comment again
```CPP
reader.parse("{\"p\":[//\n//\n//\n]}", root);
std::cout<<Json::writeString(wb, root);
```
output is:
```CPP
{
	"p" : 
	[
		//
		//
		//
		null
	]
}
```
the **"null"** may be a wrong string

-----
> 2nd bug about comment again
```CPP
reader.parse("{\"a\":1234567890,\"p\":[//\n//\n//\n]}", root);
std::cout<<Json::writeString(wb, root);
```

output is:
```CPP
{
	"a" : 1234567890, //
	"p" : 
	[
		//
		//
		null
	]
}
```
may be first comment mark goes to wrong place

> 3rd something interesting
```CPP
reader.parse("{\"a\":1234567890,\\ pop\n\"p\":[//\n]}", root);
output
{
	"a" : 1234567890
}
```
missing comment and following part

> 4th 
```CPP
reader.parse("\\ pop\n{\"a\":1234567890,\"p\":[//\n]}", root);
```
can not parse

> 5th 
```CPP
reader.parse("{\\ pop\n\"a\":1234567890,\"p\":[//\n]}", root);
output:
{}
```
missing all data but {} mark

**PS:I use lastest code from jsoncpp**

**Comment by kjflyback** [comment]
@dota17 please check these 2 issues, they are not the same error

**Comment by dota17** [comment]
https://github.com/open-source-parsers/jsoncpp/issues/1238#issuecomment-730386607
@kjflyback  It is the duplicate content.
