### ISSUE TITLE
Unresolved external symbol error VS2019 

### ISSUE THREAD

**Issue by HTT5041** [open-source-parsers/jsoncpp#1242]
**Describe the bug**
Upon compilation, multiple errors are thrown all to do with 'unresolved external symbols'.

**To Reproduce**
Not too sure.

**Expected behavior**
It to compile.

**Desktop (please complete the following information):**
Windows 10
I'm trying to compile an x86 DLL

**Additional context**
Hi, I'm trying to compile my DLL with jsoncpp, however I am getting this unusual error I have never really seen before:
`1>dllmain.obj : error LNK2001: unresolved external symbol "class std::basic_istream<char,struct std::char_traits<char> > & __cdecl Json::operator>>(class std::basic_istream<char,struct std::char_traits<char> > &,class Json::Value &)" (??5Json@@YAAAV?$basic_istream@DU?$char_traits@D@std@@@std@@AAV12@AAVValue@0@@Z)`

`1>dllmain.obj : error LNK2001: unresolved external symbol "public: class Json::Value & __thiscall Json::Value::operator[](char const *)" (??AValue@Json@@QAEAAV01@PBD@Z)`

`1>dllmain.obj : error LNK2001: unresolved external symbol "public: int __thiscall Json::Value::asInt(void)const " (?asInt@Value@Json@@QBEHXZ)`

`1>dllmain.obj : error LNK2001: unresolved external symbol "public: __thiscall Json::Value::~Value(void)" (??1Value@Json@@QAE@XZ)`

`1>dllmain.obj : error LNK2001: unresolved external symbol "public: __thiscall Json::Value::Value(enum Json::ValueType)" (??0Value@Json@@QAE@W4ValueType@1@@Z)`

I have included value.h & json.h in my project.

Like I said, I haven't really seen this error before and I'm not too sure what is happening, after some googling I came to no conclusion. Thanks for any help given.

(Sorry if I've missed something and this isn't the right place to ask)

**Comment by cdunn2001** [comment]
I think you're not linking with the DLL. It's probably not an error in the library. I seems like an integration problem, and that's difficult to debug remotely. Sorry! Maybe try a much simpler library first, to learn how this can be solved.
