### ISSUE TITLE
please use standard filename for static library

### ISSUE THREAD

**Issue by skoehler** [open-source-parsers/jsoncpp#1245]
For some reason, the filename of the static library is `libjsoncpp_static.a` instead of `libjsoncpp.a` when using the cmake build process. That should be fixed. Currently, I override that by passing `-DSTATIC_SUFFIX=""` to cmake.

Actual Result: `gcc -static test.c -ljsoncpp` fails
Expected Result:  `gcc -static test.c -ljsoncpp` succeeds

**Comment by skoehler** [comment]
To the best of knowledge, it is also not possible to specify different filenames for the static and the dynamic library in the pkg-config file.

**Comment by cdunn2001** [comment]
Maintaining cmake is very difficult. Not sure why. Maybe because cmake itself keeps changing? But we generally accept pull-requests for changes to the cmake files. If you submit a pull-request, and if it doesn't seem to break too many other users, we'll simply merge it.

Thanks for the details on `-DSTATIC_SUFFIX="" `. Feel free to update our WIki. Our give you permission if you don't have it already.

I use only **meson** myself. I think we have ci tests for **cmake** too though.

**Comment by skoehler** [comment]
Maintaining cmake is not very difficult, IMHO. I just think that the cmake contributors don't following the same rules or have independent ideas as the people who developed the meson build files.

As far as I can see, the mingw-w64 packages on Arch Linux and the mingw-w64 of MSYS2 are built using cmake. The MSYS2 people provide both (`libjsoncpp_static.a` and `libjsoncpp.a`), even though the files are not identical! The Arch Linux contributor is confused and wants to follow upstream. He rejected to use `-DSTATIC_SUFFIX=""`.

As you can see, having two build systems which differ does cause some confusion.

**Comment by cdunn2001** [comment]
> Maintaining cmake is not very difficult, IMHO.

I wish that were my experience.

I have no idea why someone decided to insert `_static` for **cmake**... Oh, apparently someone thought this was important:
```
+    # avoid name clashes on windows as the shared import lib is alse named jsoncpp.lib
+    if(NOT DEFINED STATIC_SUFFIX AND BUILD_SHARED_LIBS)
+        set(STATIC_SUFFIX "_static")
+    endif()
```
commit cfc1ad72ad7e0a6d625686182bce1aefa118b308

    Author: Chen <chenguopingdota@163.com>
    Date:   Mon Jul 13 07:33:58 2020

Just submit a passing PR. We're happy to merge. Someone may decide to make an exception for Windows, but that's fine as a separate issue.

**Comment by skoehler** [comment]
Thanks for clarifying. That explains why `_static` was added. Apparently, somebody wanted to solve a Windows issue (Windows has these import libraries for DLLs) but coincidentally changed the name of the UNIX libraries as well.

I am not sure what the naming convention for Microsoft toolchains is (if there is any), to be honest. But for GNU-toolchains (Linux, mingw, etc.) one should follow the standard conventions.

Should I have time I will submit a patch that keeps the filenames for Microsoft toolchains as is and restores the default name for GNU toolchains.
