### ISSUE TITLE
Issues combining JSON values with insert and append

### ISSUE THREAD

**Issue by Skewjo** [open-source-parsers/jsoncpp#1247]
**Describe the bug**
Good morning jsoncpp. I don't believe this is a bug, but I'm not really sure where to turn for help. I've looked (as thoroughly as my abilities would allow) through the ```Json::Value``` documentation, but I didn't see a function that would allow me to do what I need to do.

When I combine ```Json::Value```'s together using append or insert, it turns them into an array. 
This array is adding unneeded complexity to the API I'm sending to because I was previously able to parse the entire file by field name, but I now have to explicitly state which array index contains the field I'm after.

**To Reproduce**
I was previously creating and using a single ```Json::Value``` in a single class/function, but I've recently split much of my data collection into new classes/objects:

Before:
```
Json::Value jsonSLD;
jsonSLD["SLD"]["Counter"] = 0;
jsonSLD["HardwareID"]["HardwareID"] = "{12345}";
jsonSLD["UserMachineInfo"]["CPU"] =  "Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz";
```

After:
```
//in class 1:
Json::Value jsonSLD;
jsonSLD["SLD"]["Counter"] = 0;

//in class 2 
Json::Value HardwareIDJSON ;
jsonSLD["HardwareID"]["HardwareID"] = "{12345}";

//in class 3
Json::Value MachineInfoJSON ;
jsonSLD["HardwareID"]["HardwareID"] = "{12345}";

//in main
Json::Value newJSON;
newJSON.append(class1->jsonSLD);
newJSON.append(class2.HardwareIDJSON);
newJSON.append(class3.MachineInfoJSON);
```

Example before:
```
{
	"SLD" : 
	{
		"Counter" : 0
	},
	"HardwareID" : 
	{
		"HardwareID" : "{12345}"
	},
	"MachineInfo" : 
	{
		"CPU" : "Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz"
	}
}
```

Example after:
```
[
	{
		"SLD" : 
		{
			"Counter" : 0
		}
	},
	{
		"HardwareID" : 
		{
			"HardwareID" : "{12345}"
		}
	},
	{
		"MachineInfo" : 
			{
				"CPU" : "Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz"
			}
	}
]
```

**Expected behavior**
I'd like/expected to see the fields from each ```Json::Value``` added to the fields of the first value without putting them in array brackets and nested curly braces.

I was thinking I may be able/need to do this in an ```operator+``` overload, but I'm not quite skilled enough for that(and I am in a bit of a time crunch), so I'm hoping I've just missed the functionality. Any help is greatly appreciated.

**Comment by BillyDonahue** [comment]
I think `append` is not what you want to do here. Append always treats the Value on which it is called as an array.
You need more of a root object key merge, which is a little more complex.


```c++
    //in main
    Json::Value newJSON;
    const Json::Value* const sources[] = {
        &class1->jsonSLD,
        &class2.HardwareIDJSON,
        &class3.MachineInfoJSON,
    };
    for (const Json::Value* src : sources)
        for (auto srcIt = src->begin(); srcIt != src->end(); ++srcIt)
            newJSON[srcIt.name()] = *srcIt;
```

Our iterators are weird. :)

**Comment by Skewjo** [comment]
Thank you very much @BillyDonahue! I'll give it a shot.

**Comment by BillyDonahue** [comment]
Great.
I'll close the issue and please let us know if it worked.

**Comment by Skewjo** [comment]
@BillyDonahue Works beautifully. Thanks again.
