### ISSUE TITLE
Still has garbled words on Chinese Characters

### ISSUE THREAD

**Issue by tianchao-haohan** [open-source-parsers/jsoncpp#1248]
**Describe the bug**
garbled words on Chinese Characters

**Desktop (please complete the following information):**
 - OS: Win 10
 - Visual Studio 2017
 - Jsoncpp  VERSION 1.9.2

**Additional context**

Code：
    Writer：
```
Json::Value JsonRoot;
Json::Value JsonResult;
JsonResult["filter_name"] = Json::Value("中文测试字符");
JsonRoot.append(JsonResult);

std::ostringstream stream;
Json::StreamWriterBuilder stream_builder;
stream_builder.settings_["emitUTF8"] = true;//Config emitUTF8
std::unique_ptr<Json::StreamWriter> writer(stream_builder.newStreamWriter());
writer->write(JsonRoot, &stream);
//copy value from stream to results.
```

 Reader：
       
 ```
JSONCPP_STRING errs;
Json::CharReaderBuilder readerBuilder;
Json::Value root;

std::unique_ptr<Json::CharReader> const jsonReader(readerBuilder.newCharReader());
res = jsonReader->parse(results, results + strlen(results), &root, &errs);
if (root[ix].isMember("filter_name") && root[ix]["filter_name"].isString())
{
	std::cout << "cpp out1: " << root[ix]["filter_name"].toStyledString() << std::endl;
	std::cout << "cpp out2: " << root[ix]["filter_name"].asCString() << std::endl;
	std::cout << "cpp out3: " << root[ix]["filter_name"].asString() << std::endl;
}
```

Output:
cpp out1: "\u4e2d\u56fd\u4e2a\u4eba\u7535\u8bdd\u53f7\u7801"
cpp out2: Σ╕¡σ¢╜Σ╕¬Σ║║τö╡Φ»¥σÅ╖τáü
cpp out3: Σ╕¡σ¢╜Σ╕¬Σ║║τö╡Φ»¥σÅ╖τáü

**Comment by BillyDonahue** [comment]
That looks like Windows codepage 437 output. Maybe it's your terminal?
I would love to see a hex dump of that output instead of just how it looks on screen.
Can you capture that?

**Comment by tianchao-haohan** [comment]
> That looks like Windows codepage 437 output. Maybe it's your terminal?
> I would love to see a hex dump of that output instead of just how it looks on screen.
> Can you capture that?

Thank you very much. It is definitely the windows terminal issue. 
Thanks again
