### ISSUE TITLE
 In old versions of jsoncpp, std::string may take up too much memory

### ISSUE THREAD

**Issue by UKeeySDis** [open-source-parsers/jsoncpp#1251]
My project use old version of jsoncpp which without `allocator.h`.And I found std::string take up too muck memory after run jeprof.
![image](https://user-images.githubusercontent.com/26181669/103126760-4af76f00-46ca-11eb-9c2e-5bd0c17342cd.png)
I know the reason for this is std::string' default memory pool, malloc use `brk` and memory pool.
And the problem may be resolved after I upgrade to the new version which has `allocator.h`(direct new and delete for string's allocator)?

**Comment by BillyDonahue** [comment]
I wouldn't expect the allocator.h header to make a difference one way or the other. It just defines a SecureAllocator class that is basically the same thing as std::allocator but zeroes out the memory on deallocation.

There is no attempt in jsoncpp at having a "smarter" allocation strategy or anything like that.

I would look at the application layer and see if you can't add some strategic std::string::shrink_to_fit calls?

**Comment by UKeeySDis** [comment]
> I wouldn't expect the allocator.h header to make a difference one way or the other. It just defines a SecureAllocator class that is basically the same thing as std::allocator but zeroes out the memory on deallocation.
> 
> There is no attempt in jsoncpp at having a "smarter" allocation strategy or anything like that.
> 
> As much as I love a good prof chart, I can't tell what the problem is.
> Are your strings left with a lot of unused capacity?
> 
> I would look at the application layer and see if you can't add some strategic std::string::shrink_to_fit calls?
> 
> If there's a time when you're finished writing Json, maybe destroy the writer to release its internal document std::string.
> It keeps that high-water-mark string allocation around to make future writes fast.

sorry, I made a mistake that allocator was not important for this fake memory leak.
> It just defines a SecureAllocator class that is basically the same thing as std::allocator but zeroes out the memory on deallocation.

you are right.


The real reason is the memory maintenance mechanism of malloc, which causes the memory leak to look more serious. The automatic expansion mechanism of the string takes up more memory.
Even if  `shrink_to_fit ` is called, malloc will not necessarily return the memory to the os, but maybe can alleviate the problem of high memory usage.thanks.

**Comment by BillyDonahue** [comment]
I will close this issue then. Please do reopen if there's something else to address here.
