### ISSUE TITLE
Question or Feature Request: Extracting member from a list or object value

### ISSUE THREAD

**Issue by daravi** [open-source-parsers/jsoncpp#1258]
**Is your feature request related to a problem? Please describe.**

Is it possible to extract a member from a list or an object value? If not, I would like to request this feature.

**Describe the solution you'd like**

I can see that with `std::map`, it is possible to `extract` a node. I would like to be able to do that, and then possibly insert the extracted node into another object/list.

**Describe alternatives you've considered**

The current alternative is to copy the `Json::Value`, and then remove the original copy.

**Comment by baylesj** [comment]
You are looking for `Value::removeMember`. Not only can you just remove a member, but you can use the overload with the |removed| parameter to get the "extracted" node:

https://github.com/open-source-parsers/jsoncpp/blob/master/include/json/value.h#L537

```c++
  /** \brief Remove the named map member.
   *
   *  Update 'removed' iff removed.
   *  \param key may contain embedded nulls.
   *  \return true iff removed (no exceptions)
   */
  bool removeMember(String const& key, Value* removed);
```
