### ISSUE TITLE
Workaround to preserve decimal formatting?

### ISSUE THREAD

**Issue by nickgeorge** [open-source-parsers/jsoncpp#1262]
Is there any way to coerce jsoncpp to represent numbers as strings internally?  Right now it's impossible to do a round-trip with jsoncpp from string -> json -> string because things like 

{ "myValue": 2.0}

make no attempt to preserve the number formatting.  Seems to me the obvious choice here would be to internally represent Number types as strings - this would require no changes to public APIs and would only affect internal representation.  I there a way to make it work like this?  Right now I'm running a regex replace that turns anything that looks numeric into quoted, but that's a pretty brutal hack :(

**Comment by cdunn2001** [comment]
Unfortunately, your hack is the right answer.

This isn't a **jsoncpp** problem; it's a **JSON** problem. If exact representation matters, I would use **msgpack** instead of **JSON**.
