### ISSUE TITLE
Build Break on Mac OS X

### ISSUE THREAD

**Issue by MichaelDevine** [open-source-parsers/jsoncpp#1266]
Build break on Mac OS X with latest commit. 
> cmake ..
...
> make
[ 23%] Built target jsoncpp_lib
[ 41%] Built target jsoncpp_object
[ 64%] Built target jsoncpp_static
[ 76%] Built target jsontestrunner_exe
[ 82%] Building CXX object src/test_lib_json/CMakeFiles/jsoncpp_test.dir/main.cpp.o
<>/jsoncpp/src/test_lib_json/main.cpp:356:12: error: implicit conversion changes signedness: 'int' to
      'Json::Value::ArrayIndex' (aka 'unsigned int') [-Werror,-Wsign-conversion]
  v.resize(n);
    ~~~~~~ ^
1 error generated.
make[2]: *** [src/test_lib_json/CMakeFiles/jsoncpp_test.dir/main.cpp.o] Error 1
make[1]: *** [src/test_lib_json/CMakeFiles/jsoncpp_test.dir/all] Error 2
make: *** [all] Error 2

**Comment by cdunn2001** [comment]
Interesting. I wonder how this passed our TravisCI gate? Should be a simple fix though.

I'm in Texas, with spotty internet connection right now. If you submit a PR, somebody will merge it.

**Comment by BillyDonahue** [comment]
Weird that I didn't notice it. I'm locally developing on Mac.
I can fix it.
