### ISSUE TITLE
CharReader parse fail cause thow exception

### ISSUE THREAD

**Issue by Qiaojiawei** [open-source-parsers/jsoncpp#1270]
**Describe the bug**
when use CharReader to pase some string that not json, it return true, but when we try to get json value, it throw exception,

**To Reproduce**
example code:

    #include "json/json.h"
    #include "stdio.h"
    #include <cstdlib>
    #include <iostream>

    int main()
    {
        //const std::string rawJson = "{\"Age\": 20, \"Name\": \"colin\"}"; 
        const std::string rawJson = "\"Age\": 20, \"Name\": \"colin\""; 
        const int rawJsonLength = static_cast<int>(rawJson.length());
        Json::Value root;
        JSONCPP_STRING err;
        Json::CharReaderBuilder builder;
        Json::CharReader* reader(builder.newCharReader());
        if (!reader->parse(rawJson.c_str(), rawJson.c_str() + rawJsonLength, &root, &err)) {
            std::cout << "error" << std::endl;
            return EXIT_FAILURE;
        }
        delete reader;
        if (!root["Name"].isNull())  // here throw exception
        {
            printf("Name not found\n");
        }
        return 0;
    }

run result:

'terminate called after throwing an instance of 'Json::LogicError'
  what():  in Json::Value::resolveReference(key, end): requires objectValue
Aborted'

**Expected behavior**
when parse failed, expect return false, or call root["Name"] not throw exception.

**Desktop (please complete the following information):**
 - OS: 
 - linux

[test.zip](https://github.com/open-source-parsers/jsoncpp/files/6022292/test.zip)

**Comment by cdunn2001** [comment]
```cpp
root["Name"]
```
If the top is not an object, that should throw an exception, right? The message seems to say exactly that:
```cpp
Json::Value::resolveReference(key, end): requires objectValue
```
That's expected behavior. Maybe not ideal, but expected.

**Comment by Qiaojiawei** [comment]
thanks for your reply, @cdunn2001 
so how to check the parse result contain a member of ""Name" ?  we try to use  root["Name"] or root.isMember("Name") ,but it always throw an exception, it seems  the only way to use try.. catch() to sovle this prolem (may be reduce some performance )? or we need to check it is a objectValue?  which is the recommended way for this?  
expect your answer, thank you.

**Comment by BillyDonahue** [comment]
To be safe, you would have to check that the root `Value` is an object or array before applying `operator[]` to it.
