### ISSUE TITLE
Version is not set in pkgconfig file

### ISSUE THREAD

**Issue by DKLind** [open-source-parsers/jsoncpp#1279]
**Describe the bug**
With v1.9.4, the Version field in jsoncpp.pc is blank

**To Reproduce**
1. Build v1.9.4
2. Look at Version field in jsoncpp.pc

**Expected behavior**
The Version field should contain 1.9.4

**Desktop (please complete the following information):**
 - Meson version
 - Ninja version

**Additional context**

**Comment by cdunn2001** [comment]
With **meson** this is trivial:
```tcl
$ cat build-shared/meson-private/jsoncpp.pc
prefix=/usr/local
libdir=${prefix}/lib
includedir=${prefix}/include

Name: jsoncpp
Description: A C++ library for interacting with JSON
Version: 1.9.4
Libs: -L${libdir} -ljsoncpp
Cflags: -I${includedir}
```
That's with a standard meson build. If you need a fix for something else, please submit a PR.

**Comment by cdunn2001** [comment]
Btw, @open-source-parsers/json-cpp , there is a new problem for **jsoncpp** with the latest MacOSX 11.3 (Big Sur) and latest Xcode (12.5 I think). It includes a header called `version`, and if our exists then the whole build fails with a long, inscrutable error message. It happens for any library with a file called `version`, e.g. **tesseract**. Very annoying. We might have to address this soon.
