### ISSUE TITLE
it appears a warning when use gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf build it

### ISSUE THREAD

**Issue by aurshon** [open-source-parsers/jsoncpp#1280]
parameter passing for argument of type ‘std::_Rb_tree_const_iterator<std::pair<const Json::Value::CZString, Json::Value> >’ changed in GCC 7.1
         __cnd2(_II __first, _II __last)

**Comment by cdunn2001** [comment]
It's hard for us to test a fix for a specific platform. Please submit a PR and we'll merge it. Thank you for pointing this out.
