### ISSUE TITLE
Request: do not set CMAKE_RUNTIME_OUTPUT_DIRECTORY etc. for submodule builds

### ISSUE THREAD

**Issue by apanteleev** [open-source-parsers/jsoncpp#1286]
When a project includes jsoncpp (or any other project for that matter) as a submodule and a static library into a larger CMake build, the submodule should not override any global and cached settings like CMAKE_RUNTIME_OUTPUT_DIRECTORY.

On a similar note, it's a good tone to start all CMake settings with the project name prefix. Currently, this is mostly followed by jsoncpp, except for BUILD_SHARED_LIBS etc.

**Comment by cdunn2001** [comment]
We just merged a bunch of cmake changes in #1271 . Maybe that will help with this? If not, please submit a PR. We generally accept user submissions for **cmake**, but prefer **meson**. Supporting **cmake** has really been a nightmare.
