### ISSUE TITLE
 Debug Error: std::length_error exception at prase()

### ISSUE THREAD

**Issue by Zhaotiedan** [open-source-parsers/jsoncpp#1291]
When I used a test case under VS 2017,my program has an exception at parse()

![image](https://user-images.githubusercontent.com/48014011/117912546-48f91a00-b312-11eb-9770-c88954c8dacd.png)

```c++ 
int main()
{
	const char* str = "{\"uploadid\": \"UP000000\",\"code\": 100,\"msg\": \"\",\"files\": \"\"}";

	Json::Reader reader;
	Json::Value root;
	if (reader.parse(str, root)) //0x000007FEFD55B3DD 处(位于 TestOpencv2.exe 中)有未经处理的异常: Microsoft C++ 异常: std::length_error，位于内存位置 0x000000000019F520 处。 

	{
		std::string upload_id = root["uploadid"].asString();  
		int code = root["code"].asInt();    // 访问节点，code = 100 
		cout << "upload_id: " << upload_id << endl;
		cout << "code: " << code << endl;
	}
	return 0;
}
```

**Comment by BillyDonahue** [comment]
If you can provide a stack trace for that exception, that would be helpful.

**Comment by Zhaotiedan** [comment]
> If you can provide a stack trace for that exception, that would be helpful.
> 
> 
> 
> 


I'm not sure if this stack information can provide you with some information to help me, please
![image](https://user-images.githubusercontent.com/48014011/117963801-67333a00-b353-11eb-9b4e-53745de2d0d7.png)

**Comment by Zhaotiedan** [comment]
> If you can provide a stack trace for that exception, that would be helpful.
> 
> 
> 
> 

Thanks so much,I reconfigured the environment and found the solution provided by you for my initial error in the closed issues.I have finished the following steps but a Debug Assertion occurred,can you help me ![image](https://user-images.githubusercontent.com/48014011/117982006-2265ce00-b368-11eb-93f4-3c735ca2c30a.png)

**Comment by Zhaotiedan** [comment]
> If you can provide a stack trace for that exception, that would be helpful.
> 
> 
> 
> 
Thanks so much!I have solved the problem
