### ISSUE TITLE
StringArray containing numeric value is not rejected by the parser itself

### ISSUE THREAD

**Issue by RamakrishnanOSS** [open-source-parsers/jsoncpp#1292]
**Description**
StringArray containing numeric value is not rejected by the parser itself.

```
{"testStringArray": {"0":["a nice string", 1, "array value"] } } 
```

This is accepted by the parser and `1` is converted to `to_string(1)` = "1";

Instead I expect it to throw some error. Or may be there must some settings to enable/disable to the parser.

For Array of Integers  it is not the case  `{"testIntArray": {"0":["1", 2, "3"] } }` -> This throws exception.

**Comment by BillyDonahue** [comment]
There's no such thing as a `StringArray` in jsoncpp.
The parser has no reason to reject that array, as an array is allowed to be heterogeneous in JSON.

> For Array of Integers it is not the case `{"testIntArray": {"0":["1", 2, "3"] } }` -> This throws exception.

Data doesn't throw, code throws. What code is throwing? I don't think it can be jsoncpp code.
