### ISSUE TITLE
Make a New Release

### ISSUE THREAD

**Issue by bazfp** [open-source-parsers/jsoncpp#1293]
It would be useful to get a new release with #1271 cmake changes applied for package managers. The release can be pushed to package managers (hunter in my case) and so we can work with libraries that already use the new `JsonCpp::JsonCpp` aliasing.

**Comment by bsergean** [comment]
The C++20 fixes would be great to have in a released version as well.

**Comment by julianoes** [comment]
Bump, it would be great to have a release, thank you :pray:.

**Comment by mloy** [comment]
Yes, this would solve the last failed in our CI...

Would be really nice.

**Comment by cdunn2001** [comment]
Sorry. I was very busy with work, and travis-ci.org became travis-ci.com, with some necessary migrations. That's done now. Our CI seems to be working again. So I tagged a new release, `1.9.5`. Unfortunately, that included a change for PIC with **cmake** that might be controversial. If that causes a problem, then please submit another PR with **cmake** changes and we will cut `1.9.6` pretty quickly.
