### ISSUE TITLE
Is Json::CharReaderBuilder thread safe?

### ISSUE THREAD

**Issue by Frodez** [open-source-parsers/jsoncpp#1310]
Can I share the same instance of Json::CharReaderBuilder with multiple threads?

**Comment by BillyDonahue** [comment]
Oops sorry for closing. Wrong button.
The `CharReaderBuilder` doesn't modify data that it doesn't own. It doesn't write globals or thread_local. It's a conventional object. That is, it is not "thread hostile". You can share it between threads the way you'd share a `std::vector<int>` or something. The client has to provide synchronization if it's necessary. It doesn't do anything threadish on its own.
