### ISSUE TITLE
Json::CharReader::parse success but object is disruption, using operator [] cause coredump

### ISSUE THREAD

**Issue by donghejun** [open-source-parsers/jsoncpp#1313]
**Describe the bug**
I use **Json::CharReader::parse**, it return sueccess, then i use operator [] to get value, the process raise an exception, gen coredump.

**To Reproduce**
1. parse string("123"), code as follows:
```
    JsonValue value;
    Json::CharReader* const reader = m_builder.newCharReader();
    reader->parse(string.c_str(), &(string[string.length()]), &value, &err)
```
1. First, i expect return is **false**, but it return **true**.
2. Seocnd, err string in empty.
3. Using operator [] to get value, just like **value[key]**, process crash.

**Expected behavior**
Program terminated with signal SIGSEGV, Segmentation fault.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Meson version: cmake 3.16.5
 - Ninja version: 
 - jsoncpp 00.11.0

**Additional context**
pasr **string("abc")**, it return false, Consistent with expectations.

**Comment by cdunn2001** [comment]
If the top JsonValue is a JsonString, not a JsonArray, then `[]` should throw an exception. Sounds like it does.
