### ISSUE TITLE
/opt/jsoncpp/src/test_lib_json/jsontest.h:87:37: error: ‘hexfloat’ is not a member of ‘std’

### ISSUE THREAD

**Issue by Alababdiy** [open-source-parsers/jsoncpp#1314]
[root@localhost /]# cd /opt/jsoncpp/
[root@localhost jsoncpp]# cd build/
[root@localhost build]# make 
[ 23%] Built target jsoncpp_lib
[ 47%] Built target jsoncpp_static
[ 64%] Built target jsoncpp_object
[ 76%] Built target jsontestrunner_exe
[ 82%] Building CXX object src/test_lib_json/CMakeFiles/jsoncpp_test.dir/jsontest.cpp.o
In file included from /opt/jsoncpp/src/test_lib_json/jsontest.cpp:7:0:
/opt/jsoncpp/src/test_lib_json/jsontest.h: In member function ‘JsonTest::TestResult& JsonTest::TestResult::operator<<(const T&)’:
/opt/jsoncpp/src/test_lib_json/jsontest.h:87:37: error: ‘hexfloat’ is not a member of ‘std’
     oss << std::setprecision(16) << std::hexfloat << value;
                                     ^
make[2]: *** [src/test_lib_json/CMakeFiles/jsoncpp_test.dir/build.make:76: src/test_lib_json/CMakeFiles/jsoncpp_test.dir/jsontest.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1086: src/test_lib_json/CMakeFiles/jsoncpp_test.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
[root@localhost build]# cmake ..
-- JsonCpp Version: 1.9.4
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/jsoncpp/build
[root@localhost build]# make 
Consolidate compiler generated dependencies of target jsoncpp_lib
[ 23%] Built target jsoncpp_lib
Consolidate compiler generated dependencies of target jsoncpp_static
[ 47%] Built target jsoncpp_static
Consolidate compiler generated dependencies of target jsoncpp_object
[ 64%] Built target jsoncpp_object
Consolidate compiler generated dependencies of target jsontestrunner_exe
[ 76%] Built target jsontestrunner_exe
[ 82%] Building CXX object src/test_lib_json/CMakeFiles/jsoncpp_test.dir/jsontest.cpp.o
In file included from /opt/jsoncpp/src/test_lib_json/jsontest.cpp:7:0:
/opt/jsoncpp/src/test_lib_json/jsontest.h: In member function ‘JsonTest::TestResult& JsonTest::TestResult::operator<<(const T&)’:
/opt/jsoncpp/src/test_lib_json/jsontest.h:87:37: error: ‘hexfloat’ is not a member of ‘std’
     oss << std::setprecision(16) << std::hexfloat << value;
                                     ^
make[2]: *** [src/test_lib_json/CMakeFiles/jsoncpp_test.dir/build.make:76: src/test_lib_json/CMakeFiles/jsoncpp_test.dir/jsontest.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1086: src/test_lib_json/CMakeFiles/jsoncpp_test.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by BillyDonahue** [comment]
But it is though. It's new in C++11.
https://en.cppreference.com/w/cpp/io/manip/fixed
Can you make sure you are building in C++11 or greater?
