### ISSUE TITLE
Ambiguity of the second parameter in parse ()

### ISSUE THREAD

**Issue by heretic13** [open-source-parsers/jsoncpp#1315]
**Describe the bug**
There is a specification for the json format:

https://datatracker.ietf.org/doc/html/rfc8259
and
https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf

These specifications are very clear about how booleans and null values should be represented.
See the picture.

**To Reproduce**
1. Let's write a very simple program

```c++
#include <json/json.h>
#include <iostream>
#include <vector>

int main() {
    struct Test {
        const char* name;
        const char* in;
    };
    const std::vector<Test> tests{
        {"test1", R"({ "param": false })"},
        {"test2", R"({ "param": "false" })"},
        {"test3", R"({ "param": null })"},
    };
    for (const auto& t : tests) {
        Json::CharReaderBuilder builder;
        const std::unique_ptr<Json::CharReader> reader(builder.newCharReader());
        Json::Value root;
        JSONCPP_STRING err;
        if (!reader->parse(t.in, nullptr, &root, &err))
            std::cout << t.name << ": " << err << std::endl;
    }
    return 0;
}
```

**Expected behavior**
I would expect the tests to pass completely.
However, the output of the program is very different from what is expected.
Program output:

`
test1: * Line 1, Column 12
  Syntax error: value, object or array expected.

test3: * Line 1, Column 12
  Syntax error: value, object or array expected.
`

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
Microsoft Visual Studio 2022 Preview
jsoncpp Version: 1.9.4

**Additional context**

**Comment by heretic13** [comment]
[TestBoolJson.cpp.txt](https://github.com/open-source-parsers/jsoncpp/files/6937787/TestBoolJson.cpp.txt)
sample code

**Comment by heretic13** [comment]
![describe](https://user-images.githubusercontent.com/11976009/128332755-cb8c4c23-9a7a-468d-9c95-a7006ea93a58.PNG)
screen from sprecification

**Comment by heretic13** [comment]
Research result.

Everything works if you fill in the second parameter in the parse () function.

I understand that this is written in the documentation, but I would like to make a comment.

Many third party APIs use a pointer to the beginning and end of text data to process strings. Very often the pointer to the end of the string can be omitted, in which case it is assumed that the string will be terminated with a 0-character. That is, the programmer will not have to calculate the length of the line, the function itself will do it.

My suggestions.

1. Clearly indicate that the second parameter CANNOT BE NULL / 0 / nullptr.
OR
2. Rewrite parse () function to automatically calculate the end of data (search for a 0-character), if the second parameter of the function = nullptr.

**Comment by heretic13** [comment]
OR
3. Hard check for a zero match of the second parameter and return an error.

**Comment by BillyDonahue** [comment]
Let's make this issue's description more specific.

**Comment by BillyDonahue** [comment]
I don't see an ambiguity specifically.
The documentation for the `parse` function is this:

```c++
/** \brief Read a Value from a <a HREF="http://www.json.org">JSON</a>
   * document.
   *
   * \param      beginDoc        Pointer on the beginning of the UTF-8 encoded
   *                             string of the document to read.
   * \param      endDoc          Pointer on the end of the UTF-8 encoded string
   *                             of the document to read.  Must be >= beginDoc.
   * \param[out] root            Contains the root value of the document if it
   *                             was successfully parsed.
   * \param      collectComments \c true to collect comment and allow writing
   *                             them back during serialization, \c false to
   *                             discard comments.  This parameter is ignored
   *                             if Features::allowComments_ is \c false.
   * \return \c true if the document was successfully parsed, \c false if an
   * error occurred.
   */
```

You really shouldn't assume you can pass `nullptr` into a function unless the docs say you can.
It even says "Must be >= beginDoc", which `nullptr` obviously cannot be. It would be redundant IMO to explicitly call out the `nullptr` value in particular.

I don't think adding a hard check for the contract violation is a good idea outside of debug builds. You don't want violations of input preconditions to become part of the documented contract of the function. That is, we don't want to specify that the parse function will definitely return an error when the user makes mistakes like this. That puts a burden on the library.

**Comment by heretic13** [comment]
Checking for incorrect data is needed.
You can see that the handling of string values is working. Only specific values do not work: false, true, null.

This can be confusing for the programmer.

**Comment by heretic13** [comment]
Checking for null is one extra instruction at the start. You have a library for processing string data. One zero check compared to the rest of your code is nothing.

**Comment by BillyDonahue** [comment]
> Checking for null is one extra instruction at the start. You have a library for processing string data.
> One zero check compared to the rest of your code is nothing.

I'm not talking about performance. I'm not willing to write a documented contract for what the parse function should do when the endDoc parameter is out of contract. Anyone who can read that contract is already reading the contract for the endDoc parameter and should get it right. The only error reporting available to this function is its bool result and an error string reference. Currently that error string reference is only used to report problems in the data, so applications can propagate those up to the data source. It would be inappropriate to stuff assertion failure messages about the calling code violating the parameter contracts in that string.
