### ISSUE TITLE
how to remove the quotes in json keys in C++ in jsoncpp

### ISSUE THREAD

**Issue by ruellm** [open-source-parsers/jsoncpp#1321]
I am reporting this as bug as the main page says, if there are questiosn report it as a bug :)

I im using jsoncpp in forming json in C++ and im certain that quotes in keys is part of standard or will not matter. However my client insisted that quotes should be removed from the keys so instead of

{
    "key1" : "value"
    "key2" : 0
}

he wants
{
    key1 : "value"
    key2 : 0
}

But basinc Jsoncpp example alone produces the quotes like so

Json:Value json;
json["key1"] = "value";
..
..

So how do I do this in jsoncpp without doing it manualy? Is it even possible?
should i write a new writer?

**Comment by cdunn2001** [comment]
I like your client's sense of aesthetics, but that's not JSON. The JSON standard requires quotation marks.
