### ISSUE TITLE
 Possible freeing of non-heap memory in Json::Value desconstructor

### ISSUE THREAD

**Issue by judyhappy** [open-source-parsers/jsoncpp#1322]
**Describe the bug**
After scanning, the Klocwork reported a potential problem, but the problem was not encountered during runtime.

Error:
#65354: Possible freeing of non-heap memory from 'mp.comments_'. Memory referenced by 'mp.comments_' is illegally freed by passing argument 0 to function '~Value' at line 109
Code: FNH.MIGHT | Severity: P1(1) | Support Level: Klocwork Certified(1) | State: Existing | Status: Analyze | Taxonomy: C and C++ | Reference: none | Owner: unowned

**To Reproduce**
Run Klocwork, my jsoncpp is 1.9.3

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: Android c++

**Additional context**
My sample code:

```
void Test::init() {
    Json::CharReaderBuilder builder;
    std::unique_ptr<Json::CharReader> reader(builder.newCharReader());
    Json::Value root;
    std::string json_doc;
    std::string errs;
    bool enable;
    if (!android::base::ReadFileToString(file_path, &json_doc)) {
        return;
    }

    if (!reader->parse(&*json_doc.begin(), &*json_doc.end(), &root, &errs)) {
        return;
    }

    Json::Value config = root["Config"];
    if (!config.isObject()) {
        return;
    }

    {
        Json::Value mp = config["monitors"];
        if (!mp.isObject()) {
            ALOGE("parse monitor process failed");
            return;
        }
        enable = mp["enable"].asBool();
        if (enable) {
            Json::Value list = mp["list"];
            //do some print of list
        }
    }  -->Issue happen

}
```
```
 Value::~Value() {
   switch (type_) {
   case nullValue:
   case intValue:
   case uintValue:
   case realValue:
   case booleanValue:
     break;
   case stringValue:
     if (allocated_)
       releaseStringValue(value_.string_);
     break;
   case arrayValue:
   case objectValue:
     delete value_.map_;
     break;
   default:
     JSON_ASSERT_UNREACHABLE;
   }
 
   if (comments_)
     delete[] comments_;   --> error
 }
```

Looks the free of Json::Value list modified the  Json::Value mp, and lead to the error when mp free.

**Comment by BillyDonahue** [comment]
This is not what the `Value::~Value()` destructor does in jsoncpp-v1.9.3.
https://github.com/open-source-parsers/jsoncpp/blob/1.9.3/src/lib_json/json_value.cpp#L441
I'm not sure what code you're looking at here.

**Comment by Mr-Crab** [comment]
Hi, I have encountered the same problem with code scan, and I have checked the up-to-date code on master branch, I think this problem is related with assigning the functional stack memory to the member variable "comments_" in Json::Value class. https://github.com/open-source-parsers/jsoncpp/blob/8190e061bc2d95da37479a638aa2c9e483e58ec6/src/lib_json/json_value.cpp#L971
I think this is not correct, the stack memory will be released once the function finishes, instead, we should use new operator for initializing the "comments_", right?
