### ISSUE TITLE
json parse failed with bool type sometimes

### ISSUE THREAD

**Issue by chris-shenzhen-china** [open-source-parsers/jsoncpp#1324]
this is json string below, and jsoncpp parse failed sometime. 
{
	"code" : "200",
	"data" : 
	{
		"exist" : false
	},
	"message" : "ok"
}

**Comment by cdunn2001** [comment]
Works for me. It might fail with an extra trailing comma, or maybe some other formatting error.

**Comment by chris-shenzhen-china** [comment]
thanks anyway, I hava changed to&nbsp;nlohmann_json.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-source-parsers/jsoncpp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月20日(星期一) 凌晨4:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-source-parsers/jsoncpp] json parse failed with bool type sometimes (#1324)





 
Closed #1324.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
