### ISSUE TITLE
Json::ValueIteratorBase::deref symbol not found

### ISSUE THREAD

**Issue by jeb2112** [open-source-parsers/jsoncpp#1328]
I compiled and installed jsoncpp using the vcpkg, am I am attempting to statically link the library in my application. When I dereference an iterator, I get an unresolved symbol error on linking.

**To Reproduce**
```
    .\vcpkg install jsoncpp
    .\vcpkg install jsoncpp:x64-windows-static
    .\vcpkg integrate install
    .\vcpkg list

```
```
    #include "json/json.h"
    Json::Value json; // class instance
    Json::Value::const_iterator outer = json.begin(); 
    for (Json::Value::const_iterator inner = (*outer).begin(); inner != (*outer).end(); inner++)
    {
        std::cout << "\t" << inner.key() << ": " << *inner << std::endl;
    }

```
**Expected behavior**
The above code snippet works when I build jsoncpp directly using meson/ninja, and statically link jsoncpp.lib into my application with LIBPATH. But using either vcpkg auto-link or regular LIBPATH linking, I get the error from the vcpkg built library.

**Desktop (please complete the following information):**
 - Windows 10
 - Microsoft Visual C++ 2019
 - Vcpkg package management program version 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04
 - meson 0.59.1
 - ninja 1.10.2

**Additional context**
Error	LNK2019	unresolved external symbol "protected: class Json::Value & __cdecl Json::ValueIteratorBase::deref(void)const " (?deref@ValueIteratorBase@Json@@IEBAAEAVValue@2@XZ) referenced in function "void __cdecl assign_vars(char *)" (?assign_vars@@YAXPEAD@Z)	projectname	C:\Users\username\source\assign_vars.obj	1		Build

**Comment by cdunn2001** [comment]
The symbol is in the code, but not in the way you link? We can't really debug your system. If you learn a work-around, please let us know. (I think this relates to which symbols are included in dynamic libraries by default.) If you find a fix for us, we'll take it!

I usually stick to meson/ninja to avoid odd problems on various platforms.

**Comment by jeb2112** [comment]
OK thanks for looking at it; of course it is just as easy to continue using meson. And yes, I can find the symbol in the source code, and all the #includes seem to be in place. After that, the vcpkg build process I think is by cmake which I don't know anything about so I can't debug it any further.    On Sunday, September 19, 2021, 4:27:28 PM EDT, Christopher Dunn ***@***.***> wrote:  
 
 


The symbol is in the code, but not in the way you link? We can't really debug your system. If you learn a work-around, please let us know. (I think this relates to which symbols are included in dynamic libraries by default.) If you find a fix for us, we'll take it!

I usually stick to meson/ninja to avoid odd problems on various platforms.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
