### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Joll123** [open-source-parsers/jsoncpp#1355]
Has anyone solved this problem? 
Illegal instruction (core dumped)
webrtc/third_party/jsoncpp/source/src/test_lib_json/CMakeFiles/jsoncpp_test.dir/build.make:147: recipe for target 'bin/jsoncpp_test' failed
make[2]: *** [bin/jsoncpp_test] Error 132
make[2]: *** Deleting file 'bin/jsoncpp_test'
CMakeFiles/Makefile2:4575: recipe for target 'webrtc/third_party/jsoncpp/source/src/test_lib_json/CMakeFiles/jsoncpp_test.dir/all' failed
make[1]: *** [webrtc/third_party/jsoncpp/source/src/test_lib_json/CMakeFiles/jsoncpp_test.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jgvidotto** [comment]
Did you solve this?
