### ISSUE TITLE
Build starts to fail with 1.9.5 due to JsonCpp::JsonCpp target not protected against multi-include

### ISSUE THREAD

**Issue by flichtenheld** [open-source-parsers/jsoncpp#1356]
**Describe the bug**
Our build suddenly started failing after upgrade to jsoncpp 1.9.5 with the following error:
```
CMake Error at C:/Jenkins/vcpkg/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
   _add_library cannot create imported target "JsonCpp::JsonCpp" because
   another target with the same name already exists.
Call Stack (most recent call first):
  C:/Jenkins/vcpkg/installed/x86-windows/share/jsoncpp/jsoncpp-namespaced-targets.cmake:5 (add_library)
  C:/Jenkins/vcpkg/installed/x86-windows/share/jsoncpp/jsoncppConfig.cmake:31 (include)
  C:/Jenkins/vcpkg/scripts/buildsystems/vcpkg.cmake:788 (_find_package)
```

**To Reproduce**
Have nested CMakeLists which at different places call find_package(jsoncpp)

**Expected behavior**
With 1.9.4 the build succeeds. All previous targets in jsoncpp-targets.cmake are protected against multiple definitions with something equivalent to "if (TARGET <target>) return() endif()". But the new target in jsoncpp-namespaced-targets.cmake is not similarly protected.

**Potential solutions**

Just adding
```
if (TARGET JsonCpp::JsonCpp)
  return()
endif()
```
to jsoncpp-namespaced-targets.cmake seems to prevent the issue. If you want I can open a PR to that effect. #1306 might also fix it, I haven't tested that, yet.

**Comment by Andres6936** [comment]
See #1374

**Comment by johnwason** [comment]
This is happening because the `jsoncpp-namespaced-targets.cmake` file is not checking if the target exists. A simple change adding a check to see if `JsonCPP::JsonCPP` is defined should fix this problem:

```cmake
if (TARGET jsoncpp_static AND NOT TARGET JsonCpp::JsonCpp)
    add_library(JsonCpp::JsonCpp INTERFACE IMPORTED)
    set_target_properties(JsonCpp::JsonCpp PROPERTIES INTERFACE_LINK_LIBRARIES "jsoncpp_static")
elseif (TARGET jsoncpp_lib AND NOT TARGET JsonCpp::JsonCpp)
    add_library(JsonCpp::JsonCpp INTERFACE IMPORTED)
    set_target_properties(JsonCpp::JsonCpp PROPERTIES INTERFACE_LINK_LIBRARIES "jsoncpp_lib")
endif ()
```

**Comment by baylesj** [comment]
What's left to resolve this issue?

**Comment by flichtenheld** [comment]
> What's left to resolve this issue? Seems like the original issue has been resolved and there may be some package resolution follow up work?

I see no indication that the original issue has been resolved. All the references to merged PRs and commits here are from other projects working around the problem. Merging #1435 would fix it.
