### ISSUE TITLE
Can add support for wchar_t type strings? 

### ISSUE THREAD

**Issue by hooger888** [open-source-parsers/jsoncpp#1379]
Can add support for wchar_t type strings? 
Many Unicode characters cannot be stored with char type characters

**Comment by BillyDonahue** [comment]
Many unicode characters can't be stored in wchar_t either. You have an encoding problem, not a representation type problem. Switching to wchar_t trades UTF-8 for UTF-16. I think the only major use of wchar_t is for interfacing with Win32 wide string APIs.

**Comment by hooger888** [comment]
In this case, the string conversion has to be performed in advance

**Comment by hooger888** [comment]
> Many unicode characters can't be stored in wchar_t either. You have an encoding problem, not a representation type problem. Switching to wchar_t trades UTF-8 for UTF-16. I think the only major use of wchar_t is for interfacing with Win32 wide string APIs. The JSON spec only deals with UTF-8 data so that's what jsoncpp deals with.
In this case, the string conversion has to be performed in advance

**Comment by hooger888** [comment]
> Many unicode characters can't be stored in wchar_t either. You have an encoding problem, not a representation type problem. Switching to wchar_t trades UTF-8 for UTF-16. I think the only major use of wchar_t is for interfacing with Win32 wide string APIs. The JSON spec only deals with UTF-8 data so that's what jsoncpp deals with.

In this case, the string conversion has to be performed in advance

**Comment by hooger888** [comment]
![3D6938E8-28C1-4040-8323-B042E77D1F10](https://user-images.githubusercontent.com/13042064/149084409-cbadda8b-2ae5-4143-b334-0a9d0dfb56d5.png)

**Comment by BillyDonahue** [comment]
That client code you posted a screengrab of looks fine to me, without knowing what CT2A does exactly.
You reopened the issue, but I'm not sure what you want jsoncpp to do differently.
