### ISSUE TITLE
jsoncpp.dll seems to go missing after debugging a project a few times

### ISSUE THREAD

**Issue by sp1222** [open-source-parsers/jsoncpp#1385]
**Describe the bug**

"The code execution cannot proceed because jsoncpp.dll was not found.  Reinstalling the program may fix this problem"

Working in Visual Studio 2019 on Windows 11.

It started to occur after debugging my project a few times, after adding other functionalities to the project.  I am only using jsoncpp to load and save data to/from json files.  After half a dozen or so debugging the project this error is thrown.

I have tried re-installing the package via NuGet, and I have tried downloading the repo.
I have tried running the python app to get the dist and include directories.  
I have tried adding direct paths to known locations for the jsoncpp.dll files that I am able to find on my machine.  
I have tried sfc /scannow in hopes that they needed to be repaired.

It seems there is not a good long-term solution to prevent this error from occurring for me at the moment.

**To Reproduce**
1. download/install jsoncpp into the project
2. start adding different features and functionalities in other areas of the project, and test the additions with Local Windows Debugger
3. after about half a dozen or so debugging sessions, the error occurs.

**Expected behavior**

I expected the desktop application to start.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11

**Additional context**

**Comment by BillyDonahue** [comment]
I feel for you, but what change could we possibly make to the jsoncpp git repo to help you with this?
Seems like a PC filesystem management issue that we have no control over.

**Comment by sp1222** [comment]
> I feel for you, but what change could we possibly make to the jsoncpp git repo to help you with this? Seems like a PC filesystem management issue that we have no control over.

Thank you Billy, I really appreciate the suggestion.  I will look into my PC filesystem management and do some research.  I was running around in circles and I did not know how else to resolve this issue.

**Comment by ymahajan111** [comment]
Unsubscribe
