### ISSUE TITLE
StreamWriterBuilder Object premature destruction 

### ISSUE THREAD

**Issue by vinifr** [open-source-parsers/jsoncpp#1401]
**Describe the bug**
I am not able to use the string created by StreamWriterBuilder/writeString without crash the application because apparently the object is destroyed before finish the use. Am I using wrongly?

**To Reproduce**
```
void send_ssid()
{
    std::string json_str;
    Json::Value root;
    Json::StreamWriterBuilder builder;

    root["name"] = "ssid";
    root["msg"] = ssid;
    root["request_id"] = 1;
    //
    json_str = Json::writeString(builder, root);
    websock_send(json_str.c_str());
}
...
send_ssid();
```

**Expected behavior**
Keep the string object created by writeString until websock_send() send the string to the server.

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 10

**Comment by lzpong** [comment]
maybe, you need to check the life cycle of json_str

**Comment by vinifr** [comment]
It is async.

**Comment by lzpong** [comment]
Apparently, it was destroyed
