### ISSUE TITLE
Json::Value object convert to std::string problem

### ISSUE THREAD

**Issue by ChaoII** [open-source-parsers/jsoncpp#1402]
Hi 
I try to convert Json::Value object to std::string. meanwhile, the json object contain some chinese characters such as "中国".
however,I use 
```
Json::StreamWriterBuilder builder;
const std::string json_str = Json::writeString(builder, root); 
```
finally, the result is 
<img width="361" alt="image" src="https://user-images.githubusercontent.com/44053467/167247080-3239ffcb-0aad-439b-b672-c4d967fbb540.png">
How can I solve it?
thank you!

**Comment by BillyDonahue** [comment]
The `builder` object has an `operator[]` through which you can set some parameters of the writer it produces.

You have to give the `StreamWriterBuilder` permission to `emitUTF8`.
It's not the default setting.


    Json::StreamWriterBuilder builder;
    builder["emitUTF8"] = true;
    const std::string json_str = Json::writeString(builder, root);
