### ISSUE TITLE
 Is there a feature to compare two different jsons and show their differences?

### ISSUE THREAD

**Issue by leoweyr** [open-source-parsers/jsoncpp#1413]
**Is your feature request related to a problem? Please describe**
As title. 😄  

**Describe the solution you'd like**
Maybe construct a \<method\> in \<class\>.

**Describe alternatives you've considered**
The following is the implementation method and use effect that I roughly came up with: 😃 

## Method prototype:

```cpp
int Json::Compare(const Json::Value compared, const Json::Value compare, Json::Value &differences);
/*The specific implementation method can search and compare differences in the json structure tree.
*@param: [in]<compared>	        A json that be compared.
*        [in]<compare>		Another json that be compared.
*	 [out]<differences>	A json shows the difference between <compared> and <compare>.
*@return: If <compared> and <compare> are the same, return 0; 
*	  if <compared> < <compare>, the return value is less than 0; 
*	  if <compared> > <compare>, the return value is greater than 0.
*	  The actual returned integer depends on the number of key-value pairs they differ from.
*/
```

**Comment by BillyDonahue** [comment]
I don't think there's a way to generalize such a function in a way that makes it useful to a wide audience.
Users have to write their own with the semantics appropriate for their application.
