### ISSUE TITLE
Why not provide such convenient methods as Json::Value::parse and Json::Value::stringify.

### ISSUE THREAD

**Issue by lzpong** [open-source-parsers/jsoncpp#1450]
Why not provide such convenient methods as Json::Value::parse and Json::Value::stringify.

Is there any benefit?

**Comment by BillyDonahue** [comment]
opinion: The way the API is structured, the `Value` is a value. It's neither the reader nor the writer. I think the separation is useful. The reader and writer objects are very configurable, and it's useful to have those be a central way to get Value into and out of string form.
