### ISSUE TITLE
I think it is because, there is no destructor written for Reader class & GCC6 might be strictly checking it.

### ISSUE THREAD

**Issue by LohitoBurrito** [open-source-parsers/jsoncpp#1452]
I think it is because, there is no destructor written for Reader class & GCC6 might be strictly checking it.
Try adding:
Reader::~Reader()
{
}

_Originally posted by @ya1gaurav in https://github.com/open-source-parsers/jsoncpp/issues/512#issuecomment-271557953_
      
Do you know where exactly we should add this? Thank You!

**Comment by BillyDonahue** [comment]
Can you please rewrite this to be a standalone issue?  I'm not sure what it's referring to.

**Comment by BillyDonahue** [comment]
#512 is resolved. This issue goes with it.
