### ISSUE TITLE
Ability to fetch member names without copying

### ISSUE THREAD

**Issue by Paril** [open-source-parsers/jsoncpp#1470]
Currently, there's no way to get the member name(s) of a Json object without performing a full copy of each string, and additionally adding this to an `std::vector`, both of which may incur some significant penalties with using the heap memory, etc.

Ideally, we'd be able to iterate the member names without needing to do any copying; for objects that have a lot of keys (or just a lot of throughput).

**Comment by BillyDonahue** [comment]
There's an iterator API. Are you saying that performs copies?

**Comment by Paril** [comment]
Yeah my bad; I didn't spot `memberName()` in the iterator until now. Thanks!
