### ISSUE TITLE
当我生成的json中含有中文时，输出显示乱码

### ISSUE THREAD

**Issue by wangxiaoer3924** [open-source-parsers/jsoncpp#1475]
当我生成的json中含有中文时，输出显示乱码，按照网上的教程修改valueToQuotedStringN函数，就编译不过去了，请问能推出一个不需要修改的版本么，apt  install   输出是没问题的，我不知道这个问题是咋回事
参考的连接类似下面修改，很奇怪
https://blog.51cto.com/fengyuzaitu/2711571

**Comment by BillyDonahue** [comment]
Please rewrite in English. thx.

**Comment by ISSIO** [comment]
编码格式的问题吧
