### ISSUE TITLE
Range constructor

### ISSUE THREAD

**Issue by MrAdkhambek** [open-source-parsers/jsoncpp#1490]
Hi there. When I use JsonCpp for my server I need to collect range of items. 
And now I collect via loop. This is pretty fast but doesn't understandable.

```cpp
vector<MyMessageClass> messages = TODO()
Json::Value json;

ranges::for_each(messages, [&json](const MyMessageClass &msg) {
    json.append(msg.to_json());
});
```

There are std containers that implement range constructors and in my opinion that is very pretty nice.
Can we add range constructor in JsonCpp ? or any advices are welcome

I am new at CPP and I have sample example:

```cpp
template<typename R>
explicit Value(const R &begin, const R &end) noexcept {
    Json::Value json(arrayValue);
    for (auto i = begin; i != end; ++i) {
        json.append(*i);
    }
    swap(json);
};
```

```cpp
vector<MyMessageClass> messages = TODO()
Json::Value json = messages
                      | ranges::views::transform(&MyMessageClass::toJson)
                      | ranges::ranges::to<Json::Value>(); // <- [ {} ] <- messages array
```

**Comment by BillyDonahue** [comment]
This would need to be very carefully done, and gated on C++23 support.

I am also not sure that we would always want it to produce an `arrayValue` in a range constructor.
I also don't want to accept arbitrary constructor arguments assuming they're a range pair of iterators.

I've never used std::ranges before, but I believe `ranges::to` can be given arguments to help select the Value constructor, like:

```c++
template <ValueType vt>
using ValueTypeTag = std::integral_constant<ValueType, vt>;

template<typename R, ValueType vt>
Json::Value(std::ranges::from_range_t, R&& r, ValueTypeTag<vt>) : Value{vt} {
    std::ranges::for_each(std::forward<R>(r), [&](auto&& x) { append(x); });
}

// ...

vector<MyMessageClass> messages = TODO()
Json::Value json = messages
                      | std::ranges::views::transform(&MyMessageClass::toJson)
                      | std::ranges::to<Json::Value>(Json::ValueTypeTag<Json::arrayValue>{});

```

I think you can also maybe create nonmember function to do the same thing and provide it as an argument to `std::ranges::to` to produce `Json::Value` in this way. That is, I think there's a way to get the elegant range construction you want without modifying `jsoncpp` at all. But I don't know this for sure.
