### ISSUE TITLE
Invalid json text but reader.parse return true.

### ISSUE THREAD

**Issue by gunli** [open-source-parsers/jsoncpp#151]
Hi, I got a text like 
"0A3TArdcg&j=%7B%22optype%22%3A1%7D%0A 200 OK\r\nConnection: close\r\nCache-Control: no-cache, must-revalidate\r\nContent-Type: text/plain\r\nContent-Length: 47\r\n\r\n{\"errcode\":40001,\"errmsg\":\"invalid credential\"}"

and use below code to test it:
int main(int argc, const char *argv[]) {

    std::string httpRsp = "0A3TArdcg&j=%7B%22optype%22%3A1%7D%0A 200 OK\r\nConnection: close\r\nCache-Control: no-cache, must-revalidate\r\nContent-Type: text/plain\r\nContent-Length: 47\r\n\r\n{\"errcode\":40001,\"errmsg\":\"invalid credential\"}";
    Json::Reader    reader;
    Json::Value     value;

    bool bRet = reader.parse(httpRsp, value);
    if (!bRet)
    {
        printf("parse response failed.");
        return -1;
    }

    int retVal = value.get("ret", -1).asInt();
    printf("parse response OK, ret=%d.", retVal);
    return 0;
}

reader.parse() do NOT return false and set the type of value to intvalue, and the process crash when is run to line:value.get("ret", -1).asInt() . Then I validate the text with  http://jsonlint.com/, it tell me that text is NOT a valid json text.  

So, I afraid there is something wrong in the logic of function reader.parse().

**Comment by cdunn2001** [comment]
```
0A3TArdcg&j=%7B%22optype%22%3A1%7D%0A 200 OK
Connection: close
Cache-Control: no-cache, must-revalidate
Content-Type: text/plain
Content-Length: 47

{"errcode":40001,"errmsg":"invalid credential"}
```
The body is valid JSON.
```
Value get(const std::string& key, const Value& defaultValue) const;
```
You are calling it like this:
```
value.get("ret", -1)
```
Instead, try this:
```
Value const minusOne(-1);
value.get("ret", minusOne);
```
And put the `asInt()` call on a separate line.

If none of that helps, run a debugger on it. If you discover the actual bug (whether in your code or in ours), please post it here, along with the version/commit/compiler/OS/machine. We're interested.

I hope that helps. We can accept bug-fixes, but we cannot debug your code.

**Comment by gunli** [comment]
Hi,

Thank you for replying me. 

I sorry that I forgot the version of jsoncpp I used in my project, I remember I downloaded it on someday of Oct 2013, it must be an old version.

In my project, I used jsoncpp to decode json string, most of the time it runs well, but it coredump on 01/27/2015, gdb showed me the string pass to function reader.parse() was

"0A3TArdcg&j=%7B%22optype%22%3A1%7D%0A 200 OK\r\nConnection: close\r\nCache-Control: no-cache, must-revalidate\r\nContent-Type: text/plain\r\nContent-Length: 47\r\n\r\n{\"errcode\":40001,\"errmsg\":\"invalid credential\"}"

I know it was an HTTP response, and the body is a valid json string, in most of the time, the caller pass the body only to the reader.parse() and it runs well, but in exception case, the whole HTTP response is passed to the reader.parse(), and it is NOT a valid json string, so I think it should return false, because it is NOT a valid json. 

I refer the RFC of json and test the string on the site of jsonlint, I don't think the string is a valid json string.

I test it again with your suggestion, it crash again. It crash on both Windows and Linux. the VERSION of jsoncpp is 0.6.0-dev. it debug test, it asert at the below code:
const Value &Value::operator[](const char *key) const {
  JSON_ASSERT_MESSAGE(
      type_ == nullValue || type_ == objectValue,
      "in Json::Value::operator[](char const*)const: requires objectValue");

I have downloaded the newest version of jsoncpp, because it use some new C++ features, I have no compiler to compile it, so I don't know if the bug fixed in the newest version.

**Comment by gunli** [comment]
if (!reader.parse(httpResponse, value))
    {
        tlog_info(appLog, 0, 0, "parse response failed.");
        return -1;
    }

    if (!value.isObject())
    {
        tlog_info(appLog, 0, 0, "parse response failed.");
        return -1;
    }

I add  if (!value.isObject()) to avoid the crash now.

**Comment by cdunn2001** [comment]
Good! Also, I think you were parsing the entire HTTP message, not just the body.
