### ISSUE TITLE
Undefined reference to things

### ISSUE THREAD

**Issue by AtomDRP** [open-source-parsers/jsoncpp#1518]
**Describe the bug**
Can't get this to compile. I have the file structure

```
├── json
│   ├── allocator.h
│   ├── assertions.h
│   ├── config.h
│   ├── forwards.h
│   ├── json_features.h
│   ├── json.h
│   ├── reader.h
│   ├── value.h
│   ├── version.h
│   └── writer.h
├── test.cpp
├── test.json
```
with `test.cpp`
```c++
#include <iostream>
#include <fstream>
#include "json/json.h"

int main()
{
    Json::Value data;
    std::ifstream infile("test.json", std::ifstream::binary);
    infile >> data;

    return 0;
}
```
and `test.json`
```json
{
    "Anna":
    { 
        "age": 18,
            "profession": "student"
        },
    "Ben":
    {
        "age" : "nineteen",
        "profession": "mechanic"
    }
}
```
When I try `g++ test.cpp`, I get the following errors
```
:> g++ test.cpp
/usr/bin/ld: /tmp/ccXsOQrc.o: in function `main':
test.cpp:(.text+0x2f): undefined reference to `Json::Value::Value(Json::ValueType)'
/usr/bin/ld: test.cpp:(.text+0x66): undefined reference to `Json::operator>>(std::istream&, Json::Value&)'
/usr/bin/ld: test.cpp:(.text+0x89): undefined reference to `Json::Value::~Value()'
/usr/bin/ld: test.cpp:(.text+0xca): undefined reference to `Json::Value::~Value()'
collect2: error: ld returned 1 exit status
```

**To Reproduce**
1. Given the `test.cpp` and `test.json` files above, try `g++ test.cpp`

**Expected behavior**
I expect this to compile without errors. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS

**Comment by k4p1cz** [comment]
Same problem but on Windows

**Comment by BillyDonahue** [comment]
You don't have a compile error. You have a link error.
You have only included a few of jsoncpp's headers. That's insufficient.

You have to install the whole library, and link your program to it.
This is not a jsoncpp bug.

You just need some more experience with the idioms for using C++ libraries.
