### ISSUE TITLE
RedHat 6.5 issue

### ISSUE THREAD

**Issue by Albert65** [open-source-parsers/jsoncpp#153]
Hi All,

RedHat 6.5 has relatively old compiler gcc 4.4.7. Although it recognizes -std=c++0x option,
nullptr is not defined. In order to compile tests I have to add an extra cmake option:

cmake ... -DCMAKE_CXX_FLAGS="-fPIC -Dnullptr=NULL"

The flag -fPIC is also useful, otherwise an application sometimes fails to link against static jsoncpp library.

Best regards,
Albert

**Comment by cdunn2001** [comment]
I need more info on the `-fPIC` problem. If you link against a static library, you might prefer the extra efficiency of non-pic code. (Also, it saves a register.) If you build *both* shared *and* static libraries, the linker will prefer the shared library, and you'll be fine.

Dropped nullptr on `master`.

We really want a clean break for C++11 at some point though. You are probably better off using `0.7.x` for an older arch. We will soon have a `0.8.x` that is binary-compatible with `0.6.x`, but I don't think that's the issue in your case.
