### ISSUE TITLE
could u support hexadecimal parameters?

### ISSUE THREAD

**Issue by dongdong-q** [open-source-parsers/jsoncpp#1540]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to use hexadecimal format and it is better than decimal when I use json as configuration files

**Describe the solution you'd like**
I hope we can support "0x*****" as input inside asInt**() APIs.

**Describe alternatives you've considered**
currently I made changes locally, recognize hex format as string and read it successfully.

**Comment by baylesj** [comment]
JSON dos not support hexidecimals. You could store them as a string?
