### ISSUE TITLE
CMake Error: INSTALL(EXPORT) given unknown export "jsoncpp"

### ISSUE THREAD

**Issue by DanTheColoradan** [open-source-parsers/jsoncpp#155]
I might be messing up somewhere here but when I try:

```{.sh}
cmake -DJSONCPP_WITH_CMAKE_PACKAGE=ON ..
```

I get the following error:

```{.txt}
-- JsonCpp Version: 1.4.0
-- Configuring done
CMake Error: INSTALL(EXPORT) given unknown export "jsoncpp"
-- Generating done
-- Build files have been written to: /Users/polancod/Git/jsoncpp/build
```

**Comment by DanTheColoradan** [comment]
By the way:
cmake version 3.1.1
Mac OS X Mavericks

**Comment by cdunn2001** [comment]
> -DJSONCPP_WITH_CMAKE_PACKAGE=ON

I get the same thing. I'm not familiar with `XXX_WITH_CMAKE_PACKAGE`. Could you link some documentation for us.

Or try the cmake line in `README.md`. I use this:
```
mkdir -p build/debug
cd build/debug
cmake -DCMAKE_BUILD_TYPE=debug -DJSONCPP_LIB_BUILD_STATIC=ON -DJSONCPP_LIB_BUILD_SHARED=OFF -G "Unix Makefiles" ../..
make
```

**Comment by DanTheColoradan** [comment]
On line 9 of the [root CMakeLists.txt](https://github.com/open-source-parsers/jsoncpp/blob/master/CMakeLists.txt#L9) it has the option. I didn't find it in the documentation so maybe it isn't supported any longer?

I forked the repo and changed [that line](https://github.com/DanTheColoradan/jsoncpp/blob/test/cmake_package/CMakeLists.txt#L9) to "ON". The travis build [fails](https://travis-ci.org/DanTheColoradan/jsoncpp). That leads me to believe it isn't a problem with passing the option, but it's something wrong with the [install line of the root cmake](https://github.com/DanTheColoradan/jsoncpp/blob/master/CMakeLists.txt#L108). Perhaps it is related to this:

["Move the 'EXPORT foo-targets' to just after 'TARGETS foo'."](http://cmake.3232098.n2.nabble.com/install-TARGETS-given-unknown-argument-quot-EXPORT-quot-with-cmake-2-8-9-td7586762.html)

The reason I was hoping to use it was because I was attempting to package jsoncpp with my own project using cmake. I'm not super experience with cmake, but that looks exactly like the option I could use.

**Comment by DanTheColoradan** [comment]
I was able to overcome this problem by using ExternalProject_Add, but I'm going to leave this issue open since it seems like it might worth looking into.

**Comment by cdunn2001** [comment]
Fixed. Thanks.
