### ISSUE TITLE
Error with parse via Json::Reader

### ISSUE THREAD

**Issue by armind13** [open-source-parsers/jsoncpp#164]
I modified one of tests, as:
``` cpp
JSONTEST_FIXTURE(ReaderTest, parseWithOneError) {
  Json::Reader reader;
  Json::Value root;
  bool ok = reader.parse(" \"property\" : \"value\" }", root);
  JSONTEST_ASSERT(!ok);
}
```
Note: missed '{' in begin of string.

**Comment by cdunn2001** [comment]
What commit had the error? I cannot find it.

**Comment by armind13** [comment]
I downloaded parser from master branch and compiled it. When I try parse string like this (when count of opening braces not equals count of closing braces)
```cpp
" \"property\" : \"value\" }" 
```
Json::Reader say that all OK and it don't found errors. But this string is wrong. Or I wrong?

**Comment by cdunn2001** [comment]
The following is valid JSON:
```
"property"
```
As soon as we have parsed valid JSON from the stream, we stop parsing. #107 is another example.

You can detect the error by parsing a second value from the same stream.

**Comment by armind13** [comment]
I think you don't understand me. Please check string "property": "value"} on http://jsonlint.com/ or http://jsonformatter.curiousconcept.com/ . After that check {"property": "value"} .

**Comment by cdunn2001** [comment]
> `"property": "value"}`

The parser accepts the first valid JSON string that it finds. It sees a string, `"property"`, so it parses a string and stops.

The odd thing is that we do not currently parse directly from the stream. We first consume the entire stream. So for the new `CharReader`, I agree that we should optionally check the rest of the input for whitespace. I'm just saying it's not a bug.

What commit/version are you using? If you're at the tip of `master`, 1.4.0-rc.3, then I can add a feature in a day or two which will cause an error if the string has trailing non-whitespace.

**Comment by cdunn2001** [comment]
Can you test that commit? It works your specific example and passes all tests, but I wouldn't mind extra testing.
