### ISSUE TITLE
Support zero, a valid UTF8 value.

### ISSUE THREAD

**Issue by cdunn2001** [open-source-parsers/jsoncpp#176]
This would be a non-default setting, since it could break things.

* http://stackoverflow.com/questions/22984475/how-to-assign-data-inside-a-char-pointer-in-c-to-jsoncpp

**Comment by cdunn2001** [comment]
From Peter Schaeffer (February 2015, privately):

> Of late I have been trying to create (serialize) JSON and use (deserialize) JSON with jsonCpp. Generally, this works pretty well. However, nulls (binary zero bytes) have been giving me fits.
 
> Consider the following C++ (not null-terminated C) string. It is three bytes long. They bytes are
```
A
Null (binary zero)
B
```
> Let’s call the string testData. The following statement fails because it stops at the binary zero.
```cpp
members["sss"] = testData;
```
In some respects, it shouldn’t fail because the code below should convert the binary zero to “\\u0000” (note that the double backslash is really just one backslash inside the C++ string). Of course, the isControlCharacter call excludes binary zero. However, the code never gets that far.
```cpp
if (isControlCharacter(*c)) {
        std::ostringstream oss;
        oss << "\\u" << std::hex << std::uppercase << std::setfill('0')
            << std::setw(4) << static_cast<int>(*c);
        result += oss.str();
      } else {
        result += *c;
      }
```
> The code below fails. duplicateStringValue is OK. Howeve, value_string is a char * pointer.
```cpp
Value::Value(const std::string& value) {
  initBasic(stringValue, true);
  value_.string_ =
      duplicateStringValue(value.c_str(), (unsigned int)value.length());
}
```
> To resolve this I decided to get smart by passing in the following
```cpp
members["sss"] = “A\\u0000B”; // (note that the double backslash is really just one backslash inside the C++ string)
```
> That helps a bit. However, the final JSON ends up with “A\\\\u0000B” (really just two consecutive backslashes inside the C++ string). The problem is that valueToQuotedString always duplicates backslash characters even if they are followed by a ‘u’ (lower case U). As you can see, I tried to fix this problem below. My fix appears to work.
```cpp
std::string valueToQuotedString(const char* value) {
  if (value == NULL)
    return "";
  // Not sure how to handle unicode...
  if (strpbrk(value, "\"\\\b\f\n\r\t") == NULL &&
      !containsControlCharacter(value))
    return std::string("\"") + value + "\"";
  // We have to walk value and escape any special characters.
  // Appending to std::string is not efficient, but this should be rare.
  // (Note: forward slashes are *not* rare, but I am not escaping them.)
  std::string::size_type maxsize =
      strlen(value) * 2 + 3; // allescaped+quotes+NULL
  std::string result;
  result.reserve(maxsize); // to avoid lots of mallocs
  result += "\"";
  for (const char* c = value; *c != 0; ++c) {
    switch (*c) {
    case '\"':
      result += "\\\"";
      break;
    case '\\':
      if (*(c+1) != 0  &&
          *(c+1) == 'u')
        result += *c;
      else
        result += "\\\\";
      break;
```
> However, the JSON fails on the input side (reading from JSON). Note that  `Reader::decodeString(Token& token, std::string& decoded)` appears to work perfectly. This routine converts `\u0000` to a single binary zero byte and builds a 3 byte C++ string containing A, null, B.

> Conversely, the code below fails
```cpp
Value::Value(const std::string& value) {
  initBasic(stringValue, true);
  value_.string_ =
      duplicateStringValue(value.c_str(), (unsigned int)value.length());
}
```
> `duplicateStringValue` is actually OK. However, `value_.string_` is a `char*`, not a C++ string. That’s fatal.

> Any ideas about how to resolve this? Have you considered using C++ strings internally rather than `char*` variables?
>
> Thank you

**Comment by cdunn2001** [comment]
We need an extra field for either size or end of string. We cannot add something to `Json::Value` without breaking binary-compatibility.

However, we can *prepend* the size to the `string_` field. That's a hack, but an efficient one. I'll cod that up and include as many of your suggestions as possible.

Peter Schaeffer, Would you like to test it? Also, if you are doing some experiments, feel free to point us to your code on a branch in GitHub.

**Comment by cdunn2001** [comment]
Look at the `allow-zero` branch. It works for normal cases. However, I do not have any good ideas for `StaticString` nor `ConstString`. Suggestions?

**Comment by pschaeffer** [comment]
Mr. C. Dunn, 
I agree about not breaking binary compatibility. 
You mentioned adding a size field as a prefix. Wouldn't it be easier to use C++ strings internally?

**Comment by pschaeffer** [comment]
Mr. C. Dunn,
Older versions of JsonCpp appear to define a copy assignment operator like
  Value &operator=( const Value &other);
Newer versions of JsonCpp appear to have a different definiition
  Value& operator=(Value &other);

This change causes some code to no longer work. Essentially the linker can not find the required entry point in the JsonCpp library. 

Any comments or suggestions you might have would be appreciated.

**Comment by cdunn2001** [comment]
What new version are you using? Try [`0.8.x`](https://github.com/open-source-parsers/jsoncpp/releases). The binary-compatibility problem (including `operator=()`) has been resolved there.

**Comment by cdunn2001** [comment]
Btw, `1.0.x` has this:
```
operator=(Value other);
```
Sans ampersand. I don't see `operator=(Value& other);` anywhere. Please specify commit/version.
