### ISSUE TITLE
Parser fails on parsing arrays with allowDroppedNullPlaceholders feature

### ISSUE THREAD

**Issue by CyberCelly** [open-source-parsers/jsoncpp#178]
Trying to parse simple arrays:

```c++
std::string documentsArray[] = {
    /*0 */"[]",
    /*1 */"[null]",
    /*2 */"[,]",
    /*3 */"[,,,]",
    /*4 */"[null,]",
    /*5 */"[,null]",
    /*6 */"[,,]",
    /*7 */"[null,,]",
    /*8 */"[,null,]",
    /*9 */"[,,null]",
    /*10*/"[[],,,]", 
    /*11*/"[,[],,]", 
    /*12*/"[,,,[]]",
};

std::vector<std::string> docs(documentsArray, 
    documentsArray + (sizeof(documentsArray) / sizeof(std::string)));
Json::CharReaderBuilder builder;
builder.settings_["allowDroppedNullPlaceholders"] = true;
std::auto_ptr<Json::CharReader> reader(builder.newCharReader());

for (std::vector<std::string>::const_iterator it = docs.begin(); it != docs.end(); ++it)
{
    Json::Value root;
    std::string errors;

    if (reader->parse(it->c_str(), it->c_str() + it->length(), &root, &errors))
    {
        std::cout << root.toStyledString() << std::endl;
    }
    else
    {
        std::cout << errors << std::endl;
    }
}
```

Output:
**case 0**
>[]

**case 1**
>[ null ]

**case 2**
>* Line 1, Column 3
>  Syntax error: value, object or array expected.

**case 3**
>* Line 1, Column 5
>  Syntax error: value, object or array expected.

**case 4**
>* Line 1, Column 7
>  Syntax error: value, object or array expected.

**case 5**
>[ null, null ]

**case 6**
>* Line 1, Column 4
>  Syntax error: value, object or array expected.

**case 7**
>* Line 1, Column 8
>  Syntax error: value, object or array expected.

**case 8**
>* Line 1, Column 8
>  Syntax error: value, object or array expected.

**case 9**
>[ null, null, null ]

**case 10**
>* Line 1, Column 7
>  Syntax error: value, object or array expected.

**case 11**
>* Line 1, Column 7
>  Syntax error: value, object or array expected.

**case 12**
>[ null, null, null, [] ]

In cases 0, 1, 5, 9, 12 parser works.
For other cases it fails with mentioned errors.

**Comment by cdunn2001** [comment]
I'm glad to hear that someone is using this strange feature. Could you tell us your use-case? JavaScript? Also, which git-commit?

You have found problems for arrays. For objects, this also fails (no comma after missing null):
```js
{
  "a":
}
```
But this works:
```js
{
  "a":,
  "b":true
}
```
I have fixed all your cases, plus that one, in pull #179.

**Comment by CyberCelly** [comment]
Thank you. Yes, I'm using this feature to parse JavaScript arrays. I tried releases  0.8.3 and 1.4.3.

**Comment by cdunn2001** [comment]
Interesting.

The tip of `master` should work for you. Do you need a release? If so, `0.8.4` or `1.4.4`? I'm just curious which branch you prefer.

**Comment by CyberCelly** [comment]
It will be good if you provide release 1.4.4. Thanks.

**Comment by cdunn2001** [comment]
[Done](https://github.com/open-source-parsers/jsoncpp/releases/tag/1.4.4).
