### ISSUE TITLE
Parser fails on 'single quoted' keys

### ISSUE THREAD

**Issue by CyberCelly** [open-source-parsers/jsoncpp#182]
Trying to parse objects with single quoted keys:
```c++
Json::CharReaderBuilder builder;
builder.settings_["allowDroppedNullPlaceholders"] = true;
std::auto_ptr<Json::CharReader> reader(builder.newCharReader());

Json::StreamWriterBuilder writer;

Json::Value root;
std::string rawJson = "{'key': \"qwerty:123456\", 'isError':  false }";
std::string errors;

if (reader->parse(rawJson.c_str(), rawJson.c_str() + rawJson.length(), &root, &errors))
{
    std::cout << Json::writeString(writer, root) << std::endl;
}
else
{
    std::cout << errors << std::endl;
}
```
Getting an error:
>* Line 1, Column 2  Missing '}' or object member name

Also, is it possible to add support of unquoted keys?

**Comment by cdunn2001** [comment]
You can try the `allow-single-quotes` branch.

Only for the reader, right? There is not much point for the writer.

**Comment by CyberCelly** [comment]
Right. This improvement make sense only for the reader.
I have tested this feature, and it is works for me. Thank you.
And what about:
>is it possible to add support of unquoted keys?

**Comment by cdunn2001** [comment]
> is it possible to add support of unquoted keys?

No, that would make parsing too difficult.
