### ISSUE TITLE
cmake source usage

### ISSUE THREAD

**Issue by marklakata** [open-source-parsers/jsoncpp#187]
I want to build jsoncpp as a CMake subdir project. Both of the following methods work, but they have disadvantages. The first one unnecessarily builds and runs the jsoncpp tests each time the project is built:

     add_subdirectory(${JSONCPP} ${CMAKE_BINARY_DIR}/jsoncpp )

This second method includes just the relevant subdirectory I really want, but without my hack it fails because RUNTIME_INSTALL_DIR et al are not defined.  I'm not using jsoncpp as an installed library, it is just source which is statically linked with my project. So I put in dummy `sets` to make CMake happy, but these are just dummies.

    set(RUNTIME_INSTALL_DIR bin)
    set(LIBRARY_INSTALL_DIR lib)
    set(ARCHIVE_INSTALL_DIR lib)
    add_subdirectory(${JSONCPP}/src ${CMAKE_BINARY_DIR}/jsoncpp )

It would be nice if you could just do

    add_subdirectory(${JSONCPP}/src ${CMAKE_BINARY_DIR}/jsoncpp )

Now I could be just doing something wrong, but I couldn't find any documentation on how to do it right.

**Comment by cdunn2001** [comment]
We don't experiment much with this because we are unable to test on all platforms. It is important for older versions of cmake to work also.

Apparently, [`EXCLUDE_FROM_ALL`](http://www.cmake.org/cmake/help/v3.0/prop_tgt/EXCLUDE_FROM_ALL.html) [could be used to avoid tests](https://github.com/open-source-parsers/jsoncpp/issues/81). Seems like [that existed on previous versions of cmake](http://www.cmake.org/cmake/help/v2.8.8/cmake.html) too. But we want the tests to run by default. They are pretty quick. Maybe you have a way to turn them off based on some flag?

**Comment by cdunn2001** [comment]
One nice feature of jsoncpp (which blep@ wrote long ago) is `amalgamate.py`. You can use it to produce a single .cpp and single .h file, which you can then copy into your own project. Trying to get cmake subprojects working might not be worth the effort.

But if you submit a pull-request, we'd probably accept it.

**Comment by Gachapen** [comment]
We do this in our project and solve the problem by forcing the JSONCPP_WITH_TESTS variable to OFF before calling `add_subdirectory`. e.g. `set(JSONCPP_WITH_TESTS OFF CACHE BOOL "Enable jsoncpp tests" FORCE)`.

It feels a bit hacky since you have to provide a new docstring, and it will override a users setting. But you can provide your own options for disabling and enabling the testing.

The code we use is available here from line 1 to 12: https://bitbucket.org/suttungdigital/nox-engine/src/59eed62fdfdc20a246c9dd68d6fa1a79555bf9cd/third_party/CMakeLists.txt?at=master#cl-1

**Comment by cdunn2001** [comment]
I'm curious: What are the speeds like for you? On my macair, the whole things takes 8s, about half in compilation of the non-test code. The tests take 1.5s. I know that every second counts in a large project, but are you mainly just annoyed by the *output* of the tests, or the runtime?

I have found a simple way to eliminate the python tests. The compiled unit-tests would still run, but those are *very* fast (< 0.1s). Would that satisfy everyone?

**Comment by cdunn2001** [comment]
Oh! Actually, the unit-tests are now run only the first time. This seems perfect. Yes?

**Comment by Gachapen** [comment]
Yes, I tested with master and the current behavior is perfect. It only runs the tests when something's changed in jsoncpp. I'll re-enable testing by default in our project when I update our jsoncpp version. Thanks!

**Comment by marklakata** [comment]
Running the tests only if there is a change to the JSONCPP source is fine.  I've tested the new code on master, and it seems to work (it ran the tests once, and appears less verbosely as well).

I suppose I am not concerned so much about running the tests, as running other things that I don't want to run in the future.  I just want the source.  

I like the CMake concept of directly importing other CMake project sources.  I'm using an IDE (CLion) that uses CMake as the core project manager, so I can easily navigate the original source code (and perhaps fix bugs in the original source code). If you run the amalgamator, then the source code is strictly "read only".

**Comment by marklakata** [comment]
Now that I've ported my CMake project to Windows, I'm having issues again with the tests being included automatically by CMake.

* Aesthetically, Visual Studio displays all of the CMake subdirs, and I don't really want to see jstontestrunner, test_lib_json, jsonchecker, etc in that list.
* Additionally, some of the tests put their output in the source tree, which causes trouble if the source tree is read-only (cf Perforce).
* And finally, there is now a dependence on python being installed to run the tests.

So I've got back to my original solution (`subdir jsoncpp/src/lib_json`) which just pulls in the source and nothing else.  Maybe I'll figure out how to do a pull request and submit a cleaner method that doesn't require setting those other 3 vars ahead of time.

**Comment by cdunn2001** [comment]
Mark, cmake is wasting hours of your time. Use `amalgamate.py`.

**Comment by marklakata** [comment]
CMake is actually quite nice when it works. Managing python on Windows and Linux is a pain in the butt, and yet another dependency of the build chain. And if I use amalgamate, I can't edit the code and submit pull-requests to git hub.

**Comment by cdunn2001** [comment]
True.

Interestingly, you can type code directly into GitHub. But personally, I would use one directory for GitHub interactions plus running amalgamate, and a separate directory for projects. I would copy the .h/.cpp to the other project. It's a rare thing.

But I don't know how to avoid Python. I really don't like relying on VisualStudio for *everything*. I need to be able to run my own program for parts of the build. If not Python, then what language?

**Comment by marklakata** [comment]
I try to use tools that are always there, until it gets so bad that I have to install another dependency. So,  first use a .BAT script if it is only a few lines. I also sometimes write my build "script" in C#, so that VisualStudio has to build it, but at least it is self contained inside the VS project (example would be something that calculates a CRC and inserts into a firmware image file). In the past, I've used perl and python to do build scripting, but it is a pain to get someone else to use the same tool chain.  Sometimes you just have to get dirty with Bison or equivalent, and that is job security...

**Comment by cdunn2001** [comment]
Oh! That's an idea! cmake can build an executable (a little C++ program) which does the amalgamating.

But is it worth it? In theory, we could simply put everything into one header and one .cpp file, obviating the whole process of "amalgamation". Sounds like you don't really want to use the amalgamated source at all. You just want cmake to work.

Maybe someday you or someone else will submit a patch for our cmakefiles to make everyone happy. I don't have a strong opinion on this.

**Comment by marklakata** [comment]
seems like amalgamate could be written as 

     cat *.h > jsoncpp.h
     cat *.cpp >> jsoncpp.cpp

and if that doesn't work, then fix the header files with appropriate preprocessor magic so that it does work.  You can also do the concatenation in cmake.

http://stackoverflow.com/questions/15282444/using-cmake-how-can-i-concat-files-and-install-them

**Comment by cdunn2001** [comment]
Does Windows have `cat`? I guess it has `type`.

Anyway, this means a script for each architecture.

Naturally, I did not write amalgamate.py. I made it python3-compatibile, but I never use it myself. Maybe it could be simpler. If you submit a .bat file that works for you, we'd probably include it.

But I don't think you even need amalgamate.py. Just include all the .cpp and .h files in your project. You could write your own .bat file to copy them from X to Y. That's what I would do. (Actually, I would copy public headers plus the built library.)

**Comment by marklakata** [comment]
I'm not planning on amalgamating. I'm just saying that `amalgamate.py` seems over-engineered.

**Comment by cdunn2001** [comment]
Mark, Python should not be needed for VS anymore. If available, you can still run the Python tests as `jsoncpp_check`, but the Python `FindPackage(PythonInterp)` is no longer required.
