### ISSUE TITLE
subclass std::runtime_error for jsoncpp specific exceptions

### ISSUE THREAD

**Issue by marklakata** [open-source-parsers/jsoncpp#188]
I would like to catch parsing exceptions due to malformed input, but I don't want to catch all `std::runtime_error` exceptions. Perhaps

    class json_runtime_error : public std::runtime_error
    {
    ...
    }

**Comment by cdunn2001** [comment]
Could you be more specific? In theory, parsing does not throw any exceptions (aside from OOM and stack-overflow). `operator>>(istream&)` does. But `bool parseFromStream()` does not, nor the lower-level `bool CharReader::parse()`.

Is there a case where an exception is thrown? We're definitely willing to use a specific exception type in those cases.

**Comment by marklakata** [comment]
I would like the JSON parser to throw exceptions if the input is invalid, that is, just bad JSON format (unclosed braces, mismatched quotes, etc). I want to be able to catch that at a different granularity than OOM problems.

**Comment by cdunn2001** [comment]
But you don't have to catch parsing errors at all. If `parse` returns false, then parsing failed. Why not check the return value and throw your own exception?

**Comment by marklakata** [comment]
I was learning from the documentation, and I didn't see a `parse` call:


    Json::Value root;   // 'root' will contain the root value after parsing.
    std::cin >> root;

I assumed this would (rightly) throw some exception if parsing failed.

**Comment by cdunn2001** [comment]
Yes, `operator>>(istream&, Value&)` will throw an exception, because the only other way to show an error would be set the error on the istream, which is not semantically correct.

But look at [Advanced Usage](http://open-source-parsers.github.io/jsoncpp-docs/doxygen/).
```cpp
bool parseFromStream(...)
```
That requires a `StreamWriterBuilder`. You can simply instantiate the default version, as in the example.
```cpp
Json::Value root;
Json::CharReaderBuilder rbuilder;
std::string errs;
bool ok = Json::parseFromStream(rbuilder, std::cin, &root, &errs);
```
One neat thing is `errs`, which you can print to show exactly what line/column had the parsing error.

**Comment by cdunn2001** [comment]
JSON_ASSERT now throws `std::logic_error`. In a way, that goes the wrong direction, but it forces people to trap `std::exception` instead of `std::runtime_error`, which will help if/when we provide our own exception class.
