### ISSUE TITLE
Build error: missing include <algorithm>

### ISSUE THREAD

**Issue by rickyviking** [open-source-parsers/jsoncpp#200]
Hi there,

I've just downloaded version 1.5.1 and it doesn't build on VisualStudio 2013 with he following error:
> jsoncpp-1.5.1\src\lib_json\json_value.cpp(237): error C2039: 'min' : is not a member of 'std'
>jsoncpp-1.5.1\src\lib_json\json_value.cpp(237): error C3861: 'min': identifier not found

\#include \<algorithm\> fixes the issue.

VS2013 also reports some warning due to type casting, I just report some of them as a reference, in case you're not using this compiler:
> jsoncpp-1.5.1\src\lib_json\json_value.cpp(328): warning C4267: 'argument' : conversion from 'size_t' to 'unsigned int', possible loss of data
> jsoncpp-1.5.1\src\lib_json\json_value.cpp(940): warning C4267: 'argument' : conversion from 'size_t' to 'unsigned int', possible loss of data
> jsoncpp-1.5.1\src\lib_json\json_value.cpp(960): warning C4244: 'argument' : conversion from '__int64' to 'unsigned int', possible loss of data

**Comment by cdunn2001** [comment]
Could you try the new tip of `master`, ff63d034e565d29fb189840fe82a019ada0dd431?

**Comment by rickyviking** [comment]
Hi Christopher,
it builds now. There are still link errors on the tests when building as shared library:
>------ Build started: Project: jsoncpp_test, Configuration: Release x64 ------
>main.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl Json::writeString(class Json::StreamWriter::Factory const &,class Json::Value const &)" (?writeString@Json@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVFactory@StreamWriter@1@AEBVValue@1@@Z) referenced in function "public: virtual void __cdecl TestStreamWriterTestdropNullPlaceholders::runTestCase(void)" (?runTestCase@TestStreamWriterTestdropNullPlaceholders@@UEAAXXZ)
>D:\SourceCode\jsoncpp\VS2013-x64\src\test_lib_json\Release\jsoncpp_test.exe : fatal error LNK1120: 1 unresolved externals

With the static config everyhing runs smooth.
Ricky

**Comment by cdunn2001** [comment]
Oh! Thanks for posting that.

**Comment by cdunn2001** [comment]
Hmmm. Did you run cmake first? That symbol is definitely defined. I think your VS setup is not linking with the shared library at all.

... Oh, I'll bet those global functions need dllexport annotations. Would you try the tip of `master` again? (And would you be willing to try a branch?)

**Comment by rickyviking** [comment]
Hi,
things getting better - jsontestrunner_exe build fine now.
Errors are now in jsoncpp_test, complaining about something in the post-build events - see below.
No problem in switching to a branch!
Cheers,
ricky

>------ Build started: Project: jsoncpp_test, Configuration: Release x64 ------
>  jsoncpp_test.vcxproj -> D:\SourceCode\jsoncpp\VS2013-x64\src\test_lib_json\Release\jsoncpp_test.exe
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: The command "setlocal
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: Release\jsoncpp_test.exe
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :cmEnd
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :cmErrorLevel
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: exit /b %1
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :cmDone
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :VCEnd" exited with code -1073741515.
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========

**Comment by cdunn2001** [comment]
Any ideas?

**Comment by cdunn2001** [comment]
What is your cmake command?

**Comment by rickyviking** [comment]
I attach a screenshot with the CMake settings i'm using. 
It's quite strange though that building as static doesn't raise thos issues...

![image](https://cloud.githubusercontent.com/assets/2272034/6510114/39934756-c364-11e4-9476-89961903767a.png)

**Comment by cdunn2001** [comment]
```
cmake -DCMAKE_BUILD_TYPE=debug -DJSONCPP_LIB_BUILD_STATIC=OFF -DJSONCPP_LIB_BUILD_SHARED=ON -G "Visual Studio 10" ../..
```
We see your problem now. A friend can repro. And we have a fix. Just checking some other things first...

**Comment by cdunn2001** [comment]
Try `vs` branch. Your problem should be solved.
