### ISSUE TITLE
JSONCPP_DEPRECATED should also support gcc and clang

### ISSUE THREAD

**Issue by Dani-Hub** [open-source-parsers/jsoncpp#208]
Both gcc and clang also allow for marking entities as deprecated including a way to provide a message. For these systems the proper definition of the JSONCPP_DEPRECATED would be:

```
#if (defined(__clang__) && __has_attribute(deprecated)) || (defined(__GNUC__) &&  (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 5)))
#define JSONCPP_DEPRECATED(message)  __attribute__ ((deprecated(message)))
#elif defined(__GNUC__) &&  (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 1))
#define JSONCPP_DEPRECATED(message)  __attribute__((__deprecated__))
#endif
```
The ```#elif``` should not be replaced by an independent ```#if /#endif``` block, because otherwise the second (less convenient) definition will override the improved one which supports the provided message.

**Comment by cdunn2001** [comment]
I agree. Submit a PR. And let's see if anyone objects.

**Comment by Dani-Hub** [comment]
I have created a patch file, How can I upload it?

**Comment by cdunn2001** [comment]
Best is to:

1. Fork the repo in GitHub.
2. `git clone` on your machine.
3. `git apply` to apply your patch.
4. `git push` into your fork.
1. Click on "Create Pull Request" in GitHub.

But if you can't, then mayb paste your patchfile into a "Gist" in GitHub.

**Comment by Dani-Hub** [comment]
Thanks, I will do so (presumably tomorrow)

**Comment by cdunn2001** [comment]
Next, I'll add this macro to the deprecated method, unless you'd rather do that yourself.

**Comment by Dani-Hub** [comment]
Please go ahead. I wasn't aware of additional deprecated functions.
