### ISSUE TITLE
Json::Exception broken

### ISSUE THREAD

**Issue by Dani-Hub** [open-source-parsers/jsoncpp#216]
The new exception class ```Json::Exception``` contains a data member of __reference type__. That means the initializing object is required to have a longer life-time than the exception class. But this does not happen: The class is always constructed by *temporaries*, so there are nasal daemons all around! 

I do not understand the reason to why a member reference has been chosen, but that is clearly wrong here. I suggest to replace the reference member by a normal non-reference member of type ```std::string``` that copies the provided argument.

That being said: Why does the public header value.h declare the internal exception types and the corresponding factory functions? It would seem better (regarding implementation encapsulation) to move these declarations instead into an internal header (part of src, not part of include).

**Comment by Dani-Hub** [comment]
A patch for the most serious problem (The reference member) has been pushed as fix candidate.

**Comment by cdunn2001** [comment]
Ugh! On Linux, I would run valgrind always. On the Mac, I have to be perfect, which I am not. I need to find a practical memory-checker.

Anyway, I pulled that commit. We still want `const`, but good catch on the reference. Don't know what I was thinking. Late night commit? Code-reviews wouldn't hurt.

I don't have time right now to look at the other issues. But maybe you can research when `<cmath>` became available in *gcc*. At the moment, legacy users can still get bug-fixes from the `0.*.*` branch.
