### ISSUE TITLE
Error: snprintf is not a member of std

### ISSUE THREAD

**Issue by zammbi** [open-source-parsers/jsoncpp#224]
I'm getting the error "snprintf is not a member of std" in jsoncpp.cpp, line 3969. I fixed this by removing the "std::". I was using the latest Android NDK. 

It might be part of this bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61101

**Comment by rpavlik** [comment]
Drive by portability comment: for reference, I think visual studio 2005 doesn't have snprintf at all

**Comment by zammbi** [comment]
> for reference, I think visual studio 2005 doesn't have snprintf at all
The code would use "_snprintf" on visual studio.

```
#if defined(_MSC_VER) && _MSC_VER < 1500 // VC++ 8.0 and below
#define snprintf _snprintf
```

**Comment by cdunn2001** [comment]
Your bugzilla link says the problem for that user was a spurious environment variable. Not related, I think.

Yes, `snprintf` is standard as of C++11. It happens to be available in non-standard ways in previous versions for many compilers. I think the right answer is to use std::snprintf only in the 1.*.* branch, which officially is intended only for C++11. If we can make it work for earlier versions of C++ too, even better, maybe using `#if __cplusplus >= 201103L`.

Looking at 1c58876185d2a4ed87dac4a54b82f607e74f55fd and #218, I am not happy about the increasing complexity of our snprintf handling. There are exceptions for WINCE and STDC_SECURE, and they are not clearly consistent between files. Let's try to correct this in a better way. I'll look into this more later in the week. For now, #232 should solve your problem. (I included the @baruchsiach commit from #231.)

**Comment by oumaymakabiri** [comment]
I'm getting the error: ‘vsnprintf’ is not a member of ‘std’; did you mean ‘vswprintf’?
I didn't quite understand the problem, but I think it's related to the compiler. if anyone can help me solve it please.

**Comment by BillyDonahue** [comment]
This was solved 8 years ago, wasn't it?
std::vsnprintf is part of C++11, which we require.
