### ISSUE TITLE
Reclaim Memory back after parsing large JSON ?

### ISSUE THREAD

**Issue by armadillu** [open-source-parsers/jsoncpp#229]
Hi, I am working on a project that has to load very large JSON files (100+mb) over and over, and I see my RAM usage keeps growing. Is this normal?

I am doing:

```
void loadJson(string path){
	Json::Value root;
	Json::Reader reader;
	std::ifstream test(path, std::ifstream::binary);
	bool parsingSuccessful = reader.parse( test, root, false);
	if ( !parsingSuccessful ){
		std::cout  << "failed to parse" << endl;
	}else{
		std::cout << "ok" << endl;
	}
}
```

And the app uses 13mb of memory before loadJson() is called, and 190mb after. 
Memory climbs up to 500mb while parsing, and drops to 190 when finished, but never goes back to 13mb. 

Am I doing something wrong? Or this is just due memory fragmentation?

I am on today's master branch, on OSX 10.9.
I can supply the JSON file I am loading if needed.

**Comment by cdunn2001** [comment]
It could be fragmentation, or just memory still owned by your memory manager. (A typical `malloc()` will store small deallocated chunks as linked freelists.) On Linux you could try `mallinfo` (as well as `valgrind` to look for leaks). On OSX, you could try swapping in a different memory manager for analysis.

**Comment by Dynasty9** [comment]
I don't see why this is closed due to the solution not being found. We are seeing the same results on Centos 6.5. Free lists should not take up 190mb. We are narrowing down the memory allocations and will get back to you with the results.

**Comment by Dynasty9** [comment]
Turns out std::map allocator is the problem and will return the memory to the operating system on it's own accord to prevent linked freelists. We are attempting to std::vector via the internal_maps flag to see if that clears up our issues.

**Comment by binopolackal** [comment]
Hi,
Wanted to know if this issue was fixed? Or are you still seeing the memory leak. I am also observing some similar issue?

**Comment by binopolackal** [comment]
Update: I was seeing memory leak during the reader.parse in jsoncpp 1.7.2 , but with 1.8.0 version i am not observing that. Looks like 1.8.0 has fixed the issue. Thanks.
