### ISSUE TITLE
dpkg package for jsoncpp

### ISSUE THREAD

**Issue by anirudhSK** [open-source-parsers/jsoncpp#236]
Is there a ppa that hosts a recent version of jsoncpp? I am on Ubuntu 14.10, and the version available through apt-get is 0.6.0~rc2. https://launchpad.net/~fancycode/+archive/ubuntu/jsoncpp also lists the same version.

I am interested in using jsoncpp for a project and would prefer to install it as a library rather than including the code with the project. If I can help create a PPA archive, I would be happy to do that as well.

**Comment by cdunn2001** [comment]
We are used on too many platform to distribute built libraries for each one. But if you set one up for us, that would be much appreciated. :-)

Now is a good time for it, as the code seems stable and bug-fixes have petered out. Actually, 2 PPAs could be helpful: `0.10.1` (which is *binary-compatible* with `0.6.0-rc2`) and `1.6.1` (which requires C++11). Or whichever you think is most helpful today. Thanks!

**Comment by cinemast** [comment]
Hi!

The package has been unmaintained the last years in debian (and therefore in ubuntu). We fixed that now and the 0.x.y branch should be always up2date.

Check here:

https://packages.debian.org/stretch/libjsoncpp-dev
http://packages.ubuntu.com/wily/libjsoncpp-dev

**Comment by cdunn2001** [comment]
Thanks for the links. Interesting.

Your latest submission (the ARM fix, plus some back-ported code) is in 0.10.2-p1. I could rename that to 0.10.3 if that's more convenient. It would certainly be easier to sign.

**Comment by cinemast** [comment]
No that's not required. The patch is already in, therefore I won't package 0.10.2-p1.

**Comment by cdunn2001** [comment]
Copied links into wiki. Thanks again!
