### ISSUE TITLE
jsoncpp discards everything after zero character ('\0')

### ISSUE THREAD

**Issue by vdudouyt** [open-source-parsers/jsoncpp#240]
Hi!

Here I'm trying to build a system that relies on storing some of it's internal structures in JSON format. Some of fields may contain the binary data, and I mentioned that everything after '\0' is getting discarded - just as in old good "plain C" strings:

```c++
int main()
{
   Json::FastWriter writer;
   Json::Value root;
   root["some_binary_value"] = std::string("\1\2\0\3\4", 5);
   std::cout << writer.write(root);
}
```

```nohighlight
$ ./json_test
{"some_binary_value":"\u0001\u0002"}
```

Could you please let me know if that's something that you'd like to be fixed? 
Thank you very much for your time, and sorry for bothering you with a such sort of things!

Valentin

**Comment by cdunn2001** [comment]
The new `StreamWriter` has the fix already:
```
#include <json/json.h>
#include <iostream>
#include <memory>

int main()
{
  std::unique_ptr<Json::StreamWriter> const writer(
    Json::StreamWriterBuilder().newStreamWriter());
  Json::Value root;
  root["some_binary_value"] = std::string("\1\2\0\3\4", 5);
  writer->write(root, &std::cout);
}
```
```
{
	"some_binary_value" : "\u0001\u0002\u0000\u0003\u0004"
}
```
More conveniently, use `writeString()`.

However, you're right: It does not work for some of the old (deprecated) Writers. That's easy to fix, and I guess it's not likely to break anyone.
