### ISSUE TITLE
Cross-compile using CMake

### ISSUE THREAD

**Issue by brnluiz** [open-source-parsers/jsoncpp#243]
Hi,

I am trying to cross-compile from my amd64 computer to an armhf BeagleBone. With other libraries I simply pass some arguments to ./configure and it prepare necessary Makefile. Then I compile and save it at /usr/arm-linux-gnueabihf.

How I do that for libjsoncpp?

**Comment by cdunn2001** [comment]
This is really a **cmake** question. [Here is a link](http://www.vtk.org/Wiki/CMake_Cross_Compiling) that might help.

FWIW, I suggest considering a new language called **nim** (aka nimlang, formerly nimrod).
* [Tutorial](http://nim-lang.org/tut1.html)
* [cross-compilation](http://nim-lang.org/nimc.html#cross-compilation)
* [importc/exportc](http://nim-lang.org/manual.html#importc-pragma)
* [c2nim](http://nim-lang.org/c2nim.html)
* [docs](http://nim-lang.org/documentation.html)

**Comment by brnluiz** [comment]
I solved it using this toolchain file: http://sourceforge.net/p/crengine/crengine/ci/master/tree/tools/toolchain-arm-linux-gnueabi.cmake

```
# CMake toolchain file for building ARM software on OI environment

# this one is important
SET(CMAKE_SYSTEM_NAME Linux)
#this one not so much
SET(CMAKE_SYSTEM_VERSION 1)

# specify the cross compiler
SET(CMAKE_C_COMPILER   /usr/bin/arm-linux-gnueabihf-gcc)
SET(CMAKE_CXX_COMPILER /usr/bin/arm-linux-gnueabihf-g++)
SET(CMAKE_STRIP /usr/bin/arm-linux-gnueabihf-strip)

# where is the target environment 
SET(CMAKE_FIND_ROOT_PATH  /usr/arm-linux-gnueabihf)

# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

I am using an Ubuntu 14.04 and did the same thing of README.md guide, but with some modifications:

```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=None -DJSONCPP_LIB_BUILD_STATIC=ON -DJSONCPP_LIB_BUILD_SHARED=ON -DCMAKE_INSTALL_PREFIX=/usr/arm-linux-gnueabihf -DCMAKE_TOOLCHAIN_FILE=~/Toolchain-arm-linux-gnueabihf.cmake -G "Unix Makefiles" ..
make
sudo make install
```

**Comment by cdunn2001** [comment]
Thanks! I added this to the wiki.
