### ISSUE TITLE
Please add a CHANGELOG

### ISSUE THREAD

**Issue by cinemast** [open-source-parsers/jsoncpp#245]
Please add a CHANGELOG to future releases.

**Comment by cdunn2001** [comment]
The CHANGELOG goes into the release notes. Isn't that enough?

**Comment by cinemast** [comment]
Having the changelog also in the github release notes is nice. 
But If someone receives the package e.g. from debian or other distros, its usually nice having a changelog with the source code.

For my project I usually keep the CHANGELOG file in the repo and just copy the specific contents on every release.

**Comment by cdunn2001** [comment]
But we have 0.y.z tracking 1.y.z. And soon, I expect we'll have a 2.y.z branch. The CHANGELOG would be another file to merge.

I understand that many people like it, but it's meta-data, implied by the git history. It's similar to `$Id` or other keyword tags, which can cause huge problems for proxying RCS, CVS, Subversion, or Perforce repos, not to mention branch-merges. At Amazon, I had a gigantic Perforce commit which removed the meta-tags. Nobody was happy with that, but it helped us to use a git-perforce-proxy while the company transitioned to a full git-based solution.

As long as the version string uniquely identifies a git tag, the release history is always discoverable.

**Comment by cinemast** [comment]
Well, I still don't see the trouble. By doing proper commits (which means having changelog commits separatly), there is usually no trouble at all.

Anyway, it is your project. If you don't want to have CHANGELOGS in source, just close the issue :)
