### ISSUE TITLE
Successful Compile with Visual Studio 2012

### ISSUE THREAD

**Issue by jthompsonic** [open-source-parsers/jsoncpp#246]
You can add Visual Studio 2012 to your list of supported Platforms. The one suggestion the compiler gave was to turn on the feature: Project Property --> Configuration Properties --> General --> Project Defaults --> Whole Program Optimization --> Use Link Time Code Generation (LTCG)

**Comment by cdunn2001** [comment]
Wonderful! We actually have Appveyor running CI tests now, but only for VS 2013.
