### ISSUE TITLE
parse string error

### ISSUE THREAD

**Issue by gzliudan** [open-source-parsers/jsoncpp#251]
Json::Reader reader;
Json::Value root;

if (reader.parse("9999",root))
{
    ShowMessage("parse error");
}

**Comment by cdunn2001** [comment]
That method returns `true` on success.

* http://open-source-parsers.github.io/jsoncpp-docs/doxygen/namespace_json.html

**Comment by gzliudan** [comment]
but "9999" is invalid json object, parse result should return false

**Comment by cdunn2001** [comment]
It's a valid JSON *value*. See [the JSON state machine](http://www.json.org/).

To get an error non-objects, you can use a [`CharReaderBuilder`](http://open-source-parsers.github.io/jsoncpp-docs/doxygen/class_json_1_1_char_reader_builder.html#ac69b7911ad64c171c51ebaf2ea26d958) with `"strictRoot"` set to `true`. `setStrictMode()` will do that for you. Or use `strictMode` on the deprecated `JsonFeatures`.
