### ISSUE TITLE
Can you make jsoncpp support C++ Builder by default?

### ISSUE THREAD

**Issue by gzliudan** [open-source-parsers/jsoncpp#269]
According to Victor Chen's blog(http://www.cppfans.com/sdk/json/jsoncpp.asp), we can use jsoncpp under C++ Builder platform after below two steps:

1) move below lines to the end of class ValueIteratorBase in the file value.h
 ```cpp
public:
ValueIteratorBase();
explicit ValueIteratorBase(const Value::ObjectValues::iterator& current);
```
2) add below lines to the file writer.cpp:
```cpp
#if defined(__BORLANDC__)  
#include <float.h>
#define isfinite _finite
#define snprintf _snprintf
#endif

```
I have tested jsoncpp under C++ Builder XE5, XE6, XE7, it works fine. Thank victor chen for his smart work.

**Comment by cdunn2001** [comment]
Of course, we're fine with this change. But note that we cannot guarantee not to break "Borland" in the future. We have CI tests for gcc, clang, and vs only.

**Comment by gzliudan** [comment]
I only tested jsoncpp on C++ Builder 32 bit platform, not 64 bit. C++ Builder 64 bit can support C++11, 32 bit can't support C++11.
