### ISSUE TITLE
Json::Exception is defined inside a .cpp file

### ISSUE THREAD

**Issue by luca3m** [open-source-parsers/jsoncpp#272]
Hi,

Why this exception: `Json::Exception`is defined inside a `.cpp` file? I have this one thrown with a bad JSON file and I would like to catch it from my code and go over. But I can't if I don't include the `.cpp`, which is not a good design.

**Comment by cdunn2001** [comment]
Exceptions are a recent addition. We don't expose more than necessary, because we cannot remove anything later without breaking compatibility. Probably we will expose `Json::Exception` eventually, so that you can see the exception message.

For now, do this:
```
try {
  ..
} catch (Json::Exception const&) {
}
```
The exception message is rarely needed because most of the information we have goes into the error string, which is always available, unless you are using the stream extractor. In fact, that extractor is the main reason why we added exceptions.

**Comment by gerhardusmuller** [comment]
Hi

I am not understanding your interrim solution.  I don't have access to the exception that is defined in the .cpp and therefor the compiler generates a forward declaration error.  In my case the exceptions are logic errors and it would really be useful not to have to use a debugger to step the code to find which exception is actually being generated.

Thanks

**Comment by cdunn2001** [comment]
For now, you can forward-declare it, right? As long as you do not actually use it, I think that will work.

We'll probably expose this soon though.

**Comment by gerhardusmuller** [comment]
Good Morning Christopher
    
    Thanks for your response.  I actually need to access the error
    string on catching the exception and therefor need access to the
    object.  I'll wait until the class is publicly defined.
    
    Thanks
    
    On 07/17/2015 01:42 PM, Christopher
      Dunn wrote:
    
    
      For now, you can forward-declare it, right? As long as you do
        not actually use it, I think that will work.
      We'll probably expose this soon though.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by cinemast** [comment]
I would also very much like to have the exception properly defined. After this is fixed. I would like to package the 1.x branch for debian.

**Comment by cdunn2001** [comment]
Tonight...

**Comment by cdunn2001** [comment]
* https://github.com/open-source-parsers/jsoncpp/releases/tag/0.10.5

**Comment by cdunn2001** [comment]
Also

* https://github.com/open-source-parsers/jsoncpp/releases/tag/1.6.5

**Comment by gerhardusmuller** [comment]
Thanks!

**Comment by cinemast** [comment]
Great. Thank you. I already started on the 1.x branch. http://anonscm.debian.org/cgit/collab-maint/libjsoncpp.git/log/?h=experimental

**Comment by cdunn2001** [comment]
Good. When it definitely works, I'll sign a release.
