### ISSUE TITLE
Provide amalgamated C++ on GitHub

### ISSUE THREAD

**Issue by keithkml** [open-source-parsers/jsoncpp#281]
I would like to use jsoncpp in my iOS app, which I develop using Xcode. I don't know what CMake is, but I downloaded it so I could build jsoncpp. However it did not go well.

- I tried using cmake-gui but it just produced a bunch of errors about Xcode command line parameters
- Then I tried your command-line build instructions, but it did not produce a .cpp file (see below)

I would really like to use your library, and I'm not sure how to do it. Please provide a .cpp and .h file so I can just drop it into my project.

```
$ mkdir -p build/debug
$ cd build/debug
Keiths-MacBook-Pro:debug keith$ cmake -DCMAKE_BUILD_TYPE=debug -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF -G "Unix Makefiles" ../..
-- The C compiler identification is Clang
-- The CXX compiler identification is Clang
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- JsonCpp Version: 1.6.2
-- Found PythonInterp: /usr/local/bin/python (found suitable version "2.7.2", required is "2.6")
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_STATIC_LIBS


-- Build files have been written to: /Users/keith/Downloads/jsoncpp-1.6.2/build/debug
$ find . | fgrep .cpp
./CMakeFiles/CompilerIdCXX/CMakeCXXCompilerId.cpp
```

**Comment by jporsay** [comment]
Have you tried following the following section of the README?
https://github.com/open-source-parsers/jsoncpp#generating-amalgamated-source-and-header

**Comment by keithkml** [comment]
I didn't see that because it's buried in pages and pages of documentation that is not relevant to me.

I've made some changes to the README and created a pull request. I think this will help quite a bit with new users like myself.

https://github.com/open-source-parsers/jsoncpp/pull/282

**Comment by cdunn2001** [comment]
@jporsay or @keithkml, if you want, modify `dev.makefile` to copy amalgamated .h/.cpp into the jsoncpp-docs directory. Then we could release amalgamated code with the documentation. If you think that would help anyone. I don't have time right now.
