### ISSUE TITLE
Non-C++ 11 branch is using C++ 11 detection

### ISSUE THREAD

**Issue by holiveros** [open-source-parsers/jsoncpp#286]
Trying to use jsoncpp 1.6.2 on Cygwin, using g++ 4.9.2 with C++ 11 features enabled; compilation fails on:
/jsoncpp-1.6.2/dist/jsoncpp.cpp:3969:18: error: ‘snprintf’ is not a member of ‘std’

Switching to non-C++ 11 jsoncpp branch, 0.10.2, yields a similar error:
/jsoncpp-0.10.2/dist/jsoncpp.cpp:3790:18: error: ‘snprintf’ is not a member of ‘std’

Turns out Cygwin has a bug where std::snprintf is not included when using C++ 11 features.

Checking amalgamated jsoncpp.cpp, turns out it still has C++ 11 detection, which it shouldn't have:
line 3787:
# if defined(_MSC_VER) && _MSC_VER < 1500 // VC++ 8.0 and below
# define snprintf _snprintf
# elif __cplusplus >= 201103L
# define snprintf std::snprintf
# endif

What applies in this case besides removing the std:: from that define?
Compiling a C++ 11 project, using jsoncpp in non-C++ 11 in non-lib mode.

**Comment by cdunn2001** [comment]
See #224 and its links. For even more fun, see #283 etc. Floating-point conversion with a variety of old compilers has been difficult. If you know the right macro to use, please let us know, but read those links to avoid breaking others.

Maybe you can simply use this: `-std=c++11`. With that, `snprintf` *should* be in `std::`. It's not?
* http://gcc.gnu.org/projects/cxx0x.html
* https://gcc.gnu.org/wiki/C11Status

**Comment by cdunn2001** [comment]
The latest tip of *master* (e22a2f36f7e8e9ec7598d1b58c1c7992b1b5b02e) uses `-std=c++11` instead of `-std=c++0x`. (We overcame a problem in Travis CI.) Let's see if that solves your problem. (See #313.)

**Comment by hjmjohnson** [comment]
All master branch is now C++11.  Closing as out of date.
