### ISSUE TITLE
doxybuild.py fails if there is a space in the path to the Doxygen executable

### ISSUE THREAD

**Issue by tylerknott** [open-source-parsers/jsoncpp#287]
On Windows the default Doxygen installer installs it under "C:\Program Files\doxygen\bin\doxygen.exe"  If this path is passed to doxybuild.py it will fail with the following error message:

```'c:\Program' is not recognized as an internal or external command, operable program or batch file.```

Replacing the `os.system(' '.join(cmd))` call in `run_cmd(cmd)` with `subprocess.call(cmd)` fixes the issue.

**Comment by cdunn2001** [comment]
Thanks.
