### ISSUE TITLE
crash by Initialization jsondata

### ISSUE THREAD

**Issue by freshbird** [open-source-parsers/jsoncpp#289]
jsondata:
<link rel='stylesheet' type='text/css' href='http://tools.oschina.net/js/syntaxhighlighter_3.0.83/styles/shCoreEmacs.css'/><div id="highlighter_204769" class="syntaxhighlighter  js"><div class="toolbar"><span><a href="#" class="toolbar_item command_help help">?</a></span></div><table border="0" cellpadding="0" cellspacing="0"><tbody><tr><td class="gutter"><div class="line number1 index0 alt2">1</div><div class="line number2 index1 alt1">2</div><div class="line number3 index2 alt2">3</div><div class="line number4 index3 alt1">4</div><div class="line number5 index4 alt2">5</div><div class="line number6 index5 alt1">6</div><div class="line number7 index6 alt2">7</div><div class="line number8 index7 alt1">8</div><div class="line number9 index8 alt2">9</div><div class="line number10 index9 alt1">10</div><div class="line number11 index10 alt2">11</div><div class="line number12 index11 alt1">12</div><div class="line number13 index12 alt2">13</div><div class="line number14 index13 alt1">14</div></td><td class="code"><div class="container"><div class="line number1 index0 alt2"><code class="js plain">{</code></div><div class="line number2 index1 alt1"><code class="js spaces">&nbsp;&nbsp;&nbsp;</code><code class="js string">"DLL64MD5"</code>&nbsp;<code class="js plain">:&nbsp;</code><code class="js string">"50b0d0dbc81b99124dd2e2c1d90cc865"</code><code class="js plain">,</code></div><div class="line number3 index2 alt2"><code class="js spaces">&nbsp;&nbsp;&nbsp;</code><code class="js string">"DLLMD5"</code>&nbsp;<code class="js plain">:&nbsp;</code><code class="js string">"ef842a947c6924646e7dbe29853ccc00"</code><code class="js plain">,</code></div><div class="line number4 index3 alt1"><code class="js spaces">&nbsp;&nbsp;&nbsp;</code><code class="js string">"Driver64MD5"</code>&nbsp;<code class="js plain">:&nbsp;</code><code class="js string">"378cecd9f9a24fa49048bc7e0183d7b5"</code><code class="js plain">,</code></div><div class="line number5 index4 alt2"><code class="js spaces">&nbsp;&nbsp;&nbsp;</code><code class="js string">"HandshakeLoopTime"</code>&nbsp;<code class="js plain">:&nbsp;30000,</code></div><div class="line number6 index5 alt1"><code class="js spaces">&nbsp;&nbsp;&nbsp;</code><code class="js string">"PopMD5"</code>&nbsp;<code class="js plain">:&nbsp;</code><code class="js string">"2ebdcfdc41704b3e01126a0bbba703df"</code><code class="js plain">,</code></div><div class="line number7 index6 alt2"><code class="js spaces">&nbsp;&nbsp;&nbsp;</code><code class="js string">"PopPraveMD5"</code>&nbsp;<code class="js plain">:&nbsp;</code><code class="js keyword">null</code><code class="js plain">,</code></div><div class="line number8 index7 alt1"><code class="js spaces">&nbsp;&nbsp;&nbsp;</code><code class="js string">"PraveDLL64MD5"</code>&nbsp;<code class="js plain">:&nbsp;</code><code class="js keyword">null</code><code class="js plain">,</code></div><div class="line number9 index8 alt2"><code class="js spaces">&nbsp;&nbsp;&nbsp;</code><code class="js string">"PraveDLLMD5"</code>&nbsp;<code class="js plain">:&nbsp;</code><code class="js keyword">null</code><code class="js plain">,</code></div><div class="line number10 index9 alt1"><code class="js spaces">&nbsp;&nbsp;&nbsp;</code><code class="js string">"PraveDriver64MD5"</code>&nbsp;<code class="js plain">:&nbsp;</code><code class="js keyword">null</code><code class="js plain">,</code></div><div class="line number11 index10 alt2"><code class="js spaces">&nbsp;&nbsp;&nbsp;</code><code class="js string">"PraveDriverMD5"</code>&nbsp;<code class="js plain">:&nbsp;</code><code class="js keyword">null</code><code class="js plain">,</code></div><div class="line number12 index11 alt1"><code class="js spaces">&nbsp;&nbsp;&nbsp;</code><code class="js string">"ServerMD5"</code>&nbsp;<code class="js plain">:&nbsp;</code><code class="js string">"37ec9a2c1698de96d754f71ce1b02a72"</code><code class="js plain">,</code></div><div class="line number13 index12 alt2"><code class="js spaces">&nbsp;&nbsp;&nbsp;</code><code class="js string">"BrowserProcessMatch"</code>&nbsp;<code class="js plain">:&nbsp;</code><code class="js string">"*browser*|QQBrowser.exe|chrome.exe|iexplore.exe|firefox.exe|360se.exe|sogouexplorer.exe|*opera*|TaoBrowser.exe|liebao.exe"</code></div><div class="line number14 index13 alt1"><code class="js plain">}</code></div></div></td></tr></tbody></table></div>

Initialization code:

<link rel='stylesheet' type='text/css' href='http://tools.oschina.net/js/syntaxhighlighter_3.0.83/styles/shCoreFadeToGrey.css'/><div id="highlighter_967623" class="syntaxhighlighter  c"><div class="toolbar"><span><a href="#" class="toolbar_item command_help help">?</a></span></div><table border="0" cellpadding="0" cellspacing="0"><tbody><tr><td class="gutter"><div class="line number1 index0 alt2">1</div><div class="line number2 index1 alt1">2</div><div class="line number3 index2 alt2">3</div></td><td class="code"><div class="container"><div class="line number1 index0 alt2"><code class="c plain">Json::Value&nbsp;m_Status;</code></div><div class="line number2 index1 alt1"><code class="c plain">Json::Reader&nbsp;r;</code></div><div class="line number3 index2 alt2"><code class="c plain">r.parse(jsondata,m_Status);</code></div></div></td></tr></tbody></table></div>

then crash at json_value.cpp line 405.

I think the current version of jsoncpp caused the crash,When I switched to a previous version(I don't know which one), I had a good run.the fine version json_value.cpp code is begin like this:
<link rel='stylesheet' type='text/css' href='http://tools.oschina.net/js/syntaxhighlighter_3.0.83/styles/shCoreEmacs.css'/><div id="highlighter_269398" class="syntaxhighlighter  c"><div class="toolbar"><span><a href="#" class="toolbar_item command_help help">?</a></span></div><table border="0" cellpadding="0" cellspacing="0"><tbody><tr><td class="gutter"><div class="line number1 index0 alt2">1</div><div class="line number2 index1 alt1">2</div><div class="line number3 index2 alt2">3</div><div class="line number4 index3 alt1">4</div><div class="line number5 index4 alt2">5</div><div class="line number6 index5 alt1">6</div><div class="line number7 index6 alt2">7</div><div class="line number8 index7 alt1">8</div><div class="line number9 index8 alt2">9</div><div class="line number10 index9 alt1">10</div><div class="line number11 index10 alt2">11</div><div class="line number12 index11 alt1">12</div><div class="line number13 index12 alt2">13</div><div class="line number14 index13 alt1">14</div><div class="line number15 index14 alt2">15</div><div class="line number16 index15 alt1">16</div><div class="line number17 index16 alt2">17</div><div class="line number18 index17 alt1">18</div></td><td class="code"><div class="container"><div class="line number1 index0 alt2"><code class="c preprocessor">#include&nbsp;&lt;iostream&gt;</code></div><div class="line number2 index1 alt1"><code class="c preprocessor">#include&nbsp;&lt;json/value.h&gt;</code></div><div class="line number3 index2 alt2"><code class="c preprocessor">#include&nbsp;&lt;json/writer.h&gt;</code></div><div class="line number4 index3 alt1"><code class="c preprocessor">#include&nbsp;&lt;utility&gt;</code></div><div class="line number5 index4 alt2"><code class="c preprocessor">#include&nbsp;&lt;stdexcept&gt;</code></div><div class="line number6 index5 alt1"><code class="c preprocessor">#include&nbsp;&lt;cstring&gt;</code></div><div class="line number7 index6 alt2"><code class="c preprocessor">#include&nbsp;&lt;cassert&gt;</code></div><div class="line number8 index7 alt1"><code class="c preprocessor">#ifdef&nbsp;JSON_USE_CPPTL</code></div><div class="line number9 index8 alt2"><code class="c preprocessor">#&nbsp;include&nbsp;&lt;cpptl/conststring.h&gt;</code></div><div class="line number10 index9 alt1"><code class="c preprocessor">#endif</code></div><div class="line number11 index10 alt2"><code class="c preprocessor">#include&nbsp;&lt;cstddef&gt;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;size_t</code></div><div class="line number12 index11 alt1"><code class="c preprocessor">#ifndef&nbsp;JSON_USE_SIMPLE_INTERNAL_ALLOCATOR</code></div><div class="line number13 index12 alt2"><code class="c preprocessor">#&nbsp;include&nbsp;"json_batchallocator.h"</code></div><div class="line number14 index13 alt1"><code class="c preprocessor">#endif&nbsp;//&nbsp;#ifndef&nbsp;JSON_USE_SIMPLE_INTERNAL_ALLOCATOR</code></div><div class="line number15 index14 alt2">&nbsp;</div><div class="line number16 index15 alt1"><code class="c preprocessor">#define&nbsp;JSON_ASSERT_UNREACHABLE&nbsp;assert(&nbsp;false&nbsp;)</code></div><div class="line number17 index16 alt2"><code class="c preprocessor">#define&nbsp;JSON_ASSERT(&nbsp;condition&nbsp;)&nbsp;assert(&nbsp;condition&nbsp;);&nbsp;&nbsp;//&nbsp;@todo&nbsp;&lt;=&nbsp;change&nbsp;this&nbsp;into&nbsp;an&nbsp;exception&nbsp;throw</code></div><div class="line number18 index17 alt1"><code class="c preprocessor">#define&nbsp;JSON_ASSERT_MESSAGE(&nbsp;condition,&nbsp;message&nbsp;)&nbsp;if&nbsp;(!(&nbsp;condition&nbsp;))&nbsp;throw&nbsp;std::runtime_error(&nbsp;message&nbsp;);</code></div></div></td></tr></tbody></table></div>

I don't know why it would crash, maybe it's my code, and maybe it's the current version of jsoncpp.. Can you help me solve this problem? Otherwise I'll just switch to the old version..

**Comment by freshbird** [comment]
I'm sorry my English is not good.

**Comment by freshbird** [comment]
fixed! its my code problem.

**Comment by cdunn2001** [comment]
If you think it would teach the rest of us something, please post. Everybody makes mistakes.

**Comment by freshbird** [comment]
I dont know why it crash,but I know how,If your code like this(win):
<link rel='stylesheet' type='text/css' href='http://tools.oschina.net/js/syntaxhighlighter_3.0.83/styles/shCoreDefault.css'/><div id="highlighter_600371" class="syntaxhighlighter  c"><div class="toolbar"><span><a href="#" class="toolbar_item command_help help">?</a></span></div><table border="0" cellpadding="0" cellspacing="0"><tbody><tr><td class="gutter"><div class="line number1 index0 alt2">1</div><div class="line number2 index1 alt1">2</div><div class="line number3 index2 alt2">3</div><div class="line number4 index3 alt1">4</div><div class="line number5 index4 alt2">5</div><div class="line number6 index5 alt1">6</div><div class="line number7 index6 alt2">7</div><div class="line number8 index7 alt1">8</div><div class="line number9 index8 alt2">9</div><div class="line number10 index9 alt1">10</div><div class="line number11 index10 alt2">11</div><div class="line number12 index11 alt1">12</div><div class="line number13 index12 alt2">13</div><div class="line number14 index13 alt1">14</div><div class="line number15 index14 alt2">15</div><div class="line number16 index15 alt1">16</div><div class="line number17 index16 alt2">17</div><div class="line number18 index17 alt1">18</div><div class="line number19 index18 alt2">19</div><div class="line number20 index19 alt1">20</div><div class="line number21 index20 alt2">21</div><div class="line number22 index21 alt1">22</div><div class="line number23 index22 alt2">23</div><div class="line number24 index23 alt1">24</div><div class="line number25 index24 alt2">25</div><div class="line number26 index25 alt1">26</div><div class="line number27 index26 alt2">27</div><div class="line number28 index27 alt1">28</div><div class="line number29 index28 alt2">29</div><div class="line number30 index29 alt1">30</div><div class="line number31 index30 alt2">31</div><div class="line number32 index31 alt1">32</div><div class="line number33 index32 alt2">33</div><div class="line number34 index33 alt1">34</div><div class="line number35 index34 alt2">35</div><div class="line number36 index35 alt1">36</div><div class="line number37 index36 alt2">37</div><div class="line number38 index37 alt1">38</div><div class="line number39 index38 alt2">39</div><div class="line number40 index39 alt1">40</div><div class="line number41 index40 alt2">41</div><div class="line number42 index41 alt1">42</div></td><td class="code"><div class="container"><div class="line number1 index0 alt2"><code class="c preprocessor">#include&nbsp;"stdafx.h"</code></div><div class="line number2 index1 alt1">&nbsp;</div><div class="line number3 index2 alt2"><code class="c keyword bold">using</code>&nbsp;<code class="c keyword bold">namespace</code>&nbsp;<code class="c plain">std;</code></div><div class="line number4 index3 alt1"><code class="c plain">string&nbsp;GetFileText(</code><code class="c keyword bold">const</code>&nbsp;<code class="c color1 bold">char</code>&nbsp;<code class="c plain">*&nbsp;file)</code></div><div class="line number5 index4 alt2"><code class="c plain">{</code></div><div class="line number6 index5 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c color1 bold">FILE</code><code class="c plain">*&nbsp;f;</code></div><div class="line number7 index6 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c keyword bold">if</code><code class="c plain">(0&nbsp;==&nbsp;fopen_s(&amp;f,file,</code><code class="c string">"r"</code><code class="c plain">))</code></div><div class="line number8 index7 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">{</code></div><div class="line number9 index8 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c keyword bold">if</code><code class="c plain">(!</code><code class="c functions bold">feof</code><code class="c plain">(f))</code></div><div class="line number10 index9 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">{</code></div><div class="line number11 index10 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c color1 bold">char</code>&nbsp;<code class="c plain">c;</code></div><div class="line number12 index11 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">string&nbsp;req;</code></div><div class="line number13 index12 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c keyword bold">do</code></div><div class="line number14 index13 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">{</code></div><div class="line number15 index14 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">fread_s(&amp;c,1,</code><code class="c keyword bold">sizeof</code><code class="c plain">(</code><code class="c color1 bold">char</code><code class="c plain">),1,f);</code></div><div class="line number16 index15 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">req&nbsp;+=&nbsp;c;</code></div><div class="line number17 index16 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">}</code><code class="c keyword bold">while</code><code class="c plain">(!</code><code class="c functions bold">feof</code><code class="c plain">(f));</code></div><div class="line number18 index17 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c functions bold">fclose</code><code class="c plain">(f);</code></div><div class="line number19 index18 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c keyword bold">return</code>&nbsp;<code class="c plain">req;</code></div><div class="line number20 index19 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">}</code></div><div class="line number21 index20 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c functions bold">fclose</code><code class="c plain">(f);</code></div><div class="line number22 index21 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">}</code></div><div class="line number23 index22 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c keyword bold">return</code>&nbsp;<code class="c string">""</code><code class="c plain">;</code></div><div class="line number24 index23 alt1"><code class="c plain">}</code></div><div class="line number25 index24 alt2">&nbsp;</div><div class="line number26 index25 alt1"><code class="c keyword bold">class</code>&nbsp;<code class="c plain">A</code></div><div class="line number27 index26 alt2"><code class="c plain">{</code></div><div class="line number28 index27 alt1"><code class="c keyword bold">private</code><code class="c plain">:</code></div><div class="line number29 index28 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">Json::Value&nbsp;data;</code></div><div class="line number30 index29 alt1"><code class="c keyword bold">public</code><code class="c plain">:</code></div><div class="line number31 index30 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">A()</code></div><div class="line number32 index31 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">{</code></div><div class="line number33 index32 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">Json::Reader&nbsp;reader;</code></div><div class="line number34 index33 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">string&nbsp;text&nbsp;=&nbsp;GetFileText(</code><code class="c string">"C:/somejsondata.txt"</code><code class="c plain">);</code></div><div class="line number35 index34 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">reader.parse(text,data);</code></div><div class="line number36 index35 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">}</code></div><div class="line number37 index36 alt2"><code class="c plain">};</code></div><div class="line number38 index37 alt1"><code class="c plain">A&nbsp;a;</code></div><div class="line number39 index38 alt2"><code class="c color1 bold">int</code>&nbsp;<code class="c plain">_tmain(</code><code class="c color1 bold">int</code>&nbsp;<code class="c plain">argc,&nbsp;_TCHAR*&nbsp;argv[])</code></div><div class="line number40 index39 alt1"><code class="c plain">{</code></div><div class="line number41 index40 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c keyword bold">return</code>&nbsp;<code class="c plain">0;</code></div><div class="line number42 index41 alt1"><code class="c plain">}</code></div></div></td></tr></tbody></table></div>
you will get my crash,I think maybe it caused by a certain sequence of initialization.
the solution is run the Json::Reader code after main() called like this:
<link rel='stylesheet' type='text/css' href='http://tools.oschina.net/js/syntaxhighlighter_3.0.83/styles/shCoreDefault.css'/><div id="highlighter_68302" class="syntaxhighlighter  c"><div class="toolbar"><span><a href="#" class="toolbar_item command_help help">?</a></span></div><table border="0" cellpadding="0" cellspacing="0"><tbody><tr><td class="gutter"><div class="line number1 index0 alt2">1</div><div class="line number2 index1 alt1">2</div><div class="line number3 index2 alt2">3</div><div class="line number4 index3 alt1">4</div><div class="line number5 index4 alt2">5</div><div class="line number6 index5 alt1">6</div><div class="line number7 index6 alt2">7</div><div class="line number8 index7 alt1">8</div><div class="line number9 index8 alt2">9</div><div class="line number10 index9 alt1">10</div><div class="line number11 index10 alt2">11</div><div class="line number12 index11 alt1">12</div><div class="line number13 index12 alt2">13</div><div class="line number14 index13 alt1">14</div><div class="line number15 index14 alt2">15</div><div class="line number16 index15 alt1">16</div><div class="line number17 index16 alt2">17</div><div class="line number18 index17 alt1">18</div><div class="line number19 index18 alt2">19</div><div class="line number20 index19 alt1">20</div><div class="line number21 index20 alt2">21</div><div class="line number22 index21 alt1">22</div><div class="line number23 index22 alt2">23</div><div class="line number24 index23 alt1">24</div><div class="line number25 index24 alt2">25</div><div class="line number26 index25 alt1">26</div><div class="line number27 index26 alt2">27</div><div class="line number28 index27 alt1">28</div><div class="line number29 index28 alt2">29</div><div class="line number30 index29 alt1">30</div><div class="line number31 index30 alt2">31</div><div class="line number32 index31 alt1">32</div><div class="line number33 index32 alt2">33</div><div class="line number34 index33 alt1">34</div><div class="line number35 index34 alt2">35</div><div class="line number36 index35 alt1">36</div><div class="line number37 index36 alt2">37</div><div class="line number38 index37 alt1">38</div><div class="line number39 index38 alt2">39</div><div class="line number40 index39 alt1">40</div><div class="line number41 index40 alt2">41</div><div class="line number42 index41 alt1">42</div><div class="line number43 index42 alt2">43</div></td><td class="code"><div class="container"><div class="line number1 index0 alt2"><code class="c preprocessor">#include&nbsp;"stdafx.h"</code></div><div class="line number2 index1 alt1">&nbsp;</div><div class="line number3 index2 alt2"><code class="c keyword bold">using</code>&nbsp;<code class="c keyword bold">namespace</code>&nbsp;<code class="c plain">std;</code></div><div class="line number4 index3 alt1"><code class="c plain">string&nbsp;GetFileText(</code><code class="c keyword bold">const</code>&nbsp;<code class="c color1 bold">char</code>&nbsp;<code class="c plain">*&nbsp;file)</code></div><div class="line number5 index4 alt2"><code class="c plain">{</code></div><div class="line number6 index5 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c color1 bold">FILE</code><code class="c plain">*&nbsp;f;</code></div><div class="line number7 index6 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c keyword bold">if</code><code class="c plain">(0&nbsp;==&nbsp;fopen_s(&amp;f,file,</code><code class="c string">"r"</code><code class="c plain">))</code></div><div class="line number8 index7 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">{</code></div><div class="line number9 index8 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c keyword bold">if</code><code class="c plain">(!</code><code class="c functions bold">feof</code><code class="c plain">(f))</code></div><div class="line number10 index9 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">{</code></div><div class="line number11 index10 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c color1 bold">char</code>&nbsp;<code class="c plain">c;</code></div><div class="line number12 index11 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">string&nbsp;req;</code></div><div class="line number13 index12 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c keyword bold">do</code></div><div class="line number14 index13 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">{</code></div><div class="line number15 index14 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">fread_s(&amp;c,1,</code><code class="c keyword bold">sizeof</code><code class="c plain">(</code><code class="c color1 bold">char</code><code class="c plain">),1,f);</code></div><div class="line number16 index15 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">req&nbsp;+=&nbsp;c;</code></div><div class="line number17 index16 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">}</code><code class="c keyword bold">while</code><code class="c plain">(!</code><code class="c functions bold">feof</code><code class="c plain">(f));</code></div><div class="line number18 index17 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c functions bold">fclose</code><code class="c plain">(f);</code></div><div class="line number19 index18 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c keyword bold">return</code>&nbsp;<code class="c plain">req;</code></div><div class="line number20 index19 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">}</code></div><div class="line number21 index20 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c functions bold">fclose</code><code class="c plain">(f);</code></div><div class="line number22 index21 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">}</code></div><div class="line number23 index22 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c keyword bold">return</code>&nbsp;<code class="c string">""</code><code class="c plain">;</code></div><div class="line number24 index23 alt1"><code class="c plain">}</code></div><div class="line number25 index24 alt2">&nbsp;</div><div class="line number26 index25 alt1"><code class="c keyword bold">class</code>&nbsp;<code class="c plain">A</code></div><div class="line number27 index26 alt2"><code class="c plain">{</code></div><div class="line number28 index27 alt1"><code class="c keyword bold">private</code><code class="c plain">:</code></div><div class="line number29 index28 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">Json::Value&nbsp;data;</code></div><div class="line number30 index29 alt1"><code class="c keyword bold">public</code><code class="c plain">:</code></div><div class="line number31 index30 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c color1 bold">VOID</code>&nbsp;<code class="c plain">init()</code></div><div class="line number32 index31 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">{</code></div><div class="line number33 index32 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">Json::Reader&nbsp;reader;</code></div><div class="line number34 index33 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">string&nbsp;text&nbsp;=&nbsp;GetFileText(</code><code class="c string">"C:\\Windows\\TaokeServiceSTATUS"</code><code class="c plain">);</code></div><div class="line number35 index34 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">reader.parse(text,data);</code></div><div class="line number36 index35 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">}</code></div><div class="line number37 index36 alt2"><code class="c plain">};</code></div><div class="line number38 index37 alt1"><code class="c plain">A&nbsp;a;</code></div><div class="line number39 index38 alt2"><code class="c color1 bold">int</code>&nbsp;<code class="c plain">_tmain(</code><code class="c color1 bold">int</code>&nbsp;<code class="c plain">argc,&nbsp;_TCHAR*&nbsp;argv[])</code></div><div class="line number40 index39 alt1"><code class="c plain">{</code></div><div class="line number41 index40 alt2"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c plain">a.init();</code></div><div class="line number42 index41 alt1"><code class="c spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="c keyword bold">return</code>&nbsp;<code class="c plain">0;</code></div><div class="line number43 index42 alt2"><code class="c plain">}</code></div></div></td></tr></tbody></table></div>

**Comment by cdunn2001** [comment]
Hmm. A static initialization problem. That's hard to track-down without being on your machine. Thanks for posting though.

**Comment by freshbird** [comment]
e...my OS is win7-64bit,IDE is VS2005 SP1,and create a console project with normal 32bit set.

I hope you can reproduce.
