### ISSUE TITLE
How do I know which overloaded [] operator the compiler is using?

### ISSUE THREAD

**Issue by b06stiles** [open-source-parsers/jsoncpp#317]
I recently tracked down a mysterious bug in my JSON validation code where a known good JSON expression was failing against a known good JSON schema.  It turned out that:

`std::string protocoldir = scan["protocolfilepath"].asString();`

was creating an unwanted extra node in cases where this value - legally - did not exist.  I was readily able to substitute the slightly less elegant

`std::string protocoldir = scan.get("protocolfilepath",Json::nullValue).asString();`

but I'm using constructs such as (where `key` is a string variable)

`Json::Value properties = schema["properties"][key];`

all over the rest of my code and I'm concerned that I'm going to get all sorts of wierd side effects if missing nodes are silently being created.  In the above example, if neither key in the [][] expression existed, would two new nodes appear?  How would I write this using the portly

`scan.get("protocolfilepath",Json::nullValue)`?

My implementation is nearly finished and I really don't want to do a rewrite!

In the documention there are several flavours of operator [].  For the above cases there are 

`Value & 	operator[] (const std::string &key)
 	Access an object value by name, create a null member if it does not exist.`

and 

`const Value & 	operator[] (const std::string &key) const
 	Access an object value by name, returns null if there is no member with that name.`

The latter is obviously what I want.  Do I need a cast of some kind to force the compiler to use it?  (Some non-trivial code examples would be really useful).

I'm anticipating that the former is intended to be used on the lhs of an expression as the target of an assignment, and the latter on the rhs as a 'getter' although, interestingly a naked

`scan["protocolfilepath"];`

without any assigment - still manages to create a node. How can I check for a non-existent node using

`scan["protocolfilepath"].isNull();`

without creating one? Argh!

The ultimate question may be: is my implemetation basically flawed?

Many thanks in advance.

**Comment by cdunn2001** [comment]
I'm not a fan of C++ operators. More a bug than a feature. I avoid them. I think there are other ways to do the same thing, and it might be hard to fix your problem without breaking backward compatibility. But if you have ideas, we're interested.

Note that if `scan` is `const`, then you'll have the non-mutating version for sure.

**Comment by b06stiles** [comment]
This is just what I need!  

I can't declare `scan` as `const` outright, since I have to `parse` into it.  However I can force the non-mutating version as advised using a cast, thus:

`std::string protocoldir = ((const Json::Value)scan)["protocolfilepath"].asString();`

I've checked with `scan.getMemberNames()` and with the cast no node is getting created, which suggests that the non-mutating version is getting called.

Following that, the validation code, which doesn't need to modify either the schema or the target, declares both as `const`. This should ensure that neither gets modified during validation. No re-write required!

Thanks and regards.
