### ISSUE TITLE
Sorting Array of Objects

### ISSUE THREAD

**Issue by mtangoo** [open-source-parsers/jsoncpp#318]
I have array of Objects like
```json
[
    {"name": "Stefano", "height":"10M"},
    {"name": "Abel", "height":"40M"},
    {"name": "Turkan", "height":"30M"}
]
```
I want to sort them by name so that array goes like
```json
[
    {"name": "Abel", "height":"40M"},
    {"name": "Stefano", "height":"10M"},
    {"name": "Turkan", "height":"30M"}
]
```
How can I do that? I read here [1] that JSonCpp cannot use std::sort, is that still the case?

[1] http://stackoverflow.com/questions/24706247/jsoncpp-how-to-stdsort-a-jsonvalue-that-is-an-array

**Comment by cdunn2001** [comment]
That's still the case. JSON does not specify sorting. There is also a request to preserve order, which is harder. We might support both someday, but not until v2, since it would probably break binary-compatibility.

**Comment by mtangoo** [comment]
youhave any suggestion for me (a favor)

**Comment by cdunn2001** [comment]
Well, I guess you could get the keys, sort them, then walk through the sorted container and use the keys to look up associated values.

**Comment by mtangoo** [comment]
thank you!

**Comment by BillyDonahue** [comment]
It's occurred to me a few times that begin() and end() shouldn't be direct members of Json::Value.
Json::Value is a variant type, and accessors to its different facets could be provided. Object and Array facets would have begin and end members, sure, and they'd do different things. That would be so much simpler, IMO.

if (v.is_array()) {
  Json::ArrayValue& va = v.AsArray();
  std::sort(va.begin(), va.end(), comparator);
}

I think we could just add this kind of accessor without breaking anything. Just a thought.

**Comment by cdunn2001** [comment]
:+1:
