### ISSUE TITLE
preventing reader from crashing on bad json

### ISSUE THREAD

**Issue by uriva** [open-source-parsers/jsoncpp#319]
Hi
Is there any way to prevent crashing in malformatted json?

**Comment by cdunn2001** [comment]
There are *some* requirements which can be relaxed. Configure a `CharReaderBuilder`:
* http://open-source-parsers.github.io/jsoncpp-docs/doxygen/class_json_1_1_char_reader_builder.html#ac69b7911ad64c171c51ebaf2ea26d958

**Comment by ya1gaurav** [comment]
Use Jsoncpp in strict mode.
Use exception handling at application side.

**Comment by uriva** [comment]
Unfortunately exception handling is frowned upon where I'm at so that's not an option :)

It would be useful that asString asDouble etc' would have parallels that return a status.

**Comment by uriva** [comment]
I missed the fact that there are isString, isDouble etc'
However I found myself writing something like this, which perhaps should be handled by the library.

    // Converts an HTTPServerRequest to JSON, and make sure all given required
    // parameters exist with the given type. Returns false if not.
    bool ReadRequestJSON(
        HTTPServerRequest* request,
        const vector<pair<string, Json::ValueType>>& required_params,
        Json::Value* json) const {
      auto buffer = request->input();
      char* data = buffer->Read(buffer->Length());
      Json::Reader reader;
      if (!reader.parse(data, *json)) {
        LOG(ERROR) << "Bad request: Received malformatted JSON:\n" << data;
      }
      // Check all required keys exist with correct type.
      for (const auto& param : required_params) {
        if (!json->isMember(param.first)) {
          LOG(ERROR) << "Bad request: Missing required parameter: ["
                     << param.first << "]";
          return false;
        }
        if ((*json)[param.first].type() != param.second) {
          LOG(ERROR) << "Bad request: Wrong type in parameter: [" << param.first
                     << "]";
          return false;
        }
      }
      return true;
    }

**Comment by cdunn2001** [comment]
That's useful code, but beyond the scope of jsoncpp, isn't it?

**Comment by uriva** [comment]
I'll leave this to your better judgement... :)
