### ISSUE TITLE
Where can I find jsoncpp design?

### ISSUE THREAD

**Issue by ya1gaurav** [open-source-parsers/jsoncpp#324]
Please tell me where can I found design document for jsoncpp.
Thanks.

**Comment by ya1gaurav** [comment]
Basically I am looking for jsoncpp flow digram

**Comment by cdunn2001** [comment]
The JSON spec is here:
* http://json.org/

As for a design doc, if you write one, we'd link to it.

**Comment by baylesj** [comment]
I don't think there is any work to do for this issue at this time. Feel free to reopen if we want to plan on adding more documentation.
