### ISSUE TITLE
Any chance of just having root.get("SomeObj.arrayName[1].fieldName") syntax?

### ISSUE THREAD

**Issue by jbmonroe** [open-source-parsers/jsoncpp#329]
Is the syntax I illustrated in the title possible and I just missed something in the documentation?

**Comment by cdunn2001** [comment]
Why not this:

    jsoncpp::ext::get(root, "SomeObj.arrayName[1].fieldName");

You could write that as a wrapper. We'd be happy to provide wiki links to convenient wrappers. But I'd rather not maintain that myself.

**Comment by jbmonroe** [comment]
Yeah, that's a good approach.  Right now I'm doing a walk-down from the outside, and once that works it could be used as a springboard to an extension.

**Comment by cdunn2001** [comment]
:+1:
