### ISSUE TITLE
what about saving JSON format into Mysql database

### ISSUE THREAD

**Issue by chfakht** [open-source-parsers/jsoncpp#330]
Hi ,
i want to save JSON fromat from c++ into Mysql

i'm following the first example found here 
http://www.thomaswhitton.com/blog/2013/06/28/json-c-plus-plus-examples/

a part from the code 

    mysql_init(&mysql);   
    string player = "INSERT INTO tab values (\"";
    player += jsonMessage; 
    player += "\")";  
    connection = mysql_real_connect(&mysql,HOST,USER,PASSWD,DB,0,NULL,0); 
    query_state=mysql_query(connection, player.c_str()); 

this simply doesn't work , i think because the jsonMessage contain a lot of double quotes  " "  , { } , and [ ] so how can i do this ?
the query worked if i insert a simple string like jsonMessage = "hello jsoncpp"

**Comment by cdunn2001** [comment]
Yes, I think it's the quotation marks.

**Comment by chfakht** [comment]
please is there a solution for this , or maybe i should post the problem to a MySql forum , thanks

**Comment by cdunn2001** [comment]
Yes, a mysql forum might be able to help you better.
