### ISSUE TITLE
Are there advantages of Jsoncpp over RapidJson?

### ISSUE THREAD

**Issue by ya1gaurav** [open-source-parsers/jsoncpp#357]
I have seen many links of benchmark results & rapidjson is really very fast.
I would like to know advantages of jsoncpp over rapidjson. Is there some blog/document?

**Comment by cdunn2001** [comment]
**gason** is the fastest. Depends on what you need.

Jsoncpp is for configuration files. It's highly flexible, configurable, and easy to use. It also has a niche in JavaScript compatibility. It's reasonably performant, but performance is not the priority.

**Comment by ya1gaurav** [comment]
I saw some benchmark related to string conversions - https://github.com/miloyip/dtoa-benchmark
Can such things be done in jsoncpp to improve performance? Or currently there is not much focus on performance?

**Comment by cdunn2001** [comment]
I wouldn't mind adding Milo. But first I'd like to see some profiling. If you could provide profile data for jsoncpp in some typical scenarios, that would be valuable.

**Comment by adah1972** [comment]
Milo has also written a JSON benchmarker. Maybe you want to have a look:

https://github.com/miloyip/nativejson-benchmark

**Comment by baylesj** [comment]
I don't think there's any additional work here. I'm down to reopen if we have a specific deliverable in mind.
