### ISSUE TITLE
got a error when using with cocoapods.

### ISSUE THREAD

**Issue by liaogang** [open-source-parsers/jsoncpp#359]
I can download and use it , when I add it in my Podfile.  
But got a error when I want to use jsoncpp as my dependency podspecs.(s.dependency 'jsoncpp', '~> 0.6.0.rc2')

```
xcodebuild:  Last.fm/Last.fm/Last_fm.h:26:10: fatal error: 'json/json.h' file not found
```

I'm using this to include the jsoncpp header file:

```
#include <json/json.h>
```

You can download my project 

```
     git clone https://github.com/liaogang/Last.fm.git
```

and use this to test it.

```
   pod spec lint
```

**Comment by hjmjohnson** [comment]
Not enough information to construct a response.  Please try a newer version of jsoncpp.
