### ISSUE TITLE
Seeing memory leak while using Json::Reader parse function

### ISSUE THREAD

**Issue by VIJT** [open-source-parsers/jsoncpp#360]
Hi Team,

We are using jsonlib.so by bilding/compiling jsoncpp-src-0.5.0 version.
We could see some continuos memory leak after using reader.parse in our piece of code.
Following is the sample and we could see the continous increase when using this function, 
```cpp
void leak1 ()
{
cout<<"json sleeping 1"<<endl;
sleep(5);
Json::Value jsonRoot;
Json::Reader reader;
std::ifstream file("test.json");
bool parsingSuccessful = reader.parse(file, jsonRoot);//file contains the content of our json data
Json::Value respData=jsonRoot;
cout<<"respData size is " <<respData << "   "<<endl << respData.size()<<endl;
}
```
Is there any API to free the json allocate data explicitly or is there any fix given in latest release for this issue.
Please let us know if there is any clarrification.

Thanks,
Vijayan

**Comment by BillyDonahue** [comment]
It's unclear what failure you're reporting.
What's in the "test.json" file?
Can you reproduce this without the sleep(5)?
Is the copy from jsonRoot to respData necessary to create the leak?
I think it's necessary to reduce the variables to narrow this down.

How are you measuring the memory leak?

**Comment by VIJT** [comment]
test.json is a example json data for our application.
we can even reproduce this issue without sleep, sleep is just to confirm at that point of time what is the value of heap memory, it is 0 and after parsing only the value is increased to 10MB and it is not freed.
Meanwhile we will reduce the variable and narrow down the issue.

**Comment by ya1gaurav** [comment]
is there any progress?

**Comment by cdunn2001** [comment]
0.10.* versions are binary-compatible with 0.5.0 and no leaks have been reported. In fact, 0.5.0 is the old sourceforge-vended version.

**Comment by winsvega** [comment]
# define JSONCPP_VERSION_STRING "1.8.0"

confirm, looks like having a memory leak in parse function too.

**Comment by BillyDonahue** [comment]
We need a repro for this or there's little we can do about it.
If you can confirm it, attach the code.
