### ISSUE TITLE
static library will link error when change the order of 'main.cpp' and '-ljsoncpp'

### ISSUE THREAD

**Issue by orestonce** [open-source-parsers/jsoncpp#376]
Hello, my system is fedora 20 and compiler is gcc 4.8.3 20140911 (Red Hat 4.8.3-7).
I build the library with cmake as libjsoncpp.a and write a test program:
````
#include <iostream>
#include <json/json.h>

int main()
{
   Json::Value root;

    return 0;
}
````

````
.
|-- json
|   |-- assertions.h
|   |-- autolink.h
|   |-- config.h
|   |-- features.h
|   |-- forwards.h
|   |-- json.h
|   |-- reader.h
|   |-- value.h
|   |-- version.h
|   `-- writer.h
|-- libjsoncpp.a
`-- main.cpp

````

I can compile the main.cpp usi ng : 
` g++ main.cpp -L. -ljsoncpp`
But when I use :
`g++ -L. -ljsoncpp main.cpp` 
 I got an error  `undefined reference to 'Json::Value::Value(Json::ValueType)'`

Addition, clang++ is the same.
But dynamic library will work fine at clang++ and g++.

**Comment by cdunn2001** [comment]
That's a quirk of static archives in UNIX. The order matters. The linker pulls compilation units out of the archive and pulls symbols from them only when needed. To force *all* symbols into your program:

    g++ -Wl,--whole-archive ...

Or use the correct order. Or use shared libraries (.so instead of .a).

**Comment by orestonce** [comment]
Oh, I see, thank you.
