### ISSUE TITLE
CMake and Mac OS X El Capitan

### ISSUE THREAD

**Issue by michaelainsworth** [open-source-parsers/jsoncpp#380]
I've just updated my MacBook Pro to Mac OS X El Capitan, and my existing projects, which previously compiled perfectly, now fail.

```
jsoncpp/src/lib_json/json_reader.cpp:36:14: error: no type named 'unique_ptr' in namespace 'std'
typedef std::unique_ptr<CharReader> CharReaderPtr;
```

Is this a known issue?

**Comment by cdunn2001** [comment]
Hmm. Maybe we need to include a different header. I have El Capitan.

* Which branch?
```
$ git rev-parse HEAD
9c17e61bd016a84dbae1009857adf258797f2ce3
```
* What are your arguments to cmake?
* What compiler/version?
```
$ clang++ --version
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

**Comment by michaelainsworth** [comment]
master branch.

    git rev-parse HEAD
    9c17e61bd016a84dbae1009857adf258797f2ce3

No arguments to CMake.

clang version:

    clang++ --version
    Apple LLVM version 7.0.0 (clang-700.0.72)
    Target: x86_64-apple-darwin15.0.0
    Thread model: posix

**Comment by cdunn2001** [comment]
`cmake` fails without arguments.

So far, the code looks good. We have the proper header for `std::unique_ptr<>`.

Please provide as much detail as possible on the commands you are actually running. We need to reproduce this in order to fix it (unless you have an idea).

**Comment by laserroger** [comment]
Similar here. Cannot make anymore. And I found that there is an error that cmake cannot find my headfile like stdio.h. Maybe I should change the install_prefix in EI Capitan?

**Comment by cdunn2001** [comment]
I having been on El Capitan for weeks without a problem. I'll need very specific details to help you debug this.

Try updating Xcode. I think I had to do that (independent of jsoncpp).

**Comment by cdunn2001** [comment]
For me, `std::unique_ptr<>` comes from `<memory>` here:

    /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory

But IIRC I had to re-install XCode command-line tools.

**Comment by hjmjohnson** [comment]
Closing as this issue is no longer relevant after updates requiring C++11.
