### ISSUE TITLE
jsoncpp parse "1xxx"(with numeric prefix) string return true

### ISSUE THREAD

**Issue by pinguo-huangqi** [open-source-parsers/jsoncpp#383]
Json::Value data;
Json::Reader reader;
if (!reader.parse("111", data, false))
{
    printf("Parse failed!!!\n");
    return 0;
}

**Comment by pinguo-huangqi** [comment]
I test following case:

**Comment by cdunn2001** [comment]
Try it with strict-mode.

* http://open-source-parsers.github.io/jsoncpp-docs/doxygen/index.html
* http://open-source-parsers.github.io/jsoncpp-docs/doxygen/class_json_1_1_char_reader_builder.html


```cpp
Json::CharReaderBuilder rbuilder;
Json::CharReaderBuilder::strictMode(&rbuilder._settings);

std::string errs;
Json::Value root;
bool ok = Json::parseFromStream(rbuilder, std::cin, &root, &errs);
```

**Comment by pinguo-huangqi** [comment]
thanks for cdunn2001
I improved my code as following:

	Json::Reader reader(Json::Features::strictMode());
	Json::Value root;
	if (!reader.parse(sDoc, root, false))
	{
		printf("Parse %s failed!!!\n", sDoc.c_str());
		return false;
	}
	if (root.empty())
	{
		printf("Empty Json Data!!!\n");
		return false;
	}

**Comment by cdunn2001** [comment]
Nice!
