### ISSUE TITLE
Reader parse function usage not clear

### ISSUE THREAD

**Issue by redagito** [open-source-parsers/jsoncpp#385]
In the Json Reader class, the function
> bool parse(const std::string& document, Value& root, bool collectComments = true);

implies that a document name instead of a whole json text is required as the first parameter.
Basically I started using the API and expected this function to just open the file and use the stream processing function, but instead it seems to expect the whole json string in memory.
Maybe the parameter naming can be improved (json_text instead of just document).
Also the comment
> \param document UTF-8 encoded string containing the document to read.

still is not clear that the whole json data is required instead of just the file path/name

**Comment by cdunn2001** [comment]
I agree, but that's old. I recommend the newer `Json::parseFromStream()`:
* http://open-source-parsers.github.io/jsoncpp-docs/doxygen/index.html
