### ISSUE TITLE
Json testing with equals is failing. 

### ISSUE THREAD

**Issue by zammbi** [open-source-parsers/jsoncpp#388]
I'm trying to test if 2 pieces of json is the same but having trouble with this one test.
This is the console output below, is this a bug or am I doing equals testing wrong? 

``` json
 FAILED:
  REQUIRE( returnJson == CEJsonHelper::parse( "{\"apiVersion\" : \"1.0.0\",\"inEffect\" : false,\"methodCaller\" : \"getDuckworthLewisStern\",\"oversRemainingIncludingBreaks\" : -1,\"oversUsedIncludingBreaks\" : -1,\"parScore\" : -1,\"projectedScore\" : -1,\"runsToWin\" : -1,\"runsToWinPerOver\" : -1,\"runsToWinPerOverAverage\" : -1,\"showResults\" : false,\"targetScore\" : -1,\"validResult\" : false,\"winningBy\" : -1,\"methodCaller\":\"getDuckworthLewisStern\"}") )
with expansion:
{
 "apiVersion" : "1.0.0",
  "inEffect" : false,
  "methodCaller" : "getDuckworthLewisStern",
  "oversRemainingIncludingBreaks" : -1,
  "oversUsedIncludingBreaks" : -1,
  "parScore" : -1,
  "projectedScore" : -1,
  "runsToWin" : -1,
  "runsToWinPerOver" : -1,
  "runsToWinPerOverAverage" : -1,
  "showResults" : false,
  "targetScore" : -1,
  "validResult" : false,
  "winningBy" : -1
  }
  ==
  {
  "apiVersion" : "1.0.0",
  "inEffect" : false,
  "methodCaller" : "getDuckworthLewisStern",
  "oversRemainingIncludingBreaks" : -1,
  "oversUsedIncludingBreaks" : -1,
  "parScore" : -1,
  "projectedScore" : -1,
  "runsToWin" : -1,
  "runsToWinPerOver" : -1,
  "runsToWinPerOverAverage" : -1,
  "showResults" : false,
  "targetScore" : -1,
  "validResult" : false,
  "winningBy" : -1
  }
```

**Comment by cdunn2001** [comment]
Possibly a bug. But we'll need you track it down so it can be fixed. Submit a pull-request if you find it.

**Comment by zammbi** [comment]
I think the problem it is hitting this line:
```
case objectValue:
    return value_.map_->size() == other.value_.map_->size() &&
           (*value_.map_) == (*other.value_.map_);
```
Shouldn't it hit ```case stringValue```?

**Comment by cdunn2001** [comment]
Try stepping in with a debugger to see exactly where the values are said to differ.

**Comment by zammbi** [comment]
So I printed "* value_.map_" vs "* other.value_.map_"

A lot of it is the same but found large differences in the first object in the map.

```
[0] = {
    first = {
      cstr_ = 0x0000000100b06ae0 "apiVersion"
       = {
        index_ = 41
        storage_ = (policy_ = 1, length_ = 10)
      }
    }
    second = {
      value_ = {
        int_ = 4306513232
        uint_ = 4306513232
        real_ = 2.127700241291954E-314
        bool_ = true
        string_ = 0x0000000100b02d50 "\x05"
        map_ = 0x0000000100b02d50 size=778923875
      }
      type_ = stringValue
      allocated_ = 1
      comments_ = 0x0000000000000000
      start_ = 0
      limit_ = 0
    }
  }
  [1] = {
    first = {
      cstr_ = 0x0000000100b02f10 "inEffect"
       = {
        index_ = 33
        storage_ = (policy_ = 1, length_ = 8)
      }
    }
    second = {
      value_ = {
        int_ = 140734799793664
        uint_ = 140734799793664
        real_ = 6.9532229752395135E-310
        bool_ = false
        string_ = 0x00007fff5fbfce00 ""
        map_ = 0x00007fff5fbfce00 size=0
      }
      type_ = booleanValue
      allocated_ = 0
      comments_ = 0x0000000000000000
      start_ = 0
      limit_ = 0
    }
  }
```

vs

```
  [0] = {
    first = {
      cstr_ = 0x0000000100e66100 "apiVersion"
       = {
        index_ = 41
        storage_ = (policy_ = 1, length_ = 10)
      }
    }
    second = {
      value_ = {
        int_ = 4310117872
        uint_ = 4310117872
        real_ = 2.1294811700815792E-314
        bool_ = true
        string_ = 0x0000000100e72df0 "\x05"
        map_ = 0x0000000100e72df0 size=1953719636
      }
      type_ = stringValue
      allocated_ = 1
      comments_ = 0x0000000000000000
      start_ = 16
      limit_ = 23
    }
  }
  [1] = {
    first = {
      cstr_ = 0x0000000100e939b0 "inEffect"
       = {
        index_ = 33
        storage_ = (policy_ = 1, length_ = 8)
      }
    }
    second = {
      value_ = {
        int_ = 4309716480
        uint_ = 4309716480
        real_ = 2.1292828560838637E-314
        bool_ = false
        string_ = 0x0000000100e10e00 "re\" : -1,\"projectedScore\" : 249,\"runsToWin\" : -1,\"runsToWinPerOver\" : -1,\"runsToWinPerOverAverage\" : -1,\"showResults\" : false,\"targetScore\" : -1,\"validResult\" : true,\"winningBy\" : -1}"
        map_ = 0x0000000100e10e00 size=1399088500
      }
      type_ = booleanValue
      allocated_ = 0
      comments_ = 0x0000000000000000
      start_ = 37
      limit_ = 42
    }
  }
```

Each map has 13 objects but two of the objects(from the same map) have part of the json in its ```string_```, so maybe that is the issue.

**Comment by zammbi** [comment]
For anyone looking for a temporary hack. Use ```toStyledString()``` instead.

**Comment by cdunn2001** [comment]
I still don't see a difference. A map is a tree of key-value pairs. You're showing one such pair. Their keys match (if `operator==()` is correct for the key). And their values match too (again assuming a correct comparison), since the values are both `false` booleans. Everything looks fine to me. We would need a repro. Or you'd need to step in with a debugger. Or maybe add some printfs. Note that we have extensive test-cases, so the burden is on you.

Add your test into your test-suite and submit that as a pull-request. Then, when we can see the failing test-case and repro myself, we'll look into it.

**Comment by zammbi** [comment]
Thanks for your comments. 
For now I'm just using the workaround and comparing the strings. But I'll see if I can create a better test case that anyone can run.

**Comment by ycqiu** [comment]
did this bug fixed already, if not, i would like to find  and fix it

**Comment by BillyGoto** [comment]
It's not clear that there's a bug here.

The printout of "* value_.map_" vs "* other.value_.map_ has no surprises in
it.
The active union members had equal values.

They both looked like correct representations of the json object:

{ {"apiVersion", "\x05"}, {"inEffect", false} }

Looking for differences in uninitialized memory referred to by dangling
pointers isn't going to yield wisdom. We need a failing repro case.


On Thu, Jan 21, 2016 at 9:38 PM, ycqiu <notifications@github.com> wrote:

> did this bug fixed already, if not, i would like to find and fix it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-source-parsers/jsoncpp/issues/388#issuecomment-173784355>
> .
>



-- 
ǝnɥɐuop ʎllıq

**Comment by ycqiu** [comment]
yes , i think it possible not a bug, i need  a clear case.

**Comment by zammbi** [comment]
Sorry guys, I'll get you a simple case when I'm free at work to do this. 

The differences between the two json methods is that one sets up the json in code, and the other turns a string into json.

**Comment by matsbror** [comment]
I have a problem with operator== too when the input values serialized through << are equal but the expression Value1 == Value2 fails. I'll see if I can add a test case.

**Comment by BillyDonahue** [comment]
Any value containing a NaN would have this property, I think.

**Comment by matsbror** [comment]
Thanks for the reply, but there's no NaN, I think, but a few empty strings. They compare equal with toStyledString, which is what I use now for comparison.

**Comment by zammbi** [comment]
I'm no longer having any equal issues with the newest way to parse (`Json::parseFromStream`).
I did have one problem where I had to add ".0" to the end of my floats but that was an easy fix.

**Comment by cdunn2001** [comment]
@zammbi, maybe file a new Issue for the `.0` problem?

**Comment by zammbi** [comment]
I didn't think it was a bug?
Basically, my json string was 
>  {"value": 1}

Which value ended up being "1".


In code:
```
float one = 1;
Json::Value v;
v["value"] = one;
```

Which ended value being "1.0". I can create an issue if you think the code version should be "1".

**Comment by cdunn2001** [comment]
Those both look correct. Seems fine.
