### ISSUE TITLE
Json::Reader is not thread safe

### ISSUE THREAD

**Issue by tekknolagi** [open-source-parsers/jsoncpp#394]
There is a global variable, `stackDepth_g`, that can get incremented by many threads and blow the artificial stack limit.

My team ran into this problem when trying to highly parallelize our ray tracer. I am trying to submit a pull request soon.

**Comment by cdunn2001** [comment]
See comment in #395.

I'm curious: Why are you using the old `Reader` API? Is there a problem with `CharReaderBuilder`? Or are you still using an old version (i.e. `0.y.z`).

**Comment by tekknolagi** [comment]
I don't know how, but my team completely missed the fact that Reader was
deprecated. I don't know if there is a problem with CharReaderBuilder
because we haven't explored it.

**Comment by cdunn2001** [comment]
`Reader` is thorny. We'd remove it completely (from `1.y.z`) but it's popular. Most C++ coders don't like builders. It's an area where Java coders have a good idea.

**Comment by tekknolagi** [comment]
Interesting. We'll look into CharReaderBuilder. Thank you for explaining!
