### ISSUE TITLE
Why doesn't this work?

### ISSUE THREAD

**Issue by ibc** [open-source-parsers/jsoncpp#398]
This work as expected:

```c++
Json::Value root(Json::objectValue);
Json::Value foo(Json::objectValue);

foo["bar"] = 1234;
root["foo"] = foo;
```

But this does not work (`"bar`" is not present in the resulting `root`):

```c++
Json::Value root(Json::objectValue);
Json::Value foo(Json::objectValue);

root["foo"] = foo;
foo["bar"] = 1234;  // <-- this has no effect in `root`
```

Which is the rationale behind this behavior?

**Comment by cdunn2001** [comment]
Both the copy-ctor and the assignment operator are "deep copy", not "shallow copy" -- i.e. copy-by-value, not by-reference. This avoids all sorts of complexity.

* http://open-source-parsers.github.io/jsoncpp-docs/doxygen/namespace_json.html

**Comment by ibc** [comment]
Clear. Thanks.
