### ISSUE TITLE
Json::StreamWriter::write doc is wrong

### ISSUE THREAD

**Issue by ibc** [open-source-parsers/jsoncpp#399]
According to http://open-source-parsers.github.io/jsoncpp-docs/doxygen/class_json_1_1_stream_writer.html#a237368cf13b41decc015640d25f176ab:

```
virtual int Json::StreamWriter::write ( Value const & root, std::ostream * sout)
```

But in this case it always take a pointer which becomes `true`, so the method writes "true" into the stream.

The correct declaration is:

```
virtual int Json::StreamWriter::write ( Value const root, std::ostream * sout)
```

**Comment by cdunn2001** [comment]
I'm confused. You want to change a reference to a copy? I don't understand what that fixes. Could you provide example code?

**Comment by ibc** [comment]
Sorry, my fault. I've got confused with `CharReader.parse()` which requires a pointer to `Value`.

**Comment by cdunn2001** [comment]
Oh. We try to follow Google C++ Style Guide, where return values are trailing pointer parameters.
