### ISSUE TITLE
C++11 optimizations

### ISSUE THREAD

**Issue by cdunn2001** [open-source-parsers/jsoncpp#40]
Re: issue #37

**Comment by cdunn2001** [comment]
E.g. see discussion at pull #75.

Also, with pull #133, we at least have `-std=c++0x` for gcc and `-std=c++11` for clang.

**Comment by cdunn2001** [comment]
We now have `-std=c++11` on *master*. See #313.

**Comment by zammbi** [comment]
Can we get constexpr added? :)

**Comment by cdunn2001** [comment]
Sure! Submit a pull-request.

**Comment by hjmjohnson** [comment]
Support for constexpr now is supported universally,  pull requests are welcome.
