### ISSUE TITLE
Maybe a bug in jsoncpp decodeString(Token& token, std::string& decoded)

### ISSUE THREAD

**Issue by ZhengfengRao** [open-source-parsers/jsoncpp#407]
using newest master-branch code on windows, vs2010 x86.
Test Code:

    Json::Reader reader;
    Json::Value root;
    bool ret = reader.parse("{\"skuName\":\"/测ü\\ \\\\/红色\"}",root,false); 
    std::string str3 = root.toStyledString();
    int a = 0;

the ret value will always be error, error msg: "Bad escape sequence in string". The jsoncpp should not try to decode the "\ ".

Any suggesttion? 
Thanks a lot.

**Comment by BillyDonahue** [comment]
I believe jsoncpp is correct.

Why do you say this:

> The jsoncpp should not try to decode the "\ ".

Look at the spec for string here http://www.json.org.
Only a few things are allowed to follow a backslash:
These are `"`, `\`, `/`, `b`, `f`, `n`, `r`, `t` or `uxxxx`.
Space is not allowed, so jsoncpp reports a formatting error, correctly IMO.
