### ISSUE TITLE
Compilation: override specifier 'override' not allowed on a destructor

### ISSUE THREAD

**Issue by DaltonSleeper** [open-source-parsers/jsoncpp#410]
Hi,

I'm trying to compile the JasonCPP solution but I'm getting an error about the override specifier on some of the destructors. Does anyone know how to solve this without causing any issues? This does not happen when having VC++ 2012 as target.

Windows 10 x64
Visual Studio 2012

One of many:
Error	2	error C3665: 'Json::CharReaderBuilder::~CharReaderBuilder' : override specifier 'override' not allowed on a destructor	C:\jsoncpp-master\include\json\reader.h	336	1	lib_json (Visual Studio 2010)

Best regards,
DS

**Comment by cdunn2001** [comment]
I suppose we could drop `override` for the dtors. That will not alter any symbols. However, if this is only for VS 2010, I am reluctant to adapt. Which version of jsoncpp are you using?

And could you live with an ifdef for your compiler/version? If so, maybe you could submit a pull-request.

**Comment by DaltonSleeper** [comment]
We are using the latest jasoncpp and are currently targeting VC++ 2012, 2010 and 2008. I would guess that the problem will appear for anything less than 2012. I have not gone through all the code and was not sure if override had any specific purpose. If it is safe to remove them we can do it on our side, but I would guess that there are others that will be affected by this.

Best,
DS

**Comment by cdunn2001** [comment]
I'm fine with dropping `override` for dtors. But I'd like to see `virtual`, just as a reminder.

Could you make that change and submit a pull-request?

**Comment by BillyDonahue** [comment]
I'd rather have an `#ifdef`-able override macro than a 'virtual'.
The virtual will declare a destructor virtual even if no base class has a virtual destructor. It can paper over inheritance mistakes. I'd rather have nothing at all. If it's just for documentation, let's just use /*virtual*/.
But really the compiler-conditional macro feels like a better solution than commenting. If a compiler doesn't have 'override', it serves as documentation anyway.

**Comment by RelicOfTesla** [comment]
not support VS2010 on tag 1.7.0 

\include\json\allocator.h(17): error C2873: “value_type

And bad keyword with override
Json::Exception  ~Exception() throw() override;

**Comment by cdunn2001** [comment]
@RelicOfTesla, I don't understand either of these.

A) Line 17 looks like this:
```
 13 template<typename T>
 14 class SecureAllocator {
 15   public:
 16     // Type definitions
 17     using value_type      = T;
```
How should we change that? Is it a C++11 thing?

I've removed the accidental default which caused you to include `allocator.h`, so you won't see this now. But I'm curious how you saw it if you didn't actually set `JSONCPP_USE_SECURE_MEMORY` when running **cmake**. Maybe you updated but did not run **cmake** again?

B) `Json::Exception ~Exception() throw() override;`
The override keyword should work in C++11. But we'll add a macro for VS2010, as suggested by @BillyDonahue, soon....
