### ISSUE TITLE
double to json fails standard

### ISSUE THREAD

**Issue by stefanofiorentino** [open-source-parsers/jsoncpp#420]
The follwing test case doesn't respect the standard. From wikipedia. 

> If an IEEE 754 double precision is converted to a decimal string with at least 17 significant digits and then converted back to double, then the final number must match the original.

In particular the hardcoded double precision 17 yields to stringFormat %.17g that causes the problem.

	BOOST_AUTO_TEST_CASE( UnitTest_doubleToJsonCpp )
	{
		// init
		double value = 1.0000001;

		// expected
		string expected = string("1.0000001");

		Json::Value jsonMap;
		jsonMap["val"] = value;
	
		std::stringstream ss;
		ss << jsonMap;
		std::string actual = ss.str();
		char chars[] = "\t\n ";
		for (unsigned int i = 0; i < strlen(chars); ++i)
		{
			actual.erase (std::remove(actual.begin(), actual.end(), chars[i]), actual.end());
		}
		std::cout << actual << std::endl;

		// checks
		BOOST_CHECK( expected.compare(actual)==0 );
	}

The result on std::cout is `{"val":1.0000001000000001}`

**Comment by BillyDonahue** [comment]
So what's the issue here exactly?  `Json::Value` doesn't have an `operator<<`, so how I don't think the `ss << jsonMap` expression will compile without outside help. So where's the serialization code that's failing? I'm just saying I'd need more evidence to track this down.

**Comment by stefanofiorentino** [comment]
The issue is that someone hard-coded the number 17 into the code. Then often happens that the resulting string representing the double has the last digit of mantissa that differs on different machine (I tried on Mac OS X and Win 7). This is a big portability issue. Don't you care about it?

**Comment by stefanofiorentino** [comment]
The line you should look at is
https://github.com/open-source-parsers/jsoncpp/blob/master/src/lib_json/json_writer.cpp#L1209

**Comment by BillyDonahue** [comment]
Oh, I missed the `operator<<(ostream&,Json::Value const&)` because it's in the wrong header file, frankly. It should be declared with `Json::Value` in `value.h`, not with `Json::JsonWriter` in `writer.h`.

So the fault is with `valueToString(double)`
https://github.com/open-source-parsers/jsoncpp/blob/b4d2b658416b8087f89599daac9b9c36c6c56616/src/lib_json/json_writer.cpp#L168

My first thought is that `17` should be `std::numeric_limits<double>::max_digits10`.
But that still doesn't fix the problem, because that IS `17`.

The nonliteral format string can be avoided. We're generating formatString dynamically for no reason.
We could just use `*` for the precision (which should be int, not unsigned).
https://github.com/open-source-parsers/jsoncpp/blob/b4d2b658416b8087f89599daac9b9c36c6c56616/src/lib_json/json_writer.cpp#L151

    len = snprintf(buffer, sizeof(buffer), "%.*g", precision, value);

**Comment by BillyDonahue** [comment]
So I'm a little confused about what the problem is.

    1.0000001 and 1.0000001000000001

are the same double.

    int f() { return 1.0000001 == 1.0000001000000001; }

Json hasn't distorted your data.

**Comment by stefanofiorentino** [comment]
In scientific applications is mandatory to write the entire significant
digits that are 17 for the double precision.
I'm very sorry, I'll try to build and run tests, that, in my opinion, are
wrong. A said, the problem raises when try the application with number as
0.123456789012345 that the library represents as 0.1234567890123450 on
Windows and 0.1234567890123451 on Mac. I indeed will try to help, but for
my projects I keep going with the modifications proposed.

Furthermore the comment 139 on line is correct.. (16 significant digits)
https://github.com/open-source-parsers/jsoncpp/blob/b4d2b658416b8087f89599daac9b9c36c6c56616/src/lib_json/json_writer.cpp#L139



2016-02-12 21:39 GMT+01:00 Billy Donahue <notifications@github.com>:

> Oh, I missed the operator<<(ostream&,Json::Value const&) because it's in
> the wrong header file, frankly. It should be declared with Json::Value in
> value.h, not with Json::JsonWriter in writer.h.
>
> So the fault is with valueToString(double)
>
> https://github.com/open-source-parsers/jsoncpp/blob/b4d2b658416b8087f89599daac9b9c36c6c56616/src/lib_json/json_writer.cpp#L168
>
> My first thought is that 17 should be
> std::numeric_limits<double>::max_digits10.
> But that still doesn't fix the problem, because that IS 17.
>
> The nonliteral format string can be avoided. We're generating formatString
> dynamically for no reason.
> We could just use * for the precision (which should be int, not unsigned).
>
> https://github.com/open-source-parsers/jsoncpp/blob/b4d2b658416b8087f89599daac9b9c36c6c56616/src/lib_json/json_writer.cpp#L151
>
> len = snprintf(buffer, sizeof(buffer), "%.*g", precision, value);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-source-parsers/jsoncpp/issues/420#issuecomment-183480842>
> .
>



-- 
Fiorentino Ing. Stefano
Cell. +39 340 2216385

**Comment by stefanofiorentino** [comment]
Are different because the `1.0000001000000001` is formally different from
`1.000001`.
Please, try with 16 instead of 17 and you'll have both double and string
representation bit-wise equal.
And all tests on Travis C.I. succeed.

2016-02-12 21:57 GMT+01:00 Billy Donahue <notifications@github.com>:

> So I'm a little confused about what the problem is.
>
> 1.0000001 and 1.0000001000000001
>
> are the same double.
>
> int f() { return 1.0000001 == 1.0000001000000001; }
>
> Json hasn't distorted your data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-source-parsers/jsoncpp/issues/420#issuecomment-183485940>
> .
>



-- 
Fiorentino Ing. Stefano
Cell. +39 340 2216385

**Comment by BillyDonahue** [comment]
I don't know what you mean by "formally different", but the string representation isn't the number. The number is the number. If you try with precision 16 instead of 17 (in other words, less than `std::numeric_limits<double>::max_digit10`) you'll have a double->string transform that's more stable, yes, but I think you'd be introducing a risk of distortion, as the return trip from string back to double will not yield the same double.  Maybe for 1.000001 it will work. Maybe for billions of doubles it will work, but there will be doubles for which it doesn't work.

**Comment by stefanofiorentino** [comment]
Gotcha, num_of_digits = 2 + mantissa_bits * 301L / 1000.0
Ok, you right.
Maybe it's worth to think about substituting sprintf with c++11
stringstream?

2016-02-12 22:09 GMT+01:00 Billy Donahue <notifications@github.com>:

> I don't know what you mean by "formally different", but the string
> representation isn't the number. The number is the number. If you try with
> precision 16 instead of 17 (in other words, less than
> std::numeric_limits<double>::max_digit10) you'll have a double->string
> transform that's more stable, yes, but I think you'd be introducing a risk
> of distortion, as the return trip from string back to double will not yield
> the same double. Maybe for 1.000001 it will work. Maybe for billions of
> doubles it will work, but there will be doubles for which it doesn't work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-source-parsers/jsoncpp/issues/420#issuecomment-183488893>
> .
>



-- 
Fiorentino Ing. Stefano
Cell. +39 340 2216385

**Comment by BillyDonahue** [comment]
stringstream (which was in C++98) isn't going to help.
Its output is specified in terms of printf's output.
That is to say, it's not more tightly nailed down than snprintf is.
The least-significant-digit ambiguities should still be present.

**Comment by emeltzer** [comment]
I encountered this issue as well. I went with the following approach.
http://stackoverflow.com/questions/4643641/best-way-to-output-a-full-precision-double-into-a-text-file
