### ISSUE TITLE
Parsing integers with JsonCpp

### ISSUE THREAD

**Issue by ksl67** [open-source-parsers/jsoncpp#427]
I am using JsonCpp v1.6.5 to parse a JSON file that contains the following:

    { "some-property" : 32 }

After parsing the type of the value is `intValue` rather than `uintValue`. 

How does the parser interpret an integer as unsigned?

**Comment by cdunn2001** [comment]
I think it's always signed. But maybe it's unsigned if it's too large. You can use a `UInt` method to get the unsigned version.
