### ISSUE TITLE
jsoncpp can parse utf-8 string？

### ISSUE THREAD

**Issue by cug2104518294** [open-source-parsers/jsoncpp#428]
jsoncpp can parse utf-8 string？
maybe jsoncpp can only parse ansi string！！！！

**Comment by cdunn2001** [comment]
UTF-8 strings should be fine. However, you will need to beware embedded zeores. You should avoid the old API method which returns null-terminated `char*`.

The rest of the JSON input must be ASCII, as specified in the standard.
