### ISSUE TITLE
Unexpectedly large memory consumption?

### ISSUE THREAD

**Issue by JonMarbach** [open-source-parsers/jsoncpp#433]
Hi there - First time reporting an issue here on GitHub... 

I've just gotten into JSON as a format and tried your library first. It's very easy to use and I like the single-header implementation. 

The problem I've run into is that I'm loading a large file (500MB) but the resulting Value object after parsing is using ~3.6GB RAM in Release mode and 7+GB in Debug (vs2012.) Is this expected or explainable? For comparison, I just switched my code to rapidjson which isn't quite as friendly as your library but only uses about 200MB.

I can't share the file itself but the format is something like this with many nested arrays:
```
{
	"GriddedSurfaces" : 
	[
		{
			"hasVertexNormals" : true,
			"height" : 57,
			"normals" : 
			[
				[
					[
						0,
						0,
						1
					],
					[
						0,
						0,
						1
					],

...
],
			"vertices" : 
			[
				[
					[
						5229.943359375,
						8931.4990234375,
						-358.82843017578125
					],
					[
						5230.6865234375,
						8931.0849609375,
						-359.35418701171875
					],
...
],
			"nulls" : 
			[
				[
					true,
					true,
...
				]
			]
		}
	]
```				

Thoughts?

**Comment by cdunn2001** [comment]
> For comparison, I just switched my code to rapidjson which isn't quite as friendly as your library but only uses about 200MB.

Yes, different trade-offs. JsonCpp is moderately efficient, given the nested STL structures, but far from the best. IMO, the simplest -- and nearly most efficient --  is [gason](https://github.com/open-source-parsers/gason--). JsonCpp's main selling points are
* friendliness (though you might consider the new [json](https://github.com/open-source-parsers/json) for better C++11 integration)
* embedded comments, and
* highly configurable parsing/dumping.

It's best for meta-data. For a large data-store like yours, I'm not even sure that JSON is smart. I highly recommend [msgpack(http://msgpack.org/index.html).]

**Comment by JonMarbach** [comment]
Thanks for the feedback and the pointers! You're right that JSON is probably not optimal for what we're doing but I wanted to try it out anyway. I'll look into some of the alternatives you mention here. Thanks again.
