### ISSUE TITLE
jsoncpp fails to compile on MSVC16 (visual studio 10)

### ISSUE THREAD

**Issue by toeb** [open-source-parsers/jsoncpp#443]
The problems are the override specifiers on destructors.  When removing these everything compiles fine.  I solved this by adding a `#define override` for msvs 10 which override the override specifier to be  empty.

**Comment by ya1gaurav** [comment]
override is C++-11 feature. Your compiler should support C++-11, otherwise use 0.x.y branch.

**Comment by cdunn2001** [comment]
The good news is that 0.10.* releases maintain binary-compatibility, and they are readily updated with bug-fixes, rarely needed.

**Comment by cdunn2001** [comment]
VS 2010 might actually work for you now. If not, and if you come up with a solution, please re-open.

**Comment by toeb** [comment]
ty :+1:
