### ISSUE TITLE
amalgamated header json.h is broken

### ISSUE THREAD

**Issue by mchalupa** [open-source-parsers/jsoncpp#448]
Hi,

the last merge broke the amalgamated sources, namely this line: https://github.com/open-source-parsers/jsoncpp/commit/ae564653c4c9acac795d189efb463ea13194169c#diff-3c93282e96d1ef08ede694c0f5ea8108R122

The json.h file now contains inlined version.h file (which is fine) and then there's an extra #include "version.h" (which breaks compilation if these files are used out of the tree)

**Comment by cdunn2001** [comment]
Please re-open if that doesn't fix it. Thanks for bringing it to our attention.
