### ISSUE TITLE
warning C4275

### ISSUE THREAD

**Issue by rickyviking** [open-source-parsers/jsoncpp#450]
Hi guys,

whenever I include (amalgamated) json.h in the header file of a class exported with Visual Studio, I get the C4275 warning as some classes used as base are not exported. 

> .../json.h(1504): warning C4275: non dll-interface class 'Json::CharReader::Factory' used as base for dll-interface class 'Json::CharReaderBuilder'
>          .../json.h(1482) : see declaration of 'Json::CharReader::Factory'
>          .../json.h(1504) : see declaration of 'Json::CharReaderBuilder'

Now, the sibling warning C4251 is disabled in jsoncpp code:
https://github.com/open-source-parsers/jsoncpp/blob/master/include/json/value.h#L42

Should C4275 be disabled as well? 
Or maybe the base class should be exported to silent the warning?

**Comment by cdunn2001** [comment]
I guess we need to expose the base class. Can you make the change, verify it with you VS, and post here (or submit a pull-request if possible)?

**Comment by rickyviking** [comment]
Hi @cdunn2001, 
after updating to the latest version the warning disappeared. 
In the meantime all the base classes have been added with the export directive, so I don't have to submit any pull request. 
I'm closing the issue, thank you.
