### ISSUE TITLE
clang 3.8 : compile fail

### ISSUE THREAD

**Issue by proller** [open-source-parsers/jsoncpp#451]
src/lib_json/json_tool.h:66:18: error: implicit conversion changes signedness: 'signed char' to 'char' [-Werror,-Wsign-conversion]
    *--current = static_cast<signed char>(value % 10U + static_cast<unsigned>('0'));
               ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by cdunn2001** [comment]
Please re-open if this change does not solve the problem.
