### ISSUE TITLE
Usage of the jsoncpp CMake package

### ISSUE THREAD

**Issue by ghisvail** [open-source-parsers/jsoncpp#455]
Dear jsoncpp developers,

I tried to use the CMake package built by `jsoncpp` (and provided by `libjsoncpp-dev` on Debian / Ubuntu) on a CMake project depending on it.

I tried the following discovery via CMake config mode:

```
find_package(jsoncpp REQUIRED)
include_directories(${jsoncpp_INCLUDE_DIRS})
link_libraries(${jsoncpp_LIBRARIES})
```

But it does not seem to work. I then ran the the following test:

```
cmake_minimum_required(VERSION 2.6.2)
project(jsoncpp_test)

find_package(jsoncpp REQUIRED)
message("FOUND CONFIG: ${jsoncpp_CONFIG}")
message("INCLUDE DIRS: ${jsoncpp_INCLUDE_DIRS}")
message("LIBRARIES: ${jsoncpp_LIBRARIES}")
```

which produced the following output:

```
FOUND CONFIG: /usr/lib/x86_64-linux-gnu/cmake/jsoncpp/jsoncppConfig.cmake
INCLUDE DIRS: 
LIBRARIES: 
```

meaning the CMake package file is found but none of the expected variables is set.

How are we expected to discover and use `jsoncpp` under CMake then? FYI, using pkg-config works fine, but is not what I would consider a solution.

Many thanks,
Ghis

**Comment by arrufat** [comment]
I've managed to make it work like this
``` cmake
find_package(PkgConfig REQUIRED)
pkg_check_modules(JSONCPP jsoncpp)
link_libraries(${JSONCPP_LIBRARIES})
add_executable(myprogram myprogram.cpp)
target_link_libraries(landmarks ${JSONCPP_LIBRARIES})
```

**Comment by cdunn2001** [comment]
Thanks, Max Headroom. Update the wiki too, if you want.

**Comment by sizeofvoid** [comment]
Did you read your `CMakeLists.txt`?
```
find_package(Boost REQUIRED filesystem system thread)
find_package(jsoncpp CONFIG REQUIRED)
...
```

**Comment by pazz** [comment]
thanks @arrufat 
Silly question: you would then include jsoncpp in your main file as 

```C++
#include <jsoncpp/json/json.h>
```

right? Does that mean the code is not portable in the sense that if will only compile if run on a distri that packages the headers in this way?

**Comment by arrufat** [comment]
Yes, I had exactly this issue with Arch Linux and Ubuntu...

**Comment by pazz** [comment]
Thanks for the quick response. I've just seen that you can add the discovered include path with

```
include_directories("${JSONCPP_INCLUDE_DIRS}")
```

in `CMakeLists.txt`. Then you can just include as `<json/json.h>`...

**Comment by christian-rauch** [comment]
The `jsoncppConfig.cmake` defines property `INTERFACE_INCLUDE_DIRECTORIES` for targets `jsoncpp_lib` and `jsoncpp_lib_static`.

You need to query the target property and set it manually:
```cmake
get_target_property(JSON_INC_PATH jsoncpp_lib INTERFACE_INCLUDE_DIRECTORIES)
include_directories(${JSON_INC_PATH})
```

**Comment by cdunn2001** [comment]
@christian-rauch , If you submit a PR, we'll merge it. We don't maintain the Cmake files anymore; users do that. We use only the Meson files ourselves.

**Comment by christian-rauch** [comment]
@cdunn2001 The code snippet that I mentioned has to be used on the user side, e.g. an application that wants to use jsoncpp.

If someone is interested in making the usage of jsoncpp in CMake projects easier, there is a way to export header and libraries in such a way that an application can just import the library without dealing with include directories and libraries manually: https://rix0r.nl/blog/2015/08/13/cmake-guide/

**Comment by cdunn2001** [comment]
Thanks. Updated our Wiki.

If you submit the change to simplify Cmake, we'd merge it.

**Comment by mathemaphysics** [comment]
I'm trying to use jsoncpp via `add_subdirectory()`. I can't seem to guess the target names right. Neither `jsoncpp` nor `json` appear to be library targets. I'm planning on reading through all the CMake files, but I thought I'd ask here just in case anyone could help.

**Comment by karl0st** [comment]
> I'm trying to use jsoncpp via `add_subdirectory()`. I can't seem to guess the target names right. Neither `jsoncpp` nor `json` appear to be library targets. I'm planning on reading through all the CMake files, but I thought I'd ask here just in case anyone could help.

Did you figured it out ?

**Comment by Leonkoithara** [comment]
Hi I'm using mac os x(installed jsoncpp using `brew install jsoncpp`) and I found ${JSONCPP_LINK_LIBRARIES} was the required library to be linked. Sample CMakeLists.txt
```
cmake_minimum_required(VERSION 3.22)
set(CMAKE_CXX_STANDARD 11)

find_package(PkgConfig REQUIRED)
pkg_check_modules(JSONCPP jsoncpp)

add_executable(utils main.cpp)

target_link_libraries(
    utils
    ${JSONCPP_LINK_LIBRARIES}
)
```

**Comment by Lithimlin** [comment]
I can't work out how to include this library when installed on Ubuntu 22.04.

I've tried the version in the wiki, the one above, and a method I found on [stackoverflow](https://stackoverflow.com/a/67813341/6155242).
I'm trying to include the library using `#include <json/json.h>`.

**Comment by eli-schwartz** [comment]
> Hi I'm using mac os x(installed jsoncpp using `brew install jsoncpp`) and I found ${JSONCPP_LINK_LIBRARIES} was the required library to be linked. Sample CMakeLists.txt

From the CMake docs: https://cmake.org/cmake/help/latest/module/FindPkgConfig.html
> New in version 3.6: The IMPORTED_TARGET argument will create an imported target named PkgConfig::<prefix> that can be passed directly as an argument to [target_link_libraries()](https://cmake.org/cmake/help/latest/command/target_link_libraries.html#command:target_link_libraries).

Please switch this:
```cmake
pkg_check_modules(JSONCPP jsoncpp)

target_link_libraries(
    utils
    ${JSONCPP_LINK_LIBRARIES}
)
```

for this:
```cmake
pkg_check_modules(JSONCPP jsoncpp IMPORTED_TARGET GLOBAL)

target_link_libraries(
    utils
    PkgConfig::JSONCPP
)
```
