### ISSUE TITLE
Unable to create object of Value class, used in an MFC project

### ISSUE THREAD

**Issue by madhavgaur** [open-source-parsers/jsoncpp#459]
But I can use MACRO - JSONCPP_STRING
I get linker error LNK2019 while creating object of Value class in my project.

"Json::Value value1(text);"

**Comment by cdunn2001** [comment]
Need more info. What is `text`?

It's possible that you have built the library with support for the new memory-wiping allocator. You might only need to update and rebuild the library. But we cannot debug this remotely.

**Comment by madhavgaur** [comment]
text is JSONCPP_STRING
I simply added the project in my solution and it's correctly linked with my project. I tried everything for creating that object but still I'm nowhere.

**Comment by cdunn2001** [comment]
What git-commit are you using?

And are you using **cmake**?

**Comment by madhavgaur** [comment]
I got that to work but how do i get the section, key value pairs to a data structure like:
{
 "General":{
  "a" = 1
  "b" = 2
}
}

in 

struct gEN_DATA
{
int var1;
int var2;
};

**Comment by cdunn2001** [comment]
This library does not deserialize. It just parses into nested maps/arrays. But see the docs for what is available:
* http://open-source-parsers.github.io/jsoncpp-docs/doxygen/index.html
