### ISSUE TITLE
No more VS2010 support in trunk and 1.7.1

### ISSUE THREAD

**Issue by bialix** [open-source-parsers/jsoncpp#461]
Your announce https://github.com/open-source-parsers/jsoncpp/releases/tag/1.7.1 said it should support VS2010. I've just tried to build amalgamated sources from trunk ~1.7.2 with 2010 and get compilation errors, related to SecureMemory template:

   json\json.h(135): error C2873: 'value_type' : symbol cannot be used in a using-declaration
          jsoncpp\json\json.h(197) : see reference to class template instantiation 'Json::SecureAllocator<T>' being compiled

**Comment by cdunn2001** [comment]
This could be a mistake in how amalgamate works. You should not see SecureAllocator at all. What git-commit are you using?

**Comment by bialix** [comment]
I've tried both tag-1.7.1 and Commit: 45da594e71ad0ac323aada534c338a308d63b84f which is latest commit in master branch ATM.

**Comment by cdunn2001** [comment]
You're right. The amalgamated header should not include allocator.h. Fixing...

**Comment by bialix** [comment]
Thanks, it works now with VS2010.
