### ISSUE TITLE
jsoncpp_test - ValueTest/integers unit test failure

### ISSUE THREAD

**Issue by minyang** [open-source-parsers/jsoncpp#462]
After compiling the latest version on QNX with a set of minor patches (e.g., disabling C++11 compiler option in CMake, adding explicit numerical casting, etc, to remove compiler errors), it looks like ``ValueTest/integers`` test of ``jsoncpp_test`` fails.  Looking at ``JSONTEST_ASSERT_EQUAL`` macro, I noticed the macro has a static_cast conversion and thus added a few debug log inside ``test_lib_json/main.cpp`` as follows:

```
...
Testing ValueTest/strings: OK
Testing ValueTest/bools: OK
Testing ValueTest/integers: kint32max     : 2147483647
kfint32max    : 2147483648.00000000002400000000
val.asFloat()    : 2147483648.00000000002400000000
static_cast<float>(kfint32max): 2147483648.00000000002400000000
static_cast<float>(kfint32max) != val.asFloat: TRUE
DIFFERENT!
static_cast<float>(kfint32max) - val.asFloat(): 1.00000000000000000000
a1=(double) (static_cast<float>(kfint32max)): 2147483648.00000000002400000000
a2=(double) val.asFloat(): 2147483646.99999999999100000000
a1-a2: 1.00000000000000000000
FAILED
Testing ValueTest/nonIntegers: OK
Testing ValueTest/compareNull: OK
...
```

As seen here, ``static_cast<float>(kfint32max) != val.asFloat`` becomes true, resulting in a failure of the test.  ``static_cast<float>(kfint32max) - val.asFloat()`` is equal to 1.0, so is ``a1-a2``.  This appears to be the root cause of the issue.

In contrast, the same code runs under Ubuntu as follows:

```
...
Testing ValueTest/strings: OK
Testing ValueTest/bools: OK
Testing ValueTest/integers: kint32max     : 2147483647
kfint32max    : 2147483648.00000000000000000000
val.asFloat()    : 2147483648.00000000000000000000
static_cast<float>(kfint32max): 2147483648.00000000000000000000
static_cast<float>(kfint32max) != val.asFloat: FALSE
SAME!
static_cast<float>(kfint32max) - val.asFloat(): 0.00000000000000000000
a1=(double) (static_cast<float>(kfint32max)): 2147483648.00000000000000000000
a2=(double) val.asFloat(): 2147483648.00000000000000000000
a1-a2: 0.00000000000000000000
OK
Testing ValueTest/nonIntegers: OK
Testing ValueTest/compareNull: OK
...
```

Any clue/help to resolve this issue would be appreciated.  Thanks!

**Comment by cdunn2001** [comment]
No idea. The tip of master requires C++11. You could try the old `0.y.z` branch, or a `0.*.*` release. Please re-open if you figure something out.
