### ISSUE TITLE
Dependency loop: cmake depends on jsoncpp and jsoncpp uses cmake

### ISSUE THREAD

**Issue by yurivict** [open-source-parsers/jsoncpp#471]
If jsoncpp is used by such a ubiquitous utility as cmake, you should drop the cmake build. Otherwise this is confusing.

**Comment by cdunn2001** [comment]
Interesting point. It's weird, but it's a form of boot-strapping. Not terrible. Besides, JsonCpp can be built without cmake by anyone who wants to.

**Comment by kallisti5** [comment]
Just ran into this on Haiku LOL..

*    dev-build/meson-1.8.2: cmd:ninja >= 1.6
*    dev-build-ninja/ninja-1.13.0: cmd:cmake
*    dev-build/cmake-4.0.3: lib:libjsoncpp$secondaryArchSuffix
*    dev-libs/jsoncpp-1.9.5: cmd:meson, cmd:ninja

Just a reminder it's essential to allow building jsoncpp without cmake/meson/ninja :-)
