### ISSUE TITLE
decodeString return error Bad escape sequence in string

### ISSUE THREAD

**Issue by jasonsword** [open-source-parsers/jsoncpp#472]
I get a string from web page
and the value looks like

>  "value" : "abc\'hello\'def"

 in this case, it throws an error. 
How can I do it properly?

**Comment by cdunn2001** [comment]
Not sure. You'd need to post a clearer example, with code.

**Comment by ibc** [comment]
Tested. It does not fail for me at all.

**Comment by zwmeteor** [comment]
`#include "json/json.h"
#include "json/reader.h"
#include "json/value.h"
#include <string>
#include <iostream>

using namespace std;

//#pragma comment(lib, "lib_jsond.lib")

int main(int argc, char* argv[])
{
	std::string str = "{\"one\":\"this is a \\\'bad\\\' test\"}";
	Json::Value value;
	Json::Reader reader;

	bool bret = reader.parse(str, value);
	if (bret)
	{
		cout << "parse success" << endl;
	}
	else
	{
		std::string strerror = reader.getFormattedErrorMessages();
		cout << "parse error : " << strerror << endl;
	}
	return 0;
}`

**Comment by baylesj** [comment]
Closing as "no repro" due to this being fixed in the new CharReader implementation. On latest HEAD, this prints `parse success`:

```
#include "include/json/json.h"
#include "include/json/reader.h"
#include "include/json/value.h"
#include "string"
#include "iostream"

using namespace std;

int main(int argc, char* argv[])
{
    std::string str = "{\"one\":\"this is a \\\\\'bad\\\\\' test\"}";

    Json::CharReaderBuilder builder;
    auto reader = std::unique_ptr<Json::CharReader>(builder.newCharReader());

    Json::Value value;
    Json::String errors;
    const bool bret = reader->parse(str.data(), str.data() + str.length(), &value, &errors);
    if (bret)
    {
        cout << "parse success" << endl;
    }
    else
    {
        cout << "parse error : " << errors << endl;
    }
    return 0;
}
```
