### ISSUE TITLE
Some warnings being treated as errors in building process

### ISSUE THREAD

**Issue by LucasHMS** [open-source-parsers/jsoncpp#473]
Hi, I clone the repo and tried to build as described on the README, but when I use `make` it stucks at 16% and show several errors:

> [ 16%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o
> /home/jsoncpp/src/lib_json/json_reader.cpp: In member function 'void Json::Reader::readNumber()':
> /home/jsoncpp/src/lib_json/json_reader.cpp:433:40: error: conversion to 'char' from 'int' may alter its value [-Werror=conversion]
> /home/jsoncpp/src/lib_json/json_reader.cpp:436:40: error: conversion to 'char' from 'int' may alter its value [-Werror=conversion]
> /home/jsoncpp/src/lib_json/json_reader.cpp:438:42: error: conversion to 'char' from 'int' may alter its value [-Werror=conversion]
> /home/jsoncpp/src/lib_json/json_reader.cpp:442:40: error: conversion to 'char' from 'int' may alter its value [-Werror=conversion]
> /home/jsoncpp/src/lib_json/json_reader.cpp:444:42: error: conversion to 'char' from 'int' may alter its value [-Werror=conversion]
> /home/jsoncpp/src/lib_json/json_reader.cpp:446:42: error: conversion to 'char' from 'int' may alter its value [-Werror=conversion]
> /home/jsoncpp/src/lib_json/json_reader.cpp: In member function 'bool Json::OurReader::readNumber(bool)':
> /home/jsoncpp/src/lib_json/json_reader.cpp:1397:40: error: conversion to 'char' from 'int' may alter its value [-Werror=conversion]
> /home/jsoncpp/src/lib_json/json_reader.cpp:1400:40: error: conversion to 'char' from 'int' may alter its value [-Werror=conversion]
> /home/jsoncpp/src/lib_json/json_reader.cpp:1402:42: error: conversion to 'char' from 'int' may alter its value [-Werror=conversion]
> /home/jsoncpp/src/lib_json/json_reader.cpp:1406:40: error: conversion to 'char' from 'int' may alter its value [-Werror=conversion]
> /home/jsoncpp/src/lib_json/json_reader.cpp:1408:42: error: conversion to 'char' from 'int' may alter its value [-Werror=conversion]
> /home/jsoncpp/src/lib_json/json_reader.cpp:1410:42: error: conversion to 'char' from 'int' may alter its value [-Werror=conversion]
> cc1plus: some warnings being treated as errors
> make[2]: *** [src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o] Error 1
> make[1]: *** [src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/all] Error 2
> make: *** [all] Error 2
> 

Is there something that I could do to prevent the Warnings to be treated as Errors?

**Comment by cdunn2001** [comment]
What O/S and version? What compiler and version? Other system details?

**Comment by LucasHMS** [comment]
OS: Debian-Wheezy (based on Linux Galileo 3.8.7)
Cmake: 2.8.9
Make: 3.81
g++: (Debian 4.7.2-5) 4.7.2
Python: 2.7.3
