### ISSUE TITLE
Attempt to access Json Value attribute throwing LogicError

### ISSUE THREAD

**Issue by biot023** [open-source-parsers/jsoncpp#475]
Hi -- I have this code:

```
string raw("{\"name\":\"ping\",\"data\":{\"uuid\":\"8bfa3123-a7fa-4feb-8761-ff39517063a7\"}}");
Json::Value root(raw);
cout << root << endl; // outputs: "{\"name\":\"ping\",\"data\":{\"uuid\":\"8bfa3123-a7fa-4feb-8761-ff39517063a7\"}}"
root.get("name", "unknown"); // throws the error
```

I *think* it should work. However, I get this error thrown:

> terminate called after throwing an instance of 'Json::LogicError'
>   what():  in Json::Value::find(key, end, found): requires objectValue or nullValue
> Aborted

I'm compiling with g++ 6.1.0

Could anybody please advise me on where I'm going wrong? I've been running around in circles with it for hours, now! :)
Thanks very much,
   Doug.

**Comment by cdunn2001** [comment]
You have to *parse* the string into a Json Value. Try `CharReaderBuilder`. Or simply create `std::istringstream` and extract into your `raw` Value.
* http://open-source-parsers.github.io/jsoncpp-docs/doxygen/index.html

**Comment by biot023** [comment]
Ah, brilliant -- that works, thankyou!
(Sorry it took so long to reply, I haven't been able to look at this project in nearly a month!)
Thanks again,
   Doug.
