### ISSUE TITLE
empty OBJECT parsed to empty ARRAY

### ISSUE THREAD

**Issue by JakSprats** [open-source-parsers/jsoncpp#476]
I am decoding the following string:

    {"merge_data":{"central_agent_versions" :{"1000000002" : "1000000002|1"},"gc_summary":{},"ether":{},"remove":false}}

		
and getting the following data-structure:
```js
{	"merge_data" : 
	{
		"central_agent_versions" : 
		{
			"1000000002" : "1000000002|1"
		},
		"ether" : [],
		"gc_summary" : [],
		"remove" : false
	}
}
```
The two OBJECTS ether and gc_summary are OBJECTs {} but are being decoded as ARRAYS []

I have only noticed this happening on empty OBJECTS. 

It is enough of a change to break any code that relies on these data-structures being objects (e.g. I am calling getMemberNames on them and getting SEGVs)

**Comment by cdunn2001** [comment]
You need to post your code, so we can reproduce this. Also, let us know the exact commit you are using. (E.g. `git rev-parse HEAD`.) Here is mine:
```cpp
#include <json/value.h>
#include <json/reader.h>
#include <json/writer.h>
#include <iostream>
#include <fstream>
using namespace std;

void foo() {
  ifstream fin("bad.js");
  Json::Value root;
  fin >> root;
  cout << root << "\n";
}
void bar() {
  ifstream fin("bad.js");
  Json::Value root;
  Json::CharReaderBuilder rbuilder;
  std::string errs;
  bool ok = Json::parseFromStream(rbuilder, fin, &root, &errs);
  cout << root << "\n";
}
int main() {
  foo();
  bar();
  return 0;
}
```
I see the same output in both cases. (`foo()` uses the old `Reader` and `bar()` uses the new `CharReader`.)
```js
{
	"merge_data" :
	{
		"central_agent_versions" :
		{
			"1000000002" : "1000000002|1"
		},
		"ether" : {},
		"gc_summary" : {},
		"remove" : false
	}
}
```

**Comment by JakSprats** [comment]
I have an old submodule of jsoncpp, this may have been fixed a while back

git rev-parse HEAD
5256551b0307d3e85f453faf1b1822b1d859f949

I compiled and got this

FOO: {
        "merge_data" :
        {
                "central_agent_versions" :
                {
                        "1000000002" : "1000000002|1"
                },
                "ether" : [],
                "gc_summary" : [],
                "remove" : false
        }
}

BAR: {
        "merge_data" :
        {
                "central_agent_versions" :
                {
                        "1000000002" : "1000000002|1"
                },
                "ether" : [],
                "gc_summary" : [],
                "remove" : false
        }
}

So the error is probably in my old version. I will upgrade and if everything is fixed, then sorry I wasted your time, if not I will post again.

**Comment by JakSprats** [comment]
Confirming this has been fixed with upgrade to latest code

Sorry for the invalid (aka: old) bug

**Comment by cdunn2001** [comment]
Interesting. No problem. Best of luck to you!

**Comment by JakSprats** [comment]
This "bug" probably never existed.

Needless to say I have a large codebase, passing JSON between C++ and Lua and I was getting this problem.

I have recently found this is a real bug in a Lua module I am using: 
http://regex.info/blog/lua/json so it was probably never in jsoncpp

Anyways, thanks for the quick response and great repo :)
