### ISSUE TITLE
Issue in parsing invalid Json File

### ISSUE THREAD

**Issue by DiptiGupta** [open-source-parsers/jsoncpp#480]
Hi

I am parsing following file 
```js
{
	"path": "/cc",
	"requestType": "GET",
	"parameters": [10,20]
}, // COMMA
{
	"path": "/cc",
	"requestType": "GET",
	"parameters": [10,20]
}
```
During parsing , it is not giving parsing error. Parser is treating this file as a valid JSON file. 
Kindly look into the issue

**Comment by cdunn2001** [comment]
It finds a legal JSON value and stops parsing, so it never sees the comma and next value.

If you want this to fail, you need to use the `CharReaderBuilder` and to set `"failIfExtra"` to `true`.
* http://open-source-parsers.github.io/jsoncpp-docs/doxygen/class_json_1_1_char_reader_builder.html#ac69b7911ad64c171c51ebaf2ea26d958
