### ISSUE TITLE
 Issue linking amalgamated jsoncpp. No assignment operator.

### ISSUE THREAD

**Issue by technotopia** [open-source-parsers/jsoncpp#484]
Hello, 
I have a problem with amalgamated jsoncpp.
I tried compiling it as static lib or adding amalgamted jsoncpp.cpp to the sources of my project, result looks same:

 undefined reference to `Json::Value::operator=(Json::Value const&)'

 My code looks like this:

 ...
 #include <jsoncpp/json/json.h>
 ...
 Json::Value r;
 r["key"] = value;

 value is just integer. This works perfectly when I use jsoncpp from package.
 In json.h I see this assignment operator:

 Value& operator=(Value other);
 
 But nothing like
 Value& operator=(const Value& other);
 
 Am I doing it wrong?

**Comment by technotopia** [comment]
Problem was with wrong headers (one of the projects included headers from installed jsoncpp).

**Comment by DMancilla-RMS** [comment]
@technotopia how did you manage to solve it? what did you exactly changed?
