### ISSUE TITLE
float to double conversion warnings

### ISSUE THREAD

**Issue by Gachapen** [open-source-parsers/jsoncpp#485]
With Clang 3.8.0 and the `-Wdouble-promotion` warning, a lot of errors are produced in user code because of implicit conversions from float to double when getting or storing a float value in `Json::Value`. See below for examples.

This is caused by `Json::Value` missing a constructor for float, and could easily be fixed by adding this (I could submit a PR if you'd like). It should also be fixed by merging #66.

```
warning: implicit conversion increases floating-point precision: 'float' to 'double' [-Wdouble-promotion]
 float value = componentJsonObject.get("x", 1.0f).asFloat();
                                                      ^~~~
```
```
warning: implicit conversion increases floating-point precision: 'float' to 'double' [-Wdouble-promotion]
 a["x"] = 1.0f;
```

**Comment by cdunn2001** [comment]
But #66 fails our tests. If you can fix the tests too, submit a PR and we'll probably merge it. Well, if it's not binary compatible, we might need a major version bump. So I'm not sure about releasing it immediately, but we can at least start a branch for the next major version.

**Comment by Gachapen** [comment]
Sorry for getting back so late. I could try to fix #66, but as you say, it's not binary compatible. But if I understand correctly, overloading the constructor is binary compatible (am I right?). In that case, we could add an overload for `float`, and others (I've had issues with `std::size_t` as well). What do you think?

**Comment by cdunn2001** [comment]
I think the *right* answer is to template the integer and float types, with over-rideable coverters. But then, there are so many Json libraries already.

Is there a problem if you actually use `double`?

**Comment by Gachapen** [comment]
I thought about it, and I see no problem with double promotion, so I ended up with disabling the warning.

The `std::size_t` problem is a bigger issue, though, as it is a compile error. I fix this by casting it to a compatible type, but it shouldn't be necessary. But that's another issue, so I'll close this one. I'll likely fix the template version in my own fork and make a PR so you can potentially merge it in a new major version. Sounds OK?

**Comment by cdunn2001** [comment]
Yes, that sounds like a good idea. I'll watch for the PR...
