### ISSUE TITLE
asEnum method

### ISSUE THREAD

**Issue by dan-ryan** [open-source-parsers/jsoncpp#487]
Can we get this helpful method added? 
`json[KEY].asEnum<EnumClass>();`

It's less verbose compared to:
`static_cast<EnumClass>(json[KEY].asInt())`

**Comment by cdunn2001** [comment]
Seems reasonable, assuming it compiles everywhere. Submit a PR, and be aware that if any fairly recent compilers barf, we'll have to revert or hide (conditionally compile) that method.

On the other hand, why not just create a global function yourself? I think a repo of such helpers would be ... helpful.

    asEnum<EnumClass>(json[KEY])

**Comment by zammbi** [comment]
I was thinking to put it in our JsonHelper class, but thought this would be cleaner and better supported in the library itself. 
I wouldn't know where to start for a PR. But I'm guessing the code be something like:
```
template<typename T, typename std::enable_if<std::is_enum<T>::value>::type* = nullptr>
	T toEnum() {
		return static_cast <T>(asInt());
	}
```

**Comment by BillyDonahue** [comment]
Bjarne said that the static_cast and reinterpret_cast are deliberately ugly in C++.
So you have to think when you see them. I think that holds here too.
Yes you have to write an application-level static_cast to get an enum out of a json numeric, but really I think that's probably for the best. We should be conservative about adding members to Json::Value which has an ABI compatibility concern.

**Comment by baylesj** [comment]
Agreed, thanks for taking a look. Implementing the patch has convinced me this is a bad idea.

Less verbosity != better, often times it is worse if it hides complexity that shouldn't be hidden.
