### ISSUE TITLE
Using amalgamated version of jsoncpp

### ISSUE THREAD

**Issue by ajaytiwari9** [open-source-parsers/jsoncpp#494]
I am using amalgamated version of jsoncpp library.
Python program generates three files :  1. json.h   2. json-forwards.h  3. jsoncpp.cpp

My questions,
1. In amalgamated json.h file,  first line says "/// It is intended to be used with #include "json/json.h"
what is reason for this recommendation? why can't we use as  #include "json.h" ?
2. what is the purpose of json-forwards.h file, can i leave this file and use only json.h & json.cpp files?I understand, **json-forwards.h: header that provides forward declaration of all JsonCpp types**.but I don't know They are mandatory?
As my program compiles successfully with only json.h & json.cpp.

I am using Visual Studio 2010 to compile program.
Thanks!

**Comment by cdunn2001** [comment]
I don't use the amalgamated headers myself, but I think you've got the right idea. `json-forwards` is only for building your own libraries, to be linked with jsoncpp later.

As for `json/json.h`, our cpp files include that way, slightly reducing the odds of a conflict with another json library. I'm not sure there's a simple way to avoid that. **JsonCpp** is meant to be installed as a system library, so we need some uniqueness in the name. Do you have a better way?

**Comment by nicmcd** [comment]
I have a project ([](https://github.com/nicmcd/libsettings)) that uses jsoncpp. I simply generate the amalgamated source and only use the json.h and jsoncpp.cpp (although I renamed jsoncpp.cpp to json.cc). Everything works great.
