### ISSUE TITLE
Double Serializing Objects

### ISSUE THREAD

**Issue by shockdot** [open-source-parsers/jsoncpp#495]
When I double serialize a piece of data into a JSON string, using JSONCPP, it ends up adding alot of \ characters.

For example...

Say I a collection of objects that I want to serialize into a json string. I would serialize each individual json string into an array and then serialize that array into a json string... This would produce extra \ characters, and each time I add an additional serialization level it adds even more to the previously serialized set.

**Comment by cdunn2001** [comment]
Not sure. Example?

Note: Here is the json spec: http://json.org/

**Comment by shockdot** [comment]
So let's say I have an object.. Like so

```
class SomeObj
{
public:
SomeObj()
{
id=1;
test="New String";
}

int id;
std::string test;
}
```

I then have a vector of these objects...


```
std::vector<SomeObj*> objs;
for(int i = 0; i < 99; i++)
{
objs.pushback(new SomeObj());
}
```


Now I want serialize this entire vector into json string so the way I do this in massive objects in my code is I start be serializing the inner most element... so...
```

std::vector<std::string> jsonstrings;
for(int i = 0; i < objs.size();i++)
{
Json::value json;
json["id"] = objs[i].id;
json["test"] = objs[i].test;

Json::FastWriter writer;
jsonstrings.push_back(writer.write(json));
}
```


Now we need to serialize the entire vector of serialized strings....

```
Json::value json_collection;
for(int i = 0; i < jsonstrings.size();i++)
{
json_collection[std::to_string(i)] = jsonstrings[i];
}
```

Finally, convert everything to a JSON string...
```
Json::FastWriter writer;
std::string result = writer.write(json_collection);
```

The result json string now has extra \\ symbols... Which I'm wondering why. I sometimes serialize up to 4-5 times which makes these symbols appear CONSTANTLY and in large numbers.

**Comment by cdunn2001** [comment]
I see. There are very good JSON serialization libraries. In fact, some (*e.g.* **Cereal**?) actually use **JsonCpp** under the covers. But **JsonCpp** is interested only in converting between some hand-picked C++ datatype hierarchies (which I wish were templated, but for now are hard-coded) and a JSON UTF8 string.

**Comment by shockdot** [comment]
I think you misunderstood me... The datatypes I'm converting are basic data types (int, string, etc). I literally insert each element of a class (basic elements) into the JSON string... The issue being that once a JSON String is serialized within another JSON object (for a second, third, fourth, etc time) the escape characters \ start to multiply in numbers.  Everything works as expected except this one part which is tied directly into strings...


For example, if a JSON string had a \n in the string. This now becomes \\n, and then \\\\n and then \\\\\\\\n.... Same with quotes \" becomes \\", then \\\\", then \\\\\\\\", etc...

**Comment by cdunn2001** [comment]
But that's correct behavior for JSON. If you encode a linefeed in JSON, the UTF8 string is 2 characters, `\n`. If you encode that 2-character string as JSON, then the encoded version of *that* string will escape the backslash, `\\n`, a 3-character string. I think you're confusing serialization with data-representation.
