### ISSUE TITLE
please migrate to new ABI checker

### ISSUE THREAD

**Issue by LocutusOfBorg** [open-source-parsers/jsoncpp#499]
Hi, the old ABI checker [1] seems to have been moved into a new location [2]
[1] http://abi-laboratory.pro/tracker/
[2] http://upstream.rosalinux.ru/versions/jsoncpp.html

can you please migrate there?

**Comment by lvc** [comment]
Hello,

Done: http://abi-laboratory.pro/tracker/timeline/jsoncpp/

Thank you.

**Comment by LocutusOfBorg** [comment]
thanks!
