### ISSUE TITLE
Writer::write() adds a newline at the end of its output

### ISSUE THREAD

**Issue by stijnfrishert** [open-source-parsers/jsoncpp#501]
FastWriter and StyledWriter add a newline to the output of their write function. Why? I would think it best to leave it up to the user whether they'd like to print a newline or not.

    FastWriter writer;
    cout << writer(json) << endl;

I can see how this might make sense for StyledWriter, but I use FastWriter to generate data to be sent over UDP, and it's cumbersome to `pop_back()` the returning string every time so that I don't send that extra byte over.

Is this is a conscious design decision? If so: why? If not, could it be changed?

I am using `1.7.4`, pulled from Homebrew.

**Comment by cdunn2001** [comment]
I agree with you, but this decision was taking over a decade ago. We cannot change the legacy behavior.

However, you are generally better off using the newer and more configurable `StreamWriterBuilder`. We could add a setting to suppress the extra newline. Would you switch to the builder in that case?

**Comment by cdunn2001** [comment]
Wait, I just dumped via `cout << json` and did not get an extra newline. Maybe the problem is only with the old `FastWriter/StyledWriter`, which is deprecated. `operator<<()` uses `StreamWriterBuilder`.

**Comment by stijnfrishert** [comment]
Ah! Yes, I build the `FastWriter` myself (because I need the json as a string, not in a stream), but I guess I could use `StreamWriterBuilder`, or stream it to a `stringstream`.

Thanks! I guess the issue is rightfully closed.

**Comment by cdunn2001** [comment]
Oh! That's funny because you are the victim of our fervent wish to avoid breaking backward compatibility -- with your own code! 😺 Of course, you probably wrote FastWriter to match the older Styled Writer.

**Comment by stijnfrishert** [comment]
Oh, no I didn't _write_ FastWriter myself, I _constructed_ it myself as an object in c++, instead of using the `StreamWriterBuilder`. That's what I meant ;)
