### ISSUE TITLE
Json::Reader parse large unsigned number as double

### ISSUE THREAD

**Issue by sekkwai** [open-source-parsers/jsoncpp#503]
First, I am sorry that I cannot provide the version number of the "jsoncpp" I using.
I guess it is 0.y.z.

It is cross-compiled in PPC environment.

The library is good. But I just found a strange bug and report it here.

I use a Json::Reader to parse a string which contain very large number. Then I cannot get the large number as unsigned long. The value become double. 

**The not working large number are below**

    4294967290 - 4294967295

**Code:**

```cpp
Json::Value root;
Json::Reader reader;
bool parseResult;

//        string jsonContent = "{     \"header\" : {    \"value\": 123    }}";


//        string jsonContent = "{     \"header\" : {    \"value\": 4294967288    }}";//normal
//        string jsonContent = "{     \"header\" : {    \"value\": 4294967289    }}";//normal
//        string jsonContent = "{     \"header\" : {    \"value\": 4294967290    }}";//wrong
string jsonContent = "{     \"header\" : {    \"value\": 4294967291    }}";//wrong
//        string jsonContent = "{     \"header\" : {    \"value\": 4294967292    }}";//wrong
//        string jsonContent = "{     \"header\" : {    \"value\": 4294967293    }}";//wrong
//        string jsonContent = "{     \"header\" : {    \"value\": 4294967294    }}";//wrong
//        string jsonContent = "{     \"header\" : {    \"value\": 4294967295    }}";//wrong

parseResult = reader.parse(jsonContent, root);

printf("parseResult = %d\n",parseResult);

printf("root.isNull() = %d\n",root.isNull());
printf("isNull() = %d\n",root["header"]["value"].isNull());
printf("isUInt() = %d\n",root["header"]["value"].isUInt());
printf("isNumeric() = %d\n",root["header"]["value"].isNumeric());
printf("isInt() = %d\n",root["header"]["value"].isInt());
printf("isDouble() = %d\n",root["header"]["value"].isDouble());
```

I hope that this can be fixed because it will affect my project in the future.

**Comment by cdunn2001** [comment]
```
parseResult = 1
root.isNull() = 0
isNull() = 0
isUInt() = 1
isNumeric() = 1
isInt() = 0
isDouble() = 1
```

**Comment by cdunn2001** [comment]
```cpp
cout << root;
```
```
{
	"header" :
	{
		"value" : 4294967291
	}
}
```
The round-trip works too (in that it is still shown as int, not float, although we don't really guarantee that).

**Comment by sekkwai** [comment]
Hi cdunn2001,

Thank you for your reply.

I think my jsoncpp is old version because I can't find the "asUInt64()" function.
So I will update the source code and try it again later. (not easy job in my environment, need some time to configure and cross-compile it).

I will update this thread after that.

**P.S.**
Which file can find the version number of the jsoncpp ? (I only have the .h and .cpp files in my source code, my colleague remove other files.)

**Comment by cdunn2001** [comment]
If you don't see a version number, you have *very* old code -- probably 0.5.z from sourceforge. It appears in 3 places, including in the CMakeLists.txt and in a header.
