### ISSUE TITLE
Liinking jsoncpp using ExternalProject_Add

### ISSUE THREAD

**Issue by vdsilva** [open-source-parsers/jsoncpp#505]
Dear developers/community,

I'm trying to install jsoncpp locally within the build directory using CMake's ExternalProject_Add feature and then link to it. The linker does not find the statically compiled library and I have tried to set all the variables I could to point the linker to the right location and failed. This is a minimal example of the situation.

Any suggestions for what I'm doing wrong?

[cmake_json_build.zip](https://github.com/open-source-parsers/jsoncpp/files/379069/cmake_json_build.zip)

**Comment by cdunn2001** [comment]
Hmm. I'd suggest asking in a **cmake** forum, but I'll leave this open in case anybody can help you here. I am not a cmake expert. (Actually, I hate cmake, but it gives us Windows support.)

**Comment by vdsilva** [comment]
Thanks for the response. I fixed the two issues: To the ExternalProject_Add configuration, I had to explicitly add.

```
CMAKE_ARGS        "-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}"
```

To resolve the linker issues, I added the following lines, with the variable `${jsoncpp_lib_dir}` set to the location where the static library would be built.

```
find_library(JSONCPP_LIBRARY jsoncpp HINTS ${jsoncpp_lib_dir})
include_directories(${jsoncpp_src_dir})
```
