### ISSUE TITLE
NullSingleton Memory leak

### ISSUE THREAD

**Issue by BenkovicSamuel** [open-source-parsers/jsoncpp#507]
Hi i am worrying about leak in this path of code. Visual Leak Detector give me warning there. 

```
// static
Value const& Value::nullSingleton()
{
 static Value const* nullStatic = new Value;
 return *nullStatic;
}
```

**Comment by BenkovicSamuel** [comment]
https://github.com/open-source-parsers/jsoncpp/commit/b299d3581f4dc670734f1fe1a34fce1282337802
nvm it was fixed.... sorry

**Comment by Naegolus** [comment]
Saw it too. Thx for the fix and this awesome library.

Used valgrind to see the mem leak:
$ valgrind --leak-check=full --show-leak-kinds=all ./myapp

==24984== 
==24984== HEAP SUMMARY:
==24984==     in use at exit: 40 bytes in 1 blocks
==24984==   total heap usage: 425,679 allocs, 425,678 frees, 72,162,878 bytes allocated
==24984== 
==24984== 40 bytes in 1 blocks are still reachable in loss record 1 of 1
==24984==    at 0x4C2C21F: operator new(unsigned long) (vg_replace_malloc.c:334)
==24984==    by 0x50D4439: Json::Value::nullSingleton() (in /usr/lib/x86_64-linux-gnu/libjsoncpp.so.1.7.4)
==24984==    by 0x50C6BF8: ??? (in /usr/lib/x86_64-linux-gnu/libjsoncpp.so.1.7.4)
==24984==    by 0x400F859: call_init.part.0 (dl-init.c:72)
==24984==    by 0x400F96A: call_init (dl-init.c:30)
==24984==    by 0x400F96A: _dl_init (dl-init.c:120)
==24984==    by 0x4000C59: ??? (in /lib/x86_64-linux-gnu/ld-2.24.so)
==24984==    by 0x1: ???
==24984==    by 0xFFF0001B2: ???
==24984==    by 0xFFF0001C3: ???
==24984== 
==24984== LEAK SUMMARY:
==24984==    definitely lost: 0 bytes in 0 blocks
==24984==    indirectly lost: 0 bytes in 0 blocks
==24984==      possibly lost: 0 bytes in 0 blocks
==24984==    still reachable: 40 bytes in 1 blocks
==24984==         suppressed: 0 bytes in 0 blocks
==24984== 
==24984== For counts of detected and suppressed errors, rerun with: -v
==24984== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
