### ISSUE TITLE
Problem when parsing non valid json string

### ISSUE THREAD

**Issue by Scouser87** [open-source-parsers/jsoncpp#510]
I have this code:

```
   Json::Reader reader;
   Json::Value root;
   std::string str = "\"error\":\"This user can not connect at the moment.\"}";
   bool result = reader.parse(str, root);
```

The problem is **reader.parse** returns **true** in this case, but a lot of online json validators consider this is not valid json.

**Comment by cdunn2001** [comment]
The old Reader will consume `"error"` and stop. That is valid JSON, and the presence of extra characters is not considered a bug. We must maintain backward-compatibility for the older `Reader`. Try the new `CharReadBuilder`:
* http://open-source-parsers.github.io/jsoncpp-docs/doxygen/index.html

You would need to set the `strictRoot` option:
* http://open-source-parsers.github.io/jsoncpp-docs/doxygen/class_json_1_1_char_reader_builder.html#ac69b7911ad64c171c51ebaf2ea26d958
