### ISSUE TITLE
Parsing problem with new reader

### ISSUE THREAD

**Issue by cmaeckel** [open-source-parsers/jsoncpp#511]
The parser is accepting "{}foobar" as valid JSON. The code fragment is:

	Json::CharReaderBuilder reader;
	reader.strictMode( &reader.settings_ );
	std::istringstream chrStream( "{}foobar" );
	Json::Value root;
	std::string errs;
	bool result( Json::parseFromStream( reader, chrStream, &root, &errs ) );
	std::cout << "Result " << result << " errs " << errs << std::endl;

And result comes back as true in this case and writing out the resulting JSON returns "{}". Or am I doing something wrong?

**Comment by cdunn2001** [comment]
* https://open-source-parsers.github.io/jsoncpp-docs/doxygen/class_json_1_1_char_reader_builder.html

Well, we could add a setting to strict-mode. How about `noTrailing`? If there are any unconsumed characters (including whitespace), then we fail. We would accept leading whitespace because that's harder to test.

**Comment by cmaeckel** [comment]
For my purposes leading or trailing white space is neither good or bad. So a noTrailing option would work great for me.

**Comment by cmaeckel** [comment]
This changes works well for me since I don't mind trailing white space.

```
--- /Before/json_reader.cpp	2016-08-08 16:12:28.000 -0500
+++ /After/json_reader.cpp	2016-08-08 16:13:32.000 -0500
@@ -1068,7 +1068,7 @@
   Token token;
   skipCommentTokens(token);
   if (features_.failIfExtra_) {
-    if (token.type_ != tokenError && token.type_ != tokenEndOfStream) {
+    if ((features_.strictRoot_ || token.type_ != tokenError) && token.type_ != tokenEndOfStream) {
       addError("Extra non-whitespace after JSON value.", token);
       return false;
     }
```

**Comment by cdunn2001** [comment]
Ok. I doubt this will break anyone as you've written it, but if it does, then we will have to use a new setting for this.
