### ISSUE TITLE
Please use `#if __cplusplus < 201103L` to check for `override` support

### ISSUE THREAD

**Issue by Rogier-5** [open-source-parsers/jsoncpp#515]
Currently, jsoncpp uses the following code to check for `override` support:
```c++
#if defined(_MSC_VER) && _MSC_VER <= 1600 // MSVC <= 2010
# define JSONCPP_OVERRIDE
#else
# define JSONCPP_OVERRIDE override
#endif // MSVC <= 2010
```
However, this is a c++11 feature, so please use:
```
#if __cplusplus < 201103L
# define JSONCPP_OVERRIDE
#else
# define JSONCPP_OVERRIDE override
#endif // __cplusplus < 201103L
```
instead.

**Comment by Rogier-5** [comment]
For completeness: this causes problems with at least gcc 5.4 and clang 3.8 and earlier (debian; using default settings). Gcc only uses c++11 by default [since version 6.1](https://gcc.gnu.org/projects/cxx-status.html#cxx98)

**Comment by cdunn2001** [comment]
Are you looking at something on the `0.y.z` branch? I see something different on master:
* https://github.com/open-source-parsers/jsoncpp/blob/master/include/json/config.h#L80
```cpp
#if __cplusplus >= 201103L
# define JSONCPP_OVERRIDE override
#elif defined(_MSC_VER) && _MSC_VER > 1600
# define JSONCPP_OVERRIDE override
#else
# define JSONCPP_OVERRIDE
#endif
```
Could you clarify what problem that causes and where?

**Comment by Rogier-5** [comment]
Ah...
My apologies for forgetting to check master first. The issue was fixed a few months ago (commit ba6fa48d), but debian still has version 1.7.2...

**Comment by cdunn2001** [comment]
No problem! And we probably need to tag a new release, which Debian might pick up.

**Comment by cinemast** [comment]
I just packaged 1.7.4 today.
