### ISSUE TITLE
there is a bug?

### ISSUE THREAD

**Issue by vrvmjd** [open-source-parsers/jsoncpp#520]
```cpp
std::string szReply = "this is a test";
Json::Value root;
Json::Reader reader;
if(reader.parse(szReply, root))
{
    // szReply is not json string, but it still step in.
}
```

**Comment by cdunn2001** [comment]
First, `"this"` is in fact valid JSON.

Second, you should be using the newer `CharReaderBuilder`, which on the lastest`master` will actually fail on your example in *strict* mode.
