### ISSUE TITLE
Inadequate behavior during invalid JSON parsing

### ISSUE THREAD

**Issue by grigorryev** [open-source-parsers/jsoncpp#522]
`Json::Reader::parse()` returns `true` after parsing file containing the only line:

`09432f8bf1bfa076e64c2588fbedb3ea`

as if it was valid JSON. Although, it fails later with `in Json::Value::getMemberNames(), value must be objectValue` exception after `Value::getMemberNames()` method call.

**Comment by cdunn2001** [comment]
First, `Reader` is old and hard to modify with backwards-compatibility, so I suggest `CharReaderBuiler`.

Second, try the tip of `master`, and use "strict" mode. I think you'll be happy.

The reason your example passes is that the initial digits *are* valid JSON. By default, we parse until we can't.
