### ISSUE TITLE
Android NDK fails because of locale additions

### ISSUE THREAD

**Issue by tlein** [open-source-parsers/jsoncpp#524]
This recent [commit](https://github.com/open-source-parsers/jsoncpp/commit/094a7d856409350ced93dab272b8091d19977298) causes jsoncpp to fail to build for Android because there is no support for locale C libraries in Android. (see https://code.google.com/p/android/issues/detail?id=57313)

Not sure what the best fix is, simply patched out the change for my temporary fix.

**Comment by cdunn2001** [comment]
Fixed by @gidapataki  in #523.
