### ISSUE TITLE
assignment problem

### ISSUE THREAD

**Issue by LADSoft** [open-source-parsers/jsoncpp#532]
I used to do something like this:
```cpp
Json::Value root;
root["description"] = "this is some text";
```
That doesn't currently work because of a missing assignment operator.   The closest thing to an assignment operator you have is:
```cpp
Value &Value::operator=(Value other);
```
but the compiler I'm using wants
```cpp
Value &Value::operator=(const Value &other);
```
I'm using VS2005 if that makes a difference.

**Comment by cdunn2001** [comment]
(Been traveling.)

Hmmm. VS2005 is quite old. Maybe you could try the tip of the `0.y.z` branch.

**Comment by thelema** [comment]
This was broken for you by 45cd9490cd261da31cef84a44d2c587be7e26e99, which switched to "copy and swap" idiom that replaces the `operator=(const Value&)` with an `operator=(Value)`.  Commit 8996c377aad3a333a9bada1cfe7d5924e71a3269 restored the `operator=(const Value&)` to add move assignment, but broke the copy-assignment implementation as it forgot to make the copy.  This was put back to "copy and swap" in 6a15ca64429e1ce6d2fff915ff14ce1c2a96975c which also removed the move assignment implementation.

**Comment by cdunn2001** [comment]
https://github.com/open-source-parsers/jsoncpp/pull/37

The simplest work-around for the old compiler is to wrap the `char*` in `Json::Value()`.
```cpp
root["description"] = Json::Value("this is some text");
```
 But the smartest thing is to use old versions of software with old compilers. If you cannot upgrade your compiler, you should not upgrade your libraries.

We actually have a branch which is meant to support older compilers: `0.y.z`. We don't update that much, but I expect it would work for you.
