### ISSUE TITLE
stdint.h Is Not Included

### ISSUE THREAD

**Issue by yiqiju** [open-source-parsers/jsoncpp#537]
On 1.7.6, looks like config.h trying to use int64_t but does not include stdint.h on Linux.

Details:
include/json/config.h:155 'int64_t' does not name a type

**Comment by yiqiju** [comment]
Pull request  #538 is submitted

**Comment by cdunn2001** [comment]
I think we would use `#include <cstdint>` since we are C++11 compatible. That might break an old VisualStudio version, but that's probably ok. See #509.

**Comment by yiqiju** [comment]
I suggest to keep it as-is since it builds on both old and newer compilers.

**Comment by cdunn2001** [comment]
Well, we have `stdlib.h` and `stddef.h`, so ok. Merging...
