### ISSUE TITLE
SO versioning

### ISSUE THREAD

**Issue by abucodonosor** [open-source-parsers/jsoncpp#540]
Hi ,

1.7.7 bumps soname for so.1 to so.11 ? Why this and when you need to bump why not to so.2 ?

Also why do you guys need to bump it at all in a minor release ?

Best regrads

**Comment by cinemast** [comment]
The version bump was required due to incompatible changes to the ABI. See here: https://abi-laboratory.pro/tracker/timeline/jsoncpp/

Although I would have also prefered SOVERSION 2 instead of 11.

**Comment by abucodonosor** [comment]
Well the problem is there : 

https://github.com/open-source-parsers/jsoncpp/blob/master/CMakeLists.txt#L77

is set to 11 .. maybe do a new release and bump to .2

**Comment by cdunn2001** [comment]
I wanted it to be obviously unrelated to the version number. I hope it isn't really a problem for anyone.

**Comment by cinemast** [comment]
I don't think that's a good idea. It will diverge from the version number anyway soon. It obviously raises more questions than it answers.

**Comment by cdunn2001** [comment]
I tried very hard to keep the soversion the same as the major version for a long time. A user fix slipped in that happened to be a binary-incompatible change on some platforms. That's life.

This is a big change in my mind. It means we don't have to worry about binary-compatibility at all anymore. Just bump the soversion. I'm surprised that doesn't bother anyone else, but apparently that is how most projects do it these days.
