### ISSUE TITLE
Ideology: multiple operator[<integer type>]. really?

### ISSUE THREAD

**Issue by heretic13** [open-source-parsers/jsoncpp#541]
Please explain me.
Why is it needed?

`
Value& operator[](ArrayIndex index);
Value& operator[](int index);
`

Did you know that now compilers have difficulty with the selection of the proper function when parsing [size_t]? (clang compiler).

Why should I spend the time that the compiler could he do it?

**Comment by cdunn2001** [comment]
It's hard to remove that function now, and I'm not sure what's best. But it's definitely easy to work around.

    mydict[ArrayIndex(i)]
