### ISSUE TITLE
Writer generated invalid json format.

### ISSUE THREAD

**Issue by Physicist137** [open-source-parsers/jsoncpp#544]
This simple code:

```
int main() {
    Json::Value root;
    root["x"] = 8521668621447694.0;
    root["y"] = 3023968833286199.0;

    Json::StyledWriter writer;
    std::string str = writer.write(root);
    std::cout << str << std::endl;
}
```

Generates this json:

```
{
   "x" : 8521668621447694.,
   "y" : 3023968833286199.
}
```

Which is clearly invalid. Well.. I don't know my version of jsoncpp. I don't know if you guys already fixed it sometime ago. I even tried to compile it in the most up to date version of jsoncpp, but due to several compilation problems, I gave up, and decided to post this bug regardless.

This bug was destroying all my code, and took me over 3hrs to find! You might want to take a look...

**Comment by cdunn2001** [comment]
Yeah, that needs a trailing `.0`. If you can find a simple fix for StyledWriter, we'll merge it. But note that `StyledWriter` is deprecated. Please try `StreamWriterBuilder`.

**Comment by baylesj** [comment]
I believe we checked in a fix for the trailing zeroes, so this issue should be closed. Feel free to reopen if it is still an issue with StreamWriter in new versions of JsonCpp.
