### ISSUE TITLE
Proper JSON parsing

### ISSUE THREAD

**Issue by cdunn2001** [open-source-parsers/jsoncpp#545]
I see a lot of complaints here, but the truth is that almost nobody parses JSON properly.
- http://seriot.ch/parsing_json.html

Parsing should be separate from interpretation. A separate layer should translate strings into values (ints, floats, other datatypes) at the user's discretion.

I think the right thing is to start with the wonderfully simple and efficient **gason** library, and add a layer on top of that for usability.

**Comment by baylesj** [comment]
Closing this issue--looks like no action is required for resolution.
