### ISSUE TITLE
Ensure that doubles that happen to be exact integers render as doubles in output

### ISSUE THREAD

**Issue by BrendanDrewDaqri** [open-source-parsers/jsoncpp#546]
E.g:

```c++
Json::Value x;
x["foo"] = 1.0; // note: exactly 1.0

// get a writer called w
w.write(out, x)
```

should produce something along the lines of: 

`
{
  "foo" : 1.0
}
`

instead of the behavior I observer, which is:

`
{
  "foo" : 1
}
`

The specific use case I'm trying to solve is generating documents for consumption by logstash, which complains bitterly about fields not having uniform types. It's fair to say that logstash is being brain dead in this case (it is), but I think adding support for this via a builder shouldn't be hard. I'll take a crack at a draft.

**Comment by cdunn2001** [comment]
Interesting. Thanks!

**Comment by nicmcd** [comment]
I often see very similar but backwards issues. Sometimes I specify a JSON file using something like:

`{ "foo" : 0.9 }`

But when I print it out I see:

`{ "foo" : 0.899999999 }`

Do you know why this happens? Do you consider this a problem?

**Comment by BrendanDrewDaqri** [comment]
@nicmcd 

Short answer: 0.9 isn't exactly representable as a floating point quantity.
