### ISSUE TITLE
Make indent character and size configurable

### ISSUE THREAD

**Issue by strahlc** [open-source-parsers/jsoncpp#558]
It would be nice to have the option to customize the indentation character and the indentation size.

This could be done by adding default parameter to `value::toStyledString` and `StyledWriter::StyledWriter`:

``` c++
JSONCPP_STRING toStyledString(const JSONCPP_STRING &indentCharacter=" ", size_t indentSize=3) const;
```
``` c++
StyledWriter::StyledWriter(const JSONCPP_STRING &indentCharacter=" ", size_t indentSize=3);
```

**Comment by cdunn2001** [comment]
Use `StreamWriterBuilder`. See docs on the `indentation` field.
