### ISSUE TITLE
Use GNUInstallDirs instead of defining own variables

### ISSUE THREAD

**Issue by SoapGentoo** [open-source-parsers/jsoncpp#560]
Dear JsonCpp devs,
in Gentoo we like to standardise on certain features. Autoconf+Automake can make things a lot easier for us, as automake provides a number of standard paths that can be changed. While you have a similiar scheme for your CMake, none of that is standardised. Would you consider replacing your custom variables with the `GNUInstallDirs` (https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html), provided with CMake? This provides more targets and is more idiomatic and makes it easier for downstream users to use the same conventions across packages, instead of packages reinventing this (convention over configuration). This would simplify a lot of things for us.

If you would be willing to accept such a change, I will gladly provide a Pull Request.

**Comment by cdunn2001** [comment]
Yes, we welcome contributions!

**Comment by SoapGentoo** [comment]
@cdunn2001 Thanks for the cooperative atmosphere! :smile:
