### ISSUE TITLE
Stop Alphabetical Sorting?

### ISSUE THREAD

**Issue by samsonsite1** [open-source-parsers/jsoncpp#561]
Hello,
I noticed the JSON writer is sorting my JSON data alphabetically when it writes it out.
How can I stop this from happening?

I am reading in a JSON file and then writing it out again.

Programmically, sure it doesn't matter, but I would like to maintain the original order, as certain items are listed first or grouped together to improve readability.

Sorting them alphabetically destroys readability.  The file is very hard to read now.

**Comment by cdunn2001** [comment]
We could allow an optional order-preserving dictionary, but you might be better off with a different library altogether.

**Comment by jimfred** [comment]
What about using .append() to append a key _and_ value e.g.,
```
Json::Value root(Json::objectValue);
root.append("Foo", Json::Value(mFoo)); 
root.append("Bar", Json::Value(mBar)); 
```

or insert before a specific index...
`root[0].insert("Zoo", Json::Value(mZoo));  // Insert Zoo before Foo`

**Comment by cdunn2001** [comment]
I don't see how we could make that work. And a JSON "object" itself is not ordered. If you want to store order, include a list.
