### ISSUE TITLE
Can cmake minimum version be reverted to 2.8.x?

### ISSUE THREAD

**Issue by paulobrizolara** [open-source-parsers/jsoncpp#564]
I was testing the new release 1.8.0.
Because i don't have cmake >=3.1 installed (i am using 2.8.12 version),
i changed the minimum version in cmake file back to (2.8.5) and it builds fine (all tests passed).

I am not experienced with cmake, so is there another hidden dependency that i don't saw.

Since the version changed on pull-request #562, maybe @SoapGentoo can help on this.

Thanks!

**Comment by SoapGentoo** [comment]
@paulobrizolara it only works **implicitly**. The main reason is that the `SET(CMAKE_CXX_STANDARD 11)` thingies work properly only in CMake 3.1 and above. It only works for you, because the JsonCpp codebase doesn't actually use any C++11 features yet (I can confirm that building it in C++98 mode works fine). While I understand your hardship (probably on an old RHEL or Ubuntu LTS), I am still opposed to this. Setting the C++ variant via the current mechanisms is more preferable than randomly adding `-std=c++11` to `CXXFLAGS` and hoping that it works.

**Comment by cdunn2001** [comment]
I agree with @SoapGentoo. You can either clone/branch and drop `11`, or use a previous release. Both seem like reasonable solutions.

There is a lot of interest in existing Issues for C++11 features, so I'd rather not restrict that. Sorry for any problems this has caused you.

**Comment by paulobrizolara** [comment]
Hum... ok. Now i understand.

But if the problem is only c++11 detection/activation,
these cmake 3.1 features cannot be made optional?

Ex.:
```cmake
IF(CMAKE_VERSION VERSION_LESS 3.0.0)
     set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
ENDIF()

```

**Comment by paulobrizolara** [comment]
Ok. now i have seen issue #548 .

To support also "-std=c++0x" flag, i believe this could be used:

```cmake
IF(CMAKE_VERSION VERSION_LESS 3.0.0)
    #Add the c++11 flag, whatever it is
    include(CheckCXXCompilerFlag)
    CHECK_CXX_COMPILER_FLAG(-std=c++11 COMPILER_SUPPORTS_CXX11)
    CHECK_CXX_COMPILER_FLAG(-std=c++0x COMPILER_SUPPORTS_CXX0X)
    if(COMPILER_SUPPORTS_CXX11)
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
    elseif(COMPILER_SUPPORTS_CXX0X)
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
    else()
      message(STATUS "The compiler ${CMAKE_CXX_COMPILER} has no C++11 support. Please use a different C++ compiler.")
    endif()
ELSE()
    # Require C++11 support, prefer ISO C++ over GNU variants,
    # as relying solely on ISO C++ is more portable.
    SET(CMAKE_CXX_STANDARD 11)
    SET(CMAKE_CXX_STANDARD_REQUIRED ON)
    SET(CMAKE_CXX_EXTENSIONS OFF)
ENDIF()
```

**Comment by paulobrizolara** [comment]
@cdunn2001 and @SoapGentoo , would you consider accepting a pull-request with these changes?

If you wanna encourage people to move into cmake >=3.1, without forcing them,
a warning could be added. This way, you let to the users the responsability.
What do you think?

Thanks anyway and sorry for bothering you.

**Comment by SoapGentoo** [comment]
@paulobrizolara again, `SET(CMAKE_CXX_STANDARD 11)` is the only portable solution. What if someone uses AIX? The C++11 flags are different on AIX.

Have you looked at the Travis config? On Ubuntu LTS, I would just add the cmake repo to get a more up-to-date version of CMake. For RHEL, have you tried the binaries provided by Kitware?

**Comment by paulobrizolara** [comment]
@SoapGentoo , i am not saying that you should not use the `SET(CMAKE_CXX_STANDARD 11)` solution, or proposing a "better way". 
I am not even saying that you should maintain older versions of cmake if you don't want.

I am just proposing a fix for those people that don't have cmake >=3.1.
What is better? Compile using a non portable solution or don't compile at all?
Off course, me and other users could find workarounds, use PPAs, format their machines, etc.
But i think that the simple solution above could easy the way for many users (at least for a while). 

If you wanna try, i can make a pull request, so you can check if it is ok.

**Comment by cdunn2001** [comment]
@paulobrizolara, sorry for the delay. Yes, a pull-request for cmake<3.0.0 would be fine, just as you've outlined. I don't think we will be able to test it, but I don't think that should stop us either.

**Comment by paulobrizolara** [comment]
@cdunn2001, sorry i did not see you comment until now (i have been a little off from everything these days).
I will make a pull request as soon as i can. And again, sorry for the troubles.

**Comment by cdunn2001** [comment]
> Also, would be nice to include the conan badge to help future users

The Conan idea sounds great! Could you simply add that to the wiki page, for the `master` branch?

**Comment by paulobrizolara** [comment]
@cdunn2001 , i created the pull request #601 to add the instructions in how to build with Conan and the recipe badge.

I did not changed the wiki, because the instructions to build were on the README file.
