### ISSUE TITLE
Bug: formatting real values for locales with ',' decimal separator

### ISSUE THREAD

**Issue by siddie** [open-source-parsers/jsoncpp#567]
JsonWriter (89ab7ec  on 27 Oct), line 155:
    
`// try to ensure we preserve the fact that this was given to us as a double on input
    if (!strstr(buffer, ".") && !strstr(buffer, "e")) {
      strcat(buffer, ".0");
    }
`

Let
`a = 0.1;`
     this piece of code gives me
`buffer == "0,1.0"`
     then after fixNumericLocale i get 
`buffer == "0.1.0"`

and this value is actually written to json.

The straigttforward way of fixing it is obvious, but I think you should generalize your way of working with locales. 

Anyway, thank you for this good lib.

**Comment by cdunn2001** [comment]
Interesting. Can you submit a PR to fix this? Simple fix first is fine; more complicated fix later.

**Comment by siddie** [comment]
The crucial thing I`ve found in my case is this happening at the beginning of an application I work with:
`std::locale::global(std::locale(""));`
Which of course can cause all sorts of undesired behaviours.

Without this call reading and writing JSON works as expected. Not sure whether this call sets a C locale also. If it does not, probably the bug is caused by mixing of C++ and C formatting stuff in the lib.

**Comment by bernhardHartleb** [comment]
The issue is that certain locales (like german) use a comma as decimal point, which snprintf is happy to produce. To resolve this, fixNumericLocale should be called directly after snprintf, otherwise the next search for a decimal point will fail and another ".0" is appended.
