### ISSUE TITLE
how to include jsoncpp lib on windows 

### ISSUE THREAD

**Issue by HUSTyanchao** [open-source-parsers/jsoncpp#579]
I build and installl the jsoncpp. Now I would like try to write CMakeLists.txt to include the jsoncpp library. But there is no JsoncppConfig.cmake file. So how can I include the jsoncpp library in my  CMakeLists.txt file?

**Comment by ya1gaurav** [comment]
You can use, INCLUDE_DIRECTORIES & LINK_DIRECTORIES like
and then,
TARGET_LINK_LIBRARIES(test_binary -ljsoncpp)
