### ISSUE TITLE
Json::Value  destructor bug? 

### ISSUE THREAD

**Issue by qiuhui** [open-source-parsers/jsoncpp#581]
(gdb) bt
#0  0x00007fb6d9703d58 in _int_free () from /lib64/libc.so.6
#1  0x00000000004ed11c in std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::_M_erase(std::_Rb_tree_node<std::pair<Json::Value::CZString const, Json::Value> >*) ()
#2  0x00000000004e82ee in Json::Value::~Value() ()

**Comment by ya1gaurav** [comment]
It maybe due to heap corruption in multithreaded scenario.

**Comment by cdunn2001** [comment]
Jsoncpp is not thread-safe. Please re-open if you have a test-case.
