### ISSUE TITLE
Error on compilation: expected unqualified-id before numeric constant

### ISSUE THREAD

**Issue by girishpaiv** [open-source-parsers/jsoncpp#584]
Compilation error:
```
application/management/server/json/json.h:635:23: error: expected unqualified-id before numeric constant
application/management/server/json/json.h:635:21: error: expected ';' at end of member declaration
application/management/server/json/json.h:635:23: error: expected unqualified-id before numeric constant
```
I have not used any code in my project, but just included #include "json/json.h" and compiled with it.
Looks like the above error points to 
https://github.com/open-source-parsers/jsoncpp/blob/master/include/json/value.h#L193 
```cpp
static const Value& null;  ///< We regret this reference to a global instance; prefer the simpler Value().
```
```
$ g++ --version
g++ (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)
```

**Comment by ya1gaurav** [comment]
which version of jsoncpp are u using ?

**Comment by girishpaiv** [comment]
# define JSONCPP_VERSION_STRING "1.8.0"
# define JSONCPP_VERSION_MAJOR 1
# define JSONCPP_VERSION_MINOR 8
# define JSONCPP_VERSION_PATCH 0
# define JSONCPP_VERSION_QUALIFIER
# define JSONCPP_VERSION_HEXA ((JSONCPP_VERSION_MAJOR << 24) | (JSONCPP_VERSION_MINOR << 16) | (JSONCPP_VERSION_PATCH << 8))

**Comment by girishpaiv** [comment]
Its just today I downloaded it. And looks like version is 1.8.0
\# define JSONCPP_VERSION_STRING "1.8.0"

**Comment by cdunn2001** [comment]
I think `null` is only for backward compatibility. What if we wrapped it in an ifdef? What macro name would you want?

**Comment by baylesj** [comment]
I'm closing this issue. We could wrap these static references so people could include headers without any of the source code, but what is the point of that? I don't see the use case for this.

Feel free to reopen if there is further discussion.
