### ISSUE TITLE
About duplicateStringValue [code-review]

### ISSUE THREAD

**Issue by Aethelflaed** [open-source-parsers/jsoncpp#59]
Hello,

I was looking for a good C++ json encoder / decoder and found your lib. I was looking at the code and found the duplicateStringValue function.

What is the prupose of this function considering the fact that `cstring` provides `strdup` ?

Also, there is this part of the code:

```cpp
 // Avoid an integer overflow in the call to malloc below by limiting length
// to a sane value.
if (length >= (unsigned)Value::maxInt)
    length = Value::maxInt - 1;
```

`length` is defined as an unsigned int, so it may be greater than `Value::maxInt` so I really don't know what you are trying to check here.

Anyway, why does this (C++) library does not use standard types for strings and arrays (`std::string` and `std::vector`) ? This would help having a *true* C++ lib.

**Comment by cdunn2001** [comment]
Re-open if still an issue.
