### ISSUE TITLE
FastWriter method appends new line

### ISSUE THREAD

**Issue by ardadmira** [open-source-parsers/jsoncpp#590]
FastWriter method why append new line? how to fix this issue?
[http://stackoverflow.com/questions/42734162/jsoncpp-fastwriter-right-trim](http://stackoverflow.com/questions/42734162/jsoncpp-fastwriter-right-trim)

**Comment by cdunn2001** [comment]
Please avoid the old (deprecated) `FastWriter`. Use the new `StreamWriterBuilder`, which lets you configure things like that.

(Sorry for long delay. Traveling and sick.)
