### ISSUE TITLE
Reader Parser is not able handle escape sequences in input string

### ISSUE THREAD

**Issue by hirenpitroda** [open-source-parsers/jsoncpp#595]
**Test Case-1**
```
String Input :- "abc\b"
Expected Output  from reader parser :- "abc\\b"
Observed behavior on JSONCPP :- "abc^H"
OUTPUT After Above Code changes :- "abc\\b"
```
**Test Case-2**
```
String Input :- "abc\bd"
Expected Output  from reader parser :- "abc\\bd"
Observed behavior on JSONCPP :- "abd"
```
As per reader parser API, it should handle escape sequence as it is coming. but reader parser is not behaving same as required above. Please share your thoughts.

**Comment by cdunn2001** [comment]
You closed #596 a day after posting this, yes? Did that not solve your problem? Did it contradict the JSON spec? May we close this?

**Comment by hirenpitroda** [comment]
No, i am working on PATCH for this issue, i will submit a PATCH for this. wait for 2 days.

**Comment by hirenpitroda** [comment]
@cdunn2001 ..
Added PATCH, with some test cases. Have a look.
Provide Comments.

**Comment by cdunn2001** [comment]
I am not convinced. I agree that it would be nice if a JSON library gave the user the ability to determine the internal representation, but that's just not how jsoncpp works. This library converts the escaped characters to 8-bit characters internally. That's just how it works. `\b` is converted to the ASCII "Bell", code 7. In theory, the writer will convert that back to `\b`. It's only the round-trip that matters. JSON.org does not specify the *parsed* representation.

But I'm confused by your examples. Why would JSON `"\b"` become `"\\b"` internally? Are you looking at Python? I'm very confused.

**Comment by hirenpitroda** [comment]
give me some time i will provide my exact requirement. i identified that my changes will lead to some other things to breakdown. so i am working to provider a API for my problem statement.

**Comment by hirenpitroda** [comment]
After Recent work with JSON CPP ,after reading JSON spec and doing some internal UT, found that. its client's(browser) responsibility to handle input Payload, i.e., if user is giving input payload as {"password":"abc\b"} than its browser or client tool responsibility to handle proper escaping and provide same input below layer APIs to work.
Closing this issue.
