### ISSUE TITLE
Assert in Value destructor (Win but not Mac)

### ISSUE THREAD

**Issue by TDI-tenderholt** [open-source-parsers/jsoncpp#605]
I'm seeing an assert thrown at Line 2950 in the aggregated ```jsoncpp.cpp file``` due to ```JSON_ASSERT_UNREACHABLE```:

```
Value::~Value() {
  switch (type_) {
  case nullValue:
  case intValue:
  case uintValue:
  case realValue:
  case booleanValue:
    break;
  case stringValue:
    if (allocated_)
      releasePrefixedStringValue(value_.string_);
    break;
  case arrayValue:
  case objectValue:
    delete value_.map_;
    break;
  default:
    JSON_ASSERT_UNREACHABLE;
  }

  delete[] comments_;

  value_.uint_ = 0;
}
```
How can ```Value``` be created without a type? Any ideas on where the problem might be? 

Note that this only occurs on Windows and not Mac.

Details:

* jsoncpp 1.8.0 aggregated
* Windows 7 with Visual Studio 2015
* Mac Sierra with clang 8.1.0 (Xcode 8.3.1).
* CMake project

**Comment by cdunn2001** [comment]
> Note that this only occurs on Windows and not Mac.

Interesting. Maybe you can help track this down? Try putting a breakpoint on `throw` or some variant of that.

**Comment by TDI-tenderholt** [comment]
My VisualStudio skills are lacking, but I found that ```type_ = -35``` when the assert statement fails. I'm guessing that it's a bug in *my* code that's causing the problem, but haven't been able to track it down yet.

BTW, I'm using a ```Json::Value*```, which is initialized in a class constructor and deleted in the class destructor (see https://github.com/Veritomyx/PeakInvestigator-CPP-SDK/blob/master/PeakInvestigator/Actions/BaseAction.cpp), but it's the [```InitAction```](https://github.com/Veritomyx/PeakInvestigator-CPP-SDK/blob/master/PeakInvestigator/Actions/InitAction.cpp) subclass where I see the problem. The JSON is valid according to http://jsonlint.com/.

(I'm probably also using ```Json::nullValue``` incorrectly in ```get()``` since it's an enum and not a static instance of ```Json::Value``` with a null type, but making that change didn't seem to help.)

I plan on testing in Ubuntu as soon as possible.

**Comment by TDI-tenderholt** [comment]
Quick update: unable to reproduce the crash with Ubuntu 16.10. I profiled with Valgrind (```valgrind --leak-check=full --show-leak-kinds=all```), but there weren't any jsoncpp-related leaks.

**Comment by TDI-tenderholt** [comment]
I inserted some debugging statements, and noticed that ```type == -35``` is consistent with this error being thrown. If I change ```ValueType.nullValue = 30```, the value of the other types change accordingly (e.g. ```realValue == 33```) but the problematic instance stays at -35.

**Comment by TDI-tenderholt** [comment]
I think I finally figured it out.

Wrapping a ```Json::Value*``` with ```std::unique_ptr``` resulting in errors indicating that compiler-generated copy constructors aren't exported from DLLs. So my guess is that I was getting corrupted ```Json::Value*``` when I was passing around objects between functions.

**Comment by cdunn2001** [comment]
Do we need to provide those explicitly? Maybe via `= default`? If that works for you, please submit a PR.

**Comment by TDI-tenderholt** [comment]
I don't think any changes to JsonCpp are necessary since the problem seems due to my C++ inexperience. I had written a some classes with a ```Json::Value*``` attribute, and while I was (probably) using the pointer correctly, I didn't understand that returning an object invoked a copy constructor:

```
InitAction someFunc() {
  InitAction action(...);   // has a Json::Value* attribute via super BaseAction class
  return action;            // uses InitAction::InitAction(const InitAction& copy);
}
```

Since I hadn't written any copy constructors for my classes, the compiler generated copy constructors. I think this was the problem, because as soon as I wrapped ```Json::Value``` in ```std::unique_ptr```, Visual Studio complained about a missing copy constructor. As soon as those were implemented, the problem went away.

Here's a project that works fine on Mac but gives the error with VS 2015: https://github.com/Veritomyx/TestJsonCPP. Output below. Interestingly, destructors are called at different times relative to "Exiting func()".

Mac output:
```
Start.
Entering ~Value() with type: 0
... repeats ...
Entering ~Value() with type: 0
Exiting func().
Entering ~Value() with type: 7
Entering ~Value() with type: 4
Entering ~Value() with type: 3
Entering ~Value() with type: 6
Entering ~Value() with type: 7
Entering ~Value() with type: 3
Entering ~Value() with type: 4
Entering ~Value() with type: 4
Entering ~Value() with type: 7
Entering ~Value() with type: 3
Entering ~Value() with type: 4
Entering ~Value() with type: 4
Entering ~Value() with type: 7
Entering ~Value() with type: 3
Entering ~Value() with type: 4
Entering ~Value() with type: 4
Entering ~Value() with type: 7
Entering ~Value() with type: 3
Entering ~Value() with type: 4
Entering ~Value() with type: 4
Entering ~Value() with type: 7
Entering ~Value() with type: 3
Entering ~Value() with type: 4
Entering ~Value() with type: 4
Entering ~Value() with type: 7
Entering ~Value() with type: 3
Entering ~Value() with type: 4
Entering ~Value() with type: 4
Entering ~Value() with type: 7
Entering ~Value() with type: 3
Entering ~Value() with type: 4
Entering ~Value() with type: 4
Entering ~Value() with type: 7
Entering ~Value() with type: 3
Entering ~Value() with type: 4
Entering ~Value() with type: 4
Entering ~Value() with type: 4
Entering ~Value() with type: 1
End.
Entering ~Value() with type: 0
```

And the Windows output:
```
Start.
Entering ~Value() with type: 0
... repeats ...
Entering ~Value() with type: 0
Entering ~Value() with type: 7
Entering ~Value() with type: 4
Entering ~Value() with type: 1
Entering ~Value() with type: 3
Entering ~Value() with type: 6
Entering ~Value() with type: 7
Entering ~Value() with type: 4
Entering ~Value() with type: 4
Entering ~Value() with type: 3
Entering ~Value() with type: 7
Entering ~Value() with type: 4
Entering ~Value() with type: 4
Entering ~Value() with type: 3
Entering ~Value() with type: 7
Entering ~Value() with type: 4
Entering ~Value() with type: 4
Entering ~Value() with type: 3
Entering ~Value() with type: 7
Entering ~Value() with type: 4
Entering ~Value() with type: 4
Entering ~Value() with type: 3
Entering ~Value() with type: 7
Entering ~Value() with type: 4
Entering ~Value() with type: 4
Entering ~Value() with type: 3
Entering ~Value() with type: 7
Entering ~Value() with type: 4
Entering ~Value() with type: 4
Entering ~Value() with type: 3
Entering ~Value() with type: 7
Entering ~Value() with type: 4
Entering ~Value() with type: 4
Entering ~Value() with type: 3
Entering ~Value() with type: 7
Entering ~Value() with type: 4
Entering ~Value() with type: 4
Entering ~Value() with type: 3
Entering ~Value() with type: 4
Exiting func().
Entering ~Value() with type: -35
Assertion failed: false, file C:\Users\local_admin\Desktop\TestJsonCPP\jsoncpp.cpp, line 2952
```

**Comment by TDI-tenderholt** [comment]
P.S. I just updated the ```TestJsonCPP``` repo. A wrapper without an explicit copy constructor crashes, but the one with finishes fine.
