### ISSUE TITLE
isConvertibleTo doesn't support uint64

### ISSUE THREAD

**Issue by stonewesley** [open-source-parsers/jsoncpp#608]
I'm trying to test if an uint64 isConvertibleTo Json::uintValue, since there is no uint64Value.
While actually, it failed to convert. I look through, and find the code maybe lack of something in function isConvertibleTo when the case is uintValue.
It only use isUInt() but not isUInt64(). And in function isUInt(), it compares value_ to maxUInt which is the max value of uint32, so it failed.
I don't know if there is another way to test an uint64 value.
Hope this may help.

**Comment by cdunn2001** [comment]
See #509, maybe.

My own preference would be to read/write JSON as strings, and to let type-conversion be a separate step. That's a little slower, but sooooooo much easier to code (and to test/debug). I think most Json libraries do this wrong. An implementation of the type-converter could then be templated on integer, float, string, array, and map. But that would be a new library.
