### ISSUE TITLE
How To Install jsoncpp in windows with Visual Studio 2013

### ISSUE THREAD

**Issue by Igamegum** [open-source-parsers/jsoncpp#611]
Very Hope your help!

**Comment by cdunn2001** [comment]
It should be simple if you have **cmake**. We actually test ever update on Windows. But we rely on other users for the Windows-specific details.

**Comment by jbmonroe** [comment]
If one has Python installed, start a command session at the top of the folder chain in which you've placed the jsoncpp source.  (Or _cd_ to that folder.)  If one does not have Python installed, install Python. :)  You may use either the 2.6+ or 3.4+ releases.

Launch amalgamate.py using python (the header in the file shows you how).  When it completes there will be a folder named 'dist ' that contains everything you need to use jsoncpp in a VS2013 project--just copy the folder over to your project and add the .cpp and both .h files to the build.
