### ISSUE TITLE
jsoncpp fails to detect unique_ptr is not available

### ISSUE THREAD

**Issue by chfast** [open-source-parsers/jsoncpp#612]
In exotic combination of clang (with c++11) and libstdc++ (no unique_ptr) on macOS, jsoncpp thinks unique_ptr is available.

Code: https://github.com/open-source-parsers/jsoncpp/blob/master/src/lib_json/json_writer.cpp#L78-L82.

Test build: https://travis-ci.org/ingenue/hunter/jobs/232088295.

**Comment by cdunn2001** [comment]
Could someone submit a PR?

**Comment by chfast** [comment]
I'm not sure how to check libstdc++ version.

**Comment by ya1gaurav** [comment]
Please check  if https://github.com/open-source-parsers/jsoncpp/pull/613 , solves your problem.

**Comment by baylesj** [comment]
Closing as won't fix. For one, you should be using libc++ if you are already using clang and LLVM, and for two, update your Mac 👍
