### ISSUE TITLE
Confusion around Reader/Writer vs CharReader/StreamWriter APIs

### ISSUE THREAD

**Issue by davidzchen** [open-source-parsers/jsoncpp#619]
I recently tried using jsoncpp for a project of mine, and I would like to give some feedback on the documentation of this library based on my experience as a user and some confusion I initially had:

- Based on what I have read from various issues and pull requests (see #283, #468, and #361), the Reader/Writer API is apparently deprecated. However, it is not clear at all from the documentation that this API is deprecated. The only reference that I found of this deprecation other than the above issues and pull requests was [this comment](https://github.com/open-source-parsers/jsoncpp/blob/762ad0fe9d7a5fd8c48dbf3229fe31e04997f2f3/include/json/reader.h#L33_). Assuming this API is actually deprecated, I think it would be a good idea to make this clear in the documentation and indicate that the CharReader/StreamWriter APIs replace the Reader/Writer APIs so that users that do not prefer using the stream-based API would have a clear migration path.
- As I was reading the code to try to understand the relationships between these different APIs, I found the comment documenting OurReader, stating ["exact copy of Reader, renamed to OurReader"](https://github.com/open-source-parsers/jsoncpp/blob/559b4416e6f923183b02ffe73e5167bad79b669e/src/lib_json/json_reader.cpp#L920), to be very confusing because it does not tell the reader why there is an exact copy of the Reader. After reading the code for CharReader, I finally understood that the Reader implementation is kept for binary compatibility whereas OurReader is used by the new CharReader API and a copy of the implementation is added so that it may be extended with new features. I think that it would greatly help users of this library if this point would be made more clear. Further, the new OurReader/CharReader implementation should ideally live in its own source file separate from the deprecated implementation rather than in the same source file.
- In [this comment](https://github.com/open-source-parsers/jsoncpp/issues/283#issuecomment-106109529) on #283, @cdunn2001 stated that it is not the intention for users to create their own StreamWriter and CharReader classes. However, I think the documentation does seem to suggest that users should be able to create their own StreamWriter and CharReader classes because:
    1) The main page of the documentation discusses the StreamWriter/CharReader API under the "Advanced Usage" section.
    2) The use of the Builder pattern seems to suggest that there may be multiple implementations of CharReader/StreamWriter, which may be instantiated using a factory.
    3) The documentation states, "Configure builders to create readers and writers. For configuration, we use our own Json::Value (rather than standard setters/getters) so that we can add features without losing binary-compatibility." The part of the sentence stating that "we can add features without losing binary-compatibility" seems to suggest that this can be an extension API for users of the library to add additional features for parsing or serializing, which is, in fact, something I am looking for for #618. If this is in fact not the case, then it is unclear how this API would allow for "advanced usage" of the library.
    
I think that many points of confusion that users of this library might have can be resolved by addressing and clarifying these above points. Please correct me if any of my assumptions are incorrect.

**Comment by cdunn2001** [comment]
1. Good idea. Please submit a PR to make this more clear.
2. `.cpp` docs are for developers of this library, not for users. But you are correct. Feel free to clarify that as well. A separate source-file takes a lot of work because it means updating `amalgamate.py` and cmake-files, and I am not convinced that simply moving code into a new file would make anything more clear.
3. Yes.
    1. Yes.
    2. Yes, potentially, but hidden from the user.
    3. Feel free to clarify. The "advanced usage" is in the fact that these allow a variety of settings which affect the behavior of reading and writing.
