### ISSUE TITLE
A problem while installing JsonCpp

### ISSUE THREAD

**Issue by billchenchina** [open-source-parsers/jsoncpp#624]
I'm using Eclipse to build my porject,and i'm meeting a problem:
I ran `python amalgamate.py`and get the `dist/` directory,then I copied `json.h` and `json-forwards.h` to my project folder and include it.
When I used `Json::Value root;` in my `main.cpp`,Eclipse tells that 
`Errors (2 items)
make:***[Project_Name] Error 1
recipe for target 'Project_Name' failed
`
So what can I do to solve the two problems?
Thanks.

**Comment by billchenchina** [comment]
Just these simple codes:
`#include <iostream>
#include "json/json.h"
#include "json/json-forwards.h"
int main(){
	std::cout<<"This is a test output";
	Json::Value root;
	return 0;
}`

**Comment by cdunn2001** [comment]
I can't debug this without being on your system. My best guess is that you did not put the headers into a `json/` sub-directory.

If you figure this out and find a bug in jsoncpp, please re-open let us know.

**Comment by billchenchina** [comment]
@cdunn2001 Thanks,but I have already put the two files(json.h and json-forwards.h) into a sub-directory(json/).
And it still doesn't WORK.
Thanks.

**Comment by cdunn2001** [comment]
You could try the new `meson.build` with the visual-studio backend. Google 'meson build' documentation.

**Comment by billchenchina** [comment]
Solved

**Comment by cdunn2001** [comment]
Was it something others could learn from? If so, please post here.

**Comment by billchenchina** [comment]
Oops...I just forget to copy  ```jsoncpp.cpp``` into my project...: )Well,thanks. @cdunn2001
