### ISSUE TITLE
Problem in Reader::decodeNumber() for numbers greater than maxInt?

### ISSUE THREAD

**Issue by timcoleman** [open-source-parsers/jsoncpp#633]
I am looking at decodeNumber(), and if the value is greater than Value::LargestUInt(Value::maxInt) then it will be returned as a Value::LargestUInt(). But I think the check should be if the value is greater than Value::LargestUInt(Value::maxLargestInt). Otherwise, int64 values will be converted to uint64 if they are greater than maxInt (but smaller than maxInt64).

**Comment by baylesj** [comment]
Fixed in #961
