### ISSUE TITLE
Unable to read json from a file.

### ISSUE THREAD

**Issue by trehman65** [open-source-parsers/jsoncpp#634]
fstream file("input.json");

json::Value root = file; //what to do here
json::Value ocr = root["ocroutput"];

**Comment by Dark-Passenger** [comment]
fstream file("input.json");

Json::Value root;

root << file;

Json::Value ocr = root["ocroutput"];

**Comment by Dark-Passenger** [comment]
Read the documentation next time :)

and you might want to close this.
