### ISSUE TITLE
Can you provide a C++ code which read JSON file (.json)?

### ISSUE THREAD

**Issue by shubhamnr** [open-source-parsers/jsoncpp#639]
An example. Could not find in your project.

**Comment by xPrzybyLx** [comment]
It's in the documentation :
http://open-source-parsers.github.io/jsoncpp-docs/doxygen/index.html

**Comment by JiatLn** [comment]
I want to know, too.

**Comment by cdunn2001** [comment]
It's also possible to search the Issue archives. This question comes up now and then. I think you already have permission to add a wiki page. Feel free. Please, re-open if you encounter a problem.

https://github.com/open-source-parsers/jsoncpp/wiki
