### ISSUE TITLE
Conversion of Json::Value to long int is ambiguous

### ISSUE THREAD

**Issue by orodbhen** [open-source-parsers/jsoncpp#64]
Trying to copy a Json::Value object to a long int fails to compile, because Json::Uint64 and Json::Int64 are mapped to unsigned long int and long int, respectively.

On Linux/Unix systems, at least, these should instead be mapped to uint64_t and int64_t, which will always be 64 bit.

Also note that these typedefs (int64_t and uint64_t) don't work either with the Json::Value constructor, because they are typdefed to long int when __WORDSIZE == 64. They do work when __WORDSIZE == 32, because then they map to long long int, just like Json::Int64.

**Comment by orodbhen** [comment]
just checking back to see if any work has been done on this. I find jsoncpp to be very unfriendly to programming with templates.

Currently, I use a wrapper I created that maps the type of the output buffer to the correct jsoncpp type. It's original purpose was to provide a C interface to jsoncpp, but I use it in C++ as well.

It would be nice, though, to have a more generalized interface for C++ that works with templates. I'd like to contribute, but first I need to know how the maintainers want to implement it.

**Comment by cdunn2001** [comment]
Maybe some sort of wrapper? You can derive your own CharReader and StreamWriter to operate on your data-types. But if you want to templatize `Json::Value`, you might be better off forking the whole project.

**Comment by TuNguyen89** [comment]
Today I'm get the different result of function ```Value::UInt64 Value::asUInt64() const```

I have ```Value["key"] = 18446744073709551616```   (Max unsigned 64 bit + 1)
Then the Value["key"] converted to real.
When I use the function value.asUInt64() I get different value for the same compiler but different architect (amd64 vs arm64)

In amd64, 2^64 is returned.
In arm64,  0 is return.
