### ISSUE TITLE
C4996 Error on VS2015

### ISSUE THREAD

**Issue by llluiop** [open-source-parsers/jsoncpp#642]
hi, i compiled lib_json by vs2015, it works fine, but when i used the lib_json.lib in a new application, i got a c4996 error:  error C4996: 'Json::Writer': Use StreamWriter instead.
I think it was caused by:
```cpp
#  if _MSC_VER >= 1500 // MSVC 2008
    /// Indicates that the following function is deprecated.
#    define JSONCPP_DEPRECATED(message) __declspec(deprecated(message))
#  endif
```
i just include `<json/json.h>` without using any object in jsoncpp, is it normarl? now i have to disable this warning, any good solutions , thanks.

**Comment by cdunn2001** [comment]
Check the docs for how to use the `StreamWriterBuilder`. That is more configurable.

But the old `Writer` still works, if you don't mind the deprecation warning.

**Comment by wujiyoung** [comment]
@llluiop Have you solved it? I met this problem too.
@cdunn2001 It is not warning, it is error, so, any further idea to resolve it ?

**Comment by cdunn2001** [comment]
We build in AppVeyor before releasing, so I know the code can work with VisualStudio. If there is a problem with in VS2015, please try to help us fix it. We cannot test on all versions of all platforms.

**Comment by wujiyoung** [comment]
@cdunn2001 I have fixed my problem.
lib_json.lib is built with multi thread(MT) mode in your makefile vs project, while my project is under multi thread dynamic(MD) mode, So I rebuild the lib_json.lib with MD mode, and it works well.

**Comment by zouzhiquan** [comment]
This doesn't make any sense, as the initial post said that he only "#include <json/json.h>" then he got this warning.
