### ISSUE TITLE
Int comparison fail on Android

### ISSUE THREAD

**Issue by amostyaev** [open-source-parsers/jsoncpp#644]
I'm using the latest Android NDK 15.1.4119039 and JsonCpp version 1.8.0.

The code generates "LargestInt out of Int range" during asInt() check of value = `1`. This happens only at debug build.

The following change fixes the issue (json_value.cpp file):

```
- return value_.int_ >= minInt && value_.int_ <= maxInt;
+ return Int(value_.int_) >= minInt && Int(value_.int_) <= maxInt;
```

So, we should make an explicit cast to `Int` of the `LargestInt` value. It looks logic, so you can support more compilers. Can you make this change into the library?

**Comment by cdunn2001** [comment]
I guess we need this fix. Would you submit this as a Pull-Request?

**Comment by amostyaev** [comment]
Sure. Here is it https://github.com/open-source-parsers/jsoncpp/pull/647
