### ISSUE TITLE
Any known issues with ObjC linker flag ?

### ISSUE THREAD

**Issue by AlfredJohensson** [open-source-parsers/jsoncpp#645]
Hi,
Are there any known issues with json_cpp built with -ObjC linker flag in xcode ?
decodePrefixedString() [json_value.cpp] is not returning right length for stringValue when -ObjC flag is given at the link time. I thought i would ask here if someone has already seen this issue.

thanks,
AJ

**Comment by AlfredJohensson** [comment]
I am using 1.8.0 version

**Comment by cdunn2001** [comment]
Sorry. I haven't seen this. If you come up with a fix, please submit a Pull-Request.
