### ISSUE TITLE
API-change without SO-name bump…

### ISSUE THREAD

**Issue by besser82** [open-source-parsers/jsoncpp#654]
https://github.com/open-source-parsers/jsoncpp/commit/8996c377aad3a333a9bada1cfe7d5924e71a3269 introduced an API / ABI change without correctly bumping the SO-name…  This affects v1.8.2 release. Sadly it's not the first time this happens…

**Comment by cdunn2001** [comment]
I was afraid of that. (See release notes.) We'll bump the ABI version number.

**Comment by besser82** [comment]
Thank you!  =)

**Comment by cinemast** [comment]
@cdunn2001  Might I suggest the great tools of @lvc https://github.com/lvc/abi-tracker

**Comment by cinemast** [comment]
https://abi-laboratory.pro/tracker/compat_report/jsoncpp/1.8.1/1.8.2/b37a5/abi_compat_report.html It did in fact catch the problem.

**Comment by cdunn2001** [comment]
@besser82 and @cinemast, Sure, that's a good idea to check the abi-tracker for symbol changes in the future.

However, was there any *actual* problem this time. The abi-tracker shows only one removed symbol, `Value::CZString::operator = ( Value::CZString other )`, replaced by reference and move versions. `CZString` is private. Publicly, it is used only in `ObjectValues* map_`, which is a pointer that is not dereferenced publicly. I do not see how anything could have broken.

Just for clarification, are you saying that you prefer to trust the strict abi-checker? Or was there an actual runtime problem somewhere?

**Comment by besser82** [comment]
@cdunn2001 In this particular case it possibly wouldn't have done any harm, but none the less the exported symbols of the dso were changed.  In such cases it's always recommended to bump the dso version, just to play safe.

**Comment by besser82** [comment]
@cdunn2001 Could you please tag the new release, so I can update to recent version in Fedora?
