### ISSUE TITLE
ver1.8.3 StreamWriterBuilder and CharReaderBuilder performance is lower than before. 

### ISSUE THREAD

**Issue by leiwenbin** [open-source-parsers/jsoncpp#658]
ver1.8.3 StreamWriterBuilder and CharReaderBuilder performance is lower than before. 
except OO，What is the purpose of this modification？
test case:
```cpp
    long long int t2 = mdf::MillTime();
    for (int i = 0; i < 1000000; ++i) {
        Json::FastWriter w;
        string str = w.write(value);
        //printf("json: %s\n", str.c_str());

        Json::Reader reader;
        Json::Value v;
        reader.parse(str, v);
        //printf("json_a:%s, parse err:%s\n", v["a"].asString().c_str(), err.c_str());
    }
    printf("cost time: %llu.\n", mdf::MillTime() - t2);

    long long int t = mdf::MillTime();
    for (int i = 0; i < 1000000; ++i) {
        Json::StreamWriterBuilder writer;
        string str = Json::writeString(writer, value);
        //printf("json: %s\n", str.c_str());

        Json::Value v;
        string err = "";
        Json::CharReaderBuilder reader;
        Json::parseFromString(reader, str, &v, &err);
        //printf("json_a:%s, parse err:%s\n", v["a"].asString().c_str(), err.c_str());
    }
    printf("cost time: %llu.\n", mdf::MillTime() - t);

    long long int t1 = mdf::MillTime();
    Json::StreamWriterBuilder writer;
    Json::CharReaderBuilder reader1;
    for (int i = 0; i < 1000000; ++i) {
        string str = Json::writeString(writer, value);
        //printf("json: %s\n", str.c_str());

        Json::Value v;
        string err = "";
        Json::parseFromString(reader1, str, &v, &err);
        //printf("json_a:%s, parse err:%s\n", v["a"].asString().c_str(), err.c_str());
    }
    printf("cost time: %llu.\n", mdf::MillTime() - t1);`
```
![image](https://user-images.githubusercontent.com/13939970/29962637-70b46b8e-8f36-11e7-8c12-4db0cf84620a.png)

**Comment by cdunn2001** [comment]
Interesting. Compared with which version precisely? 1.8.2? In theory, a move constructor was made available.

I hope more people notice this question. People were clamoring for the move ctor, but if it's a real performance hit, we might drop it.

**Comment by cdunn2001** [comment]
Wait. Even the old (and deprecated) `FastWriter` is slower (test1). (Note: test2 is not a big deal. You should usually not need to recreate the Builders in the loop.)

One thing that changed (and to be sure, we need to state very clearly what version or commit you used for the older test) is a fix to how comments are stored. But you might have several other changes.

**Comment by leiwenbin** [comment]
All of our tests are based on version 1.8.3, please focus on test1 and test3, because at the level of a million calls, the same version (1.8.3) looks like the old  (and deprecated) method FastWriter and Reader is 25% better than the new method StreamWriterBuilder and CharReaderBuilder.

![image](https://user-images.githubusercontent.com/13939970/30903087-23fa5eb0-a3a0-11e7-951d-f41cd3cb51fe.png)

**Comment by cdunn2001** [comment]
Json::parseFromString(reader1, str, &v, &err);

That method does not exist.

Anywy, if you want efficiency, you're using the builders wrong. The function you're calling is only for convenience:
```cpp
JSONCPP_STRING writeString(StreamWriter::Factory const& builder, Value const& root) {
  JSONCPP_OSTRINGSTREAM sout;
  StreamWriterPtr const writer(builder.newStreamWriter());
  writer->write(root, &sout);
  return sout.str();
}
```
See? It allocates (and later destroys) a Writer on the heap. You should do this:
```cpp
    Json::StreamWriterBuilder wbuilder;
    Json::CharReaderBuilder rbuilder;
    Json::StreamWriterPtr const writer(wbuilder.newStreamWriter());
    Json::CharReaderPtr const reader(rbuilder.newCharReader());
    for (int i = 0; i < 1000000; ++i) {
        std::ostringstream sout;
        writer->write(value, sout);
        string str = sout.str();

        Json::Value v;
        std::istringstream sin;
        sin << str;
        reader->parse(sin, v, false);
    }
```
That may still be a little slower than the older version, but it is far more flexible. Other libraries are faster. JsonCpp has specific features, and the Builders make new features easier to add without breaking backward compatibility.

**Comment by Globik** [comment]
And how then to convert the sout.str() to C string? To char*?
So far so good const_cast char* sout.str().c_str()
They said the pointer is dangling

**Comment by cdunn2001** [comment]
Converting from `std::stringstream` to `std::string` is a question for a different forum.
