### ISSUE TITLE
Documentation site is broken

### ISSUE THREAD

**Issue by ibc** [open-source-parsers/jsoncpp#662]
http://open-source-parsers.github.io/jsoncpp-docs/doxygen/index.html

No index, no classes, no API. I assume this is broken, right?

**Comment by cdunn2001** [comment]
http://open-source-parsers.github.io/jsoncpp-docs/doxygen/

http://open-source-parsers.github.io/jsoncpp-docs/doxygen/class_json_1_1_value.html

I don't see any obvious link to the class docs, but if you click on `Json::Value` in the "Code Example", it's linked. If more obvious link is neeed, please submit a PR.

**Comment by ibc** [comment]
A PR to where? I just mean that the overall homepage does not provide a clear way to open the API. And I report this because it did not happen some months before.

**Comment by cdunn2001** [comment]
It is all comes from the doxygen inputs and the source code, all in the repo. See `doc/jsoncpp.dox`. Maybe doxygen changed? I'll see if I can figure something out.

**Comment by cdunn2001** [comment]
http://open-source-parsers.github.io/jsoncpp-docs/doxygen/

Better?

**Comment by ibc** [comment]
yes! :)
