### ISSUE TITLE
Value::toFastString is gone?

### ISSUE THREAD

**Issue by Renshk** [open-source-parsers/jsoncpp#674]
the json string which Value::toStyledString returns is not suitable for persistence to db

**Comment by cdunn2001** [comment]
Could you explain?

**Comment by Renshk** [comment]
In a word, I can't find the Value::toStyleString  interface in the last version.

**Comment by cdunn2001** [comment]
`toFastString()` is nowhere in the git history of this code-base. Maybe you are thinking of a different JSON library?
