### ISSUE TITLE
Issue: compatibility of methods and JSON object types

### ISSUE THREAD

**Issue by sharpie7** [open-source-parsers/jsoncpp#682]
I think this is probably "design intent", but I want to raise this issue to invite consideration of possible change to the code, or an addition to the documentation.

If you call the 'isMember()' method on a a variable that is not an "Object" type it will throw an error. I can see the logic for doing that, but you could also consider that non-object types have no members and therefore "isMember()" should just return false.

My general point is that it would be helpful to document which methods are allowed for which JSON object types. As far as I know, currently this can only be deduced by inspecting or testing the code.

Edit-to-add: thanks for a very helpful library BTW

**Comment by cdunn2001** [comment]
I think your way could make more sense, but it's too late to change.

Yes, exceptions should be doxygen-documented. If you do that, submit a pull-request and we'll merge it.
