### ISSUE TITLE
OK to use Value* to contained elements?

### ISSUE THREAD

**Issue by rickyviking** [open-source-parsers/jsoncpp#684]
I'm thinking about using Json::Value items read from file directly as generic data container to be presented by a GUI (similar to a "variant" class).
For the UI I need to wrap the data in a data model which allows to store a pointer to custom user data.
I was wondering if it's safe to use a Json::Value* to the ith Value of a collection (extracted as Value& from array or object elements), taking care of re-assigning those pointers every time a container is modified. 
Is that ok or pointers to nested Values might change also for other conditions?
Thanks

**Comment by cdunn2001** [comment]
We use STL data-structures, so any operation which can create copies could invalidate your `Value*`. The dictionaries are fine, but if you resize an array, you could have a problem.
