### ISSUE TITLE
Json::Reader::Char': Use CharReader and CharReaderBuilder instead

### ISSUE THREAD

**Issue by ItsChoudhry** [open-source-parsers/jsoncpp#685]
I am using visual studio 2017 and the Amalgamated source empty project with just the 2 header files and the single .cpp counter part. I added the json folder to the include under C/C++ general. 

[errors.txt](https://github.com/open-source-parsers/jsoncpp/files/1348573/errors.txt)

**Comment by cdunn2001** [comment]
Please show us how to fix it and submit a pull-request.
