### ISSUE TITLE
Is jsoncpp not support "redirect" semantic?

### ISSUE THREAD

**Issue by waveness** [open-source-parsers/jsoncpp#692]
Hello:
      I have a json file like test1.json,  it use "redirect" semantic  redirect to test2.json,  but it seems jsoncpp do not support this usage, I can not get right value from test2.json after "redirect",
     please tell me if i use wrong way or give me the right useage sample code,thanks

**Comment by waveness** [comment]
follow is my test set, I can't read test2 value when I use root["test2"].asString() or root["another"]["test2"]
======mytest.json==========
{
	"insert": {
		"mem1": "test mem1"
	},
	"people":{
		"name": "czb",
		"age": 23
	},
	"float": 1.20,
	"another":{
		"redirect" : "mytest2.json"
	}
}
=======mytest2.json=============
{
	"test2":"this is test2"
}

**Comment by cdunn2001** [comment]
Sorry. We do not support the "redirect" notation. Interesting though.

**Comment by waveness** [comment]
oh, I'm sorry to hear that
