### ISSUE TITLE
msvc warnings

### ISSUE THREAD

**Issue by dansgithubuser** [open-source-parsers/jsoncpp#696]
I'm using jsoncpp amalgamated-source-wise in a project I'd prefer to have no warnings in (so that new warnings stick out -- globally disabling warnings doesn't solve the issue). I'm inheriting Json::Value in a generic Serializable class and catch a Json::RuntimeError in one spot. The warnings are about deprecated Json::Reader::Char and such, which I don't think I'm using.

I guess I'll start with some high-level questions though:
1) Am I doing something unexpected?
2) Are warnings expected?

Using tip of master and msvc 2017.

**Comment by dansgithubuser** [comment]
Ah, I think it's because I'm using operator>> which uses StyledStreamWriter which is deprecated.

**Comment by dansgithubuser** [comment]
No, that's only in the documentation. In the amalgamated jsoncpp.cpp I'm using, operator<< uses StreamWriterBuilder.

**Comment by dansgithubuser** [comment]
Ah. I have to disable 4996 when compiling jsoncpp.cpp and also do a pragma warning push, disable:4996, pop around my inclusion of json.h.

**Comment by cdunn2001** [comment]
We have a recent change to suppress some MSVC warnings. Let us know if that works for you.
