### ISSUE TITLE
Value::empty()

### ISSUE THREAD

**Issue by bxq2011hust** [open-source-parsers/jsoncpp#698]
if Json::Value's `ValueType` is `stringValue` and the string is empty, then `Value::empty()` will return false which is not my  expected.  If there is a function can judge a Value(ValueType : stringValue) is empty?
https://github.com/open-source-parsers/jsoncpp/blob/d61cddedac68f6dd3991d285045a23aeb253aa53/src/lib_json/json_value.cpp#L958-L963

**Comment by cdunn2001** [comment]
You're right. It might have made sense to think of a string as another container.

But another point-of-view is that a string is a value, like int and float, and empty string is a valid value.

Maybe it's better to deprecated `empty()`. Anyway, we cannot break backward-compatibility. Sorry.

**Comment by BillyDonahue** [comment]
The persistent confusion is that there’s not a clearly defined “viewport” onto a Value as an Array or Object. The Value-as-Array and Value-as-Object Member functions are mixed in with the Value-as-variant member functions. To view a Value as int or string, you call an as<T> accessor and gou get an object with an expanded API of T. There is no such accessor for Array or Object, which is a conceptual weakness IMO, so it then sets up expectation that Value-as-string should work. I don’t believe it should. We should be going the other direction and adding accessors for the asArray and asObject personalities.
