### ISSUE TITLE
A little patch to allow building jsoncpp with MS compiler -sdl security option

### ISSUE THREAD

**Issue by BeErikk** [open-source-parsers/jsoncpp#700]
The `-sdl` MS compiler option turn some warnings into errors, one of them being `C4996` (use of a function marked as deprecated). See MSDN [/sdl (Enable Additional Security Checks)](https://docs.microsoft.com/en-gb/cpp/build/reference/sdl-enable-additional-security-checks)

To be able to build jsoncpp with `-sdl`, you need to disable the `JSONCPP_DEPRECATED` macro somehow. For example like this somewhere:
`#define JSONCPP_DEPRECATED(x)`

and  then apply this simple patch:
[depricated.vs.sdl.patch.txt](https://github.com/open-source-parsers/jsoncpp/files/1464356/depricated.vs.sdl.patch.txt)

**Comment by cdunn2001** [comment]
Please submit as a PR. We run Windows CI builds on AppVeyor to test MS compiler features.

**Comment by BeErikk** [comment]
Well, this was more like an explanation why the library breaks the MS compiler in a very subtle and not obvious way. I have no idea how to patch it properly and suitably. Perhaps replace `#pragma deprecated` with a `#pragma message("This piece of code is deprecated")`?
