### ISSUE TITLE
Setting "allowComments" = false not working for comments inside of object

### ISSUE THREAD

**Issue by Nomk** [open-source-parsers/jsoncpp#706]
With the following settings
```
Json::CharReaderBuilder builder;
builder["collectComments"] = true;
builder["allowComments"] = false;
```
and
```
Json::CharReader *reader = builder.newCharReader();
```
the parse-function `reader->parse(...)` returns true, instead of false for the following input:
```
{
    // some comment
    "int": -3
}
```

Writing the comment outside of the object, like this
```
// some comment
{
    "int": -3
}
```
returns false (and an error), as expected.

**Comment by cdunn2001** [comment]
We put emphasis on *accepting* unusual input flexibly, rather than on *rejecting* bad input. In other words, JsonCpp is not meant to be a validator. If you can find a simple way to get `false` for your case, please submit a PR. Otherwise, this is pretty low priority for us.
