### ISSUE TITLE
Parsing Multiple root element present in JSON

### ISSUE THREAD

**Issue by puagg281** [open-source-parsers/jsoncpp#709]
Hi Everyone,

Is there any way to parse multiple root elements present in single json file. I am stuck here .

**Comment by cdunn2001** [comment]
Like this?
```js
{
  "a": 1
}
{
  "b": 2
}
```
That's not valid JSON. One might think of it as a stream of multiple JSON elements. I think the parser is capable of parsing just the first part, but I don't think there is anything to tell you the index of the last-parsed character in the input string. We could add that. Is that all you need?

**Comment by puagg281** [comment]
Yes, i am looking for the same. I have the JSON file which has the records in the same format as suggested by you. !!

**Comment by cdunn2001** [comment]
Could you submit a pull-request for the change you think would work?

**Comment by dota17** [comment]
Closing.
Multiple root element  is not valid in JSON, it does not follow the JSON specifications. and all the json library should follow the JSON stanard. So, I'm afraid we can't implement this function
We don't know what the user will write to the file. but if you want to parse it, you can call the parse() multiplely until it go end of the file.
