### ISSUE TITLE
Is this intended?

### ISSUE THREAD

**Issue by yuwenyong** [open-source-parsers/jsoncpp#711]
I'm reading source code recently.In function "utf8ToCodepoint"  contains code below(almost line 202 in json_writer.cpp):
`if (calculated >= 0xD800 && calculated >= 0xDFFF)
      return REPLACEMENT_CHARACTER;`
It seems first condition is redundant. Should second condition be less equal? Is this intended?

**Comment by cdunn2001** [comment]
https://github.com/open-source-parsers/jsoncpp/blob/master/src/lib_json/json_writer.cpp#L173

Maybe you are looking at old code?

**Comment by yuwenyong** [comment]
I am looking at the code follow your link and it's the same version as mine.The "problem code" is in the 201 line.

**Comment by cdunn2001** [comment]
@yuwenyong, thanks for following up. There seems to be a bug in #687. I'll give the author some time to respond, but if you'd like, go ahead and submit a pull-request with your proposed fix.

**Comment by wenlian** [comment]
it may cause some chinese  punctuation transcoding get wrong code, such as: , (0xFF0C) ? (0xFF1F)  ! (0xFF01)  ; (0xFF1B) ...

**Comment by pkierski** [comment]
Sorry for late response. It's a bug, #712 resolves it.

**Comment by cdunn2001** [comment]
Fixed by #712/#714.
