### ISSUE TITLE
Memory access violation 

### ISSUE THREAD

**Issue by liranHaim** [open-source-parsers/jsoncpp#719]
I add the jsoncpp as lib to my DLL.
I Loading the DLL in windows XP SP3.
I get Memory access violation exception in the cpp file json_value.cpp, at the function 
`Value const& Value::nullSingleton()
{
 static Value const nullStatic;
 return nullStatic;
}`

If i take the declaration line "static Value const nullStatic;" outside the function  body
` static Value const nullStatic;
Value const& Value::nullSingleton()
{
return nullStatic;
}`
it working.

**Comment by cdunn2001** [comment]
Well, we could `#ifdef` that for windows. The global variable has been a big headache until we switched to this model. Could you specify you compiler version? And what version/sha1 of jsoncpp?

**Comment by liranHaim** [comment]
I am using VS2017 with windows SDK 10.0.16299.0.
This bug was reproduce the current master version.

**Comment by BillyDonahue** [comment]
Is the caller retaining and accessing the returned reference after the DLL is unloaded?

I’d like to know more about the caller.

**Comment by liranHaim** [comment]
The caller  is a c++ app that using LoadLabry.
The LoadLabry  it self  failed with system error 998.
Only when i run the app using windbg i saw the memory access violation exception

**Comment by MarcelRaad** [comment]
Looks like you're running into this issue:
https://stackoverflow.com/a/32776479

The combination function-local statics + Windows XP / Server 2003 + DLL crashes unless you compile with /Zc:threadSafeInit-.

**Comment by baylesj** [comment]
Closing as wont fix. Feel free to reopen if we want to look at other resolution options.
