### ISSUE TITLE
Fix warning C4996 with VS2017

### ISSUE THREAD

**Issue by oxygene** [open-source-parsers/jsoncpp#728]
Class Json::Reader is marked as deprecated. Unfortunately, VS2017 issues a bunch of warnings even when client code is not using Json::Reader at all. The warnings refer to usage of Json::Reader *within* Json::Reader itself:
```
...\jsoncpp\reader.h(38): warning C4996: 'Json::Reader::Char': Use CharReader and CharReaderBuilder instead
...\jsoncpp\reader.h(37): note: see declaration of 'Json::Reader::Char'
...\jsoncpp\reader.h(181): warning C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
...\jsoncpp\reader.h(38): note: see declaration of 'Json::Reader::Location'
...\jsoncpp\reader.h(182): warning C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
[...]
```

This minimal example also results in warnings: 
```
class Foo
{
    typedef char Char; // C4996 WARNING HERE
};

void main()
{
  // not using Foo
}
```

What works for VS2017 is the following:

```
// class declaration without declaring as "deprecated" yet
class Foo
{
    typedef char Char; // C4996 WARNING HERE
};
// now make it deprecated
class __declspec(deprecated("FOOBAR")) Foo;
```

I have *not* tested it whether this also works on other platforms with the JSON_DEPRECATED macro.

**Comment by nichmj01** [comment]
I have the same problem in VS2015. It seemed similar to the problem listed here: https://stackoverflow.com/questions/46151531/how-works-deprecated-warnings-and-how-to-remove-them-when-using-jsoncpp

So for now, I disabled warning 4996 around the Reader class just like in the referenced link, but don't know what side effects that may have.

**Comment by oxygene** [comment]
I've created a pull request where I propose to only deprecate the constructors of Json::Reader. This should fix the false positives but still catch actual uses of Json::Reader.
