### ISSUE TITLE
Warning C4275

### ISSUE THREAD

**Issue by nichmj01** [open-source-parsers/jsoncpp#730]
jsoncpp Version: 1.8.3
OS: Windows
Compiler: VS2015

I'm including jsoncpp as part of a DLL and I need to export the JSON functionality. I use JSON_BUILD_DLL to enable exporting the JSON API but I get a bunch of C4275 warnings because the Json::Exception classes inherit from std::exception.

From these 2 StackOverflow pages: 

- https://stackoverflow.com/questions/32019547/deriving-from-stdexception-in-a-library-does-a-headers-only-solution-work-for
- https://stackoverflow.com/questions/24511376/how-to-dllexport-a-class-derived-from-stdruntime-error

It seems like I can ignore the warnings but we try to avoid doing that so I removed the export of the Exception classes and moved the definition to the header. 

What's the best way to get the warnings removed in a future version?

**Comment by cdunn2001** [comment]
Not sure. Submit a PR?

**Comment by dota17** [comment]
Closing. 
[Warning (level 2) C4275](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-2-c4275?view=vs-2019) can be ignored by adding `#pragma warning(disable : 4275)` in the header file.
