### ISSUE TITLE
cmake/meson inconsistent soversion with 1.8.4

### ISSUE THREAD

**Issue by userwithuid** [open-source-parsers/jsoncpp#734]
[meson.build](https://github.com/open-source-parsers/jsoncpp/blob/ddabf50f72cf/meson.build#L56) uses 20
[CMakeLists.txt](https://github.com/open-source-parsers/jsoncpp/blob/ddabf50f72cf/CMakeLists.txt#L67) uses 19

**Comment by cdunn2001** [comment]
This will probably happen again. Could you help us to include a single soversion into both?

**Comment by baylesj** [comment]
Added some comments to hopefully avoid this in future releases.

**Comment by dota17** [comment]
Closing. seems like this has been resolved.
