### ISSUE TITLE
how can I get unformat json string without fastwriter

### ISSUE THREAD

**Issue by violiu** [open-source-parsers/jsoncpp#735]
I like StreamWriterBuilder which use builder pattern. But I can not find how to get unformat json string which like fastwriter did.
Please help me. 
Thank you!

**Comment by cdunn2001** [comment]
> how to get unformat json string which like fastwriter did

Could you explain? Example?

**Comment by violiu** [comment]
serialization string without \t or white space. maybe looks like:{"name":"json"} .but not like:
{
       "name":"json"
}

**Comment by violiu** [comment]
sorry about my poor  English expression

**Comment by cdunn2001** [comment]
Oh, you want just a minimal JSON string. Use a `StringWriterBuilder`:
```cpp
Json::StreamWriterBuilder wbuilder;
wbuilder["indentation"] = "";
std::string document = Json::writeString(wbuilder, root);
```
* http://open-source-parsers.github.io/jsoncpp-docs/doxygen/index.html
* http://open-source-parsers.github.io/jsoncpp-docs/doxygen/class_json_1_1_stream_writer_builder.html
* http://open-source-parsers.github.io/jsoncpp-docs/doxygen/class_json_1_1_stream_writer_builder.html#a79bdf2e639a52f4e758c0b95bd1d3423 (see here for possible settings)

**Comment by violiu** [comment]
thank you,  I have resolve the my problem which how to get a minimal json
string.

On Wed, Feb 14, 2018 at 11:36 AM, Christopher Dunn <notifications@github.com
