### ISSUE TITLE
undefined reference to `Json::Value::Value(Json::ValueType)'

### ISSUE THREAD

**Issue by FatmanurKucukayvaz** [open-source-parsers/jsoncpp#738]
I use clion. I want to use json library. But i have soo many problems. Firstly undefined reference to `Json::Value::Value(Json::ValueType)'. How can i solve this problem.

**Comment by ya1gaurav** [comment]
It means you are not linking to libjsoncpp correctly. Can u paste 'make V=1' output.

**Comment by fawdlstty** [comment]
I've had this problem, too. output like this, thx
g++ -std=c++11 -g -DDEBUG -I /usr/include -c *.cpp
g++ -std=c++11 -g -DDEBUG -I /usr/include -o MerchantServer main.o -L /usr/lib64 -lstdc++ -lm -ldl -lpthread -lcrypto -lcurl -liconv -lbsoncxx -lmongocxx -ljsoncpp -ljson
main.o: In function `obj_merchant::get_root()':
/root/project_ms/obj_merchant.hpp:61: undefined reference to `Json::Value::operator=(Json::Value)'
/root/project_ms/obj_merchant.hpp:64: undefined reference to `Json::Value::operator=(Json::Value)'
/root/project_ms/obj_merchant.hpp:68: undefined reference to `Json::Value::append(Json::Value&&)'
/root/project_ms/obj_merchant.hpp:69: undefined reference to `Json::Value::append(Json::Value&&)'
main.o: In function `request_process::do_request(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >)':
/root/project_ms/request_process.hpp:66: undefined reference to `Json::Value::operator=(Json::Value)'
/root/project_ms/request_process.hpp:127: undefined reference to `Json::Value::append(Json::Value&&)'
/root/project_ms/request_process.hpp:128: undefined reference to `Json::Value::append(Json::Value&&)'
/root/project_ms/request_process.hpp:156: undefined reference to `Json::Value::operator=(Json::Value)'
/root/project_ms/request_process.hpp:160: undefined reference to `Json::StreamWriterBuilder::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/root/project_ms/request_process.hpp:160: undefined reference to `Json::Value::operator=(Json::Value)'
/root/project_ms/request_process.hpp:161: undefined reference to `Json::StreamWriterBuilder::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/root/project_ms/request_process.hpp:161: undefined reference to `Json::Value::operator=(Json::Value)'
/root/project_ms/request_process.hpp:162: undefined reference to `Json::writeString[abi:cxx11](Json::StreamWriter::Factory const&, Json::Value const&)'
collect2: error: ld returned 1 exit status
make: *** [MerchantServer] Error 1

**Comment by cdunn2001** [comment]
@fawdlstty, you have jsoncpp compiled with a different C++ ABI than you link against. The easiest solution is to use exactly the same compiler-version to build both library and executable.

**Comment by fawdlstty** [comment]
i want use gcc-7.3.0 to compile, and i use ln "/usr/bin/gcc" and "/usr/bin/g++" to new version, but the cmake still use the old version gcc-4.8.5 to compile, can you fixed it?thx

**Comment by fawdlstty** [comment]
@cdunn2001

**Comment by cdunn2001** [comment]
If there is a problem with the CMakefiles, please submit a fix. We rely on users for that.

We use Meson instead of Cmake for our continuous builds, and that is what I recommend.

**Comment by coleged** [comment]
Thanks for the suggestion. My g++ was already 7.x, so I did a clean build of 8.2.0, and rebuilt jsoncpp. However, it didn't bode well to see that the libjsoncpp.a file differed from the one built using g++7 by just one byte. Needless to say, exactly the same failure to fine any symbols. ......

$ make
g++ -std=c++17 -L.  -ljsoncpp  -c neohub.cpp -o neohub.o
g++ -std=c++17 -L.  -ljsoncpp  -c main.cpp -o main.o
g++ -std=c++17 -L.  -ljsoncpp  -c functions.cpp -o functions.o
g++ -L.  -ljsoncpp   neohub.o  main.o  functions.o \
	 -o nprobe
neohub.o: In function `Neohub::init()':
neohub.cpp:(.text+0xb2): undefined reference to `Json::Value::Value(Json::ValueType)'
neohub.cpp:(.text+0x125): undefined reference to `Json::Value::operator=(Json::Value)'
neohub.cpp:(.text+0x134): undefined reference to `Json::Value::~Value()'
neohub.cpp:(.text+0x148): undefined reference to `Json::Value::Value(Json::ValueType)'
neohub.cpp:(.text+0x17a): undefined reference to `Json::Value::operator[](char const*)'
neohub.cpp:(.text+0x194): undefined reference to `Json::Value::begin()'
neohub.cpp:(.text+0x1aa): undefined reference to `Json::Value::end()'

etc. etc.

**Comment by fawdlstty** [comment]
在这个仓库的issue里面说这个可能比较拆台，在这里给作者赔个不是。。。我建议你，玩玩nlohmann的json，一个头文件，直接引入就好，没有任何其他负担

**Comment by coleged** [comment]
Thanks - I'll look into Niohmann; I was beginning to think jsoncpp looked a bit rusty. It will probably take less time to migrate than it took to compile gcc ;-)

**Comment by cdunn2001** [comment]
Things work much better if you build using **meson**.

JsonCpp is a niche library, with advantages that some people find helpful. There are definitely other libraries available. Cheers!

**Comment by psp3dcg** [comment]
you may have to link the lib by yourself, like this:
g++ main.cpp -o main -L/usr/lib/libjson_linux-gcc-5.4.0_libmt.a /usr/lib/libjson_linux-gcc-5.4.0_libmt.so

**Comment by mad-redhead** [comment]
> It means you are not linking to libjsoncpp correctly. Can u paste 'make V=1' output.

@ya1gaurav Can you please explain what do you mean by that? Im having same issue. Installed jsoncpp through cygwin package installer though.

**Comment by HassanNawazish1** [comment]
main.cpp:8: undefined reference to `Json::Value::Value(Json::ValueType)'
How to fix this issue
?

**Comment by cdunn2001** [comment]
@HassanNawazish1 , I'm pretty sure that exists, so maybe this is an issue with how you link?

**Comment by HassanNawazish1** [comment]
should i change my CMakeLists.txt and if it is then what should i include?

**Comment by fawdlstty** [comment]
Why not serve the library as header only?

**Comment by marduk-eyes** [comment]
Having the same problem from an Ubuntu compile code to archlinux, the code takes an `input.json` and generates an `output.json`.
So in Ubuntu everything compiles fine but in my machine only a version that takes the `input.json` compiles

```
takezono.cpp:(.text+0x11b7): undefined reference to `Json::StreamWriterBuilder::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/bin/ld: takezono.cpp:(.text+0x11cc): undefined reference to `Json::Value::operator=(Json::Value)'
/usr/bin/ld: takezono.cpp:(.text+0x125a): undefined reference to `Json::StreamWriterBuilder::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/bin/ld: takezono.cpp:(.text+0x126f): undefined reference to `Json::Value::operator=(Json::Value)'
/usr/bin/ld: takezono.cpp:(.text+0x13c7): undefined reference to `Json::Value::operator=(Json::Value)'
/usr/bin/ld: takezono.cpp:(.text+0x145c): undefined reference to `Json::Value::operator=(Json::Value)'
/usr/bin/ld: takezono.cpp:(.text+0x14f1): undefined reference to `Json::Value::operator=(Json::Value)'
/usr/bin/ld: takezono.cpp:(.text+0x1586): undefined reference to `Json::Value::operator=(Json::Value)'
/usr/bin/ld: /takezono.o:takezono.cpp:(.text+0x161b): more undefined references to `Json::Value::operator=(Json::Value)' follow
collect2: error: ld returned 1 exit status
make: *** [Makefile:19: main] Error 1
```
This is my makefile(never used meson so I don't know hot to use it)
```makefile
  CC = g++ -std=c++11 -m64 -fopenmp
  BUILDIR = build
  SRCDIR = src
  CFLAGS = -Wall -Wl,--no-as-needed
  INC = ./include
  MKLROOT = /opt/intel/mkl
  NUMPY = /usr/lib/python3.9/site-packages/numpy/core/include
  DAE = $(INC)
  MATPLOTDIR = $(DAE)/external/matplotlib-cpp
  IDIRS = -I$(INC) -I$(MKLROOT)/include -I/usr/include/python3.9 -I$(MATPLOTDIR) -I$(NUMPY)
  LDIRS = -L/usr/lib  -L$(MKLROOT)/lib/intel64 -L/usr/lib/python3.9 -L./lib 
  LIBS = -lm -ldl -lomp -lmkl_core -lmkl_intel_lp64 -lmkl_intel_thread -lpthread -lpython3.9 -ldaecpp -ljsoncpp
  OBJECTS = $(shell find $(SRCDIR) -name "*.cpp" | sed -r "s|$(SRCDIR)/([a-zA-Z]+).cpp|$(BUILDDIR)/\1.o|")
  TARGET = bin/arce
   
  default: main
  
  main: $(OBJECTS)
     $(CC) $(CFLAGS) $(IDIRS) $(LDIRS) $(LIBS) -o $(TARGET) $^
  
  $(BUILDDIR)/%.o: $(SRCDIR)/%.cpp
     @mkdir -p $(BUILDIR)
     $(CC) $(CFLAGS) $(IDIRS) $(LDIRS) $(LIBS) -c $^ -o $@
  clean:
     @echo "Removing $(BUILDIR)/"; rm -r $(BUILDIR) && rm /bin/arce
```
If I remove the link ```-ljsoncpp``` more errors of undefined reference appear

**Comment by cdunn2001** [comment]
If your `libjsoncpp.a` is static, then the order of linking matters.

If it's `libjsoncpp.so`, then order shouldn't matter (since you have `--no-as-needed`, which reverses the default on Ubuntu). In that case, I suspect that the problem is in using a different compiler for jsoncpp than for your own code. The simplest way to ensure that's not the cause is to compile jsoncpp as part of your project.

It's very difficult to debug this remotely. Sorry. I don't think it's a bug in the library though.

**Comment by qshuai** [comment]
C++程序员一半时间在解决编译、链接问题
