### ISSUE TITLE
visual studio c++ reading json file

### ISSUE THREAD

**Issue by ngminteck** [open-source-parsers/jsoncpp#740]
I following the https://en.wikibooks.org/wiki/JsonCpp , trying modify and read my json file.

I get link error at Json::Value

![obj](https://user-images.githubusercontent.com/36160697/35807790-c7ab67a4-0abe-11e8-8644-09d0a81e713b.PNG)
![capture](https://user-images.githubusercontent.com/36160697/35807794-cabe346c-0abe-11e8-8569-dd730a8a626c.PNG)

**Comment by armedturret** [comment]
That error means you haven't set up the library properly in your linker. Go to Project->settings->VC++ directories and add the library directory to additional library directories. Then, go to C++->input, and under additional libraries add the library name.
