### ISSUE TITLE
Can't register libjsoncpp-20.dll

### ISSUE THREAD

**Issue by borsti87** [open-source-parsers/jsoncpp#742]
Hi,

I have builded JsonCpp with Meson and Ninja on Win7 64-bit.
But i can't register the libjsoncpp-20.dll via regsvr32.

![libjsoncpp-20 dll](https://user-images.githubusercontent.com/8202684/36074495-c9f89e7e-0f40-11e8-80cc-4763744177a2.png)

First I tried to build this way:
```
cd c:\jsoncpp\
meson --buildtype debug--default-library shared . build-shared
ninja -v -C build-shared test
cd build-shared
ninja install
```

then I tried:
```
cd c:\jsoncpp\
meson --buildtype release --default-library shared . build-shared
ninja -v -C build-shared test
cd build-shared
ninja install
```

both run in a batch file with admin rights. Always with the same problem.

Can anybody help me?

Thanks borsti87

Version notice:
Meson 0.44.0-64bit
Python 3.6

**Comment by res2k** [comment]
jsoncpp is not a COM component. Running `regsvr32` on it is nonsensical.
