### ISSUE TITLE
How can it build with cmake when it itself is a cmake dependency?

### ISSUE THREAD

**Issue by yurivict** [open-source-parsers/jsoncpp#745]
I am trying to update the FreeBSD port, but it used to be built with scons, and now - only with cmake.
However, cmake itself depends on jsoncpp, which causes a chicken-n-egg problem.

How can I build it without depending on cmake?

**Comment by cdunn2001** [comment]
Interesting. I didn't know that.

Use `meson`. That's what we use in Travis-CI. In fact, we have **cmake** rules only for convenience of some users. We would rather not support **cmake** at all.

Note: For **meson**, you will need python3. But other than that, most people find it much easier than **cmake**.
