### ISSUE TITLE
Is there a omitEndingLineFeed equivalent in StreamWriterBuilder?

### ISSUE THREAD

**Issue by dueringa** [open-source-parsers/jsoncpp#746]
The StreamWriterBuilder documentation doesn't mention an option to omit newlines (i.e. all newlines, I don't want human-readable JSON, it should be as compact as possible). However, FastWriter got deprecated, so its use is discouraged.

I have been using version 1.7.7 previously and just updated to 1.8.4.

**Comment by cdunn2001** [comment]
If you set indentation to `""`, then no newline is written.

I guess the docs need to clarify this, as this question comes up from time to time.
