### ISSUE TITLE
Non-parsable JSON identifies as an array.

### ISSUE THREAD

**Issue by zfields** [open-source-parsers/jsoncpp#754]
Example Code:

```c++
    std::string json("^_^");

    if ( !reader.parse(json, root, false) ) {
        std::cerr << reader.getFormattedErrorMessages();
    }

    if ( root.isArray() ) {
        // debug execution reaches this point
        throw;
    }
```

This code will `throw` inside the second `if` block. The obvious work around is an `else` clause after the first `if`, however I am surprised by this behavior.

**Comment by cdunn2001** [comment]
```cpp
bool Value::isArray() const { return type_ == arrayValue; }
```
I don't understand. How can [that](https://github.com/open-source-parsers/jsoncpp/blob/master/src/lib_json/json_value.cpp#L1432) crash? You'll need to debug this for us.

**Comment by zfields** [comment]
It doesn't crash on the call to `isArray`, it crashes because of the `throw` in the code sample (line 9). The point is, it should never reach the throw statement, because it is not an array.

**Comment by zfields** [comment]
I have also realized that my group uses an older version of `JsonCpp` to support `c++0x` instead of `c++11`. Can you tell me how to identify the version? Is it in a README in the repo?

**Comment by zfields** [comment]
In my version, the logic for `isArray` is:

```c++
bool 
Value::isArray() const
{
   return type_ == nullValue  ||  type_ == arrayValue;
}
```

Which is the source of my problem...

I can see from your link, it has been cleared up.

**Comment by cdunn2001** [comment]
1. Yes.
2. Upgrade. You'll find a version number in a header.
