### ISSUE TITLE
double include

### ISSUE THREAD

**Issue by AlexFundorin** [open-source-parsers/jsoncpp#755]
Why does the library complains when I'm trying to include it into several classes of the same project?

I need to pass reference to json Value objects from one class as arguments to the method of the other class.
When I don't include the library into the second class header, I get multiple errors about "unknown Value object", but when I include it, I get the following errors:
https://i.imgur.com/s54O77C.png

**Comment by BillyDonahue** [comment]
I think we have to close this. Image is now a dead link. No idea what the complaint was.
This was likely a user error. I just verified that we have unique include guards on our headers.
