### ISSUE TITLE
Unicode issue: Not able to serialize properly some character like "式，进"

### ISSUE THREAD

**Issue by afrozm** [open-source-parsers/jsoncpp#756]
When I build a json object containing UTF8 encoded value of string "式，进" 
serialize this json object to string
parse the string again into another json object and read the value
Result: string is lost
here is sample pseudo code
```cpp
Json::Value json;
json["abc"] = UnicodeToUTF8(L"式，进"); // wrapper over MultiByteToWideChar API
// serialize json to string
std::string jsonString = json.toStyledString();
// now parse again
Json::Value json2 = parse(jsonString); // parse using Json::CharReader
std::wstring unicodeString = UTF8ToUnicode(json2["abc"]); // wrapper over MultiByteToWideChar API
assert(unicodeString == L"式，进"); // fails
```
I checked `UnicodeToUTF8` and `UTF8ToUnicode` works fine.
The only problem I see in `toStyledString()` API which make character encoding weird in output

**Comment by BillyDonahue** [comment]
This is an incomplete repro and it's hard to help you.

"I checked UnicodeToUTF8 and UTF8ToUnicode works fine." How do you know that? What do they produce? Why not include them? Repro should start and end with the utf8, so we aren't relying on functions we don't have access to.

You also just said that your assert fails, but not how. That doesn't really help.

Where's the body of 'parse'?

We need exact stimulus and response involving only the jsoncpp library if possible.
There are too many moving parts in your example.

**Comment by SuperBlc** [comment]
In the main.cpp, about `Line1651`
I change
```c++
const std::string uni =  u8"式，进"; // "\u5f0f\uff0c\u8fdb"
```
to
```c++
const std::string uni = "\u5f0f\u77db\u839e";
```

and  it works.
