### ISSUE TITLE
CharReaderBuilder and C++11

### ISSUE THREAD

**Issue by Viatorus** [open-source-parsers/jsoncpp#758]
My project is using the Json::Reader, which is now deprecated:

```cpp
Json::Reader reader;

std::string input = "{}";
Json::Value output;

if (!reader.parse(input, output)) {
  throw ...
}
```

The new equivalent is (with my understanding):
```cpp
Json::CharReaderBuilder builder;
Json::CharReader *reader = builder.newCharReader();

std::string input = "{}";
Json::Value output;
std::string errors;

if (!reader->parse(input.c_str(), input.c_str() + input.length(), &output, &errors)) {
  throw ...
}

delete reader;
```

I am unsure if I get this right but is this "alternative API" of using the CharReaderBuilder *highly* uncomfortable and error-prone.

Is there an easier and safer way to simply parse a string?

**Comment by cdunn2001** [comment]
```cpp
std::istringstream sin(input);
output << sin;
```

The defaults are usually fine.

If you want to customize, then you need to accept the trade-offs. We try hard to maintain binary compatibility. That's why the implementation of the CharReader is hidden.

**Comment by Viatorus** [comment]
Thank you. This worked:

```cpp
std::istringstream sin(input);
sin >> output;
```
