### ISSUE TITLE
Parser state in case of Junk data.

### ISSUE THREAD

**Issue by ya1gaurav** [open-source-parsers/jsoncpp#76]
My application is doing exception handling for the throw done by Jsoncpp like in JSON_FAIL_MESSAGE & JSON_ASSERT_MESSAGE.
If application receives junk data somehow, it catches exception & start to parse again because next time it can expect correct data. It can try for say 10 times till it receives correct data.

In such a case, is it fine to use same Json::Value object or do we need change some state of parser ?

**Comment by cdunn2001** [comment]
I wouldn't expect the Reader to be re-entrant. To be safe, just create a new Reader for the next call.
