### ISSUE TITLE
How to serialize a Json::Value to a unordered string?

### ISSUE THREAD

**Issue by lls2wow** [open-source-parsers/jsoncpp#763]
Hi @cdunn2001 ,
Could you tell me if there's a new branch solve the order problem from now on ? I'd reather serialize a Json::Value to string like {'C':'xxxx','B':'xxxx','A':'XXXX' } not {'A':'xxxx','B':'xxxx','C':'XXXX' }

Thank you very much

**Comment by cdunn2001** [comment]
Sorry. Nothing yet.
