### ISSUE TITLE
Parsing from string

### ISSUE THREAD

**Issue by felixschlesinger** [open-source-parsers/jsoncpp#778]
With the new API (based on Reader/Writer Builder) what is the preferred way to parse a Json Value from a string? Is it: Make a ReaderBuilder, Make a Reader (through unique_pointer), get pointers (not iterators) to string beginning/end, use reader.parse? I see utility functions for parsing streams but not strings.

Thanks (and sorry, I am most likely missing something obvious).

**Comment by cdunn2001** [comment]
See #779. If you have std::string, you may as well use std::istringstream. If you want low-level `char*`, you have to use the lower-level methods.

I'm closing this, but you can join the discussion in #779 if you want.
