### ISSUE TITLE
why don't operator= for Json::Value?

### ISSUE THREAD

**Issue by hsnks100** [open-source-parsers/jsoncpp#779]
example:
```
std::string strJson = R"({"foo": "bar"})";
Json::Value root = strJson; // if it implement operator=(std::string&)
```

instead
```
std::string strJson = R"({"foo": "bar"})";

Json::CharReaderBuilder builder;
Json::CharReader* reader = builder.newCharReader();

Json::Value json;
std::string errors;

bool parsingSuccessful = reader->parse(
    strJson.c_str(),
    strJson.c_str() + strJson.size(),
    &json,
    &errors
);
delete reader;
```

My think is the former is very convenient than the latter. Why don't operator= for Json::Value?

**Comment by cdunn2001** [comment]
The latter allows a lot of configuration of the builder. We can add features without breaking binary compatibility.

The former is almost legal code already. Try this:
```cpp
Json::Value json;
std::istringstream sin(R"({"foo": "bar"})");
sin >> json;
```

As for `operator=()`, I think there is a lot of discussion in the issue archives, pros and cons.

**Comment by felixschlesinger** [comment]
I would prefer a top-level function
Value readString(CharReaderFactory, std::string)
similar to the top-level writeString function.
Maybe with another overload supporting &errors and &value and returning bool success.

That way allows configuring the reader, but is much easier to use than the full version above.

**Comment by cdunn2001** [comment]
Push a PR for `readString()`. I think it can ignore the "errors" string.

I might not be able to merge for couple weeks though.
