### ISSUE TITLE
python amalgamate.py - error #include <json/config.h>

### ISSUE THREAD

**Issue by pavel-pimenov** [open-source-parsers/jsoncpp#782]
fatal error C1083: Cannot open include file: 'json/config.h': No such file or directory

Fix
#if !defined(JSON_IS_AMALGAMATION)
#include <json/config.h>
#endif

?

**Comment by kuang93** [comment]
I have the same error with you, finally i fix it with switching the branch to "0.y.z", and run "python amalgamate.py"

**Comment by hhyyrylainen** [comment]
I also had this same error. And everything worked after I added that `#if !defined(JSON_IS_AMALGAMATION)` check.

**Comment by cdunn2001** [comment]
Add it where? Can this be added only to `amalgamate.py`? Please submit a PR so we can fix this permanently.

**Comment by hhyyrylainen** [comment]
After amalgamating the latest version adding that check around line 95. This is the code around that area (starting from line 83):
```
// //////////////////////////////////////////////////////////////////////
// Beginning of content of file: src/lib_json/json_tool.h
// //////////////////////////////////////////////////////////////////////

// Copyright 2007-2010 Baptiste Lepilleur and The JsonCpp Authors
// Distributed under MIT license, or public domain if desired and
// recognized in your jurisdiction.
// See file LICENSE for detail or copy at http://jsoncpp.sourceforge.net/LICENSE

#ifndef LIB_JSONCPP_JSON_TOOL_H_INCLUDED
#define LIB_JSONCPP_JSON_TOOL_H_INCLUDED

#if !defined(JSON_IS_AMALGAMATION)
#include <json/config.h>
#endif

// Also support old flag NO_LOCALE_SUPPORT
#ifdef NO_LOCALE_SUPPORT
#define JSONCPP_NO_LOCALE_SUPPORT
#endif

#ifndef JSONCPP_NO_LOCALE_SUPPORT
#include <clocale>
#endif
```
