### ISSUE TITLE
Is this really supported in JSONCPP library using c++ code

### ISSUE THREAD

**Issue by manoalt** [open-source-parsers/jsoncpp#794]
{
  "location": {
  }
}
Need help to generate this above lines of JSON string, i tried using Json::Value::empty , null and "". 
Is this really supported using this jsoncpp library using c++ code?

**Comment by kscxx** [comment]
use jsoncpp like this:
``` C++

	Json::Value root(Json::objectValue);
	Json::Value location(Json::objectValue);
	root["location"] = location;

	string sroot(Json::StyledWriter().write(root));

```
and you'll get what you want.

**Comment by manoalt** [comment]
Thank you 👍

**Comment by cdunn2001** [comment]
`StyledWriter` is deprecated. `StreamWriterBuilder` is more configurable. But you can also simply use `>>`.
```cpp
std::ostringstream sout;
sout << root;
```
