### ISSUE TITLE
Incorrect output with -DNDEBUG

### ISSUE THREAD

**Issue by jitaogithub** [open-source-parsers/jsoncpp#805]
I found a weird behavior of the library. When I compile this piece of code:
```
#include <iostream>
#include <string>
#include <cassert>
#include <jsoncpp/json/json.h>
int main () {
    std::string exampleString = "{  \"a\": 1,\n  \"b\": 2,\n \"c\": 123456789\n}";
    Json::Value parsedFromString;
    Json::Reader reader;
    assert(reader.parse(exampleString, parsedFromString));
    std::cout << parsedFromString["a"].asInt() << std::endl 
              << parsedFromString["b"].asInt() << std::endl  
              << parsedFromString["c"].asUInt64() << std::endl;
    return 0;
}
```
with command line:
`g++ -std=c++11 -DNDEBUG test.cpp -o test -ljsoncpp`
and run with
`./test`
The result is:
```
0
0
0
```
However, if I remove  `-DNDEBUG` then the result is correct:
```
1
2
123456789
```
Could anyone help with this problem? Thank you in advance.

Environment:
```
ubuntu 16.04
    kernel 4.13.0
gcc 5.4.0
jsoncpp 1.7.2
```

**Comment by cdunn2001** [comment]
```cpp
assert(reader.parse(exampleString, parsedFromString));
```
LOL. I actually reproduced your error before I noticed this glaring mistake. `-DNDEBUG` removes this `assert()` from your own code! Without it, `parse()` is never called.
