### ISSUE TITLE
Compile time error in reader.h

### ISSUE THREAD

**Issue by BhayanakMoth** [open-source-parsers/jsoncpp#810]
I am new  to Jsoncpp and I was trying to run this code:
![devenv_2018-07-18_14-41-04](https://user-images.githubusercontent.com/17413156/42871706-a62aaa2c-8a98-11e8-981a-023587c7ff64.png)
When I tried to compile the code I got these errors and I don't understand how to solve them.
![devenv_2018-07-18_14-43-30](https://user-images.githubusercontent.com/17413156/42871858-f900a828-8a98-11e8-82e6-e82b69d2d5fb.png)
I don't understand what's happening, I went to check what the errors were pointing to but there were no syntax errors. Is it because I am using CharReader incorrectly? 
I installed jsoncpp using vcpkg.

**Comment by cdunn2001** [comment]
I guess this is related to #686 for VisualStudio. If you know the proper way to deprecate code for VS, please help by offering a PR.
