### ISSUE TITLE
Reader::pushError() maybe has typeset error

### ISSUE THREAD

**Issue by lymslive** [open-source-parsers/jsoncpp#812]
Recently I'm reading and learning the source, and seam to find a error:

in file json_reader.cpp:861(Reader::pushError)
token.end_ = end_ + value.getOffsetLimit();

I'm confused, maybe it should be:
token.end_ = begin_ + value.getOffsetLimit();

And in json_reader.cpp:1876 (OurReader::pushError) seams to have the same error.

**Comment by cdunn2001** [comment]
Not sure. (And I never liked the pushError stuff.) Try an example and see if anything is wrong.

**Comment by lilinchao-git** [comment]
As lymslive mentioned above，there are obvious contradictions at line 843 and line 862 in function pushError().

**Comment by baylesj** [comment]
Fixed in #930
