### ISSUE TITLE
Json parsing does not catch missing open and closing braces in JSON file.

### ISSUE THREAD

**Issue by XainFaith** [open-source-parsers/jsoncpp#813]
I had an incorrectly formatted Json file where it was missing the Opening { and the closing } no errors reported when parsing however exceptions were thrown when attempting to read data in from Json::Value.

Expected behavior is that an exception would be thrown on on parsing of json data into Json::Value.

if you need the code that produce this error on my system i would be more then happy to provide it as its a small section of code. 

I am also using the amalgamated source.

**Comment by cdunn2001** [comment]
The newer WriterBuilder should allow configuration which says whether an error should cause failure.

Yes, a code snippet is helpful, plus a small test-case. This might not be a bug. JsonCpp is not designed as a JSON validation tool.

**Comment by Curley-Joe** [comment]
I ran into the same issue.  I was sending messages through RabbitMQ and parsing with JsonCpp and one of the messages looked like this:

"key" : "value"

It parsed fine, but I was not able to read the value because it wasn't an object.

**Comment by cdunn2001** [comment]
You'd need to submit more details. Again, the Reader and Writer can be configured to catch most errors.

But note that `"key"` is valid JSON. It's just a "string". The parser stops parsing when it finishes a valid input. You might be able to check yourself whether any characters of the input remain unconsumed.
