### ISSUE TITLE
error C4996: 'Json::Reader': Use CharReader and CharReaderBuilder instead

### ISSUE THREAD

**Issue by lzpong** [open-source-parsers/jsoncpp#815]
error C4996: 'Json::Reader': Use CharReader and CharReaderBuilder instead
error C4996: 'Json::Reader::parse': Use CharReader and CharReaderBuilder instead

```cpp
	Json::Reader reader;
	Json::Value root;
	char dd[] = "{a:'1',b:1}";
	bool bo = reader.parse(dd, dd + sizeof(dd), root);
```
why it has err?
class of `Json::Reader` for what? it can not be use?

**Comment by BillyDonahue** [comment]
Message C4996 is only a warning.

https://msdn.microsoft.com/en-us/library/ttcz0bys.aspx

You seem to have your build set to make the warning fatal.

`Json::Reader` is retained for backward compatibility and shouldn't be used in new code.

**Comment by ganeshkamath89** [comment]
Can someone give an example replacing 'Json::Reader' with 'CharReader'/'CharReaderBuilder' please

**Comment by dota17** [comment]
> Can someone give an example replacing 'Json::Reader' with 'CharReader'/'CharReaderBuilder' please

See the example [here](https://github.com/open-source-parsers/jsoncpp/blob/master/example/readFromString/readFromString.cpp).

**Comment by ganeshkamath89** [comment]
Thankyou @dota17 

I used your example code to replace my code:

```
Json::Reader reader;
reader.parse("{}", root);
```

with
```
JSONCPP_STRING err;
string rawJson = "{}";
Json::CharReaderBuilder builder;
const std::unique_ptr<Json::CharReader> reader(builder.newCharReader());
reader->parse(rawJson.c_str(), rawJson.c_str() + rawJson.length(), &root, &err);
```

**Comment by cdunn2001** [comment]
If you don't want to configure anything, [simply use this](https://open-source-parsers.github.io/jsoncpp-docs/doxygen/index.html#_example):
```cpp
Json::Value root; 
std::istringstream sin("{}");
sin >> root;
```

For an example with the Builders, [see docs](https://open-source-parsers.github.io/jsoncpp-docs/doxygen/index.html#_advanced).

**Comment by wengjianhong** [comment]
> Thankyou @dota17
> 
> I used your example code to replace my code:
> 
> ```
> Json::Reader reader;
> reader.parse("{}", root);
> ```
> 
> with
> 
> ```
> JSONCPP_STRING err;
> string rawJson = "{}";
> Json::CharReaderBuilder builder;
> const std::unique_ptr<Json::CharReader> reader(builder.newCharReader());
> reader->parse(rawJson.c_str(), rawJson.c_str() + rawJson.length(), &root, &err);
> ```

more and more complex......

**Comment by cdunn2001** [comment]
@wengjianhong , I don't understand what you're saying.

```cpp
Json::Value root; 
cin >> root;
```
What's so complex?

**Comment by wengjianhong** [comment]
> @wengjianhong , I don't understand what you're saying.
> 
> ```c++
> Json::Value root; 
> cin >> root;
> ```
> 
> What's so complex?

I means in this version, I have to create   jsonBuilder  and  JsonReader.
and the parse  function,,, I feel is not easily use.
```C++
    Json::Value jsonRoot;
    Json::CharReaderBuilder  jsonBuilder;
    Json::CharReader* JsonReader(jsonBuilder.newCharReader());

    if (JsonReader->parse(str.c_str(), str.c_str() + str.size(), &jsonRoot, nullptr)) {
        // ...
    }
```

**Comment by BillyDonahue** [comment]
There are some things in your code that could be simplified, but Jsoncpp could be friendlier too.

Starting with:

```c++
Json::Value jsonRoot;
    Json::CharReaderBuilder  jsonBuilder;
    Json::CharReader* JsonReader(jsonBuilder.newCharReader());
    if (JsonReader->parse(str.c_str(), str.c_str() + str.size(), &jsonRoot, nullptr)) {
        // ...
    }
```

- For this use case, of not customizing the builder, parsing a string input, discarding the error strings (you gave nullptr), you really could do the `operator>>` suggestion.  But you do care if the parse succeeds so you should catch.

```c++
    Json::Value jsonRoot;
    try {
        std::istringstream{str} >> jsonRoot;
    } catch (const std::exception& e) {
        // ... (same error handling code as above, more or less).
    }
```

 - The builder should add a function that produces `unique_ptr<CharReader>`, and deprecate `newCharReader`. There's no reason for users to deal with the cleanup manually. Your code leaks the `JsonReader` pointer. I like to give builders a call operator so they can be used as factory function-like objects.

- The `reader->parse` should have some way to take a range-like single argument. We should not be forcing people do deal with `c_str` really.

- We should have a variant of `parse` that just returns the jsonRoot and throws on failure.

With these enhancements, I think you have:

```c++
auto jsonRoot = Json::CharReaderBuilder{}()->parse(str);
```

This might throw. But that might not be the immediate caller's concern. It can be handled by whoever prepared the `str` argument or something. Caller decides, which is the point of exceptions.

**Comment by wengjianhong** [comment]
Thank you for your replies, useful suggestions and corrections very much.
You're the most helpful person I've ever met, Ha, ha, ha....
Thank you again very much!!!

**Comment by wengjianhong** [comment]
> There are some things in your code that could be simplified, but Jsoncpp could be friendlier too.
> 
> Starting with:
> 
> ```c++
> Json::Value jsonRoot;
>     Json::CharReaderBuilder  jsonBuilder;
>     Json::CharReader* JsonReader(jsonBuilder.newCharReader());
>     if (JsonReader->parse(str.c_str(), str.c_str() + str.size(), &jsonRoot, nullptr)) {
>         // ...
>     }
> ```
> 
> * For this use case, of not customizing the builder, parsing a string input, discarding the error strings (you gave nullptr), you really could do the `operator>>` suggestion.  But you do care if the parse succeeds so you should catch.
> 
> ```c++
>     Json::Value jsonRoot;
>     try {
>         std::istringstream{str} >> jsonRoot;
>     } catch (const std::exception& e) {
>         // ... (same error handling code as above, more or less).
>     }
> ```
> 
> * The builder should add a function that produces `unique_ptr<CharReader>`, and deprecate `newCharReader`. There's no reason for users to deal with the cleanup manually. Your code leaks the `JsonReader` pointer. I like to give builders a call operator so they can be used as factory function-like objects.
> * The `reader->parse` should have some way to take a range-like single argument. We should not be forcing people do deal with `c_str` really.
> * We should have a variant of `parse` that just returns the jsonRoot and throws on failure.
> 
> With these enhancements, I think you have:
> 
> ```c++
> auto jsonRoot = Json::CharReaderBuilder{}()->parse(str);
> ```
> 
> This might throw. But that might not be the immediate caller's concern. It can be handled by whoever prepared the `str` argument or something. Caller decides, which is the point of exceptions.

Thank you for your replies, useful suggestions and corrections very much.
You're the most helpful person I've ever met, Ha, ha, ha....
Thank you again very much!!!

**Comment by lzpong** [comment]
**I do that, make it easy to use:** (v1.8.4)
```cpp
//json_value.cpp
//sstringify Json object to a string, with format or not (2018/12/19)
JSONCPP_STRING Value::stringify(bool fmt) {
	StreamWriterBuilder builder;
	if (!fmt)
		builder["indentation"] = "";//去掉缩进格式
	return writeString(builder, *this);
}
```
```cpp
//json_reader.cpp
//Parse c-str json to Json object (2018/11/29)
bool Value::parse(const char* jsonStr, size_t strLen, JSONCPP_STRING* errs) {
	CharReaderBuilder rreader;
	CharReaderPtr const  reader(rreader.newCharReader());
	bool b = reader->parse(jsonStr, jsonStr + (strLen >0? strLen :strlen(jsonStr)), this, errs);
	return b;
}
bool Value::parse(JSONCPP_STRING json, JSONCPP_STRING* errs) {
    return parse(json.data(), json.length(), errs);
}
```
**Used like this:**
```cpp
std::string str="{}",err;
Json::Value json;
bool b = json.parse(str, &err);
bool b = json.parse(str.data(), str.size(), &err);
```

**Comment by Zhaotiedan** [comment]
> > There are some things in your code that could be simplified, but Jsoncpp could be friendlier too.
> 
> > 
> 
> > Starting with:
> 
> > 
> 
> > ```c++
> 
> > Json::Value jsonRoot;
> 
> >     Json::CharReaderBuilder  jsonBuilder;
> 
> >     Json::CharReader* JsonReader(jsonBuilder.newCharReader());
> 
> >     if (JsonReader->parse(str.c_str(), str.c_str() + str.size(), &jsonRoot, nullptr)) {
> 
> >         // ...
> 
> >     }
> 
> > ```
> 
> > 
> 
> > * For this use case, of not customizing the builder, parsing a string input, discarding the error strings (you gave nullptr), you really could do the `operator>>` suggestion.  But you do care if the parse succeeds so you should catch.
> 
> > 
> 
> > ```c++
> 
> >     Json::Value jsonRoot;
> 
> >     try {
> 
> >         std::istringstream{str} >> jsonRoot;
> 
> >     } catch (const std::exception& e) {
> 
> >         // ... (same error handling code as above, more or less).
> 
> >     }
> 
> > ```
> 
> > 
> 
> > * The builder should add a function that produces `unique_ptr<CharReader>`, and deprecate `newCharReader`. There's no reason for users to deal with the cleanup manually. Your code leaks the `JsonReader` pointer. I like to give builders a call operator so they can be used as factory function-like objects.
> 
> > * The `reader->parse` should have some way to take a range-like single argument. We should not be forcing people do deal with `c_str` really.
> 
> > * We should have a variant of `parse` that just returns the jsonRoot and throws on failure.
> 
> > 
> 
> > With these enhancements, I think you have:
> 
> > 
> 
> > ```c++
> 
> > auto jsonRoot = Json::CharReaderBuilder{}()->parse(str);
> 
> > ```
> 
> > 
> 
> > This might throw. But that might not be the immediate caller's concern. It can be handled by whoever prepared the `str` argument or something. Caller decides, which is the point of exceptions.
> 
> 
> 
> Thank you for your replies, useful suggestions and corrections very much.
> 
> You're the most helpful person I've ever met, Ha, ha, ha....
> 
> Thank you again very much!!!

Excuses me,Why do I have a Debug error after I follow the above steps?
![image](https://user-images.githubusercontent.com/48014011/117981143-470d7600-b367-11eb-8c1e-9ea9040f3473.png)

**Comment by Zhaotiedan** [comment]
> Thankyou @dota17 
> 
> 
> 
> I used your example code to replace my code:
> 
> 
> 
> ```
> 
> Json::Reader reader;
> 
> reader.parse("{}", root);
> 
> ```
> 
> 
> 
> with
> 
> ```
> 
> JSONCPP_STRING err;
> 
> string rawJson = "{}";
> 
> Json::CharReaderBuilder builder;
> 
> const std::unique_ptr<Json::CharReader> reader(builder.newCharReader());
> 
> reader->parse(rawJson.c_str(), rawJson.c_str() + rawJson.length(), &root, &err);
> 
> ```
> 
> 

Excuse me,Why do I have a Debug error ?can you help me?![image](https://user-images.githubusercontent.com/48014011/117984861-c94b6980-b36a-11eb-9290-45487ddacd30.png)

**Comment by BillyDonahue** [comment]
Mysterious. This might be a DLL issue.

Memory has to be released by the same DLL that allocated it. Jsoncpp and the app testjson.exe should ideally both be using the dynamic MSVCRT for their allocations, but it looks like something is misconfigured.

Maybe this will help: ?
https://stackoverflow.com/questions/35310117/debug-assertion-failed-expression-acrt-first-block-header

**Comment by Zhaotiedan** [comment]
> Mysterious. This might be a DLL issue.
> 
> 
> 
> Memory has to be released by the same DLL that allocated it. Jsoncpp and the app testjson.exe should ideally both be using the dynamic MSVCRT for their allocations, but it looks like something is misconfigured.
> 
> 
> 
> Maybe this will help: ?
> 
> https://stackoverflow.com/questions/35310117/debug-assertion-failed-expression-acrt-first-block-header
> 
> 

Thanks so much,I have solved the problem. I changed my runtime library to DLL(MDd)
