### ISSUE TITLE
[Bug] Adding a comment first, then gets overwritten by setting other attribute

### ISSUE THREAD

**Issue by BSVogler** [open-source-parsers/jsoncpp#817]
Tested it by writing to a file.
Does work (comment in file):
```C++
root["A"]["B"] = 0.0f;
root["A"].setComment("//Test", Json::commentAfterOnSameLine);
```

Doesn't work (no comment in file):
```C++
root["A"].setComment("//Test", Json::commentAfterOnSameLine);
root["A"]["B"] = 0.0f;
```

**Comment by cdunn2001** [comment]
Hmmm. If you have a fix, please submit a PR. Otherwise, closing as relatively low-priority. In fact, I'm not sure it's a bug, as it's not clear what to do when over-writing a value and retaining comments.
