### ISSUE TITLE
v1.8.4 to v1.6.5

### ISSUE THREAD

**Issue by guigros** [open-source-parsers/jsoncpp#818]
Hello everyone,

I have a C++ MFC project using jsoncpp v1.8.4, everythings works fine.
I need to downgrade to version 1.6.5 to match the version used in an old project (This project used v1.6.5 because it is compiled with MS Toolset v90).

To do so, I've just recompile lib_json.lib and link against my project. It compiles but I'm unable to link the lib, the linker is throwing  "unresolved external symbol" error. I guess it's because my code (previously using v1.8.4) uses stuff that was not in v1.6.5.

For example, the first error is : 
`lib_json.lib(json_value.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >(char const *,char const *)" (__imp_??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@PBD0@Z) referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall Json::ValueIteratorBase::name(void)const " (?name@ValueIteratorBase@Json@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)
`
Could you help me to point what kind of call to the library could be concerned by this linking error ? Or is there a way to compile v1.8.4 with MS Toolset v90 ?

**Comment by cdunn2001** [comment]
No idea. Good luck!
