### ISSUE TITLE
[0.10.6] __GNUC__ macro does not guarantee that std::scoped_ptr exists

### ISSUE THREAD

**Issue by Phibonacci** [open-source-parsers/jsoncpp#828]
I compiled a GCC 7.3.0 on Centos 6 and compile my program using C++98 without the C++11 API thanks to the flag : `-D_GLIBCXX_USE_CXX11_ABI=0`.

The following code does not compile as scoped_ptr is not an std type.

```c++
#if __GNUC__ >= 6
typedef std::scoped_ptr<CharReader> const  CharReaderPtr;
#else
typedef std::auto_ptr<CharReader>          CharReaderPtr;
#endif
```

I don't know in which std version std::scoped_ptr exists but it does not seem to be part of the STL, if it was part of C++11 then a `__cplusplus >= 201103L`  condition would solve the issue. __GNUC__ only gives the GCC version and does not guarantee the presence of scoped_ptr.

To solve my issue I kept only the auto_ptr typedef.

**Comment by hkhatri241** [comment]
Please see #600

**Comment by Phibonacci** [comment]
The issue comes from the 0.10.6 from the release section of GitHub.

The tip of the 0.x.y branch does not contain a scoped_ptr declaration. The preprocessing conditions have been removed and only the auto_ptr typdef remains.

I believe a new release would solve this issue.

**Comment by cdunn2001** [comment]
Ok. I'll tag a new release tonight.

**Comment by cdunn2001** [comment]
`0.10.7`
