### ISSUE TITLE
How to submmit a security issue

### ISSUE THREAD

**Issue by zdzhjx** [open-source-parsers/jsoncpp#838]
I have found a security issue, but dont know how to submmit? 

As the issue will bring damage to some application, I think this should not submit here, any idea?

Thanks.

**Comment by cdunn2001** [comment]
Well, it would be obvious from the merge-commit for the eventual fix anyway. So just submit a PR here and we'll merge it quickly.

**Comment by baylesj** [comment]
+1. We definitely want to fix all security issues. Just submit the issue and we will try to respond promptly with a fix, depending on severity.

**Comment by baylesj** [comment]
Please open a new issue with the security problem that you have found.
