### ISSUE TITLE
(Double)Real value write as Integer

### ISSUE THREAD

**Issue by dcracker** [open-source-parsers/jsoncpp#85]
```
Value json;
json["dbl"] = 0.0;
// json["dbl"].type() == realValue

FastWriter writer;
string str = writer.write( json );
// "dbl" becomes 0

Reader reader;
reader.read( str, json );
// json["dbl"].type() == intValue
```

writer's sprintf with %g doesn't print dot when 0 below.
%lf is OK. but not optimized.
Maybe need to add some codes.
Or am I misunderstand something?

**Comment by ondratu** [comment]
Hi, 
in my opinion that is bad solution.

If is possible to write same output as is read, it could be write. So when you have some clever mechanism to identify number as int, resp. real, you could write real. This do python for example.

I know, that i can retype values to real from int, but for generic reading, type changing is problem.

**Comment by cdunn2001** [comment]
@ondratu, I don't think this happens for the StreamWriter, does it?

**Comment by cdunn2001** [comment]
Hmmm. I could be wrong, but I think the most recent commit to `master` actually appends a `.` always. Could you try that?

**Comment by ondratu** [comment]
Yes, master works. Thanks a lot ;-)
