### ISSUE TITLE
json_object

### ISSUE THREAD

**Issue by joslenbomon** [open-source-parsers/jsoncpp#852]
Hello!
i got project where i can see type json_object
in current LIB i can not find this type.
i guess this type exist in previous version of json lib.
can anybody tell me where i can download this type.
problem string:
static json_object * packet_list_to_json()
in this function compiler can not find type json_object

please help me

**Comment by BillyDonahue** [comment]
Doesn't look familiar, and jsoncpp doesn't use that "snake case" (underscore-separated words) naming convention. Check your other dependencies for it.
