### ISSUE TITLE
Undepricate StyledWriter or provide better serialization options

### ISSUE THREAD

**Issue by pps83** [open-source-parsers/jsoncpp#874]
Seems that latest jsoncpp has deprecated StyledWriter:
```
class JSONCPP_DEPRECATED("Use StreamWriterBuilder instead") JSON_API
    StyledWriter : public Writer {
```
and suggests to use StreamWriterBuilder instead. But StreamWriterBuilder doesn't provide similar functionality and uses std::streams for output. It may come to you as a socking surprise perhaps, but many companies do not like or outright ban std::streams in their code. On top of that StreamWriterBuilder has somewhat questionable interface: you create it, set some json values on it, and then create from it a streaming writer. Why not plain c++ struct with all the properties clearly visible, so we wouldn't need to dig docs or the code to see what properties are supported? Also, why not have simple interface as a member function on the Value itself:

```
Value json;
...
std::string jsonStr = json.serialize();
```

`serialize` may accept optional SerializationOptions struct that would override default serialization options. It may even accept a json object for that. It may as well accept std::ostream for those who prefer to serialize to a stream. Internally `serialize` may even use that awkward StreamWriterBuilder (as long as it doesn't use std::streams by default), but the goal/end result is: it should be possible to get json string in just a single line of code instead of requiring some weird mambo jumbo for those who do not care about all of that stuff.

**Comment by cdunn2001** [comment]
The "builder pattern" is popular in Java. I don't know why C++ coders hate it so much.

The reason it's used here is to allow us to alter the implementation more easily without breaking breaking backward compatibility.

> It may come to you as a socking surprise perhaps, but many companies do not like or outright ban std::streams in their code.

You can't even link with streams? That is shocking. They're pretty efficient.

> mambo jumbo

Why don't you write the wrapper that you want, and use that always? I don't understand the problem. And if you submit a PR with wrapper, I think we would merge that in, if it's that important to you. But you'd still need to *link* with streams.

**Comment by pps83** [comment]
I don't know what c++ coders hate, but I definitely prefer to avoid sticking popular patterns here and there just because they are popular.
The problem with streams imo: every input operation is actually a function call that most likely involves lots of other function calls. It's uncomparable to printf not only in code size, but quite often in terms of performance as well. If you have 10 local chars on the stack and try to output them, you'll get tons of hairy machine code generated. Uncomparable to nice code generated by printf.

Regarding builder pattern: why would anybody ever care what pattern it is: what do you usually need to do with json docs: you only serialize them (eg convert to a string), there isn't much use to them when you build them yourself. Why would you need any other helper class that does the work? I don't know.
Only if you need to serialize to a stream, then yes, perhaps regular `operator<<` overload would not be enough to support serialization style options and a helper class might be added, but `operator<<` should be sufficient by itself to output a valid json doc/value. But most common scenario is to produce a string representation from a json object and I don't see a point to use streams in this case and make that trivial operation dependent on quite non-trivial infrastructure provided by streams.

I don't use jsoncpp (we use rapidjosn with our own wrapper on top to make it sane), it just happened that multiple projects that I link to use jsoncpp and these projects use vastly different version of the jsoncpp. webrtc is a giant beast uses some ancient version of jsoncpp and then probably never bothered to update, and OpenVR uses some version of jsoncpp. So , I kind of had no choice but to try to update these projects to common version of jsoncpp. So, I saw some issues, I tried to make a couple of PRs that weren't accepted anyways (not sure if there was an alternative solution made or not).

**Comment by leesangj** [comment]
https://github.com/google/leveldb/blob/master/mailto:sanjay@google.com

**Comment by cdunn2001** [comment]
@pps83, **rapidjson** is good. Personally, I am a big fan of **gason**. **jsoncpp* fits a niche, and one requirement is to maintain ABI compatibility. That's difficult with new features. The builder-pattern allows us to configure the underlying object without exposing it.

I agree on streams. But then, I'm not a fan of C++ in general.

I guess we could technically "undeprecate" `StyledWriter` if it's so popular, but we will never actually alter it. Please submit a PR to undeprecate and we'll merge it.

**Comment by baylesj** [comment]
@pps83 I think the general idea now is that WebRTC and Chromium are going to update to using the new StreamWriterBuilder, as part of updating their JsonCpp dependencies. See this patch:

https://chromium-review.googlesource.com/c/chromium/src/+/1674449

With them updating, do you still have this issue?

**Comment by pps83** [comment]
should be ok now, thanks
