### ISSUE TITLE
JsonCpp is insecure

### ISSUE THREAD

**Issue by lamefun** [open-source-parsers/jsoncpp#88]
Doesn't allow to set nesting limit and segfaults on deeply nested objects.

**Comment by cinemast** [comment]
This is a security issue. It should not be closed that easily. Every application using jsoncpp is vulnerable to DOS attacks.

It has already been discussed and just closed here:
https://github.com/open-source-parsers/jsoncpp/issues/56

Please don't do that.

**Comment by cdunn2001** [comment]
We can't easily remove the recursion, but we can easily provide a feature to limit the recursion. Fair enough?

**Comment by cinemast** [comment]
A limit would already solve the problem, yes. Please add a limit.
