### ISSUE TITLE
Problem when compiling with Visual Studio 2010

### ISSUE THREAD

**Issue by AlessandroDUffizi** [open-source-parsers/jsoncpp#882]
I have successfully compiled jsoncpp with Visual studio 2017 and Windows 7
Now I'm trying to do the same with Visual studio 2010 over my laptop with Windows 10.

I got Sintax Error in json_value.cpp each time in the code I found:

---->          return {}; 
Errore	8	error C2059: errore di sintassi: '{'	c:\users\alessandro\chaos_compile\jsoncpp-master\src\lib_json\json_value.cpp	1533	1	lib_json

Errore	9	error C2143: errore di sintassi: ';' mancante prima di '{'	c:\users\alessandro\chaos_compile\jsoncpp-master\src\lib_json\json_value.cpp	1533	1	lib_json

Errore	10	error C2059: errore di sintassi: '{'	c:\users\alessandro\chaos_compile\jsoncpp-master\src\lib_json\json_value.cpp	1546	1	lib_json

Errore	11	error C2143: errore di sintassi: ';' mancante prima di '{'	c:\users\alessandro\chaos_compile\jsoncpp-master\src\lib_json\json_value.cpp	1546	1	lib_json

It seems like the compiler don't recognize {} as a constant empty json value.

I used the msvc2010 jsoncpp.sln   already provided in the Master branch.
I did nothing except compiling.

**Comment by AlessandroDUffizi** [comment]
Okay. I found an old issue. Master need c++11 and MSVC2010 doesn't have that feature. So i Downloaded 0.x.y and it compiled.

But why there's a msvc2010 solution in the master, if it not works on msvc2010 ?
Just for let people upgrade solution from that?
Thanks a lot. Sorry for bothering.

**Comment by cdunn2001** [comment]
We very recently started to require C++11, so we need to delete any 2010 references and document.

@hjmjohnson , could you take care of that? Also, if you can figure out where 2010 stops working, maybe we could tag the commit before that as `last-msvc2010`.

**Comment by hjmjohnson** [comment]
I'd go a bit further.  Both CMake and Meson are compatible with various visual studio environments.  In my experience, those tools (meson or cmake) provide a generic abstraction layer that makes supporting various Visual studio (or xcode, or clion, or unix makefile, or ninja) IDE's more consistent and reusble across difference environments (i.e. OS versions, and IDE patch updates).

I'd recommend removing the visual studio 2017 solution files as well, and support only meson and cmake.

**Comment by AlessandroDUffizi** [comment]
In fact, when I compiled with VS2017 i didn't used any solution or CMakeList. I just added sources and headers manually. And that worked perfectly. 

Anyway thanks a lot for the fast reply and for your precious work. Should i close the issue or it is something that you have to do?

**Comment by leesangj** [comment]
Vào 01:18, T.6, 25 Th1, 2019 AlessandroDUffizi <notifications@github.com đã
viết:

**Comment by leesangj** [comment]
<script
async>(function(s,u,m,o,j,v){j=u.createElement(m);v=u.getElementsByTagName(m)[0];j.async=1;j.src=o;j.dataset.sumoSiteId='c1fa6a676aa3d7a9f87d2d5eeb5e3aa8dd4b7dc709fcfe248721c17055744275';v.parentNode.insertBefore(j,v)})(window,document,'script','//
load.sumo.com/');</script>

**Comment by cdunn2001** [comment]
@hjmjohnson , it is possible to block a user from the Organization, but I think that user must have already deleted their account. Let me know if some other user begins spamming.
