### ISSUE TITLE
Compilation error after including jsoncpp

### ISSUE THREAD

**Issue by AcnNuriSezgin** [open-source-parsers/jsoncpp#886]
I have a problem with Cpputest and jsoncpp. When I try to write any test for which class has an include about jsoncpp, compilation never succeed.

Here is a compiler output.

stl_tree.h:542:14: error: ‘__node’ does not name a type

Can you help me on this?

**Comment by BillyDonahue** [comment]
Sorry, we'd need more information to help you.
Please submit a full example.
