### ISSUE TITLE
a little problem here.

### ISSUE THREAD

**Issue by Nitro112** [open-source-parsers/jsoncpp#887]
Hey!
So i'm using this to read offsets and netvars from .json file.
It read corretly, getting CC96B4 as a value from file. 
But it seems that i can't use this for ReadProcessMemory, without 0x0. How can i fix this?
and storing values as integer.

**Comment by BillyDonahue** [comment]
I don't know how to help you.
Are you saying jsoncpp isn't interpreting the string "CC96B4" as a hex-encoded Number for you?

There's no hex encoding in json, except for \uxxxx unicode  chars which isn't what you want.
