### ISSUE TITLE
parsing json with missing opening bracket

### ISSUE THREAD

**Issue by malytomas** [open-source-parsers/jsoncpp#893]
Json:
`"a":"b"}`
is parsed without signalling an error.

Repro case: https://github.com/malytomas/jsoncpp-issue

**Comment by cdunn2001** [comment]
`"a"` is valid JSON. After parsing, you can check whether there are more characters in the input stream.

Also, jsoncpp fills several niches, but validation is not one of them. Still, you can try the "strict" mode for a fair bit of validation.
