### ISSUE TITLE
Why quote for string when use StreamWriterBuilder?

### ISSUE THREAD

**Issue by memeda** [open-source-parsers/jsoncpp#894]
Oh, It is nice to use `StreamWriterBuilder` and I can set the precision of float values.
But, I found that all the Non-Ascii characters are quoted.

After dived into the source code, I found the `static String valueToQuotedStringN(const char* value, unsigned length)`, and it scared me: it try to quote non-ascii  characters to unicode code-point according to the UTF8 rules, **ignoring the actual String Encoding**.

I know in the document or somewhere, it says the jsoncpp only support UTF-8, but I think the brutally quote them are not proper methods. The original Api, like `FastWriter`, just return the raw bytes, Why not follow it?

Or, we can follow the  json lib of Python, like 

```
import json

s = [u"中文有时常用GB18030编码",]; # unicode
json_dumps = json.dumps(s, ensure_ascii=False) # get unicode again 
```
that is,  let us get the raw bytes by providing a settting.

**Comment by dota17** [comment]
@memeda Do you mean `non-ascii characters` and `the actual String Encoding` refering to  the `Chinese String`?  Chinese character is a widestring ,and is represented by Unicode codes on the network. and UTF-8 is one of the implementations of Unicode. and as I know jsoncpp's Reader or Writer can also support the Chinese Characters.

**Comment by memeda** [comment]
em, may be my bad English made some errors.
It's true that I came across problem when processing Chinese String. The Chinese String I processed `is encoded by GB18030, not UTF-8`, so when Json cpp quote the bytes according to UTF-8, it output the wrong result. 

The right steps may be 

```
1. decode the bytes according to right encoding (here GB18030)
2. output unicode code-point
```

while current json cpp is 
```
1. translate the bytes to code-point, according to UTF-8 <=> Unicode code-point . [x] <- here may be wrong
2. output the unicode code-point
```

**Comment by dota17** [comment]
Yes, you are right.
For the chinese string, or others, which are not encoded by UTF-8, we should decoded them to unicode firstly. 
And I think **iconv_open()** and **iconv()** can solve this problem quite well, Because the user can converts any encoding format to UTF-8 by themselves.
For example:
```c++
#include <iconv.h>
//...
int SomtypeToUTF8(const string& input, string& output, const string& type)
{
   //...
   iconv_t cd = iconv_open("utf-8",type); //decode the bytes to unicode according to right encoding (here GB18030)
   //...
   iconv(cd, &input, &InPutLen, &output, &OutPutLen); //output unicode code-point
   //...
   iconv_close(cd);
}
```

**Comment by memeda** [comment]
Oh, I did it as you said. While I still can't understand why we should quote the bytes to unicode, instead of directly use the raw bytes. May be some standard? 
I thought it is inconvenient. I just want bytes in, bytes out. Not code point, not iconv.

**Comment by dota17** [comment]
@memeda 
Hi, can you give some examples using jsoncpp ? both FastWriter and StreamWriterBuilder will be fine, and tell your expected result.

**Comment by memeda** [comment]
Thanks for keeping tracking.
The `FastWriter didn't return the raw bytes when processing non-ascii characters.` because I'm using a old version jsoncpp, like `1.8.4` (may be, I've tried some version including the `0.x`).

----

In the code you post, where

```
const std::string uni = "中文有时常用GB18030编码"; // utf-8
```

is the key point. The `uni`''s bytes may be not encoded by `utf-8`(such as `GB18030` is another popular encoding in Chinese) , and then the `*Writer` make wrong quote.

I know the best way currently is firstly translated other encoding to `utf-8`, but some times I just need the raw bytes and don't need the quoted Unicode code-point, it decrease the efficiency.
so I just hope the `*Writer` just provide a option to let the result keep the original bytes, **disable quote**, like the `json`  in Python
```
json.dumps(json_data, ensure_ascii=False)
```
to let the result keep raw-bytes

**Comment by dota17** [comment]
@memeda 
Hi,
There is a PR #1045 for emitUTF8.
I think it maybe helpful for the case - utf-8 encoding, not to quoted unicode code-point.
You can review it.

**Comment by dota17** [comment]
PR #1045 for emitUTF8 was merged.
If the question is still online, feel free to reopen.
