### ISSUE TITLE
Failing ValueTest/integers unit test

### ISSUE THREAD

**Issue by emarthinsen** [open-source-parsers/jsoncpp#90]
I'm building with CMake and getting the following error from the unit tests:

```
Testing ValueTest/checkNormalizeFloatingPointStr: OK
Testing ValueTest/memberCount: OK
Testing ValueTest/objects: OK
Testing ValueTest/arrays: OK
Testing ValueTest/null: OK
Testing ValueTest/strings: OK
Testing ValueTest/bools: OK
Testing ValueTest/integers: FAILED
Testing ValueTest/nonIntegers: OK
Testing ValueTest/compareNull: OK
Testing ValueTest/compareInt: OK
Testing ValueTest/compareUInt: OK
Testing ValueTest/compareDouble: OK
Testing ValueTest/compareString: OK
Testing ValueTest/compareBoolean: OK
Testing ValueTest/compareArray: OK
Testing ValueTest/compareObject: OK
Testing ValueTest/compareType: OK
Testing ValueTest/offsetAccessors: OK
Testing ValueTest/typeChecksThrowExceptions: OK
Testing ReaderTest/parseWithNoErrors: OK
Testing ReaderTest/parseWithNoErrorsTestingOffsets: OK
Testing ReaderTest/parseWithOneError: OK
Testing ReaderTest/parseChineseWithOneError: OK
Testing ReaderTest/parseWithDetailError: OK
Testing WriterTest/dropNullPlaceholders: OK
* Detail of ValueTest/integers test failure:
/home/eric/Development/jsoncpp/src/test_lib_json/main.cpp(664): kfint32max == val.asFloat()
  Expected: 2147483648
  Actual  : 2147483648
25/26 tests passed (1 failure(s))
make[2]: *** [jsoncpp/bin/jsoncpp_test] Error 1
make[1]: *** [jsoncpp/src/test_lib_json/CMakeFiles/jsoncpp_test.dir/all] Error 2
make: *** [all] Error 2
```

Is this an issue in the code or maybe specific to my setup?

**Comment by illuusio** [comment]
Can you determine how to make it precicely so I can test it..

**Comment by cdunn2001** [comment]
Still hoping for help on this. Maybe I will have to start a 32-bit Linux VM.

**Comment by emarthinsen** [comment]
The steps to reproduce it are pretty straightforward. Just grab the ISO for Ubuntu 12.04.5 (32-bit) and do a default install into a VM. I used VirtualBox. Clone the jsoncpp repo and build it using cmake. It was a while ago, so I don't remember which prerequisites I installed, but I think just build essentials.

**Comment by illuusio** [comment]
Yes I can get this bug on openSUSE x86 13.2 also. I digged little bit and numbers are equal when you print them out. I sound like compiler bug but because it happens wide range compilers I doub it that nobody else has spotted it..

**Comment by cdunn2001** [comment]
All tests pass for me. Here are details of my VM:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

$ dmesg ...
Linux version 3.13.0-32-generic (buildd@roseapple) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #57-Ubuntu SMP Tue Jul 15 03:51:12 UTC 2014 (Ubuntu 3.13.0-32.57-generic 3.13.11.4)

$ uname -a
Linux cd-VirtualBox 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:12 UTC 2014 i686 i686 i686 GNU/Linux

$ file /sbin/init
/sbin/init: ELF 32-bit LSB  shared object, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=c394677bccc720a3bb4f4c42a48e008ff33e39b1, stripped
```

I guess I need **WAY** more details. E.g.
* What commit are you using?
* What compiler version? 
* What is the *exact* `cmake` command-line?

Or can you simply give me shell access to your machine?

**Comment by cdunn2001** [comment]
Aha! It fails for the optimized (*Release*) build.
```
$ cmake -DCMAKE_BUILD_TYPE=Release -DJSONCPP_LIB_BUILD_SHARED=OFF -DCMA
$ make
* Detail of ValueTest/integers test failure:
/home/cd/gh/jsoncpp/src/test_lib_json/main.cpp(676): kfint32max == val.asFloat()
  Expected: 2147483648
  Actual  : 2147483648
25/26 tests passed (1 failure(s))
```
I can debug this now.

**Comment by cdunn2001** [comment]
More info:
```
$ cmake -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DJSONCPP_LIB_BUILD_SHARED=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -G "Unix Makefiles" ../..
$ cd src/test_lib_json
$ gdb ./jsoncpp_test
Breakpoint 2, TestValueTestintegers::runTestCase (this=0x809d8b0)
    at /home/cd/gh/jsoncpp/src/test_lib_json/main.cpp:676
676	  JSONTEST_ASSERT_EQUAL(kfint32max, val.asFloat());
(gdb) p kfint32max
$1 = 2.14748365e+09
(gdb) p val.asDouble()
$2 = 2147483647
(gdb) p val.asString()
$3 = {static npos = <optimized out>, 
  _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x809daac "2147483647"}}
(gdb) p val
$4 = {static null = @0x8090898, static minLargestInt = -9223372036854775808, 
  static maxLargestInt = 9223372036854775807, 
  static maxLargestUInt = 18446744073709551615, static minInt = -2147483648, 
  static maxInt = 2147483647, static maxUInt = 4294967295, 
  static minInt64 = -9223372036854775808, static maxInt64 = 9223372036854775807, 
  static maxUInt64 = 18446744073709551615, value_ = {int_ = 2147483647, 
    uint_ = 2147483647, real_ = 1.0609978949885705e-314, bool_ = 255, 
    string_ = 0x7fffffff <error: Cannot access memory at address 0x7fffffff>, 
    map_ = 0x7fffffff}, type_ = Json::intValue, allocated_ = 0, comments_ = 0x0, 
  start_ = 0, limit_ = 0}
```

**Comment by Muon** [comment]
Sanity check: `-ffast-math` is off, right?

Something you could try is `-mfpmath=sse` or `-ffloat-store` when compiling. If either of those makes the test pass in optimized mode, it's almost certainly a compiler bug.

**Comment by cdunn2001** [comment]
Thanks for the suggestions! Results:
* `-fno-fast-math` made no difference.
  * I think that's the default anyway, right?
* `-mfpmath=sse` worked!
  * `warning: SSE instruction set disabled, using 387 arithmetics [enabled by default]`
* `-ffloat-store` worked!

So that at least gives us some options. What do you suggest? I don't want to force people to use specific flags, but I guess we could use those only for the tests.

**Comment by Muon** [comment]
That's odd, that warning suggests that it didn't use SSE. Could you check again? Is there a `-march` option or `-mtune` or something?

Only using them for tests would kinda defeat the purpose of the tests, no? :stuck_out_tongue:

**Comment by cdunn2001** [comment]
Well, we don't perform any math within the parser, so I think it's ok for the float/SSE settings to be chosen by the user. This particular error has nothing to do with any jsoncpp code. It's strictly the behavior of an if-statement in the test code.

I'll look into -march and -mtune etc. soon. Thanks!

**Comment by Muon** [comment]
Another way of fixing it on i386 would be to move `kfint32max` into a separate translation unit and make it external. Unless LTO is performed, it should load the rounded value onto the FPU stack, rather than the original, thus making the comparison work. Alternatively, you could explicitly replace it with `2.14748365e+09f` instead of `float(kint32max)`.

**Comment by cdunn2001** [comment]
I found a simple fix. @Muon's ideas seem fine too. And if this ever recurs, we can apply `-ffloat-store`.

**Comment by mcauto** [comment]
@cdunn2001 
Hi! I want to use `ExternalProject_Add()`.
How to use `-ffloat-store` ??
