### ISSUE TITLE
clang linker command failed

### ISSUE THREAD

**Issue by MadhavChoudhary** [open-source-parsers/jsoncpp#903]
I installed jsoncpp using homebrew `brew install jsoncpp`  
On compiling my cpp file with g++, I got the following error:
```
Undefined symbols for architecture x86_64:
  "Json::Value::append(Json::Value&&)", referenced from:
      BTreeNode::json_graph() in btree-25403e.o
  "Json::Value::Value(Json::ValueType)", referenced from:
      BTreeNode::json_graph() in btree-25403e.o
  "Json::Value::Value(Json::Value const&)", referenced from:
      BTreeNode::json_graph() in btree-25403e.o
  "Json::Value::Value(int)", referenced from:
      BTreeNode::json_graph() in btree-25403e.o
  "Json::Value::~Value()", referenced from:
      BTreeNode::json_graph() in btree-25403e.o
  "Json::Value::operator=(Json::Value)", referenced from:
      BTreeNode::json_graph() in btree-25403e.o
  "Json::Value::operator[](char const*)", referenced from:
      BTreeNode::json_graph() in btree-25403e.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by MadhavChoudhary** [comment]
Here's what worked for me.  

Following this [link](https://github.com/open-source-parsers/jsoncpp/wiki/Amalgamated), create the amalgamated source.  
You will have a `dist/` folder.
Now, in your program `include "dist/json/json.h"`
and compile your program as `g++ <your_code>.cpp dist/jsoncpp.cpp -std=c++11`

**Comment by cdunn2001** [comment]
I'm glad the amalgamated source worked for you.

With the brew installation, did you try `pkg-config --cflags jsoncpp` and `pkg-config --libs jsoncpp`? I think you were not actually linking with jsoncpp, or you built a dynamically loaded executable and needed the libjsoncpp.dylib directory in your shell's `$DYLD_LIBRARY_PATH`.

**Comment by fooSynaptic** [comment]
@cdunn2001 `pkg-config` dont work for for my macos system as well as add `ibjsoncpp.dylib` path to dynamically loaded path, can you present more details about compile?
