### ISSUE TITLE
JSON without quotes in keys of objects

### ISSUE THREAD

**Issue by bstarynk** [open-source-parsers/jsoncpp#906]
Motivation of this issue is given [here](https://softwareengineering.stackexchange.com/q/389927/40065).

Is there a way to use json-cpp in the common case where we have JSON objects whose key strings are C identifiers (which are not JavaScript or C++ keywords), so something like `{x:1,y:2,comment:"ab",see:[1,false]}` instead of the JSON required `{"x":1,"y":2,"comment":"ab","see":[1,false]}`.

When we deal with millions of such JSON objects, I am guessing that performance would be improved, since the textual format becomes shorter.

I could even propose a patch (a pull request for that is very simple to code) if I was sure it might (after review) be accepted. It would just mean adding some additional things in  `Json::StreamWriterBuilder::settings_` etc. Maybe some `abbreviatedKeyName`.

I really want to avoid [forking](https://en.wikipedia.org/wiki/Fork_(software_development)) the json-cpp project.

**Comment by cdunn2001** [comment]
Oh, gosh. I can see the value. But I think a fork is your best best, unfortunately.
