### ISSUE TITLE
When the jsoncpp.so is C++ dynamic lib,  some C++11 dynamic lib use Reader, FastWriter, Reader::ErrorInfo. will abort or exit.

### ISSUE THREAD

**Issue by wanghancai** [open-source-parsers/jsoncpp#907]
When the jsoncpp.so is C++ dynamic lib,  some C++11 dynamic lib use Reader, FastWriter, Reader::ErrorInfo. 

The C++ 11 dynamic will auto generate the destruction functions for Reader, FastWriter, Reader::ErrorInfo.

But the auto generated functions use C++11 std string's destruction function to destroy Reader's string document_ which is newed by the C++ std string`s construction function.

Please fixed your bugs to make sure the Reader, FastWriter, Reader::ErrorInfo will destroy in the runtime which is belong to themself.

041984    36 FUNC    WEAK   DEFAULT   11 _ZN4Json6Reader9ErrorInfoD1Ev     Json::Reader::ErrorInfo::~ErrorInfo()
041984    36 FUNC    WEAK   DEFAULT   11 _ZN4Json6Reader9ErrorInfoD1Ev     Json::Reader::ErrorInfo::~ErrorInfo()
040e40    68 FUNC    WEAK   DEFAULT   11 _ZN4Json6ReaderD1Ev		     Json::Reader::~Reader()              
040e40    68 FUNC    WEAK   DEFAULT   11 _ZN4Json6ReaderD2Ev		     Json::Reader::~Reader()              
040dfc    36 FUNC    WEAK   DEFAULT   11 _ZN4Json10FastWriterD0Ev	     Json::FastWriter::~FastWriter()      
040dbc    64 FUNC    WEAK   DEFAULT   11 _ZN4Json10FastWriterD1Ev          Json::FastWriter::~FastWriter()      
040dbc    64 FUNC    WEAK   DEFAULT   11 _ZN4Json10FastWriterD2Ev          Json::FastWriter::~FastWriter()      
040dbc    64 FUNC    WEAK   DEFAULT   11 _ZN4Json10FastWriterD2Ev	     Json::FastWriter::~FastWriter()      
041984    36 FUNC    WEAK   DEFAULT   11 _ZN4Json6Reader9ErrorInfoD1Ev     Json::Reader::ErrorInfo::~ErrorInfo()
040dbc    64 FUNC    WEAK   DEFAULT   11 _ZN4Json10FastWriterD1Ev	     Json::FastWriter::~FastWriter()      
040dfc    36 FUNC    WEAK   DEFAULT   11 _ZN4Json10FastWriterD0Ev          Json::FastWriter::~FastWriter()      
040e40    68 FUNC    WEAK   DEFAULT   11 _ZN4Json6ReaderD2Ev               Json::Reader::~Reader()              
040e40    68 FUNC    WEAK   DEFAULT   11 _ZN4Json6ReaderD1Ev               Json::Reader::~Reader()              
041984    36 FUNC    WEAK   DEFAULT   11 _ZN4Json6Reader9ErrorInfoD1Ev     Json::Reader::ErrorInfo::~ErrorInfo()

**Comment by zouhuigang** [comment]
我刚发现这个问题，后来查到是说，在动态库中，如果要引用静态库，则静态库编译的时候需要加-fPIC，进行地址无关的处理。

**Comment by wanghancai** [comment]
这个问题是引用jsoncpp动态库的库会自动生成上述对象的默认析构函数，与-fPIC没关系。开源上必需禁用或提供默认析构函数，不可让编译器自动生成。典型的code bug。

**Comment by han-xie** [comment]
> 这个问题是引用jsoncpp动态库的库会自动生成上述对象的默认析构函数，与-fPIC没关系。开源上必需禁用或提供默认析构函数，不可让编译器自动生成。典型的code bug。
我发现了类似的问题，希望作者要写析构函数~

@cdunn2001 I have encountered a similar problem. I cannot find destructor function in Json::Reader class ( "json/reader.h" ) and I guess it causes SEGMENTATION FAULT.

Example: In my project, the following function will report a SEGMENTATION FAULT.
`
bool data_reader(const char* filename, double *mean, double* stddev) {
  Json::Reader __json_reader;
#ifdef _DEBUG
  return false;
#endif
  /* the right things to do below */ ...
}
`
However, the TRICKY thing is that I cannot reproduce this error with a minimal working example.
I guess it's a problem with the default destructor function.

**Comment by dota17** [comment]
In recent version  class **Reader, Writer and FastWriter** has been deprecated, one of the warning info below will occur when it runs in my machine:
```c++
warning: ‘Reader’ is deprecated: Use CharReader and CharReaderBuilder instead [-Wdeprecated-declarations]
warning: ‘Writer’ is deprecated: Use StreamWriter instead [-Wdeprecated-declarations]
warning: ‘FastWriter’ is deprecated: Use StreamWriterBuilder instead [-Wdeprecated-declarations]
``` 
If you use the recommended method,it won't happen.

**Comment by baylesj** [comment]
Closed due to deprecation. Reopen if this occurs with CharReader or StreamWriter.
