### ISSUE TITLE
jsoncpp pasre json file dump

### ISSUE THREAD

**Issue by xjy198903** [open-source-parsers/jsoncpp#908]
I want use jsoncpp parse text.json,when in single process,it works well,but when parsing is in multi-thread,it return "Segmentation fault".
PS:
[test.zip](https://github.com/open-source-parsers/jsoncpp/files/3066921/test.zip)
 
libjsoncpp-1.8.3

the code is : 
```cpp
bool parseJson(const string &info)
{
    if (info.empty())
        return false;

    bool res;
    JSONCPP_STRING errs;
    Json::Value cmd_arrays;
    Json::CharReaderBuilder readerBuilder;

    std::unique_ptr<Json::CharReader> const jsonReader(readerBuilder.newCharReader());
    res = jsonReader->parse(info.c_str(), info.c_str()+info.length(), &cmd_arrays, &errs);
    if (!res || !errs.empty()) {
        std::cout << "parseJson err. " << errs << std::endl;
    }

    return true;

}

int main()
{
    string info_str ;
    ifstream fin("test.json",ios::binary);
    if(!fin.is_open())
    {
        cout << "Error opening file\n" << endl;
        return -1;
    }

    ostringstream sin;
    sin << fin.rdbuf();
    info_str = sin.str();
    fin.close();

    parseJson(info_str);
    return 0;
}
```

**Comment by xjy198903** [comment]
In addition, plaform is linux ,the compiler version is arm-linux (7.2.1)

**Comment by cdunn2001** [comment]
Maybe if you show the simultaneous use, we could spot the error. I would expect a Json object wholly within a thread to be fine, but if it's shared between threads, any writes would be unsafe.

**Comment by xjy198903** [comment]
solve it . It's my fault when use eclipse to develop,lost CXXFLAGS
