### ISSUE TITLE
Compilation error on android arm64-v8a

### ISSUE THREAD

**Issue by ddovod** [open-source-parsers/jsoncpp#913]
Hi.
If you try to
```
Json::Value someJsonValue;
int64_t someIntValue = 45;  // <-- note on type
someJsonValue = someIntValue;  // <-- error
```
you'll get a compiler error `error: conversion from 'int64_t' (aka 'long') to 'Json::Value' is ambiguous`.
On iOS it compiles fine both for armv7 and arm64, but on android arm64-v8a `long` and `long long` are different enough to trigger compiler error, however both are 8 bytes.

**Comment by dota17** [comment]
Hi @ddovod  I've found  some issues are much the same with your question here, and probably they may be able to resolve your concerns.
1. #64  
2. #879 
3. #509

**Comment by baylesj** [comment]
Is `JSON_HAS_INT64` defined as true? Value should have a setter explicitly for int64_t...

```
typedef int64_t Int64;

#if defined(JSON_HAS_INT64)
  Value(Int64 value);
  Value(UInt64 value);
#endif // if defined(JSON_HAS_INT64)
```

**Comment by ddovod** [comment]
Hi. Probably it's fixed already because in our copy of jsoncpp `config.h` has this definitions of Int64 and UInt64:
```
#if defined(_MSC_VER) // Microsoft Visual Studio
typedef __int64 Int64;
typedef unsigned __int64 UInt64;
#else                 // if defined(_MSC_VER) // Other platforms, use long long
typedef long long int Int64;
typedef unsigned long long int UInt64;
#endif // if defined(_MSC_VER)
typedef Int64 LargestInt;
typedef UInt64 LargestUInt;
#define JSON_HAS_INT64
#endif // if defined(JSON_NO_INT64)
```
but in master it is
```
#if defined(_MSC_VER) // Microsoft Visual Studio
typedef __int64 Int64;
typedef unsigned __int64 UInt64;
#else                 // if defined(_MSC_VER) // Other platforms, use long long
typedef int64_t Int64;
typedef uint64_t UInt64;
#endif                // if defined(_MSC_VER)
typedef Int64 LargestInt;
typedef UInt64 LargestUInt;
#define JSON_HAS_INT64
#endif // if defined(JSON_NO_INT64)
```

I'll check that, thanks!

**Comment by baylesj** [comment]
Ahh, cool. It's nice when updates fix things :).

Closing now, feel free to reopen/comment/message if it comes up again.
