### ISSUE TITLE
Warning about weak-vtables

### ISSUE THREAD

**Issue by an-tao** [open-source-parsers/jsoncpp#923]
Hi
When I tried to compile this project with the `-Werror=weak-vtables` flag I got the following errors:

```
'CharReader' has no out-of-line
      virtual method definitions; its vtable will be emitted in every
      translation unit [-Werror,-Wweak-vtables]
class JSON_API CharReader {
...
```

Should I ignore these errors/warnings?

**Comment by baylesj** [comment]
I think we can just ignore it, the declarations in CharReader and OurCharReader look right and the linker can clean up any weirdness.

See: https://stackoverflow.com/questions/23746941/what-is-the-meaning-of-clangs-wweak-vtables

**Comment by an-tao** [comment]
Thanks a lot!
