### ISSUE TITLE
cannot parse the boolean???

### ISSUE THREAD

**Issue by bd7jhh** [open-source-parsers/jsoncpp#926]
Hi,

I am use php output this json string:
{"TestConn":true}

and mfc code:
Json::Vaule ReturnJsonResult;
Json::CharReaderBuilder jsonReadBuilder;
Json::CharReader* jsonReader(jsonReadBuilder.newCharReader());
Json::String jsonErrs;
BOOL isParseOK=FALSE;
isParseOK = (BOOL)jsonReader->parse(startByte, EndByte, &ReturnJsonResult, &jsonErrs);

the isParseOK value is FALSE,
the jsonErrs "* Line 1, Column 13\n  Syntax error: value, object or array expected.\n"

if use the string {"TestConn":"true"}, it's ok. JSON parse is ok.

i use jsoncpp with "Amalgamated", python create .h and .cpp

**Comment by dota17** [comment]
At the code level, this is ok，you can view relevant code in `json_reader.cpp`, and in my test code is ok too.
How do you define the variable `startByte` ? it doesn't show in your code above. If you don't point this variable to the json string, it will really arise this kind of error like `Syntax error:value,object or array expected`.

**Comment by bd7jhh** [comment]
> At the code level, this is ok，you can view relevant code in `json_reader.cpp`, and in my test code is ok too.
> How do you define the variable `startByte` ? it doesn't show in your code above. If you don't point this variable to the json string, it will really arise this kind of error like `Syntax error:value,object or array expected`.

Thanks your reply,
The JSON string data define code:

char* pJsonStringData;
unsigned int JsonStringDataLength=xxxx;


MFC code:

Json::Vaule` ReturnJsonResult;
Json::CharReaderBuilder jsonReadBuilder;
Json::CharReader* jsonReader(jsonReadBuilder.newCharReader());
Json::String jsonErrs;
BOOL isParseOK=FALSE;

char* pJsonStringData;
unsigned int JsonStringDataLength=xxxx;

isParseOK = (BOOL)jsonReader->parse(
    pJsonStringData, 
    (char*)(*myHttpReturnResult.pReturnData) + myHttpReturnResult.ReturnDataLength, 
    &ReturnJsonResult, 
    &jsonErrs
    );
`

**Comment by baylesj** [comment]
Assuming your code is correct, I know what the problem is.

The line `(char*)(*pJsonStringData)` is incorrect. Considering that `pJsonStringData` is defined as `char*`, what you are actually doing here is dereferencing to `char` and then turning that into a bad pointer. See below:
```cpp
const char* pJsonStringData = "{\"TestConn\":\"true\"}"
*pJsonStringData => '{'
(char*)(*pJsonStringData) => 0x0000007B
```

Where `0x0000007B` is a junk memory address. I'm surprised this doesn't just segfault.
