### ISSUE TITLE
How to link jsoncpp library in cmake project

### ISSUE THREAD

**Issue by ParikaGoel** [open-source-parsers/jsoncpp#927]
The `jsoncppConfig.cmake` defines property `INTERFACE_INCLUDE_DIRECTORIES` for targets `jsoncpp_lib` and `jsoncpp_lib_static`.

You need to query the target property and set it manually:
```cmake
get_target_property(JSON_INC_PATH jsoncpp_lib INTERFACE_INCLUDE_DIRECTORIES)
include_directories(${JSON_INC_PATH})
```

Linking is done via:
```cmake
target_link_libraries(${PROJECT_NAME} jsoncpp_lib)
```

_Originally posted by @christian-rauch in https://github.com/open-source-parsers/jsoncpp/issues/455#issuecomment-477307969_

**Comment by ParikaGoel** [comment]
Above solution was already posted to include the jsoncpp library in cmake projects. But this solution requires jsoncppConfig.cmake file which is available if I install default jsoncpp package provided by ubuntu.

I am compiling the jsoncpp code from source. How could I link it into my cmake project if I am compiling it from source. I also don't want to use pkgconfig to search for jsoncpp

**Comment by oleurodecision** [comment]
the jsoncppConfig.cmake is built and installed when the CMake option `JSONCPP_WITH_CMAKE_PACKAGE` is enabled, which is currently the default.

So configure build with cmake (some `
cmake
   -DCMAKE_BUILD_TYPE=Release
   -DJSONCPP_WITH_CMAKE_PACKAGE=ON
   -DCMAKE_INSTALL_PREFIX=[your install path]
   -S [path to the project source dir]
   -B [path to the build dir]
`), build and install (`cmake --build [path to the build dir] --target install`)

and for your consuming project, call CMake with CMAKE_PREFIX_PATH set to the root of the folder where you installed jsoncpp, and link your library/executable against jsoncpp_lib (`target_link_libraries (MyGreatProject PUBLIC jsoncpp_lib)`).

This should do the trick, if I don't misunderstand your question.

**Comment by baylesj** [comment]
Fixed by #934 ... thanks @oleurodecision!!!

**Comment by clouds56** [comment]
Is it possible to make meson output the `jsoncppConfig.cmake` as well?
The arch linux [package](https://github.com/archlinux/svntogit-packages/blob/packages/jsoncpp/trunk/PKGBUILD) chose to use meson to build the jsoncpp, while I'd like to link it with another library which uses CMake

**Comment by dota17** [comment]
> Is it possible to make meson output the jsoncppConfig.cmake as well?

As far as I know, it can't.

> The arch linux package chose to use meson to build the jsoncpp, while I'd like to link it with another library which uses CMake

You can still use cmake to build the jsoncpp, and then link it in another library.

**Comment by christian-rauch** [comment]
@clouds56 Do you need the `.cmake` directly? Alternatively, you can let meson generate a pkg-config file that can also be used with CMake.

**Comment by adembudak** [comment]
A common convention for CMake target name is using an alias target. I expected to *jsoncpp* target name for linking was `jsoncpp::jsoncpp` or `jsoncpp::jsoncpp_lib` instead of `jsoncpp_iib`.

**Comment by cdunn2001** [comment]
Please file a PR. We use (and strongly recommend) **meson** instead of **cmake**. We rely on users for most **cmake** updates.
