### ISSUE TITLE
Some links in FAQ has invalid and 404 No Found, please update them.

### ISSUE THREAD

**Issue by dota17** [open-source-parsers/jsoncpp#938]
1.  ***How do I fix the locale, for skipping commas in numbers?***
[discussion](https://github.com/jacobsa/jsoncpp/pull/2) and [an example](https://gist.github.com/cdunn2001/61bc4a05ce906492defd)
2. ***Where are the API docs?***
In a separate repo, to minimize the size of the code repo.
***source-code***
[https://github.com/jacobsa/jsoncpp/](https://github.com/jacobsa/jsoncpp/)
***documentation***
[http://cdunn2001.github.io/json-cpp/](http://cdunn2001.github.io/json-cpp/)
[https://github.com/cdunn2001/json-cpp](https://github.com/cdunn2001/json-cpp)

**Comment by baylesj** [comment]
Fixed in the FAQ, updated to new links.
