### ISSUE TITLE
How build jsoncpp under mac for using under ios/android 

### ISSUE THREAD

**Issue by sazizbekyants** [open-source-parsers/jsoncpp#945]
Hi All 

I am trying to build jsoncpp under mac osx and use it in my ios/android application.
 
my steps 

1. Download sources and try build by next command 
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
Run:
brew install jsoncpp .

I got libjsoncpp.1.8.4.dylib but when i tried use it in my mobile application I got next errors 

Undefined symbols for architecture arm64:
  "Json::Value::Value(Json::ValueType)", referenced from:
      void BW::BlackWhiteAPI::loadDataFromJsonFile<Node>(char const*, Node&) in BlackAndWhiteClientiOSApi

and warning 
ld: warning: ignoring file /json/lib/libjsoncpp.1.8.4.dylib, file was built for x86_64 which is not the architecture being linked (arm64): app/json/lib/libjsoncpp.1.8.4.dylib

which means that my libjsoncpp.1.8.4.dylib was  built for debug mode not for release  
so my question is next , how build jsoncpp for release mode ?

Thank you

**Comment by baylesj** [comment]
We currently don't have a build set up for arm64, so I think you are just running into issues cross compiling with Meson, since you are building on x86_64 for arm64. Try reading this:

https://github.com/mesonbuild/meson/blob/master/docs/markdown/Cross-compilation.md

And lmk how it goes.

**Comment by baylesj** [comment]
To answer your question about building in release mode, see the CONTRIBUTING.md:

```cpp
cd jsoncpp/
BUILD_TYPE=release
LIB_TYPE=shared
meson --buildtype ${BUILD_TYPE} --default-library ${LIB_TYPE} . build-${LIB_TYPE}
ninja -v -C build-${LIB_TYPE}
cd build-${LIB_TYPE}
meson test --no-rebuild --print-errorlogs
sudo ninja install
```
