### ISSUE TITLE
cmake: -std=gnu++11 in interface flags

### ISSUE THREAD

**Issue by malytomas** [open-source-parsers/jsoncpp#951]
Hi,

I am using jsoncpp as a git submodule and I have a superproject with add_subdirectory(externals/jsoncpp) in cmake.
My project requires c++14. However, when I link the jsoncpp, my own -std=c++14 is overridden by your -std=gnu++11 and causes compilation of my target to fail. Specifically, they are both added to the command line, and the later is used.

The flag is added in:
https://github.com/open-source-parsers/jsoncpp/blob/5b91551f3944d69e0090d6b6528852207de78078/src/lib_json/CMakeLists.txt#L89

I propose to split the feature tests into two categories: public and private, where the majority should be in the private set, including the cxx_std_11.

**Comment by baylesj** [comment]
We don't typically manage too much of the CMake build configurations. It sounds like you have a fix in mind, if you want to push a pull request I would be happy to look it over and submit with feedback.

**Comment by malytomas** [comment]
It appears that this problem is more difficult than it seems at first, and is discussed at cmake developers forums. See https://gitlab.kitware.com/cmake/cmake/issues/16608 and https://gitlab.kitware.com/cmake/cmake/issues/17146 .

In my code, I do a workaround: 
```cmake
# prevent the library from overriding my cxx standard flags
set_target_properties(${jsoncpp_lib_target} PROPERTIES COMPILE_FEATURES "")
set_target_properties(${jsoncpp_lib_target} PROPERTIES INTERFACE_COMPILE_FEATURES "")
```
similar to as suggested in the forum.

My approach at this point would probably be to remove the target_compile_features entirely and just set the required standard via CMAKE_CXX_STANDARD. I will leave that for your consideration.
