### ISSUE TITLE
amalgamation setup fails, can't find ../include/json/version.h

### ISSUE THREAD

**Issue by sryadgir** [open-source-parsers/jsoncpp#973]
It seems a file has been moved, causing the amalgamation setup to fail.

1. I download the repository and cd into it.
2. I run `python amalgamate.py` and get the following error:

```Amalgamating header...
Traceback (most recent call last):
  File "amalgamate.py", line 155, in <module>
    main()
  File "amalgamate.py", line 147, in main
    header_include_path=options.header_include_path)
  File "amalgamate.py", line 69, in amalgamate_source
    header.add_file("include/json/version.h")
  File "amalgamate.py", line 30, in add_file
    f = open(os.path.join(self.top_dir, relative_input_path), "rt")
IOError: [Errno 2] No such file or directory: '/opt/jsoncpp/include/json/version.h'```

**Comment by Chazz1222** [comment]
> It seems a file has been moved, causing the amalgamation setup to fail.
> 
> 1. I download the repository and cd into it.
> 2. I run `python amalgamate.py` and get the following error:
> 
> ```
> Traceback (most recent call last):
>   File "amalgamate.py", line 155, in <module>
>     main()
>   File "amalgamate.py", line 147, in main
>     header_include_path=options.header_include_path)
>   File "amalgamate.py", line 69, in amalgamate_source
>     header.add_file("include/json/version.h")
>   File "amalgamate.py", line 30, in add_file
>     f = open(os.path.join(self.top_dir, relative_input_path), "rt")
> IOError: [Errno 2] No such file or directory: '/opt/jsoncpp/include/json/version.h'```
> ``

please run cmake . first

**Comment by baylesj** [comment]
You have to run the meson or CMake build first, unfortunately. The version header is a build artifact, due to containing information from the Meson build specification.
