### ISSUE TITLE
Migrate to C++14

### ISSUE THREAD

**Issue by baylesj** [open-source-parsers/jsoncpp#975]

**Comment by dota17** [comment]
The main new features in C++14 is:
1. Return type deduction

1. Generic lambdas

1. Initialized lambda captures

1. Relaxed constexpr restrictions

1. [[deprecated]] attribute 

1. Digit separators and Binary literals

Can we apply the 6th feature to the ValueTest for a new unittest case?

**Comment by hjmjohnson** [comment]
I am a bit concerned about moving to C++14.  Many projects that will be working with jsoncpp have not yet migrated to C++14 development environment, and this change will make it difficult to incorporate jsoncpp (thus limiting its widespread adoption).

**Comment by dota17** [comment]
> I am a bit concerned about moving to C++14. Many projects that will be working with jsoncpp have not yet migrated to C++14 development environment, and this change will make it difficult to incorporate jsoncpp (thus limiting its widespread adoption).

Yes, you're right, we should be cautious in introducing new features, but if some new usages are good for performance optimization, then we can still use macro switch to keep them in the code.

**Comment by dota17** [comment]
Migrate to C++14:

- Delete JSONCPP_DEPRECATED, use [[deprecated]] instead : #978

**Comment by cdunn2001** [comment]
We could have a C++14 branch. Hopefully, after the clang-format changes, there will not be any more large changes. In general, we would need changes on both pre- and post-C++14 branches. Not fun, but possible.

**Comment by baylesj** [comment]
Let's rereview this in the future, then. I don't think the jump between 11 and 14 is great enough to warrant the suffering.
