### ISSUE TITLE
Delete JSONCPP_DEPRECATED, use [[deprecated]] instead

### ISSUE THREAD

**Issue by baylesj** [open-source-parsers/jsoncpp#981]
Is your feature request related to a problem? Please describe.
We have a hacky, compiler specific macro due to being pre C++11. This should be replaced with a standard language feature.

Describe the solution you'd like
Deletion of JSONCPP_DEPRECATED in favor of C++11's language standard deprecated

**Comment by dota17** [comment]
Actually, this is a feature in C++14, I made a typo in #978 's description:

> Language Conformance: Deletion of JSONCPP_DEPRECATED in favor of C++11's language standard [[deprecated]]

and maybe there will be some compatibility problems like issue #990
