### ISSUE TITLE
parser fails on repeated structures

### ISSUE THREAD

**Issue by DevNaga** [open-source-parsers/jsoncpp#992]
**Describe the bug**

Fails to recognize (parse) on repeated elements with in a same json object. See below steps to produce. An example of a file could be this:

```json
{
    "proc_restart_count_default": 2,
    "system_reset_enable": true,
    "proc_stats_enable": false,
    "proc_stats_socket": "udp",
    "proc_stats_socket_address": "192.168.1.1",
    "proc_stats_comms_protocol": "protobuf",
    "trace_log_enable": true,

    "process_configuration": {
        "procname" : "test1",
        "process_dep_state": 1,
        "health_monitor_id": 1,
        "thread_details": {
            "thread_name": "thread",
            "health_monitor_id": 2
        },
        "proc_command_args" : ["-t" , "-a" ],
        "proc_critical": false
    },

    "process_configuration": {
        "procname" : "test3",
        "process_dep_state": 3,
        "health_monitor_id": 2,
        "thread_details": {
            "thread_name": "thread",
            "health_monitor_id": 3
        },
        "proc_command_args" : ["-t" , "-a" ],
        "proc_critical": false
    }
}

```

here i am trying to read the contents within the repeated structure "process_configuration". However, i always get the last element in an iterative loop (range based `for` to be more precise). So i have tried repeating this 4 more times, and i always get the last element once in a iterative loop  than all the elements. See below example, 

**To Reproduce**
1. use this example,

```cpp
#include <iostream>
#include <fstream>
#include <jsoncpp/json/json.h>

int main()
{
    Json::Value root;
    std::ifstream config("ha_daemon_config.json", std::ifstream::binary);
    config >> root;

    // expect to iterate over process_configuration
    for (auto it : root["process_configuration"]) {
        std::cout << it << std::endl;
    }
}
```

output:

```
2
[
        "-t",
        "-a"
]
false
3
"test3"
{
        "health_monitor_id" : 3,
        "thread_name" : "thread"
}

```

observe the `test3`. It is the last element in the structure "process_configuration".

**Expected behavior**

I think the elements are allowed to be repeatable and so as the output when using the parser. So, basing on my above example json, it should provide me with two elements of "process_configuration" rather one element.

**Desktop (please complete the following information):**
 - OS:  Ubuntu 18.04

```bash
cmake --version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

```

jsoncpp version: 1.9.0

**Additional context**

**Comment by BillyDonahue** [comment]
Gee whiz, here's the repro:


#include <string>
#include <jsoncpp/json/json.h>

int main() {
    std::string doc = "{\"a\": 1, \"a\": 2}";
    std::unique_ptr<Json::CharReader> reader(
        Json::CharReaderBuilder().newCharReader());
    Json::Value root;
    reader->parse(doc.begin(), doc.end(), &root);
    // expect to iterate over the multiple "a"
    int dups = 0;
    for (auto&& it : root["a"]) {
        std::cout << it << std::endl;
        ++dups;
    }
    assert(dups == 2);
    return 0;
}

**Comment by BillyDonahue** [comment]
It hadn't occurred to me that JSON objects can have nonunique keys, but I guess the JSON ECMA standard technically allows it.

The expection includes this:

    // expect to iterate over process_configuration
    for (auto it : root["process_configuration"]) {
        std::cout << it << std::endl;
    }

I don't see how that would work unless Value::operator[](String) returned an iterable.
How would we syntactically distinguish the repeated-key case you expect from the case of a single-key?  That is to say, root[k] can be a string, and then iterating over it with ranged for makes sense because string is a container of char. But if there are multiple values mapped to key k, then root[k] would switch to iterating over those Values, I guess. It's a confusing API. The operator[] has to have a single return type. It can't change depending on the multiplicity of the key.  So we would need new syntax to support duplicated keys.

**Comment by DevNaga** [comment]
It works if i do :

```json
{
    "proc_restart_count_default": 2,
    "system_reset_enable": true,
    "proc_stats_enable": false,
    "proc_stats_socket": "udp",
    "proc_stats_socket_address": "192.168.1.1",
    "proc_stats_comms_protocol": "protobuf",
    "trace_log_enable": true,

    "process_configuration": [
    {
        "procname" : "test1",
        "process_dep_state": 1,
        "health_monitor_id": 1,
        "thread_details": {
            "thread_name": "thread",
            "health_monitor_id": 2
        },
        "proc_command_args" : ["-t" , "-a" ],
        "proc_critical": false
    },

    {
        "procname" : "test3",
        "process_dep_state": 3,
        "health_monitor_id": 2,
        "thread_details": {
            "thread_name": "thread",
            "health_monitor_id": 3
        },
        "proc_command_args" : ["-t" , "-a" ],
        "proc_critical": false
    }
    ]
}

```json

I could use array to keep repeated sets (but not name them before the `{`).

One of the reasons i came across this was that the copy-paste'd file is used as a configuration file in one of my personal projects.

**Comment by barsnick** [comment]
> It hadn't occurred to me that JSON objects can have nonunique keys, but I guess the JSON ECMA standard technically allows (but IIRC recommends against) it.

There are some interesting quotes in this [StackOverflow question: "Does JSON syntax allow duplicate keys in an object?"](https://stackoverflow.com/q/21832701/3974309).

Indeed, multiple identical keys are valid, so *shrug*.

> How would we syntactically distinguish the repeated-key case you expect from the case of a single-key?

Not only syntactically, but also logically. Assuming the original poster's configuration file: Which if those two configurations is supposed to be valid? (The first one found? The last one found? Any one? Neither? ;-)) If you want two provide multiple distinct configurations, put them into an array ([as suggested by the poster themself](#issuecomment-513755085)), that's the whole point of arrays.

There's some more insight in the SO answers, such as [this one](https://stackoverflow.com/a/53529204/3974309). I don't consider the suggested representation of HTML in JSON, as one answer suggests, as all too valid though, but if it's not forbidden, why not.

**Comment by cdunn2001** [comment]
It's helpful to have a 1:1 translation between dict-of-list-of-etc and JSON. If we have repeated keys, then "dict" cannot represent an "object".

It's true that the standard allows repeats, but the standard also fails to place any restriction on the size of Integer or Float. If this matters, I would suggest an implementation which allows the basic types to be defined via template arguments. Then you could provide a non-unique "dict" as well as arbitrary length integers and arbitrary precision floating point numbers.
