### ISSUE TITLE
Cannot find Version.h during Travis CI build

### ISSUE THREAD

**Issue by Google-Autofuzz** [open-source-parsers/jsoncpp#995]
Hi jsoncpp developers, 

I made a PR for [updating](https://github.com/open-source-parsers/jsoncpp/pull/994) the Fuzz.cpp and it fails at Travis CI build. It says that it can't find json/Version.h; the [link.](https://travis-ci.org/open-source-parsers/jsoncpp/jobs/565650690#L767) Do you have any idea why it is failing at this step? Thanks.

**Comment by dota17** [comment]
Me too! the same thing happened in PRs #944 and #993 a week ago.

**Comment by baylesj** [comment]
Looking at it now.

**Comment by baylesj** [comment]
Build issues were introduced in #989. My bad, was fighting Travis and got in a weird state. I'll work on getting that patch checked in again.
